/* ============================================================
   inerWeb R408 — banque de questions
   Banque complète (phase 3, 27/09/2026) : 9 questions par module
   M1 à M11 (99 au total), refonte de la banque THAU (pack.js) et
   inspiration ponctuelle du QCM primo-arrivants (sujets seulement,
   jamais les faits ni le niveau). Chaque fait testé est « vérifié »
   ou « partiellement vérifié » dans docs/SOURCES-REGLEMENTAIRES.md ;
   aucun chiffre inventé, aucun seuil « 3 mètres », aucune « habilitation ».

   FORMAT : ok = LA bonne réponse, nok = les 2 distracteurs.
   L'affichage assemble [ok, ...nok] puis MÉLANGE (Fisher-Yates).
   `m` = module qui porte le contenu testé (les questions « rappel »
   qui testent un module antérieur portent le `m` du module réellement
   testé). `sc` (facultatif) = identifiant du catalogue de scènes
   (docs/BRIEF-CONTENU.md § 5.1) — aucun autre identifiant que ceux-là.
   ============================================================ */

const QUESTIONS = [

  /* ---------- M1 · Le risque de chute ---------- */
  { m:"M1", sc:"chute-bord-vide", q:"Une chute de hauteur se produit quand…",
    ok:"une personne perd l'appui qui la retenait en surélévation",
    nok:["une personne ressent un vertige passager sans perdre l'équilibre","un objet tombe d'un plancher sans blesser personne"],
    exp:"Le risque de chute concerne la personne elle-même : la perte d'appui, pas le simple vertige ni la chute d'un objet." },
  { m:"M1", r:["DC1.a.01"], q:"La protection contre les chutes doit être mise en place…",
    ok:"dès qu'il existe un risque de chute, sans seuil de hauteur",
    nok:["seulement à partir de trois mètres de hauteur mesurés depuis le sol","uniquement si l'employeur le demande de façon expresse"],
    exp:"Depuis 2004, aucun seuil de hauteur ne déclenche l'obligation : elle existe dès qu'il y a un risque de chute." },
  { m:"M1", r:["DC1.a.03"], q:"Dans le bâtiment et les travaux publics, la chute de hauteur est…",
    ok:"la première cause de décès, alors qu'elle n'est que la deuxième cause d'accidents",
    nok:["la première cause d'accidents du secteur, mais rarement une cause de décès","une cause d'accidents assez rare, mais très souvent mortelle dans ce secteur"],
    exp:"Selon l'INRS, la chute de hauteur est le deuxième poste d'accidents du BTP mais la première cause de décès." },
  { m:"M1", sc:"chute-bord-vide", q:"Vous travaillez au bord d'un plancher sans garde-corps. Vous devez…",
    ok:"vous arrêter et ne pas vous exposer au vide",
    nok:["continuer prudemment en restant loin du bord","terminer la tâche avant de signaler le manque"],
    exp:"Sans protection efficace au bord du vide, le risque existe : on s'arrête avant d'agir." },
  { m:"M1", sc:"acces-interieur-trappe", q:"Vous devez accéder au premier niveau d'un échafaudage. Le trajet fait partie…",
    ok:"du risque de chute, autant que le travail sur le plancher",
    nok:["une question à part, sans lien avec le travail en hauteur","d'un risque qui ne concerne que le vérificateur journalier désigné"],
    exp:"On peut chuter en montant ou en descendant, pas seulement en travaillant sur la plateforme." },
  { m:"M1", sc:"acces-exterieur-interdit", q:"Vous voyez un collègue grimper sur la structure de l'échafaudage plutôt que par l'échelle. Cette pratique…",
    ok:"l'expose au vide, sans aucun garde-corps pour le retenir",
    nok:["reste sans risque tant qu'il tient fermement la structure","n'est dangereuse que si l'échafaudage a plus de deux niveaux"],
    exp:"Grimper à la structure, c'est se placer au-dessus du vide sans aucune protection." },
  { m:"M1", q:"Le risque de chute existe au bord d'un plancher…",
    ok:"dès qu'aucun obstacle efficace ne retient la personne",
    nok:["seulement si le plancher est mouillé ou glissant ce jour-là","uniquement en l'absence totale de tout collègue formé"],
    exp:"C'est l'absence d'obstacle efficace au bord du vide qui crée le risque, pas l'état du sol ni la présence de collègues." },
  { m:"M1", sc:"objet-tombe", q:"Une chute d'objet depuis un plancher en hauteur…",
    ok:"est un risque distinct, qui touche les personnes situées en dessous",
    nok:["est la même chose qu'une chute de hauteur pour la personne elle-même","ne concerne que le rangement du matériel sur le chantier, pas la sécurité"],
    exp:"Le risque de chute d'objets menace ceux qui circulent en dessous, en plus du risque de chute de la personne elle-même." },
  { m:"M1", q:"Vous préparez votre poste de travail en hauteur. Le risque de chute doit être traité…",
    ok:"avant de commencer, en même temps que le reste de la préparation",
    nok:["seulement après qu'un premier incident soit constaté sur le site","uniquement si le chantier dépasse déjà une semaine de travail"],
    exp:"Le risque de chute s'anticipe dès la préparation, il ne se traite pas après coup." },
  { m:"M1", r:["DC1.a.02"], q:"La prévention du risque de chute concerne…",
    ok:"la santé des personnes, mais aussi la responsabilité de l'entreprise et le coût d'un accident",
    nok:["seulement la santé de la personne qui travaille en hauteur ce jour précis, sans considérer le reste","uniquement le coût financier supporté par l'entreprise, sans aucun lien avec la sécurité"],
    exp:"La prévention a un enjeu humain, juridique et économique : ils se combinent, aucun ne suffit seul." },

  /* ---------- M2 · Acteurs et responsabilités ---------- */
  { m:"M2", r:["DC1.b.01"], q:"Qui autorise un salarié à utiliser, vérifier ou monter un échafaudage ?",
    ok:"l'employeur, selon le rôle confié à chacun",
    nok:["le fabricant de l'échafaudage, par sa notice","le premier collègue arrivé sur le chantier"],
    exp:"C'est l'employeur qui autorise l'utilisation, la vérification ou le montage, selon la formation et le rôle de chacun." },
  { m:"M2", sc:"montage-niveau", q:"Le montage d'un échafaudage est dirigé par…",
    ok:"une personne compétente, désignée pour cette mission",
    nok:["le plus expérimenté du chantier, sans désignation particulière","l'utilisateur final, une fois la structure achevée"],
    exp:"La direction du montage revient à une personne compétente désignée, pas simplement à la personne la plus ancienne." },
  { m:"M2", r:["DC1.b.03"], q:"Sur un chantier, les rôles monteur, utilisateur et vérificateur…",
    ok:"peuvent être tenus par des personnes différentes, ou par la même",
    nok:["sont toujours répartis à parts égales entre trois personnes distinctes","sont nécessairement confiés à une seule et même personne"],
    exp:"L'organisation dépend du chantier : rien n'impose ni trois personnes séparées, ni une seule." },
  { m:"M2", sc:"signaler-responsable", q:"Le chef de chantier vous demande de monter un échafaudage alors que vous n'y êtes pas formé. Vous devez…",
    ok:"refuser cette tâche et le signaler",
    nok:["accepter, en faisant particulièrement attention","accepter, si un collègue formé regarde faire"],
    exp:"Une tâche non autorisée par la formation reçue se refuse, elle ne se compense pas par la prudence." },
  { m:"M2", q:"Vous êtes utilisateur d'un échafaudage. On vous demande de le démonter en urgence. Vous devez…",
    ok:"refuser cette tâche, qui n'entre pas dans votre rôle",
    nok:["accepter, si la tâche paraît simple à réaliser","s'y risquer, en démontant lentement pour limiter le risque"],
    exp:"L'utilisateur n'est pas autorisé à monter ni à démonter : ce rôle revient au monteur formé." },
  { m:"M2", sc:"element-manquant", q:"Vous repérez un garde-corps manquant sur un plancher que vous utilisez. Vous devez…",
    ok:"ne pas utiliser la zone et le signaler à la personne responsable",
    nok:["ajouter vous-même un élément de fortune pour continuer à travailler","attendre que le vérificateur le remarque de lui-même un jour"],
    exp:"Refuser ce qu'on n'est pas autorisé à réparer soi-même, et signaler, protège tout le monde." },
  { m:"M2", sc:"verification-checklist", q:"Le vérificateur journalier d'un échafaudage est…",
    ok:"souvent l'utilisateur lui-même, à condition d'y être formé",
    nok:["toujours confiée à une entreprise extérieure spécialisée","généralement la même personne que le monteur, désignée pour ce rôle"],
    exp:"La vérification journalière est proche de l'utilisateur, à condition qu'il ait reçu la formation nécessaire." },
  { m:"M2", q:"Un rôle non autorisé par sa formation…",
    ok:"se refuse, même si la tâche paraît facile",
    nok:["se tente prudemment, en cas de besoin urgent","se délègue à un collègue tout aussi peu formé"],
    exp:"L'autorisation vient de la formation reçue, pas de la simplicité apparente de la tâche." },
  { m:"M2", sc:"signaler-responsable", q:"Vous constatez qu'un collègue monte sur l'échafaudage sans y être autorisé. Vous devez…",
    ok:"le signaler au responsable du chantier",
    nok:["le laisser faire, ce n'est pas votre rôle de surveiller","l'aider pour que ce soit fait plus vite"],
    exp:"Une situation dangereuse se signale au responsable, on ne la laisse pas passer ni on ne l'accompagne." },
  { m:"M2", r:["DC1.b.02"], q:"Sur un chantier, la prévention des risques implique…",
    ok:"plusieurs acteurs, pas seulement le monteur ou l'utilisateur",
    nok:["seulement l'employeur, les autres n'ont pas de rôle particulier","seulement la personne qui se trouve en hauteur ce jour-là"],
    exp:"Employeur, monteur, vérificateur, utilisateur : la prévention associe plusieurs acteurs, chacun avec son rôle." },
  { m:"M2", sc:"signaler-responsable", r:["DC1.f.01"], q:"Vous connaissez une consigne de sécurité qu'un nouveau collègue ignore. Vous devez…",
    ok:"la lui faire connaître avant qu'il ne s'expose au risque",
    nok:["le laisser l'apprendre par lui-même, un jour ou l'autre, sur le terrain","le signaler seulement le jour où il se met vraiment en danger"],
    exp:"Connaître une consigne de sécurité, c'est aussi la transmettre à qui l'ignore, avant l'exposition au risque." },

  /* ---------- M3 · Les protections, dans l'ordre ---------- */
  { m:"M3", q:"Avant d'envisager un harnais, on cherche d'abord…",
    ok:"à supprimer le risque, par exemple en travaillant depuis le sol",
    nok:["à choisir un harnais bien réglé à sa taille avant de monter","à vérifier la météo prévue pour la journée de travail"],
    exp:"Supprimer le risque à la source passe avant toute protection, y compris collective." },
  { m:"M3", sc:"collectif-avant-individuel", q:"Entre la protection collective et la protection individuelle, la priorité va…",
    ok:"à la protection collective, comme le garde-corps",
    nok:["à la protection individuelle, plus rapide à installer","aux deux en même temps, sans ordre particulier"],
    exp:"La protection collective doit être privilégiée sur la protection individuelle." },
  { m:"M3", sc:"garde-corps-trois-elements", r:["R-10"], q:"Un garde-corps complet comporte…",
    ok:"une lisse, une lisse intermédiaire et une plinthe",
    nok:["une lisse et un filet de protection, sans autre élément","deux lisses identiques superposées l'une sur l'autre"],
    exp:"Les trois éléments réglementaires du garde-corps sont la lisse, la lisse intermédiaire et la plinthe." },
  { m:"M3", sc:"garde-corps-trois-elements", q:"La hauteur d'un garde-corps réglementaire se situe…",
    ok:"entre un mètre et 1,10 mètre",
    nok:["entre 1,50 mètre et 1,80 mètre","entre 50 centimètres et 80 centimètres"],
    exp:"Le Code du travail fixe une hauteur de garde-corps comprise entre un mètre et 1,10 m." },
  { m:"M3", sc:"garde-corps-trois-elements", q:"La plinthe de butée, en bas du garde-corps, mesure…",
    ok:"de 10 à 15 centimètres",
    nok:["de 30 à 40 centimètres","de 2 à 5 centimètres"],
    exp:"La plinthe fait 10 à 15 cm selon la hauteur retenue pour le garde-corps ; elle arrête ce qui glisse au sol du plancher." },
  { m:"M3", sc:"element-manquant", q:"Vous constatez qu'un garde-corps manque sur votre poste de travail. Vous devez…",
    ok:"signaler le manque avant toute utilisation de la zone",
    nok:["mettre un harnais et continuer sans le garde-corps","travailler en restant loin du bord manquant, prudemment"],
    exp:"Une protection collective absente se signale et se rétablit, un harnais ne la remplace pas au débotté." },
  { m:"M3", sc:"port-charge", r:["DC1.e.01"], q:"Vous devez déplacer une charge sur le plancher de l'échafaudage. Vous la portez…",
    ok:"près du corps, en gardant le dos droit",
    nok:["à bout de bras, pour mieux voir où poser les pieds","sur une épaule, en tournant le buste pour avancer"],
    exp:"Porter une charge près du corps, dos droit, limite l'effort et le risque de déséquilibre." },
  { m:"M3", q:"Vous montez sur l'échafaudage : l'accès et l'équipement doivent être vérifiés…",
    ok:"l'accès d'abord, puis l'équipement de protection",
    nok:["l'équipement d'abord, l'accès n'a pas besoin de contrôle","les deux en même temps, sans ordre particulier"],
    exp:"On vérifie l'accès avant de s'équiper : un accès dangereux ne se compense pas par un équipement." },
  { m:"M3", sc:"harnais-ancrage", q:"Le harnais et la longe, en travail en hauteur, sont…",
    ok:"un dernier recours, quand la protection collective ne suffit pas",
    nok:["le premier moyen de protection à installer sur le chantier","facultatifs si le geste à faire semble bref et sans risque particulier"],
    exp:"La protection individuelle vient compléter la protection collective, jamais la remplacer d'emblée." },

  /* ---------- M4 · Signaler, rendre compte, réagir ---------- */
  { m:"M4", sc:"chute-bord-vide", r:["DC1.c.03"], q:"Face à un danger immédiat sur l'échafaudage, le premier réflexe est de…",
    ok:"arrêter l'activité et faire descendre les personnes exposées",
    nok:["continuer prudemment jusqu'à la fin de la tâche engagée","attendre l'avis du vérificateur avant d'agir soi-même directement"],
    exp:"On stoppe et on met les personnes à l'abri avant toute autre démarche." },
  { m:"M4", sc:"signaler-responsable", r:["DC1.c.02"], q:"Après avoir fait descendre les personnes exposées à un danger immédiat, il faut…",
    ok:"prévenir le responsable du chantier",
    nok:["reprendre le travail une fois le calme revenu","attendre la pause suivante pour en parler"],
    exp:"Prévenir tout de suite permet de traiter le danger avant qu'il ne cause un accident." },
  { m:"M4", sc:"alerte-secours", r:["DC1.c.04"], q:"Un collègue chute et reste au sol sans réagir. Votre premier geste est de…",
    ok:"protéger la zone, puis alerter les secours",
    nok:["le relever immédiatement pour le mettre à l'abri","attendre qu'il reprenne connaissance seul"],
    exp:"L'ordre est protéger, alerter, secourir : on ne déplace pas une victime avant d'avoir alerté." },
  { m:"M4", sc:"alerte-secours", r:["DC1.c.01"], q:"Vous devez alerter les secours après un accident sur le chantier. Vous appelez…",
    ok:"le 15, le 18 ou le 112",
    nok:["uniquement le numéro interne de l'entreprise","uniquement les renseignements téléphoniques"],
    exp:"Le 15, le 18 et le 112 sont les numéros d'urgence à composer pour alerter les secours." },
  { m:"M4", sc:"signaler-responsable", r:["DC1.d.02"], q:"Vous repérez une anomalie sur un échafaudage que vous n'utilisez pas encore. Vous devez…",
    ok:"la signaler au responsable avant que quiconque ne monte",
    nok:["la signaler seulement si quelqu'un monte devant vous","attendre la prochaine réunion de chantier pour en parler"],
    exp:"Le signalement doit être rapide, avant l'exposition de quiconque au danger." },
  { m:"M4", q:"Rendre compte d'une anomalie signifie…",
    ok:"informer la personne responsable avec des faits précis",
    nok:["en parler seulement si quelqu'un le demande","l'écrire dans un carnet personnel, sans le transmettre"],
    exp:"Rendre compte suppose une information précise, transmise à la personne responsable." },
  { m:"M4", q:"Réparer soi-même une anomalie qui n'entre pas dans sa tâche…",
    ok:"expose à un risque non maîtrisé",
    nok:["est toujours plus rapide et sans danger","est encouragé si l'on connaît bien le matériel"],
    exp:"Une réparation non prévue par la tâche confiée peut aggraver un risque déjà présent." },
  { m:"M4", sc:"chute-bord-vide", q:"En pleine tâche, vous entendez un craquement inhabituel dans la structure. Vous devez…",
    ok:"arrêter l'activité et faire descendre les personnes présentes",
    nok:["continuer en observant si le bruit inhabituel se répète","signaler le bruit seulement en fin de journée de travail"],
    exp:"Un signe inhabituel de danger immédiat impose l'arrêt et la mise à l'abri, sans attendre confirmation." },
  { m:"M4", r:["DC1.b.04"], q:"Face à un danger grave et imminent, un salarié…",
    ok:"peut se retirer de la situation et doit alerter",
    nok:["doit rester posté jusqu'à l'arrivée du responsable","peut seulement en parler à la pause suivante"],
    exp:"Le droit de retrait s'exerce face à un danger grave et imminent, accompagné d'une alerte." },
  { m:"M4", r:["DC1.d.01"], q:"Un accident du travail a le plus souvent…",
    ok:"plusieurs causes qui se combinent, presque toujours, pas une seule",
    nok:["une seule cause, facile à identifier tout de suite après coup","aucune cause identifiable, un accident relève surtout du hasard"],
    exp:"Un accident résulte en général de plusieurs causes combinées (pluricausalité), pas d'une cause unique." },

  /* ---------- M5 · Familles d'échafaudages ---------- */
  { m:"M5", sc:"echafaudage-complet", q:"Un échafaudage de pied est un échafaudage…",
    ok:"fixe, posé au sol",
    nok:["monté sur roues, déplaçable à la main","suspendu à la façade par des câbles"],
    exp:"L'échafaudage de pied repose au sol, contrairement au roulant ou au suspendu." },
  { m:"M5", sc:"echafaudage-complet", r:["2.1.01"], q:"Les deux grandes familles d'échafaudages de pied sont…",
    ok:"à cadres et multidirectionnels",
    nok:["en bois et en métal léger","à un niveau et à plusieurs niveaux"],
    exp:"On distingue les échafaudages de pied à cadres et les multidirectionnels." },
  { m:"M5", sc:"roulant-vs-pied", q:"Un échafaudage roulant relève…",
    ok:"d'une autre recommandation que celle des échafaudages de pied",
    nok:["exactement de la même recommandation que les échafaudages de pied","d'aucune recommandation particulière"],
    exp:"L'échafaudage roulant suit la R457, distincte de la R408 des échafaudages de pied." },
  { m:"M5", sc:"roulant-vs-pied", q:"On vous propose un échafaudage roulant pour un chantier prévu avec un échafaudage de pied. Vous devez…",
    ok:"signaler que ce n'est pas le même type d'échafaudage",
    nok:["l'utiliser, les deux se montent exactement de la même façon","l'accepter, en ajoutant simplement des roues bloquées"],
    exp:"Échafaudage de pied et échafaudage roulant ne suivent pas les mêmes règles de montage ni d'usage." },
  { m:"M5", r:["R-08"], q:"L'échafaudage suspendu et la console…",
    ok:"existent, mais ne sont pas enseignés à ce niveau",
    nok:["n'existent pas dans les échafaudages de chantier","sont les deux noms d'un même échafaudage de pied"],
    exp:"Ces familles existent mais restent hors du programme du CAP ; on retient seulement leur nom." },
  { m:"M5", r:["2.1.02"], q:"Vous devez repeindre une façade en hauteur pour un travail léger, sans stockage. Le choix de l'échafaudage dépend d'abord…",
    ok:"du type de travail à réaliser et du domaine d'emploi de l'échafaudage",
    nok:["de l'échafaudage disponible le plus proche du dépôt du chantier","du modèle utilisé la dernière fois sur le chantier, par simple habitude"],
    exp:"Le choix suit le besoin du chantier et le domaine d'emploi prévu, pas la disponibilité ou l'habitude." },
  { m:"M5", r:["2.1.03"], q:"Le domaine d'emploi d'un échafaudage indique…",
    ok:"pour quels travaux et quelles charges il a été conçu",
    nok:["sa couleur et le nom de sa marque commerciale du moment","le nombre d'années écoulées depuis sa fabrication"],
    exp:"Le domaine d'emploi précise l'usage pour lequel l'échafaudage a été conçu et testé, notamment sa capacité portante." },
  { m:"M5", sc:"echafaudage-complet", q:"Sur le chantier, vous reconnaissez un échafaudage à cadres. Savoir cela vous permet…",
    ok:"de connaître les règles de montage et d'usage qui s'appliquent",
    nok:["de connaître son prix de location pour la journée de travail","de deviner sa date de fabrication exacte à l'usine d'origine"],
    exp:"Reconnaître la famille d'un échafaudage renseigne sur ses règles propres de montage et d'usage." },
  { m:"M5", sc:"terrasse-toiture", q:"Une toiture-terrasse équipée d'un garde-corps périphérique fixe…",
    ok:"protège le travail sans recourir à un échafaudage",
    nok:["impose quand même le montage d'un échafaudage de pied","n'a besoin d'aucune protection particulière"],
    exp:"Un garde-corps périphérique fixe protège le travail en hauteur sans échafaudage." },
  { m:"M5", r:["2.1.04"], q:"Un échafaudage est aussi identifié par…",
    ok:"une classe, qui indique le type de travaux et de charges admis",
    nok:["une couleur, propre à chaque fabricant, sans autre signification","un numéro de série, sans lien avec son usage sur le chantier"],
    exp:"La classe d'un échafaudage renseigne sur les travaux et les charges qu'il admet ; elle est précisée sur l'étiquette." },
  { m:"M5", r:["2.1.05"], q:"Montant, lisse, plancher, diagonale…",
    ok:"sont les noms des éléments qui composent un échafaudage",
    nok:["sont des noms réservés aux seuls échafaudages à cadres","changent de sens selon la marque du fabricant"],
    exp:"Chaque élément d'un échafaudage a un nom précis, le même d'un fabricant à l'autre." },
  { m:"M5", r:["2.1.06"], q:"Un plancher en porte-à-faux ou en déport…",
    ok:"est une configuration particulière, qui sort du montage simple",
    nok:["est la configuration la plus courante d'un échafaudage de pied","n'existe que sur les échafaudages roulants"],
    exp:"Porte-à-faux et déport sont des configurations particulières, à distinguer du montage simple appris en CAP." },
  { m:"M5", r:["2.1.07"], q:"Les échafaudages « Montage-Démontage en Sécurité » (MDS)…",
    ok:"protègent les monteurs eux-mêmes pendant qu'ils montent la structure",
    nok:["ne concernent que les utilisateurs, une fois l'échafaudage terminé","remplacent la vérification journalière une fois le montage fini"],
    exp:"Un échafaudage MDS offre une protection collective aux monteurs pendant le montage lui-même." },

  /* ---------- M6 · La notice et l'étiquette ---------- */
  { m:"M6", sc:"notice-fabricant", r:["2.2.01"], q:"La notice du fabricant d'un échafaudage fixe…",
    ok:"ses conditions de montage et d'emploi",
    nok:["uniquement son prix et ses références commerciales","une suggestion facultative, sans obligation"],
    exp:"La notice encadre le montage et l'emploi de l'échafaudage ; elle n'est pas facultative." },
  { m:"M6", sc:"etiquette-montant", q:"Le panneau affiché sur un échafaudage réceptionné indique notamment…",
    ok:"les conditions d'utilisation et les charges admissibles",
    nok:["la météo prévue pour la semaine de chantier à venir","le nom de l'entreprise voisine installée sur le chantier"],
    exp:"Le panneau porte les conditions d'utilisation et les charges admissibles du plancher." },
  { m:"M6", sc:"etiquette-montant", q:"Le panneau d'un échafaudage interdit aussi…",
    ok:"l'accès aux personnes non autorisées",
    nok:["l'accès aux jours de pluie uniquement","l'accès au-delà du premier niveau seulement"],
    exp:"Le panneau signale que l'accès est réservé aux personnes autorisées." },
  { m:"M6", sc:"etiquette-montant", r:["R-11"], q:"Vous arrivez devant un échafaudage sans aucune étiquette ni panneau. Vous devez…",
    ok:"ne pas l'utiliser et le signaler",
    nok:["l'utiliser, l'étiquette n'est qu'une formalité","chercher l'étiquette pendant que vous montez"],
    exp:"Un échafaudage sans étiquette ne se monte pas ni ne s'utilise : on signale l'absence avant toute chose." },
  { m:"M6", sc:"notice-fabricant", q:"Avant de monter sur un échafaudage déjà en place, vous consultez d'abord…",
    ok:"son panneau et, si besoin, sa notice",
    nok:["votre propre ressenti de la stabilité de l'ensemble","l'avis d'un passant présent sur le chantier"],
    exp:"Le panneau et la notice donnent une information vérifiable, pas une impression personnelle." },
  { m:"M6", sc:"notice-fabricant", r:["2.2.03"], q:"Quand le montage correspond à celui prévu par la notice, il est réalisé…",
    ok:"conformément à ce document",
    nok:["selon l'expérience personnelle du monteur","avec un plan improvisé sur le chantier"],
    exp:"Quand la notice prévoit le montage envisagé, on s'y conforme : elle n'est pas une simple base de travail." },
  { m:"M6", q:"La notice du fabricant ne prévoit pas la configuration demandée sur ce chantier. Il faut alors…",
    ok:"une note de calcul ou un plan établi par une personne compétente",
    nok:["improviser une configuration proche de celle déjà connue","utiliser la notice d'un échafaudage voisin du chantier, par défaut"],
    exp:"Sans notice applicable, une personne compétente établit un calcul ou un plan adapté." },
  { m:"M6", q:"La notice du fabricant doit rester…",
    ok:"accessible sur le lieu de travail",
    nok:["conservée uniquement au bureau de l'entreprise","transmise oralement, sans document écrit"],
    exp:"La notice et ses documents associés se conservent sur le lieu de travail, à disposition." },
  { m:"M6", sc:"plancher-surcharge", q:"Vous constatez que le panneau des charges admissibles a disparu. Vous devez…",
    ok:"signaler l'absence avant de charger le plancher",
    nok:["estimer vous-même la charge admissible à vue d'œil","charger comme d'habitude, sans vous en préoccuper"],
    exp:"Sans indication vérifiable des charges admissibles, on ne peut pas garantir de ne pas les dépasser : on signale." },
  { m:"M6", sc:"notice-fabricant", r:["2.2.02"], q:"Le nombre et la place des ancrages d'un échafaudage…",
    ok:"changent selon le montage : la notice les précise pour chaque configuration",
    nok:["sont toujours identiques, quel que soit le montage réellement réalisé sur le chantier","se choisissent librement sur le chantier, selon les besoins du moment présent"],
    exp:"Chaque configuration de montage a ses propres ancrages, fixés par la notice — jamais un chiffre unique valable partout." },
  { m:"M6", sc:"etiquette-montant", r:["R-06"], q:"Vous devez stocker des sacs de plâtre sur un plancher d'échafaudage. Vous vérifiez d'abord…",
    ok:"la classe affichée sur l'étiquette et la charge admissible en kg/m²",
    nok:["le nombre de sacs déjà posés par vos collègues la veille au soir","la taille du plancher, à l'œil, sans autre vérification particulière"],
    exp:"La classe et la charge admissible sont affichées sur l'étiquette : on les lit avant de stocker, on ne les devine pas." },
  { m:"M6", sc:"etiquette-montant", r:["R-06"], q:"Un échafaudage peut appartenir à…",
    ok:"six classes de charge différentes, indiquées sur son étiquette",
    nok:["une seule classe, valable pour tous les échafaudages de pied existants","trois classes seulement, au-delà de quoi tout est strictement interdit"],
    exp:"La norme distingue six classes de charge ; celle de l'échafaudage utilisé est celle indiquée sur son étiquette, pas une valeur devinée." },

  /* ---------- M7 · Utiliser en sécurité ---------- */
  { m:"M7", sc:"acces-interieur-trappe", r:["4.2.02"], q:"Vous devez monter au deuxième niveau de l'échafaudage. Vous passez…",
    ok:"par l'échelle intérieure et la trappe du plancher",
    nok:["par l'extérieur, en grimpant aux montants, c'est plus rapide","par le garde-corps, en prenant appui sur la lisse"],
    exp:"L'accès se fait par l'intérieur : échelle et trappe. Grimper à la structure expose au vide sans protection." },
  { m:"M7", sc:"acces-interieur-trappe", r:["4.2.02"], q:"Vous venez de passer la trappe pour accéder au plancher. Vous devez…",
    ok:"la refermer aussitôt",
    nok:["la laisser ouverte pour redescendre plus vite","la bloquer en position ouverte pour la journée"],
    exp:"Une trappe restée ouverte crée un trou dans le garde-corps du plancher : on la referme après passage." },
  { m:"M7", sc:"echafaudage-complet", q:"On peut travailler sur un plancher d'échafaudage…",
    ok:"une fois le plancher et le garde-corps complets",
    nok:["dès qu'une partie du plancher est posée","dès que le garde-corps d'un seul côté est en place"],
    exp:"Un plancher ou un garde-corps incomplet laisse un danger : on attend qu'ils soient complets." },
  { m:"M7", r:["4.2.04"], q:"Un garde-corps vous gêne pour manœuvrer une charge. Vous devez…",
    ok:"ne pas le modifier ni le retirer",
    nok:["le déplacer le temps de la manœuvre, puis le remettre","le retirer si vous le remettez avant la fin du poste"],
    exp:"Modifier ou retirer un élément de protection reste réservé à une personne compétente formée pour cela." },
  { m:"M7", sc:"plancher-surcharge", r:["4.2.03","R-09"], q:"Le plancher que vous utilisez porte déjà plusieurs sacs de matériaux. Vous devez…",
    ok:"vérifier que la charge totale ne dépasse pas la charge admissible",
    nok:["ajouter votre matériel, le plancher supporte toujours plus","déplacer les sacs vers le bord pour dégager le centre du plancher"],
    exp:"On ne dépasse jamais la charge admissible affichée, quelle que soit la répartition choisie." },
  { m:"M7", sc:"objet-tombe", r:["4.2.05"], q:"Un outil laissé au bord d'un plancher…",
    ok:"risque de tomber sur une personne située en dessous",
    nok:["reste sans danger tant qu'il ne glisse pas du plancher","concerne uniquement le rangement, pas la sécurité"],
    exp:"Un objet au bord d'un plancher peut chuter et blesser une personne en dessous." },
  { m:"M7", sc:"vent-bache", r:["R-12"], q:"Le vent forcit nettement pendant que vous travaillez sur l'échafaudage. Vous devez…",
    ok:"interrompre le travail et prévenir le responsable",
    nok:["continuer en vous tenant plus fermement","poursuivre si vous restez loin du bord du plancher"],
    exp:"Un changement notable des conditions météo, comme un vent fort, impose d'arrêter et de prévenir." },
  { m:"M7", sc:"coactivite-balisage", r:["4.2.05"], q:"Une autre équipe travaille au sol, sous l'échafaudage que vous utilisez. Vous devez…",
    ok:"tenir compte de sa présence pour éviter toute chute d'objet vers elle",
    nok:["l'ignorer, la coactivité ne concerne que le vérificateur désigné","lui demander de s'écarter, sans autre précaution de votre part"],
    exp:"La coactivité impose de tenir compte des personnes présentes en dessous ou à proximité, pas seulement de les écarter." },
  { m:"M7", q:"Les accès de l'échafaudage doivent rester…",
    ok:"dégagés en permanence",
    nok:["réservés au chef d'équipe uniquement","fermés en dehors des horaires de pause"],
    exp:"Un accès encombré ou fermé gêne la montée, la descente et une éventuelle évacuation." },
  { m:"M7", r:["4.2.01"], q:"Pour utiliser un échafaudage, un opérateur porte…",
    ok:"casque, chaussures de sécurité et gants adaptés au travail",
    nok:["une tenue légère, plus pratique pour réaliser les gestes fins","uniquement des gants, le reste de l'équipement étant facultatif"],
    exp:"L'utilisateur porte ses équipements de protection individuelle de base avant de monter, comme le monteur." },
  { m:"M7", r:["4.2.01"], q:"Vous devez monter sur l'échafaudage sans casque, le vôtre étant resté au vestiaire. Vous devez…",
    ok:"aller le chercher avant de monter",
    nok:["monter quand même, le trajet est court","emprunter le casque d'un collègue qui travaille au sol"],
    exp:"L'équipement de protection individuelle se porte avant de monter, sans exception pour un trajet jugé court." },
  { m:"M7", sc:"plancher-surcharge", r:["4.2.03","R-09"], q:"Le plancher affiche une charge admissible de 150 kg/m². Vous devez stocker des sacs supplémentaires. Vous devez…",
    ok:"refuser si la charge totale dépasse cette limite affichée",
    nok:["stocker quand même, la limite laisse toujours une marge","répartir les sacs sur tout le plancher pour rester en dessous"],
    exp:"La charge admissible affichée ne se dépasse jamais, même en répartissant différemment le stockage." },
  { m:"M7", r:["4.2.04"], q:"Vous trouvez qu'un montant gênerait moins le passage un peu plus loin. Vous devez…",
    ok:"laisser l'échafaudage tel qu'il a été monté et signaler la gêne",
    nok:["déplacer le montant vous-même, puis le remettre en fin de poste","le retirer temporairement, le temps de faire passer le matériel"],
    exp:"Aucune modification de l'échafaudage ne s'improvise, même pour une gêne ponctuelle : on signale, on ne touche pas." },

  /* ---------- M8 · Cadre des vérifications ---------- */
  { m:"M8", sc:"verification-checklist", q:"Les vérifications d'un échafaudage sont réalisées…",
    ok:"à des moments différents, par des personnes désignées selon leur rôle",
    nok:["toujours par la même personne désignée, quelle que soit la fréquence exacte","uniquement à la demande expresse de l'utilisateur du jour"],
    exp:"Le cadre distingue plusieurs vérifications, chacune confiée à une personne désignée pour ce rôle." },
  { m:"M8", q:"La vérification faite avant la première utilisation s'appelle…",
    ok:"la vérification de mise en service",
    nok:["la vérification générale trimestrielle","la vérification journalière d'usage"],
    exp:"La mise en service précède la première utilisation ; les autres vérifications suivent à d'autres moments." },
  { m:"M8", q:"Après un démontage suivi d'un remontage, l'échafaudage doit subir…",
    ok:"une vérification de remise en service",
    nok:["seulement la prochaine vérification trimestrielle prévue","aucune vérification, le montage initial suffit"],
    exp:"Un démontage suivi d'un remontage déclenche une nouvelle vérification, dite de remise en service." },
  { m:"M8", sc:"verification-checklist", q:"Trois mois se sont écoulés depuis la dernière vérification générale. Il faut…",
    ok:"réaliser la vérification trimestrielle prévue",
    nok:["attendre un signalement avant de vérifier","se contenter de la vérification journalière habituelle"],
    exp:"La vérification trimestrielle s'ajoute à la vérification journalière, à intervalle régulier." },
  { m:"M8", q:"Ce qui est constaté lors d'une vérification est…",
    ok:"consigné dans un registre de sécurité",
    nok:["gardé uniquement dans la mémoire du vérificateur","annoncé oralement, sans aucune trace écrite"],
    exp:"Les constats et les mesures prises sont consignés par écrit, dans un registre de sécurité." },
  { m:"M8", sc:"verification-checklist", q:"Vous ne savez pas si l'échafaudage que vous devez utiliser a été vérifié. Vous devez…",
    ok:"le demander avant de monter dessus",
    nok:["monter, la vérification concerne le vérificateur, pas vous","monter, l'absence de plainte antérieure suffit à rassurer"],
    exp:"Utiliser un échafaudage sans savoir s'il a été vérifié expose à un risque non maîtrisé." },
  { m:"M8", sc:"element-manquant", q:"On vous demande de monter sur un échafaudage jamais vérifié depuis son installation. Vous devez…",
    ok:"refuser, tant que la vérification de mise en service n'est pas faite",
    nok:["accepter, en restant particulièrement prudent pendant toute la montée","s'y risquer, si le montage semble visiblement solide et fini"],
    exp:"Sans vérification de mise en service, l'échafaudage ne peut pas être considéré comme sûr, même s'il paraît solide." },
  { m:"M8", q:"Savoir qui vérifie quoi, et quand, sert à…",
    ok:"éviter qu'un contrôle nécessaire soit oublié",
    nok:["répartir également le travail entre collègues","respecter une habitude propre à chaque chantier"],
    exp:"Le cadre des vérifications garantit qu'aucun contrôle nécessaire n'est laissé de côté." },
  { m:"M8", r:["3.3.04"], q:"La vérification de mise en service et la vérification trimestrielle…",
    ok:"répondent à des moments et des objectifs différents",
    nok:["se remplacent l'une l'autre selon la préférence du chantier","ne concernent que les grands chantiers de plusieurs mois"],
    exp:"Chaque vérification a son propre moment et son propre objectif, l'une ne dispense pas de l'autre." },
  { m:"M8", r:["3.3.03"], q:"Le contenu et la fréquence des vérifications d'un échafaudage…",
    ok:"sont fixés par une réglementation propre aux échafaudages",
    nok:["dépendent seulement des habitudes prises sur chaque chantier","sont laissés au choix de l'entreprise qui utilise l'échafaudage"],
    exp:"Une réglementation spécifique fixe le contenu et la fréquence des vérifications : ce n'est pas une habitude de chantier." },

  /* ---------- M9 · Vérification journalière ---------- */
  { m:"M9", sc:"verification-checklist", q:"La vérification journalière porte sur…",
    ok:"l'état de conservation de l'échafaudage",
    nok:["le prix de location de la structure","le nombre de personnes présentes sur le chantier"],
    exp:"On regarde ce qui a pu changer depuis la veille : déformation, protections, calage." },
  { m:"M9", sc:"verification-checklist", q:"Avant de monter chaque matin, vous devez…",
    ok:"examiner l'échafaudage avant de vous en servir",
    nok:["faire confiance à la vérification du premier jour","attendre le signalement d'un collègue pour vérifier"],
    exp:"La vérification journalière revient à l'utilisateur, chaque jour, avant usage." },
  { m:"M9", sc:"element-manquant", r:["3.4.06"], q:"Vous découvrez une lisse intermédiaire manquante sur un plancher. Vous devez…",
    ok:"ne pas utiliser la zone et signaler le manque",
    nok:["continuer en vous tenant loin du côté concerné","attendre la vérification trimestrielle pour le signaler"],
    exp:"Un élément de garde-corps manquant est une dégradation qui empêche l'utilisation tant qu'elle n'est pas traitée." },
  { m:"M9", sc:"semelle-cale-verin", r:["3.4.04","3.4.10"], q:"L'examen de l'état de conservation vérifie notamment…",
    ok:"les appuis, le calage, les amarrages et les planchers",
    nok:["le planning des congés et des horaires de toute l'équipe","la marque commerciale des éléments posés sur le chantier"],
    exp:"L'examen porte sur ce qui assure la stabilité et la sécurité : appuis, calage, amarrages, planchers." },
  { m:"M9", r:["R-04"], q:"Vous remarquez que le plancher est éloigné de plus de vingt centimètres de la façade, sans protection. Vous devez…",
    ok:"signaler cette non-conformité avant d'utiliser la zone",
    nok:["l'accepter, un écart de vingt centimètres reste sans risque","combler l'écart vous-même avec du matériel disponible"],
    exp:"Un vide de plus de vingt centimètres entre le plancher et la façade, sans protection, est une non-conformité à signaler." },
  { m:"M9", r:["3.4.01"], q:"Un élément d'échafaudage visiblement corrodé ou déformé…",
    ok:"signale une dégradation à traiter avant toute utilisation",
    nok:["reste utilisable tant qu'il ne casse pas visiblement","concerne uniquement la vérification trimestrielle prévue"],
    exp:"Une déformation ou une corrosion visible fait partie de ce que recherche l'examen journalier." },
  { m:"M9", sc:"element-manquant", r:["3.4.01"], q:"Vous constatez une dégradation dès le matin, avant de monter. Vous devez…",
    ok:"ne pas utiliser l'échafaudage tant qu'elle n'est pas traitée",
    nok:["l'utiliser en évitant simplement la zone concernée ce jour","attendre le soir pour voir si elle s'aggrave vraiment"],
    exp:"Une dégradation constatée doit être traitée avant l'usage, quelle que soit son importance apparente." },
  { m:"M9", sc:"amarrage-facade", r:["3.4.03","3.4.11"], q:"La vérification de la verticalité et des amarrages sert à…",
    ok:"s'assurer que l'échafaudage n'a pas bougé depuis la veille",
    nok:["contrôler la propreté générale du chantier entier","vérifier la présence de tous les outils du poste de travail"],
    exp:"Vérifier verticalité et amarrages permet de détecter un mouvement de la structure depuis la dernière vérification." },
  { m:"M9", r:["3.4.07","3.4.09"], q:"Un plancher qui n'est plus fixé ni propre lors de l'examen journalier…",
    ok:"constitue une dégradation qui empêche l'utilisation",
    nok:["reste utilisable si le désordre semble limité","concerne seulement le rangement du chantier, pas la sécurité"],
    exp:"Un plancher mal fixé ou encombré n'assure plus une surface de travail sûre : on ne l'utilise pas ainsi." },
  { m:"M9", r:["R-01"], sc:"echafaudage-complet", q:"Un pare-gravois est installé sur l'échafaudage au-dessus d'un passage piéton. Vous devez vérifier qu'il…",
    ok:"est bien fixé, avec un amarrage renforcé à son droit",
    nok:["est simplement posé, sans fixation particulière","est retiré dès que le passage piéton est fermé la nuit"],
    exp:"Le pare-gravois protège les tiers de la chute d'objets ; sa présence impose un amarrage renforcé, à vérifier." },
  { m:"M9", r:["R-01"], q:"Le pare-gravois (écran ou filet en bas de l'échafaudage) sert à…",
    ok:"protéger les personnes qui passent en dessous contre la chute d'objets",
    nok:["décorer la base de l'échafaudage pour le chantier","remplacer le garde-corps sur le premier niveau"],
    exp:"Pare-gravois, écrans et filets arrêtent les objets qui tombent, avant qu'ils n'atteignent les tiers au sol." },
  { m:"M9", r:["R-02"], sc:"vent-bache", q:"Vous devez commencer le montage d'un échafaudage. Une bâche est déjà prête sur le chantier. Vous devez…",
    ok:"ne pas la poser tant que le montage n'est pas terminé",
    nok:["la poser dès le premier niveau, pour protéger le chantier plus tôt","la poser seulement si la météo annonce de la pluie"],
    exp:"On ne bâche jamais un échafaudage en cours de montage : la bâche attend la fin du montage." },
  { m:"M9", r:["R-02","3.4.16"], sc:"vent-bache", q:"Un échafaudage bâché ou couvert de filets…",
    ok:"prend davantage le vent : la fixation et la continuité du bâchage se vérifient",
    nok:["prend moins le vent qu'un échafaudage nu, grâce à la bâche","n'a besoin d'aucune vérification supplémentaire liée au vent"],
    exp:"Une bâche ou un filet augmente la prise au vent de la structure ; leur fixation et leur continuité font partie de la vérification journalière." },
  { m:"M9", r:["3.4.16"], q:"Vous constatez qu'une bâche est déchirée sur un pan de l'échafaudage, avec un trou important. Vous devez…",
    ok:"signaler la discontinuité avant toute utilisation",
    nok:["continuer, une déchirure ne change rien à la solidité de la structure","réparer vous-même avec de l'adhésif de chantier"],
    exp:"La continuité du bâchage sur toute la surface fait partie de ce qui se vérifie chaque jour ; une déchirure se signale." },
  { m:"M9", r:["3.4.02"], q:"Vérifier l'absence de jeu dans les fixations d'un échafaudage, c'est vérifier…",
    ok:"que tous les éléments de liaison sont bien en place et serrés",
    nok:["que la couleur des fixations correspond au fabricant","que le nombre d'éléments correspond à la facture d'achat"],
    exp:"Un jeu décelable dans une fixation ou une liaison peut affecter la solidité de l'ensemble : on le vérifie chaque jour." },
  { m:"M9", r:["3.4.02"], q:"Vous remarquez qu'une fixation entre deux éléments est desserrée, avec un jeu visible. Vous devez…",
    ok:"ne pas utiliser l'échafaudage tant qu'elle n'est pas resserrée",
    nok:["continuer, un léger jeu ne change rien à la solidité","resserrer vous-même rapidement, sans rien signaler ensuite"],
    exp:"Un jeu décelable dans une fixation est une dégradation : on ne l'utilise pas tant qu'elle n'est pas traitée." },
  { m:"M9", r:["3.4.04","3.4.05"], q:"Un échafaudage bien calé au sol…",
    ok:"a toutes ses cales et éléments de stabilisation en place, sans désordre aux appuis",
    nok:["n'a besoin d'aucune vérification une fois le montage terminé","peut se passer de cale si le sol paraît plat"],
    exp:"Le calage et la stabilisation se vérifient : leur absence ou leur désordre compromet les appuis." },
  { m:"M9", r:["3.4.05"], q:"Vous remarquez qu'une cale a disparu sous un montant. Vous devez…",
    ok:"signaler l'absence avant toute utilisation de l'échafaudage",
    nok:["continuer, un seul montant sans cale ne change rien à l'ensemble","ajouter une cale de fortune trouvée sur le chantier, sans le signaler"],
    exp:"La présence de tous les éléments de calage fait partie de la vérification journalière : une cale manquante se signale." },
  { m:"M9", r:["3.4.06"], q:"La continuité des garde-corps sur un échafaudage se vérifie…",
    ok:"chaque jour, avant l'utilisation de chaque plancher, sans exception",
    nok:["une seule fois, lors du montage initial de toute la structure entière","seulement lors de la vérification trimestrielle prévue chaque trimestre"],
    exp:"La protection collective se contrôle chaque jour : un manque n'attend pas la prochaine vérification trimestrielle." },
  { m:"M9", r:["3.4.07","3.4.08"], q:"Le verrouillage anti-soulèvement d'un plancher préfabriqué et l'état de sa trappe…",
    ok:"font tous deux partie de ce que vérifie l'examen journalier",
    nok:["restent réservées à la vérification trimestrielle, pas à l'usage journalier","ne concernent que le montage, jamais l'usage ensuite au quotidien"],
    exp:"Verrouillage anti-soulèvement et trappe font partie des points de vérification journalière du plancher." },
  { m:"M9", sc:"acces-interieur-trappe", r:["3.4.08"], q:"Vous trouvez une trappe restée ouverte, sans personne en train de passer. Vous devez…",
    ok:"la refermer, une trappe ouverte crée un trou dans le plancher",
    nok:["la laisser ouverte, elle sera refermée plus tard en fin de journée","la bloquer ouverte pour faciliter le passage du niveau suivant"],
    exp:"Une trappe ouverte sans passage est un trou dans le garde-corps du plancher : elle doit être fermée." },
  { m:"M9", r:["3.4.09"], q:"Un plancher encombré de matériel qui traîne…",
    ok:"gêne la circulation et se signale lors de la vérification journalière",
    nok:["ne pose problème que les jours où il pleut fortement sur le chantier","concerne uniquement le rangement, jamais vraiment la sécurité au travail"],
    exp:"L'absence d'encombrement du plancher est un point de vérification à part entière, chaque jour." },
  { m:"M9", r:["3.4.10"], q:"Vous comptez les ancrages visibles sur un échafaudage en cours d'utilisation. Un seul manque à l'endroit prévu par la notice. Vous devez…",
    ok:"signaler l'ancrage manquant avant de continuer à utiliser l'échafaudage",
    nok:["continuer, un seul ancrage manquant ne change rien à la stabilité","attendre la vérification trimestrielle prévue pour le signaler au responsable"],
    exp:"Le positionnement et le nombre des ancrages se vérifient chaque jour : un manque se signale sans attendre." },
  { m:"M9", r:["3.4.11"], q:"Vérifier le bon montage et la résistance d'un amarrage, c'est aussi vérifier…",
    ok:"qu'il n'est ni desserré ni endommagé depuis la veille",
    nok:["qu'il porte bien le nom du fabricant de l'échafaudage","qu'il a été acheté récemment"],
    exp:"Un amarrage desserré ou endommagé ne joue plus son rôle : on le vérifie chaque jour, pas seulement au montage." },
  { m:"M9", r:["3.4.12"], q:"Le contreventement d'un échafaudage…",
    ok:"se vérifie : son nombre, sa position et son bon montage",
    nok:["ne se vérifie qu'au moment du montage, jamais ensuite","n'a pas besoin d'être vérifié si l'échafaudage tient debout"],
    exp:"Le positionnement, le nombre et le bon montage des contreventements font partie de l'examen journalier." },
  { m:"M9", r:["3.4.12"], q:"Vous remarquez qu'une diagonale de contreventement est décrochée d'un côté. Vous devez…",
    ok:"signaler le défaut avant d'utiliser l'échafaudage",
    nok:["continuer, les autres diagonales suffisent à tenir l'ensemble","la raccrocher vous-même rapidement, sans rien signaler"],
    exp:"Un contreventement mal monté ou décroché est une dégradation à signaler avant usage." },
  { m:"M9", r:["3.4.13"], q:"La présence de la 3ᵉ lisse sur un échafaudage…",
    ok:"fait partie des moyens d'accès à vérifier chaque jour",
    nok:["ne concerne que le confort du monteur, pas la sécurité","n'existe que sur les échafaudages roulants"],
    exp:"La 3ᵉ lisse, comme moyen d'accès, est un point que l'examen journalier contrôle, au même titre que le reste." },
  { m:"M9", r:["3.4.13"], q:"Vous constatez que la 3ᵉ lisse d'accès n'est pas montée à un niveau que vous devez utiliser. Vous devez…",
    ok:"signaler le manque avant d'emprunter cet accès",
    nok:["utiliser quand même l'accès, en faisant attention","attendre le lendemain pour voir si elle est montée"],
    exp:"Un moyen d'accès incomplet, comme une 3ᵉ lisse manquante, se signale avant d'être emprunté." },
  { m:"M9", r:["3.4.14","3.4.15"], q:"L'indication des charges admissibles sur un échafaudage doit être…",
    ok:"visible, et jamais dépassée par ce qui est stocké",
    nok:["visible seulement pendant le montage, plus ensuite","approximative, la marge de sécurité suffit à compenser"],
    exp:"La vérification journalière porte sur la visibilité de l'indication ET sur l'absence de charges qui la dépassent." },
  { m:"M9", r:["3.4.14"], q:"Vous ne parvenez plus à lire l'indication des charges admissibles, effacée par le temps. Vous devez…",
    ok:"signaler ce défaut avant d'utiliser le plancher pour du stockage",
    nok:["stocker en restant prudent, sans dépasser ce que vous estimez raisonnable","attendre la prochaine vérification trimestrielle pour signaler"],
    exp:"Une indication de charge illisible empêche de vérifier qu'on ne la dépasse pas : elle se signale avant usage." },
  { m:"M9", sc:"plancher-surcharge", r:["3.4.15"], q:"Le plancher porte déjà la charge maximale admissible. Un collègue veut y ajouter du matériel. Vous devez…",
    ok:"refuser, la charge admissible ne se dépasse jamais",
    nok:["accepter si le matériel supplémentaire est léger","accepter, en répartissant tout sur le centre du plancher"],
    exp:"L'absence de dépassement des charges admissibles est un point vérifié chaque jour, sans marge à négocier." },
  { m:"M9", r:["3.4.03"], q:"L'implantation d'un échafaudage se vérifie chaque jour pour s'assurer…",
    ok:"qu'il reste d'aplomb et de niveau, sans avoir bougé depuis la veille",
    nok:["qu'il occupe toujours le même emplacement sur le plan du chantier","que sa couleur n'a pas changé depuis le montage initial de la structure"],
    exp:"La verticalité et l'horizontalité de l'échafaudage se recontrôlent chaque jour, pas seulement au montage." },

  /* ---------- M10 · Préparer le montage ---------- */
  { m:"M10", sc:"semelle-cale-verin", r:["2.4.03"], q:"Avant de monter un échafaudage, on prépare d'abord…",
    ok:"le sol, les appuis et l'implantation",
    nok:["la liste des personnes présentes sur le chantier","le choix de la couleur des éléments"],
    exp:"Une préparation soignée du sol et des appuis conditionne la stabilité de toute la structure." },
  { m:"M10", sc:"semelle-cale-verin", r:["2.4.04"], q:"Sous chaque montant, on trouve généralement…",
    ok:"une semelle, une cale et un vérin réglable",
    nok:["une simple planche posée sans fixation particulière","un empilement de plusieurs briques, sans autre fixation"],
    exp:"La semelle répartit la charge, la cale compense le sol, le vérin règle l'aplomb." },
  { m:"M10", sc:"semelle-cale-verin", r:["2.4.04"], q:"Vous installez l'échafaudage sur un sol visiblement meuble. Vous devez…",
    ok:"adapter le calage avant de monter, pas après",
    nok:["monter normalement, le calage se corrige une fois en place","monter en réduisant simplement le nombre de niveaux"],
    exp:"La stabilité de l'ensemble dépend de ce qui le porte, dès la base : le calage se prépare avant montage." },
  { m:"M10", sc:"coactivite-balisage", r:["2.3.02"], q:"Avant le montage, la zone d'implantation au sol doit être…",
    ok:"balisée pour écarter les personnes qui n'y travaillent pas",
    nok:["ouverte à la circulation, pour ne pas gêner le chantier","réservée uniquement aux véhicules de livraison du chantier"],
    exp:"Le balisage protège les personnes qui circulent près de la zone de montage." },
  { m:"M10", sc:"coactivite-balisage", r:["2.3.02"], q:"Vous préparez l'implantation à proximité d'un passage piéton. Vous devez…",
    ok:"baliser la zone et dévier le passage si nécessaire",
    nok:["laisser le passage tel quel, les piétons feront attention","attendre la fin du montage pour baliser"],
    exp:"Le balisage se met en place avant le montage, pour protéger les personnes qui passent à proximité." },
  { m:"M10", sc:"amarrage-facade", r:["R-03"], q:"Les amarrages d'un échafaudage se préparent…",
    ok:"avant le montage, selon ce que prévoit la notice",
    nok:["seulement si le vent se lève en cours de chantier","après le montage, une fois la structure achevée"],
    exp:"La notice fixe le nombre et la position des amarrages ; cela se prépare en amont, pas après coup." },
  { m:"M10", sc:"amarrage-facade", r:["R-03"], q:"Vous montez un échafaudage le long d'une façade. Vous devez prévoir les amarrages…",
    ok:"aux emplacements indiqués par la notice",
    nok:["aux emplacements les plus pratiques à atteindre","seulement au dernier niveau, une fois monté"],
    exp:"Les amarrages ne s'improvisent pas : la notice indique où et combien en prévoir." },
  { m:"M10", r:["2.3.06"], q:"Vous vous préparez à monter un échafaudage. Vous portez…",
    ok:"casque, gants et chaussures de sécurité",
    nok:["une tenue légère, pour être plus à l'aise dans les gestes","uniquement des gants, le reste étant secondaire"],
    exp:"Le monteur porte ses protections individuelles de base avant de commencer, en plus du harnais si la notice l'exige." },
  { m:"M10", sc:"semelle-cale-verin", r:["2.4.05"], q:"Un sol instable sous un échafaudage…",
    ok:"compromet la stabilité de toute la structure",
    nok:["n'a d'effet que sur le premier niveau","se corrige facilement une fois l'échafaudage monté"],
    exp:"La stabilité de l'ensemble dépend de ce qui le porte, dès la base." },
  { m:"M10", r:["2.3.01"], q:"Avant le montage, l'aire de travail doit prévoir…",
    ok:"une zone de travail et une zone de stockage du matériel, bien distinctes",
    nok:["une seule zone commune pour tout le chantier, sans aucune distinction prévue","le stockage du matériel au même endroit que le passage, dès le montage commencé"],
    exp:"Définir les zones (travail, stockage) avant de commencer évite l'encombrement et les croisements dangereux." },
  { m:"M10", r:["2.3.01"], q:"Vous préparez le chantier avant le montage. Le matériel livré est encore sur la zone de passage. Vous devez…",
    ok:"le déplacer vers la zone de stockage prévue, avant de commencer",
    nok:["le laisser là, il sera déplacé plus tard au fur et à mesure du montage","commencer le montage tout de suite, le matériel ne gêne pas encore"],
    exp:"Une aire de travail bien préparée sépare la zone de stockage du reste, avant que le montage ne commence." },
  { m:"M10", r:["2.3.03"], q:"À la réception du matériel d'échafaudage, il faut vérifier…",
    ok:"son conditionnement et l'organiser pour un stockage correct jusqu'au montage",
    nok:["seulement le nombre de palettes livrées ce jour-là sur le chantier tout entier","uniquement la date de livraison indiquée sur le bon de commande reçu"],
    exp:"Réceptionner le matériel, c'est contrôler son conditionnement et prévoir un stockage qui le protège jusqu'au montage." },
  { m:"M10", r:["2.3.03"], q:"Le matériel livré arrive entassé, sans protection contre la pluie annoncée. Vous devez…",
    ok:"l'organiser et le stocker à l'abri avant le montage",
    nok:["le monter tel quel, la pluie n'abîme pas le métal","le laisser en l'état, ce n'est pas votre rôle"],
    exp:"Un stockage mal préparé expose le matériel à des dégradations avant même le montage : on le corrige." },
  { m:"M10", r:["2.3.04"], q:"Un élément d'échafaudage visiblement déformé ou corrodé, repéré avant le montage…",
    ok:"est mis au rebut, il ne se monte pas",
    nok:["se monte quand même, s'il reste à un niveau bas","se garde de côté, au cas où il redeviendrait utilisable"],
    exp:"Un élément dégradé se vérifie avant montage : s'il est abîmé, il part au rebut, il ne se monte jamais." },
  { m:"M10", r:["2.3.04"], q:"Vous triez le matériel avant le montage. Une lisse est visiblement tordue. Vous devez…",
    ok:"l'écarter du lot et ne pas la monter",
    nok:["la monter, une légère déformation ne change rien","la redresser vous-même avant de la monter"],
    exp:"Vérifier l'état du matériel avant montage permet d'écarter ce qui doit être mis au rebut, sans le monter ni le réparer soi-même." },
  { m:"M10", r:["2.3.05"], q:"Avant de monter un échafaudage, l'outillage nécessaire…",
    ok:"se sélectionne à l'avance, selon le montage prévu par la notice",
    nok:["se choisit une fois le montage commencé, au fur et à mesure","importe peu, un outillage générique convient toujours"],
    exp:"Sélectionner l'outillage avant de commencer évite d'interrompre le montage pour aller en chercher." },
  { m:"M10", r:["2.3.05"], q:"Vous arrivez sur le chantier pour monter l'échafaudage et constatez qu'il manque une clé de serrage prévue. Vous devez…",
    ok:"aller la chercher avant de commencer, l'outillage se prépare en amont",
    nok:["improviser avec un autre outil qui pourrait éventuellement convenir","commencer sans elle, vous vous débrouillerez au fur et à mesure du montage"],
    exp:"Un outillage incomplet interrompt le montage : mieux vaut le vérifier avant de commencer." },
  { m:"M10", r:["2.3.06"], q:"Vous arrivez sur le chantier pour monter un échafaudage, sans vos chaussures de sécurité, oubliées la veille. Vous devez…",
    ok:"aller les chercher avant de commencer le montage",
    nok:["commencer quand même, vous ferez attention où vous marchez","emprunter les chaussures d'un collègue, même si elles sont trop grandes"],
    exp:"Les équipements de protection du monteur se portent avant de commencer, sans exception pour un oubli." },
  { m:"M10", r:["2.3.07"], q:"Le monteur choisit son dispositif de protection individuelle contre les chutes…",
    ok:"avant de monter, selon ce que prévoit la notice pour ce montage",
    nok:["une fois arrivé au dernier niveau, si besoin s'en fait sentir","seulement si le chantier dépasse une semaine entière de travail"],
    exp:"Le choix du dispositif de protection individuelle se prépare avant le montage, avec le reste de l'équipement." },
  { m:"M10", r:["2.3.07"], q:"La notice impose un système antichute au montage de ce niveau. Vous constatez ne pas en avoir. Vous devez…",
    ok:"vous en procurer avant de poursuivre le montage",
    nok:["poursuivre, un seul niveau ne présente pas de risque particulier","emprunter un système inadapté, à défaut d'autre solution"],
    exp:"Le dispositif de protection individuelle prévu par la notice doit être là avant de continuer, jamais après." },
  { m:"M10", r:["2.3.08"], q:"Avant de s'ancrer à l'échafaudage en cours de montage, le monteur vérifie…",
    ok:"qu'un point d'ancrage adapté existe réellement à cet endroit",
    nok:["seulement que la structure paraît assez haute pour cela","seulement que la longe est assez longue pour atteindre le sol"],
    exp:"S'ancrer suppose un point prévu et adapté ; on ne s'accroche pas à n'importe quel élément de la structure." },
  { m:"M10", r:["2.3.08"], q:"Sur un échafaudage encore en cours de montage, un point d'ancrage pour le harnais du monteur…",
    ok:"doit être un point prévu à cet effet, pas un élément quelconque",
    nok:["peut être n'importe quel montant suffisamment solide visuellement","n'est nécessaire qu'à partir du troisième niveau"],
    exp:"S'ancrer sur un élément non prévu pour cela ne garantit pas sa résistance : le point d'ancrage doit être identifié comme tel." },
  { m:"M10", r:["R-04"], q:"Un écart de plus de 20 cm entre le plancher et la façade, sans protection…",
    ok:"est une non-conformité à signaler avant d'utiliser le plancher",
    nok:["reste sans danger tant que l'écart ne dépasse pas 50 cm","concerne uniquement le confort de circulation, pas la sécurité"],
    exp:"Un écart excessif entre plancher et façade, sans protection, est identifié comme une non-conformité." },
  { m:"M10", r:["R-05"], q:"Vous devez implanter un échafaudage à proximité d'une ligne électrique aérienne. Vous devez…",
    ok:"vous arrêter avant le montage et faire vérifier la distance de sécurité",
    nok:["monter normalement, la ligne n'entre jamais en contact avec la structure","déterminer vous-même la tension exacte de la ligne électrique pour décider"],
    exp:"Une ligne électrique aérienne à proximité impose un point d'arrêt : on signale, on ne détermine pas soi-même la tension." },
  { m:"M10", r:["R-05"], q:"Près d'une ligne électrique aérienne, la distance de sécurité réglementaire à respecter est…",
    ok:"de 3 mètres ou de 5 mètres, selon la tension de la ligne",
    nok:["toujours de 3 mètres, quelle que soit la tension de la ligne","laissée à l'appréciation du monteur, selon le chantier"],
    exp:"L'arrêté du 5 juillet 2024 fixe 3 m jusqu'à 50 000 volts, et 5 m au-delà : ce n'est jamais un choix du monteur." },
  { m:"M10", r:["R-07"], q:"Un échafaudage de pied doit être utilisé…",
    ok:"toujours ancré, amarré, ou stabilisé par un moyen équivalent",
    nok:["sans ancrage, tant qu'il ne dépasse pas deux niveaux de hauteur","avec un simple lestage au sol, sans autre fixation particulière"],
    exp:"Un échafaudage de pied doit toujours être ancré ou amarré, ou stabilisé par un moyen d'efficacité équivalente." },
  { m:"M10", r:["R-07"], q:"Vous devez monter sur un échafaudage qui n'est relié à rien : ni ancrage, ni amarrage visible. Vous devez…",
    ok:"refuser de monter tant que rien n'assure sa stabilité",
    nok:["monter en restant loin des bords, par simple prudence personnelle","grimper quand même, si l'échafaudage ne comporte qu'un seul niveau"],
    exp:"Sans ancrage, amarrage ou moyen équivalent, la stabilité n'est pas assurée : on ne monte pas dessus." },
  { m:"M10", sc:"etiquette-montant", r:["R-11"], q:"Le panneau apposé sur un échafaudage réceptionné indique…",
    ok:"les conditions d'utilisation et interdit l'accès aux personnes non autorisées",
    nok:["seulement le nom de l'entreprise qui a réalisé le montage, sans autre précision","uniquement la date du prochain chantier prévu à cet endroit du site"],
    exp:"Le panneau porte les conditions d'utilisation et interdit l'accès à qui n'est pas autorisé." },

  /* ---------- M11 · Monter et démonter ---------- */
  { m:"M11", sc:"montage-niveau", r:["2.4.06"], q:"Le montage d'un échafaudage suit…",
    ok:"un ordre précis, fixé par la notice du fabricant",
    nok:["l'ordre choisi librement par chaque monteur","un ordre libre, du moment que tout est fixé à la fin"],
    exp:"La notice fixe l'ordre de montage, notamment pour que les protections soient posées au bon moment." },
  { m:"M11", sc:"montage-niveau", r:["2.4.08"], q:"Pendant le montage, le garde-corps d'un niveau est posé…",
    ok:"depuis le niveau inférieur déjà protégé, avant le plancher supérieur",
    nok:["depuis le niveau supérieur, seulement une fois le plancher déjà posé","à la toute fin du montage, sur tous les niveaux à la fois"],
    exp:"Le garde-corps se pose depuis un niveau déjà protégé, avant que le monteur avance vers le niveau du dessus." },
  { m:"M11", sc:"montage-niveau", r:["2.4.08"], q:"Vous montez le niveau supérieur d'un échafaudage. Le garde-corps de ce niveau doit être posé…",
    ok:"avant que vous ayez besoin d'y travailler",
    nok:["une fois que vous avez fini de poser le plancher","seulement si un contrôle est annoncé ce jour-là"],
    exp:"Une protection posée trop tard ne protège pas pendant le montage lui-même." },
  { m:"M11", sc:"harnais-ancrage", r:["2.4.01"], q:"Vous ne pouvez pas poser le garde-corps à montage définitif avant d'avancer. Vous devez…",
    ok:"vous protéger par un système antichute, à défaut du garde-corps",
    nok:["avancer sans aucune protection, le temps de finir ce niveau","poser le garde-corps après coup, une fois le niveau entièrement fini"],
    exp:"Le système antichute individuel n'intervient qu'à défaut de la protection collective, jamais à sa place par choix." },
  { m:"M11", sc:"demontage-ordre", r:["2.4.06"], q:"Le démontage d'un échafaudage suit…",
    ok:"un ordre précis, encadré comme le montage",
    nok:["l'ordre inverse improvisé, du plus rapide au plus lent","aucun ordre particulier, le chantier étant terminé"],
    exp:"Le démontage reste encadré par la notice, au même titre que le montage." },
  { m:"M11", sc:"demontage-ordre", q:"Vous démontez un plancher en hauteur. L'élément retiré doit être…",
    ok:"descendu de main en main, jamais jeté",
    nok:["lancé au sol si la zone est bien dégagée","posé en équilibre sur le niveau du dessous"],
    exp:"Un élément démonté se fait descendre de main en main : le jeter expose les personnes en dessous." },
  { m:"M11", r:["2.4.20"], q:"Le montage de l'échafaudage vient de s'achever. Avant de l'utiliser, il faut…",
    ok:"vérifier sa conformité",
    nok:["attendre la première pluie pour tester sa résistance","commencer directement, le montage suffit"],
    exp:"Après montage, on contrôle la conformité de l'ensemble avant toute utilisation." },
  { m:"M11", q:"Modifier l'ordre de montage prévu par la notice…",
    ok:"peut laisser une protection absente au moment où elle est nécessaire",
    nok:["accélère le chantier, sans aucune autre conséquence importante à prévoir","n'a d'effet que sur l'esthétique final de la structure montée"],
    exp:"Changer l'ordre prévu risque de retarder la pose d'une protection au moment où elle protège réellement." },
  { m:"M11", sc:"demontage-ordre", q:"Vous terminez le démontage du dernier niveau. Les éléments retirés sont…",
    ok:"rangés et comptés, dans l'ordre inverse du montage",
    nok:["laissés au pied de l'échafaudage jusqu'au lendemain","empilés rapidement pour libérer la zone au plus vite"],
    exp:"Le démontage se fait dans l'ordre inverse du montage, avec un rangement soigné des éléments." },
  { m:"M11", r:["2.4.01"], q:"Vous montez un niveau où la notice impose un harnais avec longe. Le vôtre est resté au sol. Vous devez…",
    ok:"redescendre le chercher avant de continuer à monter",
    nok:["continuer, vous redescendrez le prendre au niveau suivant","emprunter la longe d'un collègue sans vérifier qu'elle convient"],
    exp:"L'équipement de protection du monteur se porte avant de continuer, jamais après." },
  { m:"M11", r:["2.4.03"], q:"Le choix des appuis d'un échafaudage se fait…",
    ok:"avant le montage, selon la nature du sol à cet endroit",
    nok:["après le montage, en ajustant si besoin","une fois pour toutes, quel que soit le chantier"],
    exp:"Choisir les appuis fait partie de l'implantation, préparée avant que le montage ne commence." },
  { m:"M11", r:["2.4.05"], q:"Après avoir monté deux niveaux, vous remarquez que la structure n'est plus bien verticale. Vous devez…",
    ok:"corriger l'aplomb avant de poursuivre le montage",
    nok:["continuer, la structure se stabilisera avec les niveaux suivants","attendre la fin du montage pour tout corriger d'un coup"],
    exp:"Verticalité et horizontalité se contrôlent au fur et à mesure du montage, pas seulement à la fin." },
  { m:"M11", r:["2.4.20"], q:"L'autocontrôle réalisé juste après le montage sert à…",
    ok:"vérifier que l'échafaudage est conforme à la notice avant utilisation",
    nok:["remplacer la vérification de mise en service prévue ensuite","vérifier uniquement le nombre d'éléments utilisés"],
    exp:"L'autocontrôle du monteur vérifie la conformité au plan avant que quiconque n'utilise l'échafaudage." },
  { m:"M11", sc:"vent-bache", r:["R-12"], q:"Un orage éclate pendant le montage d'un échafaudage. Vous devez…",
    ok:"interrompre le montage et en référer au responsable de chantier",
    nok:["terminer rapidement le niveau en cours du montage avant de descendre","continuer si la pluie reste faible, sans autre précaution particulière"],
    exp:"Une météo dégradée (orage, vent fort, gel) impose d'interrompre le montage et d'en référer au responsable." },
  { m:"M11", r:["2.4.02"], q:"Pendant le montage, l'outillage se choisit…",
    ok:"pour chaque opération, sans en détourner l'usage prévu",
    nok:["au hasard, l'important est d'aller vite","une seule fois, le même outil pour toutes les opérations"],
    exp:"Chaque outil a un usage prévu ; l'utiliser pour autre chose expose à un risque évitable." },
  { m:"M11", r:["2.4.02"], q:"Vous n'avez pas la bonne clé sous la main pour serrer un raccord. Vous devez…",
    ok:"aller chercher l'outil adapté avant de continuer",
    nok:["utiliser une pince pour serrer à sa place, ça ira plus vite","serrer à la main, ce sera resserré plus tard"],
    exp:"Un raccord mal serré, faute du bon outil, compromet la solidité de l'ensemble." },
  { m:"M11", r:["2.4.07","2.4.09"], q:"Le montage d'un niveau suit un ordre : d'abord les poteaux ou cadres, puis…",
    ok:"les planchers préfabriqués, posés une fois la structure du niveau en place",
    nok:["le garde-corps du niveau du dessus, avant même d'avoir posé les cadres","le contreventement du niveau suivant, avant que les cadres soient en place"],
    exp:"Poteaux ou cadres d'abord, puis planchers préfabriqués : chaque élément a sa place dans l'ordre de montage." },
  { m:"M11", r:["2.4.07"], q:"Vous montez les cadres d'un nouveau niveau. Un cadre ne s'emboîte pas correctement. Vous devez…",
    ok:"vérifier l'assemblage avant de poursuivre, sans le forcer",
    nok:["le forcer légèrement, il finira bien par s'emboîter correctement","poursuivre le montage, vous reviendrez dessus un peu plus tard"],
    exp:"Un cadre mal emboîté ne tient pas correctement : on vérifie avant d'avancer, on ne force pas l'assemblage." },
  { m:"M11", r:["2.4.09"], q:"Vous posez les planchers préfabriqués d'un niveau. L'un d'eux ne repose pas bien à plat. Vous devez…",
    ok:"le repositionner correctement avant de l'utiliser",
    nok:["le laisser ainsi, la différence est minime","poser le suivant, celui-ci se stabilisera avec le poids"],
    exp:"Un plancher préfabriqué mal posé n'assure plus une surface plane et sûre : on le repositionne avant usage." },
  { m:"M11", r:["2.4.10"], q:"Le contreventement d'un échafaudage sert à…",
    ok:"rigidifier la structure et l'empêcher de se déformer",
    nok:["porter le poids du plancher, exactement comme le font les montants","faciliter uniquement l'accès aux niveaux supérieurs de la structure"],
    exp:"Le contreventement (croix, diagonales) rigidifie la structure : il se pose au nombre et à l'emplacement prévus par la notice." },
  { m:"M11", r:["2.4.10"], q:"La notice prévoit une diagonale de contreventement à ce niveau. Vous n'en avez plus dans le lot. Vous devez…",
    ok:"vous en procurer avant de continuer, sans improviser",
    nok:["continuer sans elle, les autres niveaux compenseront","utiliser un autre élément disponible à la place"],
    exp:"Le contreventement prévu par la notice n'est pas facultatif ; il ne se remplace pas par un élément quelconque." },
  { m:"M11", r:["2.4.11"], q:"L'accès d'un échafaudage (échelle, trappe) se positionne…",
    ok:"à l'endroit et de la façon prévus par la notice, protégé comme le reste",
    nok:["là où c'est le plus pratique pour le monteur ce jour-là, précisément et simplement","à l'extérieur de la structure, pour ne pas gêner le plancher intérieur"],
    exp:"L'accès suit la notice, comme les autres éléments : position et protection ne s'improvisent pas." },
  { m:"M11", r:["2.4.11"], q:"Vous montez l'accès d'un niveau. La trappe prévue n'est pas encore posée. Vous devez…",
    ok:"attendre de l'avoir avant d'ouvrir cet accès à la circulation",
    nok:["laisser un trou ouvert, en avertissant les collègues oralement","poser une planche provisoire à la place de la trappe"],
    exp:"Un accès sans sa trappe n'est pas complet : il ne s'ouvre pas à la circulation avant d'être terminé." },
  { m:"M11", r:["2.4.12"], q:"Au fil du montage, la verticalité et l'horizontalité de la structure…",
    ok:"se recontrôlent à chaque niveau ajouté",
    nok:["ne se vérifient qu'une fois, avant de commencer à monter","ne concernent que le dernier niveau, une fois terminé"],
    exp:"Un défaut d'aplomb s'accumule niveau après niveau s'il n'est pas recontrôlé en cours de montage." },
  { m:"M11", r:["2.4.12"], q:"Vous ajoutez un niveau et sentez que la structure penche légèrement. Vous devez…",
    ok:"corriger avant de poser le niveau suivant",
    nok:["continuer, un léger défaut se corrigera avec le poids ajouté","noter le défaut pour le signaler à la fin du montage"],
    exp:"Un défaut de verticalité se corrige dès qu'il apparaît, avant d'ajouter un niveau de plus par-dessus." },
  { m:"M11", r:["2.4.13"], q:"Un montage avec console, porte-à-faux ou poutre de franchissement…",
    ok:"est une configuration spécifique, qui suit toujours sa propre note de calcul",
    nok:["se monte exactement comme une structure simple, sans aucune particularité","est interdit dans tous les cas sur un chantier de niveau CAP, sans exception"],
    exp:"Ces montages spécifiques sortent du montage simple : ils suivent une note de calcul ou un plan propre à leur configuration." },
  { m:"M11", r:["2.4.13"], q:"Le levage de charges par potence sur un échafaudage…",
    ok:"est un montage spécifique, encadré par la notice ou un plan propre",
    nok:["se fait avec n'importe quel point d'accroche paraissant solide","est une opération courante, identique sur tous les chantiers rencontrés"],
    exp:"Potence, escaliers d'accès, console : chaque montage spécifique suit ses propres instructions, jamais improvisées." },
  { m:"M11", r:["2.4.14"], q:"Faire monter des éléments d'échafaudage aux différents niveaux par élingage…",
    ok:"suit des règles précises pour que la charge reste maîtrisée en montant",
    nok:["se fait en lançant les éléments d'un niveau à l'autre","ne concerne que les très grands chantiers de plusieurs semaines"],
    exp:"L'élingage d'éléments vers un niveau en hauteur maîtrise la charge tout au long de la montée, jusqu'au point d'arrivée." },
  { m:"M11", r:["2.4.14"], q:"Une charge d'éléments est élinguée pour monter vers le niveau où vous travaillez. Vous devez…",
    ok:"rester à l'écart de sa trajectoire pendant qu'elle monte",
    nok:["la réceptionner à bout de bras dès qu'elle approche","continuer votre tâche sans vous préoccuper de son passage"],
    exp:"Une charge en cours d'élingage peut se balancer ou chuter : on reste hors de sa trajectoire." },
  { m:"M11", r:["2.4.15","2.4.16"], q:"Un ancrage par cheville, une fois posé, se contrôle…",
    ok:"avec un extractomètre, pour vérifier sa résistance à l'arrachement",
    nok:["à l'œil, en observant simplement sa couleur et son aspect général","en tirant dessus à la main, de toutes ses forces, sans autre outil"],
    exp:"L'extractomètre mesure la résistance réelle d'un ancrage par cheville, un contrôle visuel ne suffit pas." },
  { m:"M11", r:["2.4.15"], q:"Vous posez un ancrage par cheville dans un support dont vous doutez de la solidité. Vous devez…",
    ok:"le vérifier avant de vous y fier, sans le monter comme acquis",
    nok:["le monter quand même, la cheville compense un support faible","choisir une cheville plus grosse, sans vérifier la solidité du support"],
    exp:"Une cheville adaptée aux efforts à transmettre suppose un support vérifié, pas seulement une cheville robuste." },
  { m:"M11", r:["2.4.16"], q:"L'extractomètre utilisé sur un ancrage sert à…",
    ok:"mesurer la force qu'il peut réellement supporter avant de céder",
    nok:["mesurer la longueur de la cheville posée","peindre l'ancrage pour le repérer plus facilement"],
    exp:"L'extractomètre teste la résistance réelle de l'ancrage, pour s'assurer qu'il tient l'effort attendu." },
  { m:"M11", r:["2.4.17","2.4.18"], q:"Le rôle d'un amarrage, une fois monté, est vérifié…",
    ok:"pour s'assurer qu'il est bien fixé et qu'il résiste à l'effort attendu",
    nok:["seulement pour compter le nombre exact d'amarrages posés sur la façade","surtout pour vérifier qu'il reste bien visible depuis le sol du chantier"],
    exp:"Un amarrage relie l'échafaudage à la façade ; son montage et sa résistance se vérifient avant de le considérer acquis." },
  { m:"M11", r:["2.4.17"], q:"Vous venez de poser un amarrage entre l'échafaudage et la façade. Vous devez…",
    ok:"vérifier qu'il joue bien son rôle avant de passer au suivant",
    nok:["passer directement au suivant, il sera contrôlé plus tard par un autre","le considérer acquis dès la pose, sans rien vérifier de plus"],
    exp:"Poser un amarrage ne suffit pas : son rôle (tenir l'échafaudage à la façade) se vérifie tout de suite." },
  { m:"M11", r:["2.4.18"], q:"Vérifier le bon montage et la résistance d'un amarrage après sa pose…",
    ok:"fait partie du geste du monteur, pas seulement de la vérification journalière",
    nok:["revient uniquement au vérificateur journalier attitré, jamais vraiment au monteur","ne concerne que les amarrages posés au tout dernier niveau qui a été monté"],
    exp:"Le monteur qui pose un amarrage vérifie aussitôt son montage et sa résistance, avant de le laisser en service." },
  { m:"M11", r:["2.4.19"], q:"Une fois l'échafaudage monté, le panneau indiquant les charges d'exploitation…",
    ok:"est apposé par le monteur, avant toute utilisation",
    nok:["est facultatif si la notice ne le précise pas","est apposé seulement si un contrôle est annoncé"],
    exp:"Apposer le panneau des charges fait partie du montage : sans lui, personne ne sait ce que le plancher admet." },
  { m:"M11", r:["2.4.19"], q:"Le montage est terminé mais aucun panneau de charges n'a encore été posé. Vous devez…",
    ok:"le poser avant de considérer l'échafaudage prêt à l'emploi",
    nok:["laisser les utilisateurs le poser eux-mêmes, s'ils en ont besoin","attendre la vérification de mise en service pour le poser"],
    exp:"Le panneau de charges se pose à la fin du montage, par le monteur, avant que quiconque n'utilise l'échafaudage." },

];
