/* Les documents à télécharger, exercice par exercice (l'accueil et la page de jeu lisent ici) : le TP élève est libre ;
   les documents professeur se demandent par courriel (coffre). Deux feuilles élève : « eleve » (en deux temps : tout l'écran,
   puis la platine) et « fil » (fil par fil : le carnet de câblage) ; « tuto » : la feuille du tutoriel (prise en main), à donner sur
   la station Départ et dans le jeu quand l'adresse porte &tuto. Pour cablage-9, cablage-9-commande et cablage-1-commande, « eleve »
   reste le TP réel de l'enseignant (TP-2-Puissance, TP-Commande, Mise-sous-tension) et « fil » est la feuille générique. Les nombres de
   feuilles sont ceux des PDF (outils/fabriquer-documents-exercices.py --noms les réécrit). */
window.CABLAGE_DOCUMENTS = {
    'allumage-simple': {eleve: 'documents/exercices/allumage-simple/allumage-simple-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (4 feuilles)', fil: 'documents/exercices/allumage-simple/allumage-simple-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (6 feuilles)', tuto: 'documents/Tutoriel-Prise-en-main-ELEVE.pdf', nomTuto: 'Feuille élève du tutoriel : prise en main (3 feuilles)'},
    'cablage-1-commande': {eleve: 'documents/Mise-sous-tension-ELEVE.pdf', nom: 'Mise sous tension : l’essai (élève, 3 feuilles)', fil: 'documents/exercices/cablage-1-commande/cablage-1-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (8 feuilles)'},
    'cablage-1': {eleve: 'documents/exercices/cablage-1/cablage-1-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (4 feuilles)', fil: 'documents/exercices/cablage-1/cablage-1-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (7 feuilles)'},
    'cablage-2': {eleve: 'documents/exercices/cablage-2/cablage-2-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-2/cablage-2-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-3-commande': {eleve: 'documents/exercices/cablage-3-commande/cablage-3-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (7 feuilles)', fil: 'documents/exercices/cablage-3-commande/cablage-3-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (12 feuilles)'},
    'cablage-3': {eleve: 'documents/exercices/cablage-3/cablage-3-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (5 feuilles)', fil: 'documents/exercices/cablage-3/cablage-3-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (9 feuilles)'},
    'cablage-4-commande': {eleve: 'documents/exercices/cablage-4-commande/cablage-4-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-4-commande/cablage-4-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-4': {eleve: 'documents/exercices/cablage-4/cablage-4-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (4 feuilles)', fil: 'documents/exercices/cablage-4/cablage-4-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (7 feuilles)'},
    'cablage-5-commande': {eleve: 'documents/exercices/cablage-5-commande/cablage-5-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-5-commande/cablage-5-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-5': {eleve: 'documents/exercices/cablage-5/cablage-5-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (5 feuilles)', fil: 'documents/exercices/cablage-5/cablage-5-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (8 feuilles)'},
    'cablage-6-commande': {eleve: 'documents/exercices/cablage-6-commande/cablage-6-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (7 feuilles)', fil: 'documents/exercices/cablage-6-commande/cablage-6-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (12 feuilles)'},
    'cablage-6': {eleve: 'documents/exercices/cablage-6/cablage-6-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-6/cablage-6-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-7-commande': {eleve: 'documents/exercices/cablage-7-commande/cablage-7-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (7 feuilles)', fil: 'documents/exercices/cablage-7-commande/cablage-7-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (13 feuilles)'},
    'cablage-7': {eleve: 'documents/exercices/cablage-7/cablage-7-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-7/cablage-7-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (11 feuilles)'},
    'cablage-8-commande': {eleve: 'documents/exercices/cablage-8-commande/cablage-8-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (9 feuilles)', fil: 'documents/exercices/cablage-8-commande/cablage-8-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (17 feuilles)'},
    'cablage-8': {eleve: 'documents/exercices/cablage-8/cablage-8-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (7 feuilles)', fil: 'documents/exercices/cablage-8/cablage-8-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (13 feuilles)'},
    'demarrage-direct-tri': {eleve: 'documents/exercices/demarrage-direct-tri/demarrage-direct-tri-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (4 feuilles)', fil: 'documents/exercices/demarrage-direct-tri/demarrage-direct-tri-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (7 feuilles)'},
    'telerupteur': {eleve: 'documents/exercices/telerupteur/telerupteur-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (4 feuilles)', fil: 'documents/exercices/telerupteur/telerupteur-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (6 feuilles)'},
    'va-et-vient': {eleve: 'documents/exercices/va-et-vient/va-et-vient-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (4 feuilles)', fil: 'documents/exercices/va-et-vient/va-et-vient-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (6 feuilles)'},
    'cablage-10': {eleve: 'documents/exercices/cablage-10/cablage-10-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-10/cablage-10-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-10-commande': {eleve: 'documents/exercices/cablage-10-commande/cablage-10-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (11 feuilles)', fil: 'documents/exercices/cablage-10-commande/cablage-10-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (17 feuilles)'},
    'cablage-11': {eleve: 'documents/exercices/cablage-11/cablage-11-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-11/cablage-11-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-11-commande': {eleve: 'documents/exercices/cablage-11-commande/cablage-11-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (7 feuilles)', fil: 'documents/exercices/cablage-11-commande/cablage-11-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (12 feuilles)'},
    'cablage-12': {eleve: 'documents/exercices/cablage-12/cablage-12-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (5 feuilles)', fil: 'documents/exercices/cablage-12/cablage-12-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (8 feuilles)'},
    'cablage-12-commande': {eleve: 'documents/exercices/cablage-12-commande/cablage-12-commande-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (9 feuilles)', fil: 'documents/exercices/cablage-12-commande/cablage-12-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (15 feuilles)'},
    'cablage-13': {eleve: 'documents/exercices/cablage-13/cablage-13-ELEVE.pdf', nom: 'Feuille élève, en deux temps : câbler, essayer, réaliser (6 feuilles)', fil: 'documents/exercices/cablage-13/cablage-13-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-9': {eleve: 'documents/TP-2-Puissance-ELEVE.pdf', nom: 'TP 2 — Puissance (élève, 7 feuilles)', fil: 'documents/exercices/cablage-9/cablage-9-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (10 feuilles)'},
    'cablage-9-commande': {eleve: 'documents/TP-Commande-ELEVE.pdf', nom: 'TP — Commande (élève, 5 feuilles)', fil: 'documents/exercices/cablage-9-commande/cablage-9-commande-ELEVE-FIL.pdf', nomFil: 'Feuille élève, fil par fil : carnet de câblage (13 feuilles)'},
};
