/* Les documents à télécharger, exercice par exercice (l'accueil et la page de jeu lisent ici) : le TP élève est libre ;
   les documents professeur se demandent par courriel (coffre). */
window.CABLAGE_DOCUMENTS = {
    'allumage-simple': {eleve: 'documents/Tutoriel-Prise-en-main-ELEVE.pdf', nom: 'Feuille élève du tutoriel (2 feuilles)'},
    'cablage-1-commande': {eleve: 'documents/Mise-sous-tension-ELEVE.pdf', nom: 'Mise sous tension : l’essai (élève, 3 feuilles)'},
    'cablage-1': {eleve: 'documents/exercices/cablage-1/cablage-1-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-2': {eleve: 'documents/exercices/cablage-2/cablage-2-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-3-commande': {eleve: 'documents/exercices/cablage-3-commande/cablage-3-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-3': {eleve: 'documents/exercices/cablage-3/cablage-3-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-4-commande': {eleve: 'documents/exercices/cablage-4-commande/cablage-4-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-4': {eleve: 'documents/exercices/cablage-4/cablage-4-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-5-commande': {eleve: 'documents/exercices/cablage-5-commande/cablage-5-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-5': {eleve: 'documents/exercices/cablage-5/cablage-5-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-6-commande': {eleve: 'documents/exercices/cablage-6-commande/cablage-6-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-6': {eleve: 'documents/exercices/cablage-6/cablage-6-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-7-commande': {eleve: 'documents/exercices/cablage-7-commande/cablage-7-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-7': {eleve: 'documents/exercices/cablage-7/cablage-7-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-8-commande': {eleve: 'documents/exercices/cablage-8-commande/cablage-8-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-8': {eleve: 'documents/exercices/cablage-8/cablage-8-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'demarrage-direct-tri': {eleve: 'documents/exercices/demarrage-direct-tri/demarrage-direct-tri-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'telerupteur': {eleve: 'documents/exercices/telerupteur/telerupteur-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'va-et-vient': {eleve: 'documents/exercices/va-et-vient/va-et-vient-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-10': {eleve: 'documents/exercices/cablage-10/cablage-10-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-10-commande': {eleve: 'documents/exercices/cablage-10-commande/cablage-10-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-11': {eleve: 'documents/exercices/cablage-11/cablage-11-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-11-commande': {eleve: 'documents/exercices/cablage-11-commande/cablage-11-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-12': {eleve: 'documents/exercices/cablage-12/cablage-12-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-12-commande': {eleve: 'documents/exercices/cablage-12-commande/cablage-12-commande-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-13': {eleve: 'documents/exercices/cablage-13/cablage-13-ELEVE.pdf', nom: 'Feuille élève : câbler, essayer, réaliser (3 feuilles)'},
    'cablage-9': {eleve: 'documents/TP-2-Puissance-ELEVE.pdf', nom: 'TP 2 — Puissance (élève, 6 feuilles)'},
    'cablage-9-commande': {eleve: 'documents/TP-Commande-ELEVE.pdf', nom: 'TP — Commande (élève, 4 feuilles)'},
};
