/* Fichier GÉNÉRÉ par build/registre.mjs — ne pas modifier à la main.
   La description de chaque cours, relevée de sa <meta name="description">,
   pour la vue de ligne du plan (index.html). */
window.PLAN_DESC = {
 "bilan-thermique-performance-interactif": "Cours interactif professionnel : bilan thermique d’une chambre froide, climatisation en chaud et en froid, COP, EER, SCOP et SEER.",
 "bouteille-liquide-pedagogique": "Parcours interactif pour comprendre la bouteille liquide frigorifique, son tube plongeur et sa vanne de départ liquide.",
 "capsules": "Capsule narrée : le chapitre expliqué à voix haute, écran par écran, avec ses animations.",
 "chaine-intervention-interactive": "Cours interactif commun aux fiches p1, p3 et p5 : manifold, raccordement, tirage au vide, isolement et déconnexion avec un minimum d’émissions.",
 "chaleur-circuit-interactif": "Comprenez les transferts de chaleur, la saturation, la surchauffe et le sous-refroidissement dans un circuit frigorifique interactif.",
 "chaleur-interactive": "Découvrez comment la chaleur se déplace, du glaçon aux changements d’état, puis comment le circuit frigorifique absorbe et rejette l’énergie.",
 "circuit-organe-par-organe": "Comprenez le rôle du compresseur, du condenseur, du détendeur et de l’évaporateur dans un circuit frigorifique, avec schémas et exercices interactifs.",
 "co2-r744": "Module inerWeb Édu hors ligne : la ligne CO₂ / R744 en douze escales — point critique, cycle transcritique, haute pression optimale, centrale booster, éjecteur, sécurité.",
 "compresseur-interactif": "Cours interactif A1/A2 sur le compresseur : installer avec ses sécurités, régler en prouvant à l’instrument, vérifier l’huile et son retour.",
 "condenseur-interactif": "Cours interactif A1/A2 sur le condenseur : encrassement, haute pression, ventilation, installation, régulation, inspection et rapport.",
 "cours-classes-securite": "Cours interactif : lire une classe NF EN 378 (A1, A2L, A3, B2L…), le triangle du feu, le domaine d'explosivité et un cas réel d'accident.",
 "detendeur-interactif": "Parcours interactif pour comprendre le détendeur thermostatique, la surchauffe et le réglage de l’alimentation de l’évaporateur.",
 "diagramme-enthalpique": "Apprenez à lire un diagramme enthalpique frigorifique log p-h, courbe par courbe, avec parcours interactifs, quiz et exercices gratuits.",
 "electrovanne-interactive": "Parcours interactif pour comprendre le rôle, la commande, le montage et les limites de diagnostic d’une électrovanne frigorifique.",
 "etancheite-interactive": "Cours interactif réunissant g4a, g4b et g4c : registre, points de fuite, méthodes indirecte et directe, détecteur électronique et traçabilité.",
 "evaporateur-interactif": "Module interactif A1 sur l’installation, le réglage et la vérification d’un évaporateur : givre, dégivrage, régulation, inspection et rapport d’état.",
 "fil-conducteur-intervention": "Une seule planche de synthèse : le parcours complet d'une intervention fluide en six étapes — comprendre, être autorisé, préparer, intervenir, contrôler, tracer. Animation et voix française locale, avec réglage de vitesse.",
 "film-effet-de-serre": "Film animé narré (53 s) : l’effet de serre, le PRP des fluides frigorigènes et l’équivalence en kilomètres de voiture — R404A, R32, R290. Voix française, débit réglable, l’image se cale sur la voix.",
 "film-ozone": "Film animé narré (45 s) : la couche d’ozone, les CFC, l’ODP et le protocole de Montréal, 1987. Voix française, débit réglable, l’image se cale sur la voix.",
 "filtre-deshydrateur-pedagogique": "Parcours interactif pour comprendre le filtre-déshydrateur frigorifique, ses composants et ses variantes.",
 "frise-vivante": "Frise interactive et racontée de l’histoire des fluides frigorigènes.",
 "froid-clim-academie": "Cours interactifs et ludiques pour former aux bases du froid, de la climatisation et des fluides frigorigènes.",
 "glissement-temperature": "Découverte racontée et illustrée des fluides zéotropes, azéotropes et du glissement de température, depuis la chaleur latente jusqu'au diagramme log p-h.",
 "hydrocarbures-a1-a2": "Mission interactive A1/A2 : pourquoi le R-290, risques d’inflammation, analyse de zone, calcul documenté, outillage hydrocarbures et conduite à tenir.",
 "intervention-hydrocarbures-interactive": "Suite pratique de Mission 290 : parcours à embranchements pour ouvrir, remplacer, éprouver, tirer au vide, charger, contrôler et tracer sur un circuit hydrocarbure.",
 "mission-bouteilles": "Auto-formation interactive sur les bouteilles de transfert et de récupération des fluides frigorigènes.",
 "nomenclature-interactive": "Cours interactif : comprendre la désignation des fluides frigorigènes.",
 "parcours-manometres": "Deux modules inerWeb Édu pour lire les manomètres frigorifiques puis calculer surchauffes et sous-refroidissements.",
 "pose-manifold-2-voies-interactive": "Entraîneur inerWeb pour comprendre, poser, utiliser et déposer un manifold 2 voies sur deux vannes de service Rotolock.",
 "pose-manifold-interactive": "Atelier interactif inerWeb : contrôler, poser, tirer au vide, mettre en lecture et déposer un manifold 4 voies sur deux vannes de service.",
 "pression-temperature-interactive": "Comprenez la relation pression-température, l’ébullition sous vide, la saturation et le glissement des fluides frigorigènes avec une expérience interactive.",
 "pressostat-bp-kp1": "Module inerWeb Édu hors ligne : comprendre et régler un pressostat basse pression de sécurité.",
 "pressostat-combine-kp15": "Comprendre le pressostat combiné Danfoss KP15 : fonctionnement HP/BP, réglage CUT IN/CUT OUT, différentiel, câblage A/B/C/D et contrôle.",
 "pressostat-hp-kp5": "Module inerWeb Édu hors ligne : comprendre et régler un pressostat haute pression de sécurité.",
 "pupitre-reglage-interactif": "Cours interactif A1/A2 : régler thermostats, pressostats et limiteurs — consigne, différentiel, et la preuve à l’instrument.",
 "recuperation-fluide-interactive": "TP interactif inerWeb : raccorder un manifold 4 voies, récupérer le fluide avec une station Minimax-E, peser, auto-purger puis tirer l'installation au vide.",
 "regulateur-electronique-interactif": "Cours interactif : lire une sonde résistive, régler consigne et différentiel, programmer un régulateur électronique de froid, régler le dégivrage et câbler son bornier.",
 "regulateur-kvr-nrd": "Animation (92 s) : pourquoi la haute pression s’effondre quand l’air extérieur est froid, ce que fait le régulateur KVR à la sortie du condenseur, et pourquoi il faut lui adjoindre le clapet différentiel NRD pour repressuriser le réservoir. Symboles normalisés ou dessinés, au choix.",
 "regulateurs-kv-pedagogiques": "Parcours inerWeb Édu pour comparer, comprendre et régler les régulateurs de pression KVP, KVL et KVR.",
 "surchauffe-sous-refroidissement-interactif": "Apprenez à mesurer et calculer la surchauffe et le sous-refroidissement d’un circuit frigorifique, pas à pas, avec exercices et quiz.",
 "tome-3-technologie-organes": "Tome 3 interactif inerWeb Édu : reconnaître, situer et comprendre les organes d’un circuit frigorifique.",
 "vanne-service-interactive": "Cours interactif sur la vanne de service à deux prises : les trois positions en coupe animée, la voie de service P et la prise permanente P1, le sens BP et HP, le geste de raccordement du manifold et deux mini-jeux corrigés.",
 "voyant-liquide-pedagogique": "Parcours interactif pour comprendre le voyant liquide frigorifique, avec ou sans indicateur d’humidité."
};
