window.OIL_MODULE = {
  id: "traxoil-installer",
  title: "TraxOil : monter et diagnostiquer",
  subtitle: "LE CIRCUIT D’HUILE · STATION 12",
  codes: ["1.05", "6.05"],
  voix: true,
  nextStep: "Poursuivre avec le pressostat différentiel d’huile : après le niveau du carter, il faut encore protéger la pression nette de lubrification des compresseurs équipés d’une pompe.",
  nextUrl: "../pressostat-differentiel-huile-pedagogique/index.html",
  nextLabel: "Station 13 · Le pressostat d’huile : la pression nette",
  summaryVisual: { kind: "levelZones", label: "TraxOil avec zones de niveau, injection par électrovanne et contact d’alarme" },
  lessons: [
    { id: "modeles", short: "Modèles", kicker: "Station 1 · Domaine", title: "OM3, OM4 et OM5 ne sont pas interchangeables", lead: "Leur domaine de pression, leurs fluides et leurs joints correspondent à des applications différentes.", details: ["La gamme OM3/OM4 couvre des applications HFC/HFO sélectionnées ; l’OM4 possède aussi des usages R744 subcritiques.", "L’OM5 vise les applications R744 transcritiques. Pour A2L ou A3, employer uniquement la version, l’adaptateur et le câblage approuvés."], box: { type: "exam", text: "Toujours relever la référence complète avant de chercher la signification d’une LED." }, visual: { kind: "triple", title: "Croiser modèle, fluide et compresseur", label: "Triplet fluide, compresseur et régulateur électronique compatible" } },
    { id: "montage", short: "Monter", kicker: "Station 2 · Installation", title: "Position, adaptateur et câblage conditionnent la mesure", lead: "Le régulateur se monte sur le raccord de voyant avec l’adaptateur prévu.", details: ["Respecter orientation, joints, alimentation électrique, contact d’alarme et mise à la terre selon la notice.", "Installer les vannes et le filtre demandés en amont ; réaliser le contrôle d’étanchéité avant mise en service."], box: { type: "warning", text: "Une bonne LED sur un montage incliné ou mal câblé ne valide pas l’installation." }, visual: { kind: "oilLine", title: "Préparer toute la ligne", label: "Réservoir, vanne, filtre, TraxOil et carter" } },
    { id: "bp", short: "Circuit BP", kicker: "Station 3 · Architecture", title: "En basse pression, un réservoir dégaze et distribue", lead: "Le séparateur envoie l’huile vers un réservoir maintenu au-dessus de la pression des carters.", details: ["Une branche de dégazage contrôlée rejoint l’aspiration ; la ligne liquide d’huile passe par vannes et filtre vers le TraxOil.", "Cette architecture découple la haute pression de refoulement de l’alimentation des carters."], box: { type: "key", text: "Clapet différentiel sur la pression ; TraxOil sur la distribution d’huile." }, visual: { kind: "bpHp", title: "Repérer le circuit basse pression", label: "Séparateur, réservoir basse pression, clapet différentiel, filtre et régulateur" } },
    { id: "hp", short: "Circuit HP", kicker: "Station 4 · Architecture", title: "En haute pression, le régulateur doit accepter toute la différence", lead: "Une réserve intégrée au séparateur peut alimenter directement un régulateur électronique compatible.", details: ["L’huile sous haute pression contient davantage de fluide dissous ; sa détente au carter peut provoquer dégazage et mousse.", "Le débit, l’orifice, le modèle et la stratégie d’injection sont donc imposés par le fabricant."], box: { type: "warning", text: "Un régulateur mécanique standard ne remplace pas un modèle prévu pour retour haute pression." }, visual: { kind: "bpHp", title: "Comparer BP et HP", label: "Réservoir basse pression séparé et réserve haute pression alimentant un régulateur compatible" } },
    { id: "diagnostic", short: "Diagnostiquer", kicker: "Station 5 · Chaîne de preuve", title: "Une LED rouge ne désigne pas automatiquement un TraxOil défectueux", lead: "Elle indique que le niveau n’est pas revenu comme attendu.", details: ["Vérifier réserve, pression amont, vannes, filtre, alimentation électrique, électrovanne, adaptateur et historique.", "Puis contrôler séparateur, retour naturel, fuites et régimes : le contrôleur peut signaler correctement un défaut extérieur."], box: { type: "exam", text: "Lire l’état, mesurer l’amont, vérifier la commande, puis décider." }, visual: { kind: "diagnostic", title: "Chercher la cause en amont et en aval", label: "Chaîne de diagnostic du circuit jusqu’au régulateur électronique" } }
  ],
  quiz: [
    { prompt: "Que vérifier avant de remplacer un OM3 par un OM4 ou un OM5 ?", options: ["La couleur du boîtier et sa hauteur", "Pression, fluide, joints et alimentation", "Rien : les trois sont équivalents"], correct: 1, why: "Pression, fluide, joints, adaptateurs et alimentation doivent correspondre.", code: "1.05" },
    { prompt: "Que contrôler lors du montage ?", options: ["Longueur du câble et tension du réseau", "Repère du voyant et sens du regard", "Orientation, adaptateur, joints, filtre"], correct: 2, why: "La mesure et l’étanchéité dépendent de toute l’installation.", code: "1.05" },
    { prompt: "Dans un circuit BP, où agit le clapet taré ?", options: ["Sur la branche de pression vers l’aspiration", "Sur la conduite d’huile vers le carter", "Sur la ligne liquide, après le détendeur"], correct: 0, why: "Il maintient la pression du réservoir au-dessus de l’aspiration.", code: "1.05" },
    { prompt: "Quel risque accompagne un retour HP direct ?", options: ["Gel de la ligne liquide au condenseur", "Dégazage et mousse à la détente au carter", "Perte totale de l’huile du carter"], correct: 1, why: "Le fluide dissous peut se vaporiser brutalement à la chute de pression.", code: "1.05 · 6.05" },
    { prompt: "La LED rouge du TraxOil est allumée. Que faire ?", options: ["Remplacer le contrôleur sans mesurer", "Ajouter de l’huile jusqu’à extinction", "Vérifier toute la chaîne d’alimentation"], correct: 2, why: "Le contrôleur peut signaler correctement un défaut qui lui est extérieur.", code: "6.05" }
  ],
  sources: [
    { title: "Copeland — OM3/OM4/OM5 TraxOil Technical Information", url: "https://media.copeland.com/d8f801b5-15db-4430-bbda-b16b01022eae/OM3_OM4_OM5_TB_EN_0820_R08.pdf", use: "capteur Hall, électrovanne, zones, alarme et domaines OM3/4/5" },
    { title: "BITZER — Parallel compounding with oil level controllers", url: "https://www.bitzer.de/shared_media/html/kt-600/en-GB/313846411313848587.html", use: "architectures basse et haute pression" },
    { title: "Parker Sporlan — Oil Level Control System", url: "https://www.parker.com/content/dam/Parker-com/Literature/Sporlan/Sporlan-pdf-files/Sporlan-pdf-110/SD-129_-Oil-Level-Control-System-Installation.pdf", use: "filtration, réservoir et diagnostic de ligne" },
    { title: "Légifrance — Attestation d’aptitude fluides", url: "https://www.legifrance.gouv.fr/jorf/id/JORFSCTA000053004646", use: "compétences 1.05 et 6.05" }
  ]
};
