(() => {
  "use strict";
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><pattern id="drop-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#c9451a" stroke-width="2"/></pattern></defs>${body}</svg>`;

  const identify=shell("loss-ident","Résistances régulières et singulières","Une longueur droite porte des pertes régulières. Un coude, une vanne et un filtre portent des pertes singulières. Toutes participent à la perte de pression du chemin.",
    `<text x="360" y="42" text-anchor="middle" font-size="22" font-weight="700">OÙ LE PASSAGE RÉSISTE-T-IL ?</text>
     <g transform="translate(35 92)"><rect width="300" height="240" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><path d="M45 125H255" stroke="#3d7fca" stroke-width="18"/><path d="M65 95h170M65 155h170" stroke="#1b3a63" stroke-width="2" stroke-dasharray="7 5"/><text x="150" y="45" text-anchor="middle" font-size="19" font-weight="700">RÉGULIÈRE</text><text x="150" y="205" text-anchor="middle" font-size="15">longueur · diamètre · débit</text></g>
     <g transform="translate(385 92)"><rect width="300" height="240" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><path d="M40 145H100V80H260" fill="none" stroke="#3d7fca" stroke-width="18" stroke-linejoin="round"/><image href="assets/vanne_manuelle.svg" x="115" y="48" width="70" height="70"/><image href="assets/filtre_hydraulique.svg" x="200" y="48" width="70" height="70"/><text x="150" y="45" text-anchor="middle" font-size="19" font-weight="700">SINGULIÈRE</text><text x="150" y="205" text-anchor="middle" font-size="15">coude · vanne · filtre</text></g>
     <text x="360" y="380" text-anchor="middle" font-size="16">Les mots et les formes restent lisibles sans la couleur.</text>`);

  const pressure=shell("loss-pressure","Chute de pression dans le sens de l’écoulement","Deux prises de pression encadrent une résistance. Dans un état connu et avec un débit donné, la pression en aval est plus faible. La différence est la perte de charge du tronçon.",
    `<path d="M60 215H660" stroke="#3d7fca" stroke-width="18" marker-end="url(#arr-loss-pressure)"/>
     <path d="M300 165L360 215L300 265M420 165L360 215L420 265" fill="#fffdf8" stroke="#1b3a63" stroke-width="6"/>
     <circle cx="180" cy="215" r="30" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="180" y="221" text-anchor="middle" font-size="17" font-weight="700">p₁</text>
     <circle cx="540" cy="215" r="30" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="540" y="221" text-anchor="middle" font-size="17" font-weight="700">p₂</text>
     <path d="M180 170V92H540V170" fill="none" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/>
     <text x="360" y="78" text-anchor="middle" font-size="20" font-weight="700">Δp = p₁ − p₂</text>
     <text x="180" y="290" text-anchor="middle" font-size="16" font-weight="700">AMONT</text><text x="540" y="290" text-anchor="middle" font-size="16" font-weight="700">AVAL</text>
     <rect x="190" y="330" width="340" height="55" rx="14" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="360" y="364" text-anchor="middle" font-size="16" font-weight="700">Comparer à débit et état connus</text>`);

  function flowScene(q=2){const k=.5,dp=k*q*q;const width=Math.max(9,Math.min(30,q*9));const bar=Math.min(410,dp*42);return shell("loss-flow","Effet du débit sur la perte de charge",`Le modèle utilise delta p égale K fois Q au carré avec K égal à 0,5 mCE par mètre cube par heure au carré. Pour Q égal à ${q.toFixed(1)} mètre cube par heure, delta p vaut ${dp.toFixed(2)} mCE.`,
    `<text x="360" y="42" text-anchor="middle" font-size="21" font-weight="700">MODÈLE : Δp = K × Q²</text><text x="360" y="70" text-anchor="middle" font-size="15">K = 0,5 mCE/(m³/h)² · valeur pédagogique</text>
     <path d="M60 185H500" stroke="#3d7fca" stroke-width="${width}" marker-end="url(#arr-loss-flow)"/>
     <path d="M255 135L315 185L255 235M375 135L315 185L375 235" fill="#fffdf8" stroke="#1b3a63" stroke-width="6"/>
     <rect x="555" y="80" width="95" height="260" rx="15" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><rect x="570" y="${330-bar}" width="65" height="${bar}" rx="9" fill="url(#drop-loss-flow)" stroke="#c9451a" stroke-width="3"/>
     <text x="603" y="365" text-anchor="middle" font-size="15" font-weight="700">Δp</text><text x="315" y="300" text-anchor="middle" font-size="19" font-weight="700">Q = ${q.toFixed(1)} m³/h</text><text x="315" y="330" text-anchor="middle" font-size="19" font-weight="700">Δp = ${dp.toFixed(2)} mCE</text>`);}

  function passageScene(close=40){const k=.2+4*Math.pow(close/100,2),q=Math.sqrt(4/(k+.2)),dp=k*q*q,gap=Math.max(8,68*(1-close/100));return shell("loss-passage","Effet d’une vanne sur le passage","La fermeture relative vaut ${close} pour cent. Le coefficient de résistance pédagogique vaut ${k.toFixed(2)}. Le point du modèle donne un débit ${q.toFixed(1)} mètre cube par heure et une perte de charge locale ${dp.toFixed(1)} mCE.",
    `<text x="360" y="42" text-anchor="middle" font-size="21" font-weight="700">PASSAGE RÉDUIT → RÉSISTANCE PLUS FORTE</text>
     <path d="M65 220H655" stroke="#3d7fca" stroke-width="18" marker-end="url(#arr-loss-passage)"/>
     <g transform="translate(360 220)"><path d="M-95 -75L-${gap/2} 0L-95 75M95 -75L${gap/2} 0L95 75" fill="#fffdf8" stroke="#1b3a63" stroke-width="8"/><path d="M0 -120V-${gap/2}" stroke="#1b3a63" stroke-width="8"/><circle cy="-132" r="26" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/></g>
     <rect x="75" y="75" width="210" height="62" rx="15" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="180" y="102" text-anchor="middle" font-size="16" font-weight="700">FERMETURE : ${close} %</text><text x="180" y="126" text-anchor="middle" font-size="14">K = ${k.toFixed(2)}</text>
     <rect x="448" y="300" width="205" height="70" rx="15" fill="#e3f5ec" stroke="#1e7e54" stroke-width="5"/><text x="550" y="329" text-anchor="middle" font-size="16" font-weight="700">Q ≈ ${q.toFixed(1)} m³/h</text><text x="550" y="353" text-anchor="middle" font-size="16" font-weight="700">Δp locale ≈ ${dp.toFixed(1)} mCE</text>`);}

  const diag=shell("loss-diag","Chercher la résistance anormale","Le chemin critique est suivi du départ au retour. Les prises de pression sont placées de part et d’autre de chaque tronçon suspect. Mesure, comparaison et hypothèse précèdent toute intervention.",
    `<path d="M55 215H665" stroke="#1b3a63" stroke-width="12"/>
     ${[[145,"TUBE"],[300,"FILTRE"],[455,"VANNE"],[610,"BRANCHE"]].map(([x,t],i)=>`<circle cx="${x}" cy="215" r="42" fill="${i===1?"#fff4e0":"#fffdf8"}" stroke="${i===1?"#b06a00":"#1b3a63"}" stroke-width="${i===1?4:3}" stroke-dasharray="${i===1?"5 5":"0"}"/><text x="${x}" y="221" text-anchor="middle" font-size="13" font-weight="700">${t}</text>`).join("")}
     <circle cx="245" cy="120" r="25" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><text x="245" y="126" text-anchor="middle" font-size="14">p₁</text><circle cx="355" cy="120" r="25" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><text x="355" y="126" text-anchor="middle" font-size="14">p₂</text><path d="M245 145V173M355 145V173" stroke="#1b3a63" stroke-width="3" stroke-dasharray="4 3"/>
     <text x="360" y="55" text-anchor="middle" font-size="22" font-weight="700">LOCALISER AVANT DE REMPLACER</text>
     <rect x="145" y="310" width="430" height="58" rx="15" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="360" y="345" text-anchor="middle" font-size="16" font-weight="700">Q connu → Δp mesurée → comparaison → hypothèse</text>`);

  window.STATION_CONFIG={code:"E5",id:"pertes",title:"Pertes de charge",next:"poursuivre vers le vase d’expansion",levels:{CAP:{objective:"Reconnaître une résistance sur le trajet de l’eau.",assessment:"nommer une résistance et lire une pression"},TP:{objective:"Localiser une résistance hydraulique anormale par des contrôles comparés.",assessment:"distinguer les pertes et choisir les points de mesure"},BTS:{objective:"Relier géométrie, débit et pertes de charge sur le chemin critique.",assessment:"calculer dans le modèle, comparer et justifier une hypothèse"}},steps:[
    {short:"Identifier",narration: "Tout ce que l'eau traverse lui résiste, mais pas de la même façon. On distingue deux familles. La résistance régulière, c'est le frottement de l'eau contre la paroi tout au long d'une conduite droite : elle grandit avec la longueur. La résistance singulière, c'est ce que provoque un obstacle localisé — un coude, un té, une vanne, un filtre, un rétrécissement. Elle ne dépend pas de la longueur mais de la forme de l'obstacle. Cette distinction est utile en dépannage : un défaut apparu brutalement vient presque toujours d'une singularité, jamais d'une conduite droite qui aurait vieilli d'un coup.", kicker:"repérer",title:"Régulière ou singulière ?",text:"Une conduite droite et un organe ne créent pas la même famille de résistance.",cap:"Nomme un organe qui gêne le passage de l’eau.",tp:"Classe les éléments visibles.",bts:"Prépare ensuite longueurs, diamètres, débits et coefficients adaptés.",scene:identify,equivalent:"La longueur de tube représente une perte régulière. Coude, vanne et filtre représentent des pertes singulières.",action:{type:"match",prompt:"Associe chaque élément.",options:["Perte régulière","Perte singulière"],items:[{label:"Longueur droite",answer:0},{label:"Coude",answer:1},{label:"Vanne",answer:1},{label:"Filtre",answer:1}],explain:"Les deux familles s’additionnent sur le chemin hydraulique. Leur valeur dépend des conditions réelles."}},
    {short:"Fonction",narration: "Comment savoir ce qu'un élément coûte réellement à l'eau ? En mesurant la pression de chaque côté. La différence entre l'amont et l'aval est la preuve du passage : c'est ce que l'eau a dû dépenser pour traverser. Deux conditions pour que ce chiffre veuille dire quelque chose. D'abord, les deux prises doivent encadrer l'élément étudié, et lui seul — c'est le même principe que les deux sondes autour d'un émetteur à la station Écart. Ensuite, le débit doit être connu et stable, car la même perte de charge n'a pas du tout le même sens à des débits différents.", kicker:"comprendre",title:"Une différence de pression prouve le passage",text:"Place les prises amont et aval autour de l’élément étudié et garde le débit et l’état du réseau connus.",cap:"Lis les deux pressions de chaque côté de l’organe.",tp:"Lis p1, p2 et calcule la différence selon le protocole.",bts:"Relie la mesure aux hypothèses du modèle et à l’incertitude.",scene:pressure,equivalent:"Deux prises p1 en amont et p2 en aval encadrent une résistance. La perte de charge est la différence de pression à débit connu.",action:{type:"choice",prompt:"Quelle comparaison localise la résistance d’un filtre ?",options:[{label:"Pression juste avant et juste après, à débit connu"},{label:"Température extérieure seulement"},{label:"Une pression sur une autre branche"},{label:"Le bruit seul"}],correct:0,explain:"La mesure différentielle autour du filtre, dans un état défini, permet de comparer sa résistance au comportement attendu."}},
    {short:"Débit",narration: "Voilà le point le plus important de cette station. Quand le débit augmente, la perte de charge n'augmente pas proportionnellement : elle augmente beaucoup plus vite, à peu près comme le carré du débit. Doublez le débit, et la résistance est multipliée par quatre environ. Cette relation explique quantité de comportements de terrain. Elle explique pourquoi un circulateur poussé à fond n'apporte pas le gain de débit espéré : l'effort supplémentaire est mangé par la résistance qui s'envole. Elle explique aussi pourquoi les réseaux surdimensionnés en débit consomment tant.", kicker:"observer",title:"Le débit amplifie la perte",text:"Fais varier Q dans une relation quadratique pédagogique. L’unité et le coefficient sont affichés.",cap:"Lis le nouveau débit après avoir bougé le curseur.",tp:"Observe l’ordre de grandeur dans ce seul modèle.",bts:"Calcule Δp = KQ² puis distingue ce calcul d’un abaque ou d’une donnée constructeur.",scene:flowScene,equivalent:(q)=>`Pour Q ${Number(q).toFixed(1)} m³/h et K pédagogique 0,5 mCE par m³/h au carré, Δp vaut ${(0.5*q*q).toFixed(2)} mCE.`,action:{type:"range",prompt:"Modifie le débit.",label:"Débit Q",min:.5,max:3,step:.5,value:2,evaluate:(q)=>({readout:`${q.toFixed(1)} m³/h`,observation:`Δp = 0,5 × ${q.toFixed(1)}² = ${(0.5*q*q).toFixed(2)} mCE. Doubler Q multiplie ici Δp par quatre.`})}},
    {short:"Passage",narration: "Réduisez maintenant le passage d'une vanne. La résistance du réseau augmente, sa courbe se redresse, et le point de rencontre avec la pompe glisse vers un débit plus faible. Vous reconnaissez la mécanique de la station Circulateur, vue cette fois du côté du réseau. Retenez l'ordre de grandeur : une vanne à demi fermée peut coûter plus qu'une dizaine de mètres de conduite droite. C'est pourquoi une vanne d'isolement mal rouverte après un chantier passe inaperçue au premier coup d'œil et suffit à priver toute une branche.", kicker:"régler",title:"Fermer une vanne redresse le réseau",text:"Réduis le passage. La résistance augmente et le débit issu de la rencontre avec la pompe simplifiée diminue.",cap:"Lis l’effet du réglage de la vanne sur le débit.",tp:"Compare l’état avant/après sans fermer au hasard sur une installation réelle.",bts:"Relie le coefficient local à la courbe réseau et au point de fonctionnement.",scene:passageScene,equivalent:(v)=>{const k=.2+4*Math.pow(v/100,2),q=Math.sqrt(4/(k+.2));return`Fermeture relative ${v} %. Coefficient ${k.toFixed(2)}. Débit du modèle ${q.toFixed(1)} m³/h.`;},action:{type:"range",prompt:"Réduis le passage virtuel.",label:"Fermeture relative",min:0,max:90,step:10,value:40,evaluate:(v)=>{const k=.2+4*Math.pow(v/100,2),q=Math.sqrt(4/(k+.2));return{readout:`${v} %`,observation:`K ≈ ${k.toFixed(2)} ; Q ≈ ${q.toFixed(1)} m³/h. La fermeture augmente la résistance du réseau.`};}}},
    {short:"Vérifier",narration: "Chassez les pertes avec méthode, c'est-à-dire par élimination et non par remplacement. Une branche manque de débit : localisez la zone résistante en mesurant la pression en plusieurs points successifs, du départ vers l'émetteur. La chute anormale se produit quelque part entre deux de ces points, et c'est là qu'il faut chercher. Remplacer un filtre parce qu'un filtre est toujours suspect, c'est parfois efficace et jamais démontré. Si le problème réel était ailleurs, vous aurez changé une pièce pour rien, et le défaut sera toujours là.", kicker:"hypothèse",title:"Chasser les pertes avec méthode",text:"Une branche manque de débit. Localisez la zone résistante avec des mesures, sans remplacer filtre ou vanne au hasard.",cap:"Signale la branche à faible débit sans changer de pièce.",tp:"Décris le chemin, mesure puis rends compte.",bts:"Compare le chemin critique calculé et les différences de pression mesurées.",scene:diag,equivalent:"Le chemin comporte tube, filtre, vanne et branche. Deux prises de pression encadrent le filtre suspect. La démarche garde le débit connu.",action:{type:"sequence",prompt:"Ordonne la vérification.",items:["Définir l’état et le débit","Suivre le chemin critique","Mesurer Δp par tronçon","Comparer et retenir une hypothèse"],correctOrder:[0,1,2,3],explain:"La localisation vient de comparaisons cohérentes. Une pièce n’est remplacée qu’après confirmation et selon la procédure."}}
  ],quiz:[
    {context:"Une conduite longue comporte aussi deux coudes.",question:"Comment classer les résistances ?",options:["Tube : régulière; coudes : singulières","Tout est régulier","Tout est singulier","Aucune perte"],correct:0,explain:"Les pertes régulières viennent de la longueur; les singularités des changements locaux."},
    {context:"Dans le modèle Δp = 0,5 Q² avec Q = 2 m³/h.",question:"Quelle est la perte calculée ?",options:["2,0 mCE","1,0 mCE","4,0 mCE","0,5 mCE"],correct:0,explain:"0,5 × 2² = 2,0 mCE. Le coefficient est pédagogique et porte son unité."},
    {context:"Une vanne se ferme davantage.",question:"Quel effet de réseau est attendu ?",options:["Résistance en hausse et débit d’intersection en baisse","Résistance nulle","Débit garanti en hausse","Pompe supprimée"],correct:0,explain:"La restriction redresse la courbe réseau et déplace le point de fonctionnement."},
    {context:"Une branche manque de débit.",question:"Quelle vérification vient avant le remplacement du filtre ?",options:["Débit connu et Δp mesurée autour du filtre","Changer le filtre au hasard","Augmenter la pompe au maximum","Neutraliser la soupape"],correct:0,explain:"La mesure localisée, comparée à un état attendu, teste l’hypothèse de filtre résistant."}
  ],summaryScene:pressure,summaryEquivalent:"Synthèse : pertes régulières et singulières s’additionnent. Leur effet dépend fortement du débit et se localise par des mesures amont-aval en état connu."};
})();
