(() => {
  "use strict";
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><pattern id="warm-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#c9451a" stroke-width="2"/></pattern><pattern id="cool-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="1.5" fill="#3d7fca"/></pattern></defs>${body}</svg>`;
  const fields=shell("rel-fields","Les six champs d’un relevé exploitable","Une fiche associe grandeur, point, valeur, unité, date et heure, puis état de fonctionnement. Le contexte est aussi important que le nombre.",`<rect x="100" y="48" width="520" height="325" rx="22" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="360" y="84" text-anchor="middle" font-size="22" font-weight="700">FICHE DE RELEVÉ</text>${["GRANDEUR","POINT","VALEUR + UNITÉ","DATE · HEURE","ÉTAT DE FONCTIONNEMENT"].map((t,i)=>`<rect x="140" y="${105+i*47}" width="440" height="36" rx="8" fill="${i%2?"url(#cool-rel-fields)":"#fffdf8"}" stroke="#1b3a63" stroke-width="2"/><text x="160" y="${129+i*47}" font-size="15" font-weight="700">${t}</text>`).join("")}<text x="360" y="360" text-anchor="middle" font-size="15">Un tiers doit pouvoir comprendre et comparer.</text>`);
  const instrument=shell("rel-tool","Instrument et point de mesure","Un débitmètre est placé sur la conduite de la branche B. Deux sondes de contact sont posées sur le départ et le retour du même émetteur. Chaque grandeur porte son unité.",`<path d="M70 130H650V310H70Z" fill="none" stroke="#1b3a63" stroke-width="13" stroke-linejoin="round"/><path d="M135 130H300" stroke="#3d7fca" stroke-width="6" stroke-dasharray="12 8" marker-end="url(#arr-rel-tool)"/><rect x="275" y="92" width="130" height="75" rx="13" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="340" y="122" text-anchor="middle" font-size="16" font-weight="700">DÉBITMÈTRE</text><text x="340" y="149" text-anchor="middle" font-size="15">m³/h</text><circle cx="500" cy="130" r="20" fill="#fffdf8" stroke="#c9451a" stroke-width="5"/><circle cx="500" cy="310" r="20" fill="#fffdf8" stroke="#3d7fca" stroke-width="5"/><text x="535" y="137" font-size="16" font-weight="700">T départ · °C</text><text x="535" y="317" font-size="16" font-weight="700">T retour · °C</text><text x="120" y="220" font-size="18" font-weight="700">BRANCHE B</text>`);
  const record=shell("rel-record","Relevés avant et après","Deux colonnes avant et après reprennent les mêmes points, unités et état stabilisé. Les valeurs sont des données pédagogiques du scénario.",`<text x="360" y="42" text-anchor="middle" font-size="20" font-weight="700">DONNÉES PÉDAGOGIQUES DU SCÉNARIO</text>${[[45,"AVANT","08:40","0,8 m³/h","50 °C / 42 °C"],[375,"APRÈS","09:05","1,0 m³/h","50 °C / 41 °C"]].map(([x,t,h,q,temp])=>`<rect x="${x}" y="70" width="300" height="275" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="${x+150}" y="108" text-anchor="middle" font-size="20" font-weight="700">${t}</text><text x="${x+25}" y="150" font-size="16">Branche B · ${h}</text><text x="${x+25}" y="190" font-size="16">Pompe : mode constant</text><text x="${x+25}" y="230" font-size="16">État : stabilisé</text><text x="${x+25}" y="270" font-size="18" font-weight="700">Q = ${q}</text><text x="${x+25}" y="310" font-size="18" font-weight="700">T = ${temp}</text>`).join("")}<path d="M345 205H373" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-rel-record)"/>`);
  const compare=shell("rel-compare","Comparer seulement des conditions connues","Une balance compare les mêmes points, le même instrument, le même mode de pompe et deux états stabilisés. Si une condition change, la conclusion est limitée.",`<path d="M360 85V320M185 145H535" stroke="#1b3a63" stroke-width="8"/><path d="M185 145L115 270H255Z" fill="#fffdf8" stroke="#3d7fca" stroke-width="4"/><path d="M535 145L465 270H605Z" fill="#fffdf8" stroke="#c9451a" stroke-width="4"/><text x="185" y="295" text-anchor="middle" font-size="18" font-weight="700">AVANT</text><text x="535" y="295" text-anchor="middle" font-size="18" font-weight="700">APRÈS</text>${["mêmes points","mêmes unités","même mode","stabilisé"].map((t,i)=>`<rect x="275" y="${115+i*48}" width="170" height="32" rx="16" fill="#fffdf8" stroke="#1e7e54" stroke-width="3"/><text x="360" y="${137+i*48}" text-anchor="middle" font-size="14" font-weight="700">${t}</text>`).join("")}`);
  const method=shell("rel-method","Chaîne d’un réglage traçable","Cinq cartes sont reliées dans l’ordre : état initial, action unique, stabilisation, nouveau relevé, conclusion limitée aux preuves.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["ÉTAT INITIAL","ACTION UNIQUE","STABILISER","NOUVEAU RELEVÉ","CONCLURE"].map((t,i)=>`<rect x="${20+i*140}" y="155" width="120" height="100" rx="15"/><text x="${80+i*140}" y="197" text-anchor="middle" font-size="13" font-weight="700">${t}</text><text x="${80+i*140}" y="225" text-anchor="middle" font-size="12">${i+1}</text>`).join("")}</g>${[0,1,2,3].map(i=>`<path d="M${140+i*140} 205H${158+i*140}" stroke="#c9451a" stroke-width="5" marker-end="url(#arr-rel-method)"/>`).join("")}<text x="360" y="310" text-anchor="middle" font-size="17" font-weight="700">Compte rendu = faits + comparaison + limite</text>`);

  window.STATION_CONFIG={code:"M2",id:"releves",title:"Relevés — La preuve exploitable",next:"poursuivre vers la correspondance Équilibrage",levels:{CAP:{objective:"Lire une valeur avec son unité et son point de mesure.",assessment:"lire une valeur, son unité et son point"},TP:{objective:"Renseigner une fiche avant/après compréhensible par un tiers.",assessment:"choisir le point, l’instrument, l’unité et rendre compte"},BTS:{objective:"Construire une comparaison défendable et en expliciter les limites.",assessment:"contrôler la comparabilité, traiter les écarts et justifier la conclusion"}},steps:[
    {short:"Champs",kicker:"observer",title:"Un nombre ne suffit pas",text:"Le relevé doit décrire ce qui est mesuré, où, quand et dans quel état.",cap:"Montre où écrire la valeur, l’unité et l’heure.",tp:"Repère les informations à écrire sur la fiche.",bts:"Distingue donnée, métadonnée et condition de validité.",scene:fields,equivalent:"La fiche comporte grandeur, point, valeur et unité, date et heure, puis état de fonctionnement.",action:{type:"match",prompt:"Associe l’information à sa fonction.",options:["Ce qui est mesuré","Où la mesure est faite","Contexte temporel"],items:[{label:"Débit",answer:0},{label:"Branche B",answer:1},{label:"08:40 · stabilisé",answer:2}],explain:"La valeur devient interprétable quand grandeur, point et contexte sont liés."}},
    {short:"Choisir",kicker:"mesurer",title:"Instrument, point, unité",text:"Choisis un ensemble cohérent avant d’ouvrir la fiche.",cap:"Nomme l’instrument qui mesure le débit.",tp:"Associe le débitmètre et les sondes aux points indiqués.",bts:"Vérifie que la stratégie permet la comparaison recherchée.",scene:instrument,equivalent:"Le débitmètre mesure le débit de la branche B; deux sondes de contact mesurent départ et retour du même émetteur.",action:{type:"choice",prompt:"Quel ensemble produit une preuve exploitable ?",options:[{label:"Débitmètre sur B en m³/h + sondes départ/retour en °C"},{label:"Sonde d’ambiance seule, sans point"},{label:"Pression en kW/h"},{label:"Valeur sans unité"}],correct:0,explain:"L’instrument, le point et l’unité correspondent aux grandeurs comparées."}},
    {short:"Tracer",kicker:"relever",title:"Construire l’avant et l’après",text:"Les valeurs affichées sont des données pédagogiques du scénario, pas une plage universelle.",cap:"Lis le débit avant et le débit après.",tp:"Lis les deux relevés sans conclure sur une panne.",bts:"Contrôle que les conditions permettent une comparaison limitée.",scene:record,equivalent:"Avant et après portent la branche B, l’heure, le mode de pompe, l’état stabilisé, le débit et deux températures.",action:{type:"match",prompt:"Classe les éléments du compte rendu.",options:["Condition identique","Valeur avant","Valeur après"],items:[{label:"Pompe en mode constant",answer:0},{label:"Q = 0,8 m³/h",answer:1},{label:"Q = 1,0 m³/h",answer:2}],explain:"Le mode identique rend la variation de débit comparable dans ce scénario."}},
    {short:"Comparer",kicker:"interpréter",title:"Avant/après : mêmes conditions",text:"Une comparaison est fragile si le point, le mode ou l’état change en même temps.",cap:"Contrôle si les deux relevés utilisent le même point.",tp:"Vérifie les quatre conditions écrites.",bts:"Énonce ce que les données prouvent et ce qu’elles ne prouvent pas.",scene:compare,equivalent:"Les deux états sont comparés avec mêmes points, mêmes unités, même mode de pompe et après stabilisation.",action:{type:"choice",prompt:"Quelle conclusion est défendable ?",options:[{label:"Le débit de B a augmenté dans les conditions notées"},{label:"Toute panne du réseau est supprimée"},{label:"Le résultat vaut pour toutes les installations"},{label:"La température seule prouve la cause"}],correct:0,explain:"La fiche décrit une variation observée. Elle ne généralise pas et n’identifie pas seule une cause."}},
    {short:"Rendre compte",kicker:"décider",title:"Une action, puis un nouveau relevé",text:"Ordonne la méthode avant de rédiger la conclusion.",cap:"Relève l’action faite avant le deuxième relevé.",tp:"Rends compte de l’action et du contrôle.",bts:"Sépare observation, interprétation et limite du modèle.",scene:method,equivalent:"La chaîne va de l’état initial à une action unique, puis stabilisation, nouveau relevé et conclusion.",action:{type:"sequence",prompt:"Place les cinq étapes dans l’ordre.",items:["État initial","Action unique","Stabilisation","Nouveau relevé","Conclusion"],correctOrder:[0,1,2,3,4],explain:"Changer un seul paramètre et attendre la stabilisation permet d’attribuer prudemment l’effet observé."}}
  ],quiz:[
    {context:"Une fiche indique seulement 1,0.",question:"Que manque-t-il en priorité ?",options:["Grandeur, point, unité et contexte","Une couleur","Une marque","Un verdict"],correct:0,explain:"La valeur isolée n’est pas exploitable."},
    {context:"Deux débits sont comparés avec deux modes de pompe différents.",question:"Quelle attitude adopter ?",options:["Limiter la conclusion et refaire dans des conditions connues","Déclarer la panne résolue","Supprimer l’unité","Choisir le plus grand nombre"],correct:0,explain:"Le changement de mode peut expliquer une partie de l’écart."},
    {context:"Après un réglage unique, le débit change.",question:"Quelle étape vient avant la conclusion ?",options:["Stabiliser puis refaire le relevé","Changer un second réglage","Effacer l’état initial","Remplacer l’organe"],correct:0,explain:"Le nouveau relevé stabilisé constitue la preuve avant/après."},
    {context:"Le relevé avant/après est cohérent.",question:"Quel compte rendu est juste ?",options:["Faits, conditions, comparaison et limites","Une panne certaine","Une valeur sans unité","Une promesse certificative"],correct:0,explain:"Le compte rendu distingue les faits de l’interprétation."}
  ],summaryScene:method,summaryEquivalent:"Synthèse : état initial, action unique, stabilisation, nouveau relevé et conclusion limitée aux preuves."};
})();
