(() => {
  "use strict";
  const stations=[
    {id:"production",title:"Production",hint:"Fonction avant technologie",status:"QA technique"},
    {id:"echangeur",title:"Échangeur",hint:"Deux circuits séparés",status:"QA technique"},
    {id:"debit",title:"Débit",hint:"Correspondance Ligne P",status:"Correspondance P",interchange:true},
    {id:"circulateur",title:"Circulateur",hint:"Pompe + réseau",status:"QA technique"},
    {id:"pertes",title:"Pertes de charge",hint:"Résistances du chemin",status:"QA technique",interchange:true},
    {id:"vase",title:"Vase",hint:"Dilatation et précharge",status:"QA technique"},
    {id:"securite",title:"Sécurité",hint:"Protéger sans neutraliser",status:"QA technique"}
  ];
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><pattern id="warm-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#c9451a" stroke-width="2"/></pattern><pattern id="cool-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="1.5" fill="#3d7fca"/></pattern></defs>${body}</svg>`;
  const prodScene=shell("line-prod","Fonction et technologies de production","Trois technologies différentes convergent vers la fonction transférer de l’énergie avec l’eau.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["Chaudière","PAC","Groupe eau glacée"].map((t,i)=>`<rect x="${35+i*230}" y="80" width="190" height="105" rx="17"/><text x="${130+i*230}" y="140" text-anchor="middle" font-size="18" font-weight="700">${t}</text>`).join("")}</g><path d="M130 185L300 275M360 185v90M590 185L420 275" stroke="#3d7fca" stroke-width="6" fill="none" marker-end="url(#arr-line-prod)"/><rect x="245" y="275" width="230" height="85" rx="20" fill="url(#warm-line-prod)" stroke="#c9451a" stroke-width="4"/><text x="360" y="311" text-anchor="middle" font-size="18" font-weight="700">FONCTION COMMUNE</text><text x="360" y="338" text-anchor="middle" font-size="15">transférer l’énergie</text>`);
  const exScene=shell("line-ex","Échangeur à quatre piquages","Le primaire va de P1 à P2. Le secondaire va de S1 à S2 en sens opposé. Les circuits restent séparés.",`<rect x="250" y="60" width="220" height="295" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/>${Array.from({length:8},(_,i)=>`<path d="M${278+i*24} 95V320" stroke="${i%2?"#c9451a":"#3d7fca"}" stroke-width="8"/>`).join("")}<path d="M55 110H250M250 310H55" stroke="#c9451a" stroke-width="11" marker-end="url(#arr-line-ex)"/><path d="M665 310H470M470 110H665" stroke="#3d7fca" stroke-width="11" marker-end="url(#arr-line-ex)"/><text x="150" y="82" text-anchor="middle" font-size="17" font-weight="700">P1 · primaire entrée</text><text x="150" y="350" text-anchor="middle" font-size="17" font-weight="700">P2 · primaire sortie</text><text x="575" y="350" text-anchor="middle" font-size="17" font-weight="700">S1 · secondaire entrée</text><text x="575" y="82" text-anchor="middle" font-size="17" font-weight="700">S2 · secondaire sortie</text>`);
  const safeChain=shell("line-safe-chain","Chaîne de protection","Un manomètre, un vase, une soupape et une évacuation sûre sont raccordés à un réseau.",`<path d="M55 235H665" stroke="#1b3a63" stroke-width="14"/><circle cx="210" cy="165" r="45" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><path d="M210 165L235 140" stroke="#c9451a" stroke-width="5"/><text x="210" y="105" text-anchor="middle" font-size="16" font-weight="700">MANOMÈTRE</text><ellipse cx="390" cy="320" rx="55" ry="42" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><path d="M390 235V278" stroke="#1b3a63" stroke-width="10"/><text x="390" y="326" text-anchor="middle" font-size="16" font-weight="700">VASE</text><path d="M550 235V145" stroke="#1b3a63" stroke-width="10"/><path d="M510 145L550 110L590 145Z" fill="#fffdf8" stroke="#c0392b" stroke-width="5"/><path d="M590 145H660V345" fill="none" stroke="#c0392b" stroke-width="8" stroke-dasharray="11 7" marker-end="url(#arr-line-safe-chain)"/><text x="550" y="82" text-anchor="middle" font-size="16" font-weight="700">SOUPAPE</text><text x="635" y="375" text-anchor="middle" font-size="14">évacuation sûre</text>`);
  const classifyScene=shell("line-class","Pertes régulières et singulières","Une longueur droite est comparée à un coude, une vanne et un filtre.",`<rect x="35" y="80" width="300" height="250" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><path d="M75 205H295" stroke="#3d7fca" stroke-width="18"/><text x="185" y="125" text-anchor="middle" font-size="19" font-weight="700">LONGUEUR DROITE</text><text x="185" y="290" text-anchor="middle" font-size="17">RÉGULIÈRE</text><rect x="385" y="80" width="300" height="250" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><path d="M420 240H490V150H650" fill="none" stroke="#3d7fca" stroke-width="18"/><path d="M520 115L565 150L520 185M610 115L565 150L610 185" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/><text x="535" y="290" text-anchor="middle" font-size="17">SINGULIÈRES</text>`);
  const valveGraph=shell("line-valve","Effet d’une vanne sur la courbe réseau","Deux courbes réseau montantes sont affichées. La courbe vanne plus fermée est plus raide et croise la pompe à plus faible débit.",`<path d="M85 350V65M85 350H665" stroke="#1b3a63" stroke-width="4"/><path d="M90 335C250 320 350 250 650 90" fill="none" stroke="#3d7fca" stroke-width="6"/><path d="M90 350Q340 300 650 135" fill="none" stroke="#1e7e54" stroke-width="5" stroke-dasharray="10 7"/><path d="M90 350Q260 260 430 80" fill="none" stroke="#c9451a" stroke-width="6" stroke-dasharray="4 6"/><circle cx="447" cy="202" r="10" fill="#fffdf8" stroke="#1e7e54" stroke-width="5"/><circle cx="340" cy="176" r="10" fill="#fffdf8" stroke="#b06a00" stroke-width="5"/><text x="480" y="220" font-size="14" font-weight="700">ouverte : Q plus fort</text><text x="225" y="155" font-size="14" font-weight="700">fermée : Q plus faible</text><text x="375" y="400" text-anchor="middle" font-size="15">DÉBIT Q</text><text x="25" y="220" transform="rotate(-90 25 220)" text-anchor="middle" font-size="15">HAUTEUR H</text>`);
  const vaseScene=shell("line-vase","Vase à membrane","Une membrane sépare le gaz au-dessus et l’eau en dessous. L’eau dilatée déplace la membrane et comprime le gaz.",`<path d="M360 55C265 55 230 120 230 220S265 380 360 380S490 320 490 220S455 55 360 55Z" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/><path d="M240 210C290 175 430 175 480 210V218C430 255 290 255 240 218Z" fill="#fff4e0" stroke="#c9451a" stroke-width="5"/><path d="M240 215C290 250 430 250 480 215V350C430 395 290 395 240 350Z" fill="url(#cool-line-vase)"/><path d="M240 210V90C290 40 430 40 480 90V210C430 175 290 175 240 210Z" fill="url(#warm-line-vase)"/><text x="360" y="125" text-anchor="middle" font-size="20" font-weight="700">GAZ COMPRESSIBLE</text><text x="360" y="310" text-anchor="middle" font-size="20" font-weight="700">EAU DILATÉE</text><text x="585" y="215" text-anchor="middle" font-size="16">membrane</text><path d="M535 215H480" stroke="#c9451a" stroke-width="4" marker-end="url(#arr-line-vase)"/>`);
  const curveRead=shell("line-curve-read","Lecture d’une intersection pompe-réseau","Une courbe pompe descend et une courbe réseau monte. Leur intersection est repérée à Q égal 2 mètres cubes par heure et H égal 2 mètres de colonne d’eau.",`<path d="M90 350V65M90 350H660" stroke="#1b3a63" stroke-width="4"/>${Array.from({length:6},(_,i)=>`<path d="M90 ${350-i*50}H650" stroke="rgba(27,58,99,.13)"/><text x="75" y="${355-i*50}" text-anchor="end" font-size="12">${i}</text>`).join("")}${Array.from({length:6},(_,i)=>`<path d="M${90+i*100} 350V80" stroke="rgba(27,58,99,.13)"/><text x="${90+i*100}" y="372" text-anchor="middle" font-size="12">${i}</text>`).join("")}<path d="M90 90C250 110 430 180 590 320" fill="none" stroke="#3d7fca" stroke-width="6"/><path d="M90 350Q290 300 590 90" fill="none" stroke="#c9451a" stroke-width="6" stroke-dasharray="10 7"/><circle cx="290" cy="250" r="11" fill="#fffdf8" stroke="#1e7e54" stroke-width="6"/><path d="M290 250V350M90 250H290" stroke="#1e7e54" stroke-width="3" stroke-dasharray="5 5"/><text x="312" y="235" font-size="16" font-weight="700">intersection</text><text x="380" y="405" text-anchor="middle" font-size="15">Q (m³/h)</text><text x="24" y="220" transform="rotate(-90 24 220)" text-anchor="middle" font-size="15">H (mCE)</text>`);
  const calcScene=shell("line-calc","Calcul pédagogique de perte de charge","La carte affiche K égal 0,5 mCE par mètre cube par heure au carré, Q égal 2 mètres cubes par heure et la relation delta p égale K fois Q au carré.",`<rect x="95" y="65" width="530" height="280" rx="24" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="360" y="120" text-anchor="middle" font-size="24" font-weight="700">Δp = K × Q²</text><text x="360" y="175" text-anchor="middle" font-size="20">K = 0,5 mCE/(m³/h)²</text><text x="360" y="215" text-anchor="middle" font-size="20">Q = 2 m³/h</text><path d="M180 255H540" stroke="#3d7fca" stroke-width="18" marker-end="url(#arr-line-calc)"/><text x="360" y="315" text-anchor="middle" font-size="20" font-weight="700">Δp = ?</text>`);
  const speedScene=shell("line-speed","Réduction de vitesse du circulateur","Deux courbes pompe sont affichées sur la même courbe réseau. La courbe de vitesse réduite est plus basse et donne un point de fonctionnement à plus faible débit et hauteur.",`<path d="M90 350V65M90 350H660" stroke="#1b3a63" stroke-width="4"/><path d="M90 90C260 110 430 180 610 320" fill="none" stroke="#3d7fca" stroke-width="6"/><path d="M90 170C250 185 400 235 560 335" fill="none" stroke="#3d7fca" stroke-width="5" stroke-dasharray="9 7"/><path d="M90 350Q320 300 610 90" fill="none" stroke="#c9451a" stroke-width="6"/><circle cx="425" cy="205" r="10" fill="#fffdf8" stroke="#1e7e54" stroke-width="5"/><circle cx="350" cy="258" r="10" fill="#fffdf8" stroke="#b06a00" stroke-width="5"/><text x="490" y="145" font-size="15" font-weight="700">vitesse initiale</text><text x="355" y="295" font-size="15" font-weight="700">vitesse réduite</text>`);
  const foulScene=shell("line-foul","Échangeur encrassé, scène de transfert","Deux états d’un échangeur sont comparés. Dans l’état encrassé, des hachures obstruent des passages, les flèches de transfert sont moins nombreuses et la résistance est indiquée plus forte.",`<g transform="translate(35 70)"><rect width="300" height="285" rx="20" fill="#fffdf8" stroke="#1e7e54" stroke-width="5"/><text x="150" y="40" text-anchor="middle" font-size="18" font-weight="700">PASSAGES PROPRES</text>${Array.from({length:7},(_,i)=>`<path d="M${70+i*27} 75V225" stroke="${i%2?"#c9451a":"#3d7fca"}" stroke-width="8"/>`).join("")}<path d="M95 250h110" stroke="#1e7e54" stroke-width="6" marker-end="url(#arr-line-foul)"/><text x="150" y="275" text-anchor="middle" font-size="14">transfert relatif fort</text></g><g transform="translate(385 70)"><rect width="300" height="285" rx="20" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="150" y="40" text-anchor="middle" font-size="18" font-weight="700">PASSAGES ENCRASSÉS</text>${Array.from({length:7},(_,i)=>`<rect x="${65+i*27}" y="75" width="13" height="150" fill="url(#warm-line-foul)" stroke="#b06a00" stroke-width="2"/>`).join("")}<path d="M115 250h70" stroke="#b06a00" stroke-width="4" marker-end="url(#arr-line-foul)"/><text x="150" y="275" text-anchor="middle" font-size="14">transfert ↓ · résistance ↑</text></g>`);
  const dischargeScene=shell("line-discharge","Conduite sûre face à une soupape","Une soupape évacue par une conduite en tirets vers une zone interdite aux personnes. Les actions écrites sont s’éloigner, appliquer la procédure et signaler. Un bouchon est barré.",`<path d="M90 250H470" stroke="#1b3a63" stroke-width="14"/><path d="M330 250V150" stroke="#1b3a63" stroke-width="10"/><path d="M290 150L330 115L370 150Z" fill="#fffdf8" stroke="#c0392b" stroke-width="5"/><path d="M370 150H610V340" fill="none" stroke="#c0392b" stroke-width="10" stroke-dasharray="12 7" marker-end="url(#arr-line-discharge)"/><text x="330" y="82" text-anchor="middle" font-size="18" font-weight="700">SOUPAPE OUVERTE</text><rect x="75" y="300" width="390" height="70" rx="16" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="270" y="329" text-anchor="middle" font-size="16" font-weight="700">S’ÉLOIGNER · PROCÉDURE · SIGNALER</text><text x="270" y="352" text-anchor="middle" font-size="14">ne jamais neutraliser</text><circle cx="620" cy="95" r="42" fill="#fbe7e4" stroke="#c0392b" stroke-width="5" stroke-dasharray="8 5"/><path d="M594 69L646 121M646 69L594 121" stroke="#c0392b" stroke-width="8"/><text x="620" y="46" text-anchor="middle" font-size="14">BOUCHON INTERDIT</text>`);
  const diagScene=shell("line-diag","Mini-diagnostic expansion et sécurité","Un graphe montre une pression qui varie fortement entre froid et chaud. Un vase est repéré et une soupape évacue. La démarche proposée vérifie pressions, vase et conditions avant une décision.",`<path d="M75 320V70M75 320H480" stroke="#1b3a63" stroke-width="4"/><path d="M85 285C170 270 205 105 290 140S390 85 470 110" fill="none" stroke="#c9451a" stroke-width="7"/><text x="210" y="105" font-size="15" font-weight="700">variation forte</text><ellipse cx="580" cy="285" rx="70" ry="55" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="580" y="290" text-anchor="middle" font-size="17" font-weight="700">VASE</text><path d="M580 230V150" stroke="#1b3a63" stroke-width="10"/><path d="M545 150L580 115L615 150Z" fill="#fffdf8" stroke="#c0392b" stroke-width="5"/><path d="M615 150H680V260" stroke="#c0392b" stroke-width="8" stroke-dasharray="10 7" marker-end="url(#arr-line-diag)"/><text x="580" y="85" text-anchor="middle" font-size="15" font-weight="700">SOUPAPE ÉVACUE</text>`);

  function hacherTexte(texte){let hash=5381;for(let i=0;i<texte.length;i+=1)hash=((hash*33)^texte.charCodeAt(i))>>>0;hash^=hash>>>16;hash=Math.imul(hash,0x45d9f3b)>>>0;hash^=hash>>>16;hash=Math.imul(hash,0x45d9f3b)>>>0;hash^=hash>>>16;return hash>>>0;}
  function permutationDepuisIndex(n,graine){const factorielles=[1];for(let i=1;i<=n;i+=1)factorielles[i]=factorielles[i-1]*i;let reste=graine%factorielles[n];const disponibles=Array.from({length:n},(_,i)=>i);const permutation=[];for(let i=n;i>0;i-=1){const f=factorielles[i-1];const choix=Math.floor(reste/f);permutation.push(disponibles.splice(choix,1)[0]);reste%=f;}return permutation;}
  function melangerReponses(prompt,options,correct){const n=options.length;if(n<2)return{options,correct};const permutation=permutationDepuisIndex(n,hacherTexte(prompt||""));return{options:permutation.map(i=>options[i]),correct:permutation.indexOf(correct)};}

  const items=[
    {category:"1/12 · Lecture de schéma",station:"production",context:"Trois blocs techniques alimentent la même boucle d’eau.",question:"Quel point commun faut-il identifier d’abord ?",options:["La fonction de transfert d’énergie","La marque","Le combustible unique","Le circulateur intégré"],correct:0,explain:"La fonction se décrit avant la technologie ou l’énergie.",cap:"Montre la fonction commune sur le schéma.",tp:"Nommer la fonction et les raccordements.",bts:"Distinguer fonction, technologie, énergie et contraintes.",scene:prodScene,equivalent:"Chaudière, PAC et groupe d’eau glacée convergent vers une fonction de transfert d’énergie."},
    {category:"2/12 · Lecture de schéma",station:"echangeur",essential:true,context:"Le schéma recomposé montre P1, P2, S1 et S2.",question:"Quelle lecture respecte la séparation des circuits ?",options:["P1→P2 et S1→S2, sans mélange","P1→S1 dans une cuve","P2→S2 seulement","Les quatre piquages sont identiques"],correct:0,explain:"Chaque circuit possède son entrée et sa sortie; l’énergie traverse les plaques.",cap:"Suis les quatre tuyaux du schéma.",tp:"Suivre les quatre piquages.",bts:"Relier les quatre températures aux deux bilans.",scene:exScene,equivalent:"Le primaire va de P1 à P2; le secondaire de S1 à S2 en sens opposé."},
    {category:"3/12 · Lecture de schéma",station:"securite",essential:true,context:"Le réseau comporte manomètre, vase, soupape et évacuation.",question:"Quel organe limite une surpression par ouverture ?",options:["La soupape","Le manomètre","Le vase seul","Le circulateur"],correct:0,explain:"La soupape limite la pression; l’évacuation doit rester libre et sûre.",cap:"Montre la soupape sur le schéma.",tp:"Repérer la protection.",bts:"Justifier la fonction dans la chaîne de sécurité.",scene:safeChain,equivalent:"La chaîne associe mesure de pression, vase d’expansion, soupape et évacuation."},
    {category:"4/12 · Classer",station:"pertes",context:"Le schéma compare une longueur droite à des changements locaux.",question:"Quel classement est correct ?",options:["Tube : régulière; coude/vanne/filtre : singulières","Tout est régulier","Tout est singulier","Aucune résistance"],correct:0,explain:"Les deux familles s’additionnent sur le chemin hydraulique.",cap:"Montre le tube droit et les coudes.",tp:"Classer les éléments.",bts:"Préparer les données nécessaires au calcul du chemin critique.",scene:classifyScene,equivalent:"La conduite droite porte une perte régulière; les organes et coudes portent des pertes singulières."},
    {category:"5/12 · Appliquer",station:"circulateur",essential:true,context:"La vanne se ferme et la courbe réseau devient plus raide.",question:"Comment se déplace le point de fonctionnement ?",options:["Vers un débit plus faible","Vers un débit garanti plus fort","Il ne bouge jamais","La courbe pompe disparaît"],correct:0,explain:"L’intersection pompe-réseau se déplace quand la résistance change.",cap:"Compare le débit avant et après.",tp:"Comparer avant/après.",bts:"Lire le déplacement simultané de Q et H.",scene:valveGraph,equivalent:"La courbe réseau vanne fermée croise la pompe à un débit plus faible."},
    {category:"6/12 · Appliquer",station:"vase",context:"L’eau se dilate et entre dans le vase à membrane.",question:"Quel effet normal est représenté ?",options:["La membrane se déplace et le gaz se comprime","Les circuits se mélangent","Le vase crée le débit","La soupape se bouche"],correct:0,explain:"Le gaz compressible accepte une partie de la variation de volume.",cap:"Nomme l’eau, la membrane et le gaz.",tp:"Nommer eau, membrane et gaz.",bts:"Relier l’effet au volume utile et à la plage de pression.",scene:vaseScene,equivalent:"La membrane sépare l’eau dilatée du gaz compressible."},
    {category:"7/12 · Mesurer et lire",station:"circulateur",essential:true,context:"Le graphique donne une intersection repérée.",question:"Quel couple Q-H lit-on ?",options:["2 m³/h et 2 mCE","5 m³/h et 5 mCE","2 bar et 2 °C","0 m³/h et 5 mCE"],correct:0,explain:"Les pointillés projettent l’intersection sur Q=2 et H=2.",cap:"Lis le débit et la hauteur sur le graphique.",tp:"Lire les unités.",bts:"Interpréter l’intersection comme point de fonctionnement du modèle.",scene:curveRead,equivalent:"Le point est projeté vers Q égal 2 m³/h et H égal 2 mCE."},
    {category:"8/12 · Calculer",station:"pertes",context:"Le modèle donne K=0,5 mCE/(m³/h)² et Q=2 m³/h.",question:"Combien vaut Δp = KQ² ?",options:["2,0 mCE","1,0 mCE","4,0 mCE","0,25 mCE"],correct:0,explain:"0,5 × 2² = 2,0 mCE. Cette donnée reste pédagogique.",cap:"Lis la valeur donnée sur la carte.",tp:"Poser le calcul avec l’unité.",bts:"Distinguer le résultat du modèle d’un calcul de projet complet.",scene:calcScene,equivalent:"La relation affichée est delta p égale K fois Q au carré, avec K 0,5 et Q 2."},
    {category:"9/12 · Cause et effet",station:"circulateur",essential:true,context:"La vitesse du circulateur diminue, le réseau ne change pas.",question:"Quelle tendance montre le graphique ?",options:["Débit et hauteur du point diminuent","Le réseau disparaît","Le débit augmente toujours","La soupape règle la vitesse"],correct:0,explain:"La courbe pompe s’abaisse et rencontre le même réseau plus bas.",cap:"Compare les deux courbes affichées.",tp:"Comparer deux états stabilisés.",bts:"Relier la tendance au déplacement de la courbe pompe.",scene:speedScene,equivalent:"La courbe pompe à vitesse réduite est plus basse et croise le réseau à débit et hauteur plus faibles."},
    {category:"10/12 · Cause et effet",station:"echangeur",essential:true,context:"Les passages d’un échangeur s’encrassent dans le modèle.",question:"Quelles tendances doivent être vérifiées ?",options:["Transfert en baisse et résistance en hausse","Mélange automatique","Débit toujours constant","Pression nulle"],correct:0,explain:"Ces tendances se confirment par températures, débits et pression différentielle.",cap:"Montre les passages propres et les passages sales.",tp:"Observer sans conclure trop vite.",bts:"Croiser bilan thermique et hydraulique.",scene:foulScene,equivalent:"L’état encrassé montre moins de transfert relatif et davantage de résistance."},
    {category:"11/12 · Décider en sécurité",station:"securite",essential:true,context:"La soupape évacue à proximité d’un passage.",question:"Quelle conduite initiale est sûre ?",options:["Éloigner, appliquer la procédure et signaler","Boucher l’évacuation","Tenir la soupape fermée","Modifier son tarage"],correct:0,explain:"La priorité est l’exposition des personnes et l’état sûr prévu, sans neutralisation.",cap:"Ne touchez pas la soupape ; signalez et éloignez-vous.",tp:"Protéger et rendre compte.",bts:"Maintenir la chaîne de protection puis analyser la cause.",scene:dischargeScene,equivalent:"La soupape évacue; la zone est évitée et le bouchon est explicitement interdit."},
    {category:"12/12 · Mini-diagnostic",station:"vase",context:"La pression varie fortement entre froid et chaud et la soupape évacue.",question:"Quelle hypothèse faut-il vérifier avant de remplacer ?",options:["Vase, précharge, volume et remplissage","La couleur du tube","La marque du générateur seule","Le manomètre à retirer"],correct:0,explain:"Le symptôme demande des mesures et une vérification de l’expansion; la soupape reste active.",cap:"Signale une pression anormale au formateur.",tp:"Organiser les contrôles sûrs.",bts:"Comparer plage de pression, dimensionnement et conditions de fonctionnement.",scene:diagScene,equivalent:"Une forte variation de pression est reliée au vase et à la soupape; la démarche vérifie avant décision."}
  ].map(item=>item.options?{...item,...melangerReponses(item.question,item.options,item.correct)}:item);

  const els=Object.fromEntries(["routeScreen","testScreen","resultScreen","lineTrack","levelObjective","startTest","testProgress","testCategory","testTitle","testContext","levelDemand","answers","testScene","testEquivalent","testNavigation","quitTest","itemCount","nextItem","resultTitle","resultScore","resultExplain","remediation","retryTest","backRoute"].map(id=>[id,document.getElementById(id)]));
  let level="TP",index=0,score=0,answered=false,missed=[],essentialHits={echangeur:0,circulateur:0,securite:0};
  const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);

  function renderRoute(){
    els.lineTrack.innerHTML=stations.map((station,i)=>`<a class="station-link ${station.interchange?"interchange":""}" href="../../stations/${station.id}/index.html?line=E"><span class="station-number">${i+1}</span><h2>${station.title}</h2><p>${station.hint}</p><span></span><span class="status">${station.status}</span></a>`).join("");
    els.levelObjective.textContent=({CAP:"Reconnaître les organes, suivre l’eau et contrôler avec une fiche d’aide.",TP:"Identifier, contrôler et régler les organes par des observations et des mesures sûres.",BTS:"Analyser les interactions, lire les courbes et justifier les hypothèses avec les limites du modèle."})[level];
  }
  function show(name){
    els.routeScreen.hidden=name!=="route";els.testScreen.hidden=name!=="test";els.resultScreen.hidden=name!=="result";els.testNavigation.hidden=name!=="test";
  }
  function renderProgress(){els.testProgress.innerHTML=items.map((_,i)=>`<span class="test-dot ${i===index?"current":""} ${i<index?"done":""}">${i+1}</span>`).join("");}
  function renderItem(){
    const item=items[index];answered=false;renderProgress();els.testCategory.textContent=item.category;els.testTitle.textContent=item.question;els.testContext.textContent=item.context;els.levelDemand.innerHTML=`<strong>${level==="CAP"?"CAP":level==="TP"?"Bac pro":"BTS"} :</strong> ${escapeHtml(item[level.toLowerCase()]||item.tp)}`;els.testScene.innerHTML=item.scene;els.testEquivalent.textContent=item.equivalent;els.answers.innerHTML="";
    item.options.forEach((option,i)=>{const button=document.createElement("button");button.type="button";button.className="answer";button.textContent=option;button.addEventListener("click",()=>answer(i));els.answers.append(button);});
    els.nextItem.disabled=true;els.nextItem.textContent=index===items.length-1?"Voir le bilan":"Activité suivante";els.itemCount.textContent=`${index+1} / ${items.length}`;requestAnimationFrame(()=>els.testTitle.focus({preventScroll:true}));
  }
  function answer(choice){
    if(answered)return;answered=true;const item=items[index],correct=choice===item.correct;if(correct){score+=1;if(item.essential)essentialHits[item.station]+=1;}else missed.push(item.station);
    [...els.answers.children].forEach((button,i)=>{button.disabled=true;if(i===item.correct)button.classList.add("correct");});els.answers.children[choice].classList.add(correct?"correct":"wrong");
    const feedback=document.createElement("p");feedback.className=`feedback ${correct?"correct":"wrong"}`;feedback.textContent=`${correct?"✓ Correct. ":"✗ À revoir. "}${item.explain}`;els.answers.append(feedback);els.nextItem.disabled=false;
  }
  function start(){index=0;score=0;answered=false;missed=[];essentialHits={echangeur:0,circulateur:0,securite:0};show("test");renderItem();}
  function result(){
    show("result");const essentialsOk=Object.values(essentialHits).every(value=>value>0);let label,cls,explain;if(score>=9&&essentialsOk){label="ACQUIS";cls="acquired";explain="Au moins 70 % et chaque famille essentielle a été mobilisée.";}else if(score>=6){label="FRAGILE";cls="fragile";explain=score>=9&&!essentialsOk?"Le score atteint 70 %, mais une famille essentielle n’a aucune réponse juste.":"Entre 50 % et 69 %, ou une famille essentielle reste absente.";}else{label="À RENFORCER";cls="reinforce";explain="Moins de 50 % : reprendre les stations liées aux erreurs.";}
    const card=els.resultScreen.querySelector(".result-card");const grade=Math.round((score/items.length)*200)/10;card.className=`result-card ${cls}`;els.resultTitle.textContent=label;els.resultScore.textContent=`Note : ${grade.toLocaleString("fr-FR")} / 20`;els.resultExplain.textContent=`Score brut : ${score} / ${items.length}. ${explain} Note d’entraînement, jamais la validation d’un diplôme.`;
    const unique=[...new Set(missed)];els.remediation.innerHTML=unique.length?`<strong>Stations à revoir :</strong> ${unique.map(id=>{const s=stations.find(st=>st.id===id);return`<a href="../../stations/${id}/index.html?line=E">${s?.title||id}</a>`;}).join("")}`:"<strong>Aucune erreur :</strong> poursuivre vers une mission multi-lignes après validation humaine.";requestAnimationFrame(()=>els.resultTitle.focus({preventScroll:true}));
  }
  document.querySelectorAll(".level-btn").forEach(button=>button.addEventListener("click",()=>{level=button.dataset.level;document.querySelectorAll(".level-btn").forEach(item=>{const active=item===button;item.classList.toggle("is-active",active);item.setAttribute("aria-pressed",String(active));});renderRoute();if(!els.testScreen.hidden)renderItem();}));
  els.startTest.addEventListener("click",start);els.nextItem.addEventListener("click",()=>{if(!answered)return;if(index<items.length-1){index+=1;renderItem();}else result();});els.quitTest.addEventListener("click",()=>{show("route");});els.retryTest.addEventListener("click",start);els.backRoute.addEventListener("click",()=>show("route"));
  document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!els.routeScreen.hidden===false){show("route");}if(["INPUT","SELECT","BUTTON","A"].includes(event.target.tagName))return;if(event.key==="ArrowRight"&&!els.nextItem.disabled&&!els.testScreen.hidden)els.nextItem.click();});
  renderRoute();show("route");if(new URLSearchParams(window.location.search).get("evaluation")==="1")start();
})();
