const $=s=>document.querySelector(s);
const rates=[.75,.85,.95,1.05,1.15,1.25]; let rateIndex=2,current=0,voiceOn=true,speaking=false,voice=null,quizIndex=0,score=0,answered=false;
try{const r=Number(localStorage.getItem('bottle-rate'));const i=rates.indexOf(r);if(i>=0)rateIndex=i}catch{}
function bestVoice(){const vs=speechSynthesis.getVoices();return vs.find(v=>v.lang.toLowerCase()==='fr-fr'&&/natural|online|neural|google/i.test(v.name))||vs.find(v=>v.lang.toLowerCase()==='fr-fr')||vs.find(v=>v.lang.toLowerCase().startsWith('fr'))||vs[0]||null}
if('speechSynthesis'in window){voice=bestVoice();speechSynthesis.onvoiceschanged=()=>voice=bestVoice()}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();speaking=false;$('#listen').innerHTML='▶ <b>Écouter</b>'}
function speak(text){if(!voiceOn||!('speechSynthesis'in window))return;stopSpeech();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=rates[rateIndex];if(voice)u.voice=voice;u.onstart=()=>{speaking=true;$('#listen').innerHTML='■ <b>Arrêter</b>'};u.onend=u.onerror=()=>{speaking=false;$('#listen').innerHTML='▶ <b>Écouter</b>'};speechSynthesis.speak(u)}
function cylinderSvg({label='R-404A',kind='RÉCUP',level=62,redTop=false,dual=true,id=''}){return `<svg class="tech-svg" viewBox="0 0 260 340" role="img" aria-label="Bouteille ${kind} ${label}">
<defs><linearGradient id="m${id}" x1="0" x2="1"><stop offset="0" stop-color="#bfc7d0"/><stop offset=".5" stop-color="#f5f7f9"/><stop offset="1" stop-color="#aeb7c2"/></linearGradient><clipPath id="clip${id}"><rect x="67" y="92" width="126" height="196" rx="34"/></clipPath></defs>
<rect x="67" y="92" width="126" height="196" rx="34" fill="url(#m${id})" stroke="#788492" stroke-width="4"/>
<g clip-path="url(#clip${id})"><rect x="69" y="${286-level*1.92}" width="122" height="${level*1.92}" class="svg-liquid"/><rect x="69" y="94" width="122" height="${192-level*1.92}" class="svg-vapor"/></g>
<path d="M96 92 Q130 65 164 92" fill="${redTop?'#d94747':'url(#m'+id+')'}" stroke="#788492" stroke-width="4"/>
<rect x="113" y="54" width="34" height="28" rx="5" class="svg-metal"/><rect x="105" y="38" width="16" height="20" rx="4" fill="#3d7fca" stroke="#617080" stroke-width="2"/><rect x="139" y="38" width="16" height="20" rx="4" fill="${dual?'#d94747':'#8f98a4'}" stroke="#617080" stroke-width="2"/>
<path d="M105 42 h-18 M155 42 h18" stroke="#5f6976" stroke-width="5" stroke-linecap="round"/>
<rect x="82" y="195" width="96" height="55" rx="8" fill="#fffdf8" stroke="#c7ced6"/><text x="130" y="214" text-anchor="middle" class="svg-small">${kind}</text><text x="130" y="235" text-anchor="middle" class="svg-label">${label}</text>
<text x="130" y="311" text-anchor="middle" class="svg-small">Liquide ${level}% · Vapeur ${100-level}%</text></svg>`}
function valveSvg(){return `<svg class="tech-svg bottle-cutaway" viewBox="0 0 700 420" role="img" aria-label="Bouteille en coupe avec robinet vapeur et robinet liquide à tube plongeur">
<defs>
  <linearGradient id="bottleMetal" x1="0" x2="1"><stop offset="0" stop-color="#bfc7d0"/><stop offset=".48" stop-color="#f7f9fb"/><stop offset="1" stop-color="#adb7c2"/></linearGradient>
  <clipPath id="bottleClip"><rect x="215" y="88" width="270" height="280" rx="60"/></clipPath>
  <marker id="arrowBlue" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#3d7fca"/></marker>
  <marker id="arrowRed" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#d94747"/></marker>
</defs>
<rect x="215" y="88" width="270" height="280" rx="60" fill="url(#bottleMetal)" stroke="#788492" stroke-width="5"/>
<g clip-path="url(#bottleClip)">
  <rect x="219" y="215" width="262" height="149" class="svg-liquid"/>
  <rect x="219" y="92" width="262" height="123" class="svg-vapor"/>
  <path d="M219 215 H481" stroke="#2d76bc" stroke-width="4" opacity=".8"/>
</g>
<text x="350" y="150" text-anchor="middle" class="phase-title vapor-title">ZONE VAPEUR</text>
<text x="350" y="295" text-anchor="middle" class="phase-title liquid-title">FLUIDE LIQUIDE</text>

<!-- col + deux robinets -->
<path d="M282 90 Q350 48 418 90" fill="url(#bottleMetal)" stroke="#788492" stroke-width="5"/>
<rect x="310" y="48" width="80" height="45" rx="10" class="svg-metal"/>

<!-- robinet vapeur bleu -->
<g class="valve-blue">
  <rect x="265" y="25" width="38" height="32" rx="7" fill="#3d7fca" stroke="#617080" stroke-width="3"/>
  <circle cx="284" cy="22" r="27" fill="#3d7fca" stroke="#617080" stroke-width="4"/>
  <path d="M284 -2 V46 M260 22 H308" stroke="#fff" stroke-width="6" stroke-linecap="round"/>
  <path d="M284 55 V125" class="flow-path vapor-inside"/>
  <path d="M265 41 H125" class="flow-path vapor-out" marker-end="url(#arrowBlue)"/>
  <text x="120" y="16" class="svg-label blue-label">ROBINET VAPEUR</text>
  <text x="120" y="34" class="svg-small">Prélèvement dans la partie haute</text>
</g>

<!-- robinet liquide rouge + tube plongeur -->
<g class="valve-red">
  <rect x="397" y="25" width="38" height="32" rx="7" fill="#d94747" stroke="#617080" stroke-width="3"/>
  <circle cx="416" cy="22" r="27" fill="#d94747" stroke="#617080" stroke-width="4"/>
  <path d="M416 -2 V46 M392 22 H440" stroke="#fff" stroke-width="6" stroke-linecap="round"/>
  <path d="M416 55 V330" class="flow-path liquid-inside"/>
  <path d="M435 41 H575" class="flow-path liquid-out" marker-end="url(#arrowRed)"/>
  <text x="580" y="16" text-anchor="end" class="svg-label red-label">ROBINET LIQUIDE</text>
  <text x="580" y="34" text-anchor="end" class="svg-small">Relié au tube plongeur</text>
</g>

<path d="M416 330 V342" stroke="#d94747" stroke-width="12" stroke-linecap="round"/>
<path d="M432 316 H530" stroke="#637285" stroke-width="2" stroke-dasharray="5 4"/>
<text x="540" y="320" class="svg-small">TUBE PLONGEUR</text>

<!-- repères de circulation -->
<circle class="flow-dot vapor-dot" cx="284" cy="118" r="7" fill="#3d7fca"/>
<circle class="flow-dot liquid-dot" cx="416" cy="322" r="8" fill="#d94747"/>

<text x="350" y="402" text-anchor="middle" class="svg-small">La couleur aide à lire le schéma ; l’identification réelle de la bouteille reste prioritaire.</text>
</svg>`}
function pressureSvg(level,temp,bad=false){const vapor=Math.max(2,100-level); const needle=bad?72:Math.min(60,20+(temp-20)*.7+(level-70)*.45); return `<svg class="tech-svg pressure-svg ${bad?'bad-svg':''}" viewBox="0 0 360 340"><defs><clipPath id="c${bad?'b':'g'}"><rect x="100" y="85" width="160" height="205" rx="42"/></clipPath></defs><rect x="100" y="85" width="160" height="205" rx="42" class="svg-metal"/><g clip-path="url(#c${bad?'b':'g'}"><rect x="102" y="${288-level*2.0}" width="156" height="${level*2.0}" class="svg-liquid"/><rect x="102" y="87" width="156" height="${vapor*2.0}" class="svg-vapor"/></g><rect x="155" y="53" width="50" height="35" rx="6" class="svg-metal"/><circle cx="180" cy="42" r="35" fill="#fff" stroke="#7b8794" stroke-width="4"/><path d="M180 42 L${180+Math.cos((needle-90)*Math.PI/180)*26} ${42+Math.sin((needle-90)*Math.PI/180)*26}" stroke="#d94747" stroke-width="4" stroke-linecap="round"/><circle cx="180" cy="42" r="4" fill="#10233c"/><text x="180" y="318" text-anchor="middle" class="svg-label">${level}% rempli · ${temp} °C</text><text x="180" y="18" text-anchor="middle" class="svg-small">PRESSION</text>${bad?'<text x="180" y="170" text-anchor="middle" class="danger-word">DANGER</text>':''}</svg>`}
const lessons=[
{short:'Contenants',k:'Étape 1 · Voir la différence',t:'Trois bouteilles. Trois usages. Un mauvais choix = un problème.',x:'Regardez d’abord les contenants : l’usage doit être évident avant même de brancher un flexible.',s:"Commencez par regarder. Une bouteille de fluide neuf ou de transfert contient un fluide identifié et propre. Une bouteille de récupération reçoit le fluide que l'on retire d'une installation ; il peut contenir de l'huile, de l'humidité ou d'autres contaminants. Une bouteille dédiée aux fluides inflammables doit être compatible et clairement identifiée. Le premier réflexe professionnel est donc simple : je choisis le bon contenant avant de brancher.",r:()=>`<div class="visual-stage"><div class="big-message">Je <strong>regarde</strong> avant de brancher.</div><div class="bottle-row"><article class="bottle-card">${cylinderSvg({label:'R-404A',kind:'TRANSFERT',level:68,id:'1'})}<div class="bottle-caption">Transfert</div><div class="bottle-sub">Fluide identifié · circuit maîtrisé</div></article><article class="bottle-card">${cylinderSvg({label:'R-404A',kind:'RÉCUP.',level:48,id:'2'})}<div class="bottle-caption">Récupération</div><div class="bottle-sub">Fluide extrait · peut être contaminé</div></article><article class="bottle-card">${cylinderSvg({label:'R-32',kind:'A2L',level:55,redTop:true,id:'3'})}<div class="bottle-caption">Inflammable / A2L</div><div class="bottle-sub">Contenant et raccordement adaptés</div></article></div><div class="feedback">Cliquez sur la bouteille à utiliser pour vider une installation avant réparation.</div><div class="bottle-row"><span></span><button class="nav" data-pick="recovery">Choisir la bouteille de récupération</button><span></span></div></div>`},
{short:'Vannes',k:'Étape 2 · Comprendre le prélèvement',t:'Deux robinets, deux chemins : vapeur en haut, liquide au fond.',x:'Regardez la coupe de la bouteille : le chemin du fluide suffit à comprendre.',s:"Regardez la bouteille en coupe. La vapeur occupe la partie haute, au-dessus du liquide. Le robinet vapeur prélève directement dans cette zone. Le robinet liquide, lui, est relié à un tube plongeur qui descend jusqu'au fond : le liquide remonte dans ce tube avant de sortir. Il ne s'agit pas d'une vanne basse pression et d'une vanne haute pression : dans une bouteille au repos, les deux phases sont à la pression d'équilibre du fluide. Ici, les couleurs servent seulement de repère visuel. Sur le terrain, on vérifie toujours la conception, les marquages et la notice du récipient.",r:()=>`<div class="visual-stage flow-stage"><div class="big-message">Je veux de la vapeur ? <strong>Je prélève en haut.</strong><br>Je veux du liquide ? <strong>Je vais le chercher au fond.</strong></div><div>${valveSvg()}</div><div class="flow-actions"><button class="nav vapor-btn" data-flow="vapor">🔵 Prélever de la vapeur</button><button class="nav liquid-btn" data-flow="liquid">🔴 Prélever du liquide</button></div><div class="feedback" id="flow-feedback">Cliquez sur un robinet pour voir le fluide circuler.</div></div>`},
{short:'Plaque',k:'Étape 3 · La bouteille donne ses limites',t:'TW, WC, PS : trois informations, trois significations.',x:'On n’apprend pas des sigles abstraits : on les relie directement à la bouteille.',s:"Sur la bouteille, la tare T W correspond à la masse du récipient vide. W C indique la capacité en eau, donc un volume interne de référence. P S correspond à une pression de service indiquée pour le récipient. Ces données ne veulent pas toutes dire la même chose. L'objectif est de savoir où les lire et surtout ce qu'elles permettent de décider.",r:()=>`<div class="visual-stage"><svg class="tech-svg" viewBox="0 0 800 330"><g transform="translate(80 0)">${cylinderSvg({label:'R-449A',kind:'RÉCUP.',level:58,id:'p'}).replace('<svg class="tech-svg" viewBox="0 0 260 340" role="img" aria-label="Bouteille RÉCUP. R-449A">','<g>').replace('</svg>','</g>')}</g><path d="M300 145 H430" stroke="#ff6b35" stroke-width="4" marker-end="url(#a)"/><rect x="445" y="75" width="280" height="180" rx="18" fill="#fff" stroke="#cdd5de"/><text x="470" y="112" class="svg-label">TW 6,2 kg</text><text x="470" y="137" class="svg-small">Tare = masse de la bouteille vide</text><text x="470" y="177" class="svg-label">WC 12 L</text><text x="470" y="202" class="svg-small">Capacité en eau = volume interne de référence</text><text x="470" y="242" class="svg-label">PS 45 bar</text><text x="470" y="267" class="svg-small">Pression de service indiquée</text><defs><marker id="a" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#ff6b35"/></marker></defs></svg><div class="big-message">Je <strong>lis</strong> avant de calculer.</div></div>`},
{short:'Pesée',k:'Étape 4 · Brut, tare, fluide',t:'La balance donne le brut. Vous devez trouver le fluide.',x:'Une bouteille sur une balance devient un calcul très simple : brut − tare.',s:"La balance affiche la masse brute : bouteille plus fluide. La bouteille vide a une tare. Donc la masse de fluide est égale à la masse brute moins la tare. Ici, treize virgule quatre moins six virgule deux donne sept virgule deux kilogrammes de fluide. Je veux que ce calcul devienne automatique.",r:()=>`<div class="scale-lab"><div class="scale"><div class="scale-platform">${cylinderSvg({label:'R-404A',kind:'RÉCUP.',level:52,id:'w'}).replace('class="tech-svg"','style="height:170px;width:130px"')}</div><div class="display">13,4 kg</div><small>Masse brute</small></div><div class="calc"><div class="formula">13,4 kg − 6,2 kg = ?</div><label>Tare lue sur la bouteille : <b>6,2 kg</b></label><input id="mass-answer" type="number" step="0.1" placeholder="Masse de fluide"><button class="nav" id="check-mass">Vérifier</button><div class="feedback" id="mass-feedback"></div></div></div>`},
{short:'Phases',k:'Étape 5 · Liquide ou vapeur',t:'Le fluide sort de l’endroit où votre tuyau va le chercher.',x:'Visualisez la phase, le niveau et le tube plongeur avant de parler de “liquide” ou de “gaz”.',s:"Dans la bouteille, la vapeur est au-dessus du liquide. Un prélèvement en partie haute donne de la vapeur. Un tube plongeur descend jusqu'au liquide et permet de prélever la phase liquide bouteille debout. Sur certains récipients à un seul robinet, la procédure peut prévoir de retourner la bouteille pour obtenir du liquide, mais jamais par habitude : on respecte la conception et la procédure fabricant.",r:()=>`<div class="compare-pressure"><article class="pressure-card"><h3>Prélèvement vapeur</h3><svg class="tech-svg" viewBox="0 0 360 300"><rect x="90" y="55" width="180" height="210" rx="42" class="svg-metal"/><rect x="94" y="150" width="172" height="111" class="svg-liquid"/><rect x="94" y="59" width="172" height="91" class="svg-vapor"/><path d="M180 55V95H300" class="svg-pipe"/><circle cx="300" cy="95" r="8" class="svg-blue pulse-arrow"/><text x="180" y="288" text-anchor="middle" class="svg-label">On prélève en haut → vapeur</text></svg></article><article class="pressure-card"><h3>Prélèvement liquide</h3><svg class="tech-svg" viewBox="0 0 360 300"><rect x="90" y="55" width="180" height="210" rx="42" class="svg-metal"/><rect x="94" y="150" width="172" height="111" class="svg-liquid"/><rect x="94" y="59" width="172" height="91" class="svg-vapor"/><path d="M180 55V230H300" class="svg-pipe"/><circle cx="300" cy="230" r="8" class="svg-red pulse-arrow"/><text x="180" y="288" text-anchor="middle" class="svg-label">Tube plongeur → liquide</text></svg></article></div>`},
{short:'Surremplir',k:'Étape 6 · Voir la différence',t:'Même chaleur. Deux bouteilles. Une marge… ou presque plus aucune.',x:'Le volume vapeur n’empêche pas toute montée en pression : il fournit une marge de dilatation. Le surremplissage supprime cette marge.',s:"Regardez les deux bouteilles. À gauche, il reste un volume vapeur significatif. Quand le liquide se dilate avec la chaleur, ce volume se réduit et la pression augmente, mais la bouteille dispose encore de la marge prévue par le remplissage correct. À droite, la bouteille est presque pleine de liquide. Or un liquide est pratiquement incompressible. Dès qu'il se dilate, il n'a presque plus de volume disponible. La pression peut alors monter extrêmement vite. C'est cela qu'il faut comprendre : le danger vient de la disparition du volume libre.",r:()=>`<div class="visual-stage"><div class="compare-pressure"><article class="pressure-card good"><h3>Remplissage maîtrisé</h3><div id="good-pressure">${pressureSvg(75,20,false)}</div><div class="caption">Volume vapeur présent = marge disponible</div></article><article class="pressure-card bad"><h3>Surremplissage</h3><div id="bad-pressure">${pressureSvg(98,20,true)}</div><div class="caption">Presque plus de volume libre</div></article></div><div class="process-strip"><div><b>1</b>Température ↑</div><div><b>2</b>Liquide se dilate</div><div><b>3</b>Liquide ≈ incompressible</div><div><b>4</b>Pression ↑↑</div></div><div style="text-align:center"><button class="nav" id="heat-compare">☀ Chauffer les deux bouteilles</button></div><div class="feedback" id="heat-feedback">Observez les deux manomètres.</div></div>`},
{short:'Boum',k:'Étape 7 · Le mauvais scénario',t:'Si vous laissez le danger s’installer, la protection mécanique devient le dernier rempart.',x:'La soupape ou le disque de rupture ne transforme jamais un surremplissage en bonne pratique.',s:"On va volontairement aller trop loin pour mémoriser le risque. Une bouteille trop remplie chauffe. Le liquide se dilate. Comme il est pratiquement incompressible et qu'il n'y a plus de volume libre, la pression s'emballe. Certains récipients possèdent une soupape ou un dispositif de rupture qui peut évacuer la surpression. Mais cette protection est un dernier recours. Se fier à elle, c'est accepter d'avoir déjà créé une situation dangereuse. La bonne sécurité, c'est d'empêcher le surremplissage.",r:()=>`<div class="visual-stage"><div class="big-message">Trop plein + chaleur + liquide incompressible = <strong>surpression</strong></div><div id="boom-scene"><svg class="tech-svg" viewBox="0 0 760 320"><g class="bottle-main" transform="translate(170 0)">${pressureSvg(99,52,true).replace('<svg class="tech-svg pressure-svg bad-svg" viewBox="0 0 360 340">','<g>').replace('</svg>','</g>')}</g><circle class="flash" cx="350" cy="160" r="70" fill="#ffb347" opacity="0"/><rect class="boom-fragment" style="--x:-150px;--y:-80px;--r:-80deg" x="325" y="125" width="40" height="70" rx="10" fill="#aab3bd"/><rect class="boom-fragment" style="--x:160px;--y:-60px;--r:120deg" x="345" y="120" width="35" height="65" rx="10" fill="#c7cdd4"/><rect class="boom-fragment" style="--x:-120px;--y:100px;--r:60deg" x="320" y="165" width="40" height="60" rx="10" fill="#8f99a4"/><rect class="boom-fragment" style="--x:150px;--y:95px;--r:-120deg" x="350" y="165" width="40" height="60" rx="10" fill="#b9c1ca"/><text x="565" y="125" class="svg-label">Protection de dernier recours :</text><text x="565" y="155" class="svg-small">soupape / disque de rupture</text><text x="565" y="205" class="svg-label">Ne jamais compter dessus.</text></svg></div><div style="text-align:center"><button class="nav" id="boom">Faire monter la température</button></div><div class="feedback" id="boom-msg">Simulation volontairement spectaculaire pour mémoriser le risque.</div></div>`},
{short:'Défi',k:'Étape 8 · Validation',t:'Maintenant, vous décidez comme un frigoriste.',x:'Des images, des calculs et des décisions : le but est de vérifier les réflexes.',s:"Dernière étape. Vous allez vérifier les réflexes acquis : choisir le bon contenant, comprendre les vannes, lire la tare, calculer la masse de fluide et expliquer le danger du surremplissage. Une erreur corrigée ici vaut mieux qu'une erreur en atelier.",r:()=>quizMarkup()}
];
const questions=[
{q:"Pour vider une installation avant réparation, quel contenant choisissez-vous ?",a:["Une bouteille quelconque","Une bouteille de récupération adaptée et identifiée","Une bouteille de transfert propre"],c:1,w:"Le fluide extrait peut être contaminé : il va dans un contenant de récupération compatible et identifié."},
{q:"La vanne reliée à un tube plongeur permet normalement de prélever…",a:["la phase liquide","uniquement la vapeur","de l'air"],c:0,w:"Le tube descend dans le liquide : il prélève donc la phase liquide bouteille debout."},
{q:"La balance affiche 13,4 kg et la tare est 6,2 kg. Masse de fluide ?",a:["7,2 kg","19,6 kg","6,2 kg"],c:0,w:"13,4 − 6,2 = 7,2 kg."},
{q:"Pourquoi une bouteille surremplie devient-elle dangereuse quand elle chauffe ?",a:["Parce que le liquide se dilate et est pratiquement incompressible","Parce que la bouteille devient plus légère","Parce que la vapeur disparaît sans effet"],c:0,w:"Le liquide se dilate. Sans volume libre, la pression peut monter très rapidement."},
{q:"Le volume vapeur au-dessus du liquide sert surtout à…",a:["fournir une marge de dilatation","faire joli","augmenter la tare"],c:0,w:"Il fournit la marge de volume nécessaire lorsque le liquide se dilate."},
{q:"Une soupape autorise-t-elle à surremplir ?",a:["Oui","Non, c'est un dernier recours","Seulement l'hiver"],c:1,w:"La protection mécanique ne remplace jamais la prévention du surremplissage."}
];
function quizMarkup(){if(quizIndex>=questions.length)return `<div class="quiz-score"><p>Mission terminée</p><b>${score}/${questions.length}</b><p>${score===questions.length?'Parfait : les réflexes sont acquis.':score>=4?'Bien. Reprenez les points ratés.':'Reprenez le parcours visuel avant de recommencer.'}</p><button class="nav" id="quiz-restart">Refaire le défi</button></div>`;const q=questions[quizIndex];return `<div><p class="quiz-q">${quizIndex+1}. ${q.q}</p><div class="quiz-options">${q.a.map((a,i)=>`<button data-qanswer="${i}">${a}</button>`).join('')}</div><div class="feedback" id="quiz-feedback">Question ${quizIndex+1} sur ${questions.length}</div></div>`}
function buildStepper(){$('#stepper').innerHTML=lessons.map((l,i)=>`<button type="button" data-step="${i}"><b>${String(i+1).padStart(2,'0')}</b><span>${l.short}</span></button>`).join('');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>go(+b.dataset.step))}
function go(i){stopSpeech();current=Math.max(0,Math.min(lessons.length-1,i));const l=lessons[current];$('#kicker').textContent=l.k;$('#title').textContent=l.t;$('#text').textContent=l.x;$('#zone').innerHTML=l.r();$('#status').textContent=`${current+1} / ${lessons.length}`;$('#prev').disabled=current===0;$('#next').textContent=current===lessons.length-1?'Terminer':'Continuer →';document.querySelectorAll('#stepper button').forEach((b,j)=>b.classList.toggle('active',j===current));wire()}
function wire(){document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>{const stage=document.querySelector('.flow-stage');if(!stage)return;stage.classList.remove('flow-vapor-active','flow-liquid-active');const mode=b.dataset.flow;void stage.offsetWidth;stage.classList.add(mode==='vapor'?'flow-vapor-active':'flow-liquid-active');const fb=$('#flow-feedback');if(mode==='vapor'){fb.innerHTML='🔵 <strong>Vapeur :</strong> le prélèvement se fait dans la partie haute de la bouteille.'}else{fb.innerHTML='🔴 <strong>Liquide :</strong> le tube plongeur descend dans le liquide ; celui-ci remonte jusqu’au robinet.'}});if(document.querySelector('[data-pick]'))document.querySelector('[data-pick]').onclick=()=>{document.querySelector('[data-pick]').textContent='✓ Bon choix : bouteille de récupération';document.querySelector('[data-pick]').style.background='#4fb887'};if($('#check-mass'))$('#check-mass').onclick=()=>{const v=Number($('#mass-answer').value);$('#mass-feedback').textContent=Math.abs(v-7.2)<.05?'✓ Exact : 7,2 kg de fluide.':'✗ Reprenez : masse brute − tare.'};if($('#heat-compare'))$('#heat-compare').onclick=()=>{let t=20;const id=setInterval(()=>{t+=4;$('#good-pressure').innerHTML=pressureSvg(75,t,false);$('#bad-pressure').innerHTML=pressureSvg(98,t,true);$('#heat-feedback').textContent=t<48?`Température ${t} °C : la pression augmente dans les deux bouteilles, mais la bouteille surremplie perd toute marge.`:'À droite, presque plus de volume libre : la pression devient critique.';if(t>=52)clearInterval(id)},250)};if($('#boom'))$('#boom').onclick=()=>{const scene=$('#boom-scene');$('#boom-msg').textContent='Température ↑ → dilatation → volume libre ≈ 0 → pression ↑↑↑';setTimeout(()=>{scene.classList.add('explode');$('#boom-msg').textContent='BOUM — le surremplissage devait être évité avant d’en arriver là.'},900)};document.querySelectorAll('[data-qanswer]').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const q=questions[quizIndex],i=+b.dataset.qanswer;b.classList.add(i===q.c?'good':'bad');if(i===q.c)score++;document.querySelectorAll('[data-qanswer]')[q.c].classList.add('good');$('#quiz-feedback').innerHTML=(i===q.c?'✓ ':'✗ ')+q.w+` <button class="nav" id="quiz-next">${quizIndex===questions.length-1?'Résultat':'Question suivante'}</button>`;$('#quiz-next').onclick=()=>{quizIndex++;answered=false;$('#zone').innerHTML=quizMarkup();wire()}});if($('#quiz-restart'))$('#quiz-restart').onclick=()=>{quizIndex=0;score=0;answered=false;$('#zone').innerHTML=quizMarkup();wire()}}
$('#listen').onclick=()=>speaking?stopSpeech():speak(lessons[current].s);$('#slower').onclick=()=>{rateIndex=Math.max(0,rateIndex-1);saveRate()};$('#faster').onclick=()=>{rateIndex=Math.min(rates.length-1,rateIndex+1);saveRate()};function saveRate(){$('#speed-value').textContent=rates[rateIndex].toFixed(2).replace('.',',')+'×';try{localStorage.setItem('bottle-rate',rates[rateIndex])}catch{};if(speaking)speak(lessons[current].s)}
$('#prev').onclick=()=>go(current-1);$('#next').onclick=()=>current===lessons.length-1?document.querySelector('.final-message').scrollIntoView({behavior:'smooth'}):go(current+1);$('#start').onclick=()=>{document.querySelector('#module').scrollIntoView({behavior:'smooth'});setTimeout(()=>speak(lessons[0].s),450)};$('#voice-toggle').onclick=()=>{voiceOn=!voiceOn;$('#voice-toggle').textContent=voiceOn?'🔊 Voix active':'🔇 Voix coupée';if(!voiceOn)stopSpeech()};$('#refs-toggle').onclick=()=>{$('#refs').hidden=!$('#refs').hidden;if(!$('#refs').hidden)$('#refs').scrollIntoView({behavior:'smooth'})};$('#restart').onclick=()=>{quizIndex=0;score=0;answered=false;go(0);scrollTo({top:0,behavior:'smooth'})};buildStepper();saveRate();go(0);
