/* La prononciation — ce que la voix doit dire, et non ce qui est écrit.

   FICHIER GÉNÉRÉ depuis build/voix/prononciation.json, qui fait foi.
   Ne pas éditer ici : corriger la table, puis régénérer.

   POURQUOI IL EXISTE. La même table vivait déjà côté Python, dans oraliser(), et ne
   servait qu'à FABRIQUER les MP3. Dès que le navigateur prenait le relais — narration
   sans MP3, AéroRézo, ÉlectroRézo — le texte brut partait à la synthèse : « HP » épelé,
   « → » lu « flèche », les emoji nommés. Le même mot était bien dit ici, mal dit là.

   CE QU'IL NE FAIT PAS. Il ne touche ni au texte affiché, ni au texte source. La clé
   d'un MP3 est le hash de son texte d'origine : oraliser dans les sources orphelinerait
   les 3 376 fichiers. On oralise à la lecture, jamais avant le calcul de la clé.

   UN PIÈGE, RENCONTRÉ ICI. « \U0001F600 » est de la syntaxe Python. En JavaScript ce
   motif compile SANS ERREUR et fabrique une classe qui avale les lettres : « Dans »
   devenait « ·ans », sur 291 phrases. Les plages s'écrivent donc \u{...}, drapeau u. */
(function () {
  "use strict";

  var REGLES = [
    ["\\s*→\\s*$", ""],
    ["^[\\s\\S]*\\{[^{}]*:[^{}]*\\}[\\s\\S]*$", ""],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])n°\\s*", "$1numéro "],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])T°", "$1température"],
    ["(^|[^0-9])0\\s*°(?!\\s*[CFK])", "$1 0 degré"],
    ["(\\d)\\s*°(?!\\s*[CFK])", "$1 degrés"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])kJ\\s*/\\s*kg(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1kilojoules par kilogramme"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])kWh\\s*/\\s*an(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1kilowattheures par an"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])kg\\s*/\\s*m³", "$1kilogrammes par mètre cube"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])m³\\s*/\\s*h(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1mètres cubes par heure"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])m³\\s*/\\s*s(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1mètres cubes par seconde"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])mm²\\s*/\\s*s(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1millimètres carrés par seconde"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])m\\s*/\\s*s(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1mètres par seconde"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])tr\\s*/\\s*min(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1tours par minute"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])min\\s*/\\s*h(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1minutes par heure"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])L\\s*/\\s*min(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1litres par minute"],
    ["(\\d)\\s*m\\s*×\\s*(\\d)\\s*m(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1 mètres sur $2 mètres"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])mm²", "$1millimètres carrés"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])cm³", "$1centimètres cubes"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])m²", "$1mètres carrés"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])m³", "$1mètres cubes"],
    ["(\\d)\\s+mm(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1 millimètres"],
    ["(\\d)\\s+m(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1 mètres"],
    ["(\\d)\\s+g(?![A-Za-z0-9_/À-ÖØ-öø-ÿ])", "$1 grammes"],
    ["(\\d)\\s+min(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1 minutes"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Wh(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1wattheures"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])ppm(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P P M"],
    ["(^|[^0-9,.])(\\d{3,4})\\s*/\\s*(\\d{3,4})(?![0-9])(?!,\\d)", "$1$2 barre $3"],
    ["(^|[^0-9,.])(\\d{1,2})\\.(\\d)(\\d)(?![0-9])", "$1$2 point $3 $4"],
    ["(\\d) (\\d{3}) (\\d{3})(?![0-9])", "$1$2$3"],
    ["(\\d) (\\d{3})(?![0-9])", "$1$2"],
    ["(^|[^0-9])1\\s*h\\s*(\\d{2})(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$11 heure $2"],
    ["(^|[^0-9])(\\d{1,2})\\s*h\\s*(\\d{2})(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1$2 heures $3"],
    ["(^|[^0-9])(\\d{1,2})\\s*h(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])(?!\\s*\\d)", "$1$2 heures"],
    ["(\\d)\\s*–\\s*(\\d+)(\\s*K)(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "de $1 à $2$3"],
    ["(\\d)–(\\d)", "$1 $2"],
    ["(^|[^0-9])–(?![0-9])", "$1-"],
    ["(\\d)\\s*K(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1 kelvins"],
    ["(\\d)\\s*k\\s*Ω", "$1 kilo-ohms"],
    ["XXᵉ", "vingtième"],
    ["⚠️?\\s*", "Attention. "],
    ["[\\u{1F000}-\\u{1FAFF}]", " "],
    ["([.!?:;,…])\\s*[▸▶]\\s*", "$1 "],
    ["\\s*[▸▶]\\s*", ". "],
    ["[←↑↓↕-⇿⏩-⏺■-◿☀-⚟⚡-➿⟰-⟿⬀-⯿️]", " "],
    ["\\s*—\\s*,?\\s*", ", "],
    ["([.!?:;,…])\\s·\\s", "$1 "],
    ["\\s·\\s", ". "],
    ["([^.])\\.\\s*\\.(?!\\.)", "$1. "],
    ["\\s*×\\s*", " multiplié par "],
    ["\\s*÷\\s*", " divisé par "],
    ["(\\d) / (\\d)", "$1 divisé par $2"],
    ["\\s*≈\\s*", " environ "],
    ["\\s*∝\\s*", " est proportionnel à "],
    ["\\s*=\\s*(?=[-−+]?\\d)", " égale "],
    ["\\s*=\\s*", ", c'est "],
    ["\\s*−\\s*", " moins "],
    ["(\\s)-(\\s)", "$1moins$2"],
    ["\\+\\s*(?=\\d)", " plus "],
    ["([A-Za-zÀ-ÖØ-öø-ÿ0-9])\\s\\+\\s(?=[A-Za-zÀ-ÖØ-öø-ÿ])", "$1 et "],
    ["\\s<\\s", " est inférieur à "],
    ["\\s>\\s", " est supérieur à "],
    ["([A-Za-zÀ-ÖØ-öø-ÿ])_(?=[A-Za-zÀ-ÖØ-öø-ÿ])", "$1 "],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])air\\s*/\\s*air(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1air-air"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])NF\\s*/\\s*NO(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1N F ou N O"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])SG\\s*/\\s*SGP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1S G, S G P"],
    ["([A-Za-zÀ-ÖØ-öø-ÿ])/(?=[A-Za-zÀ-ÖØ-öø-ÿ])", "$1 et "],
    ["rendement volumétrique\\s+ηv", "rendement volumétrique"],
    ["ηv", " le rendement volumétrique"],
    ["π", " pi "],
    ["Δ", "delta "],
    ["Σ", " sigma "],
    ["λ", " lambda "],
    ["θ", " thêta "],
    ["Φ", " phi "],
    ["Q̇", "Q point"],
    ["ṁ", "m point"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])CUT[\\s‑-]?OUT(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1keute aoute"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])CUT[\\s‑-]?IN(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1keute inne"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])(et|est)\\s+DIFF(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1$2 le différentiel"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])DIFF(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1diff"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])RESET(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1rissette"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])booster(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1bousteur"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Booster(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1Bousteur"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])scrolls?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1scrolle"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Scrolls?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1Scrolle"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])pump[\\s‑-]?down(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1peumpe daoune"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])flash[\\s‑-]?gas(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1flache gasse"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])gas[\\s‑-]?coolers?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1gasse couleur"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])by[\\s‑-]?pass(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1baï passe"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])drop[\\s‑-]?in(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1drop inne"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Drop[\\s‑-]?in(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1Drop inne"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])retrofits?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1rétrofitte"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Retrofits?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1Rétrofitte"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])flares?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1flère"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])burn[\\s‑-]?out(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1beurne aoute"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])bi[\\s‑-]?flows?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1bi flo"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])split(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1splitte"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])OIL(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1oïl"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])ASHRAE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1Achré"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Survey(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1Seurvé"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Jr\\.", "$1junior"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])slides(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1diapositives"],
    ["AT\\s?mosph([A-Za-zÀ-ÖØ-öø-ÿ]*)\\s?EX\\s?plos", "atmosph$1 explos"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])F[\\s‑-]?[Gg][Aa][SsZz]\\s+III(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1F gaz trois"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])F[\\s‑-]?[Gg][Aa][SsZz](?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1F gaz"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])HCFC(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1H C F C"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])HFC(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1H F C"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])HFO(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1H F O"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])CFC(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1C F C"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])SCOP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1S C O P"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])SEER(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1S E E R"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])COP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1C O P"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])EER(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1E E R"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])ODP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1O D P"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])PRG(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1potentiel de réchauffement global"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])LIE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1L I E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])LSE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1L S E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])FDS(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1F D S"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])EPC(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1E P C"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])VAT(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1V A T"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])ARI(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1A R I"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])DEEE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1D E E E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])DESP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1D E S P"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])PFAS(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P F A S"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])([NP])TC(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1$2 T C"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])POE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P O E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])PVE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P V E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])PAG(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P A G"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])MO,\\s*PAO\\s+(et|ou)\\s+AB(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1M O, P A O $2 A B"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])NF\\s+EN(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1N F E N"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])NF(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1N F"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])NO(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1N O"],
    ["\\(UE\\)", "U E"],
    ["\\(CE\\)", "C E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])(marquage|le)\\s+CE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1$2 C E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])IEC(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1I E C"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])ISO\\s+VG(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1iso V G"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])SVG(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1S V G"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])TP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1T P"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])BT(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1B T"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])LP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1L P"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])PS(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P S"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])P([AB])(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])UA(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1U A"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])AC&R(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1A C et R"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])OM(\\d)(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1O M $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])KV([PLR])(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1K V $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])KV(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1K V"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])KP\\s?(\\d+)(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1K P $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])KM(\\d)(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1K M $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])KA(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1K A"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])NRD(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1N R D"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])Y(\\d)(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1Y $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])P([12])(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])([CDEQHL])(\\d)(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1$2 $3"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])G(\\d{1,2})(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1G $2"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])DPE(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1D P E"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])ACV(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1A C V"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])PMH(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1P M H"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])REP(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1R E P"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])RT(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1R T"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])UV(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1U V"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])IC(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1I C"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])annexe\\s+II(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1annexe deux"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])annexe\\s+IV(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³])", "$1annexe quatre"],
    ["\\bF[\\s‑-]?Gas\\b", "F gaz"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])kg\\s*CO[₂2][eé]q?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³₀-₉])", "$1kilogrammes équivalent dioxyde de carbone"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])CO[₂2][eé]q?(?![A-Za-z0-9_À-ÖØ-öø-ÿ²³₀-₉])", "$1équivalent dioxyde de carbone"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])CO[₂2](?![A-Za-z0-9_À-ÖØ-öø-ÿ²³₀-₉])", "$1dioxyde de carbone"],
    ["(^|[^A-Za-z0-9_À-ÖØ-öø-ÿ²³])NH[₃3](?![A-Za-z0-9_À-ÖØ-öø-ÿ²³₀-₉])", "$1ammoniac"],
    ["\\bA[\\s‑-]?1\\b", "A un"],
    ["\\bA[\\s‑-]?2[\\s‑-]?L\\b", "A deux L"],
    ["\\bA[\\s‑-]?2\\b", "A deux"],
    ["\\bA[\\s‑-]?3\\b", "A trois"],
    ["\\bB[\\s‑-]?1\\b", "B un"],
    ["\\bB[\\s‑-]?2[\\s‑-]?L\\b", "B deux L"],
    ["\\bB[\\s‑-]?2\\b", "B deux"],
    ["\\bB[\\s‑-]?3\\b", "B trois"],
    ["\\bHP\\b", "haute pression"],
    ["\\bBP\\b", "basse pression"],
    ["\\bPRP\\b", "potentiel de réchauffement planétaire"],
    ["\\bGWP\\b", "potentiel de réchauffement planétaire"],
    ["\\bEPI\\b", "équipements de protection individuelle"],
    ["\\bQCM\\b", "Q C M"],
    ["\\bR[\\s‑-]?(\\d+[A-Za-z]*)\\b", "R $1"],
    ["°\\s*C\\b", " degrés Celsius"],
    ["\\bkWh\\b", "kilowattheures"],
    ["\\bkW\\b", "kilowatts"],
    ["\\bkg\\b", "kilogrammes"],
    ["\\bW\\b", "watts"],
    ["%", " pour cent"],
    ["→", " vers "],
    ["↔", " en relation avec "],
    ["([A-Za-zÀ-ÖØ-öø-ÿ])/(?=[A-Za-zÀ-ÖØ-öø-ÿ])", "$1 et "],
    ["₀", " zéro "],
    ["₂", " deux "],
    ["₃", " trois "],
    ["₄", " quatre "],
    ["₈", " huit "],
    ["^\\s*[.,;:]+\\s*", ""],
    ["\\s+([.,…])", "$1"],
    ["⟦REECRITURE-HUMAINE⟧ 05de44d0-140", "La section du tube, c'est pi multiplié par le diamètre au carré, le tout divisé par quatre. Ici : 3,14 multiplié par 26, multiplié encore par 26, puis divisé par quatre : environ 531 millimètres carrés. Si on oublie de diviser par quatre, on trouve 2124 millimètres carrés, et c'est faux. Et pi multiplié par le diamètre tout seul, ça donne le périmètre du tube, pas sa section."],
    ["⟦REECRITURE-HUMAINE⟧ 36138df6-54", "Le débit théorique, c'est le volume balayé multiplié par la vitesse de rotation, multiplié par le nombre de cylindres. Ici : 80 centimètres cubes, multipliés par 1450 tours par minute, multipliés par deux cylindres. Ça fait 232 litres par minute, soit environ 13,9 mètres cubes par heure."],
    ["⟦REECRITURE-HUMAINE⟧ 8269086a-45", "Le volume balayé, c'est la section du piston multipliée par la course. La section, c'est pi multiplié par le diamètre au carré, divisé par quatre. Ici : pi multiplié par cinq au carré divisé par quatre, puis multiplié par quatre centimètres de course. On obtient environ 78,5 centimètres cubes."],
    ["⟦REECRITURE-HUMAINE⟧ dbe06e93-3080", "Remplacer « 22 + 90 = 112 → C·H·F₂ » par : « 22 plus 90 égale 112 : un carbone, un hydrogène, deux fluors »."],
    ["⟦REECRITURE-HUMAINE⟧ 036e6081-51", "La température s'exprime en degrés Celsius ou en kelvins. La quantité de chaleur, Q, s'exprime en joules. Et la puissance thermique, Q point, s'exprime en watts."],
    ["⟦REECRITURE-HUMAINE⟧ e49054c2-107", "Le condenseur rejette l'énergie prise dedans plus le travail fourni au compresseur : la puissance rejetée au condenseur, c'est la puissance absorbée à l'évaporateur plus le travail fourni au compresseur."],
    ["⟦REECRITURE-HUMAINE⟧ 98619e99-39", "La surchauffe, c'est la température réelle moins la température de rosée."],
    ["⟦REECRITURE-HUMAINE⟧ b6dab5a5-49", "Le sous-refroidissement, c'est la température de bulle moins la température réelle."],
    ["⟦REECRITURE-HUMAINE⟧ 64763da7-75", "La surchauffe, c'est la température du tube moins la température de saturation : sept moins deux, ça fait cinq kelvins."],
    ["⟦REECRITURE-HUMAINE⟧ 69213c78-266", "Pour chaque couche, calculez la résistance : son épaisseur divisée par sa conductivité, le lambda. Le signe sigma veut dire additionner. […] Enfin, le coefficient U, c'est un divisé par la résistance totale."],
    ["⟦REECRITURE-HUMAINE⟧ credit-SVG (16 clés)", "Supprimer la phrase de la collecte : elle n'a pas à être narrée."],
    ["⟦REECRITURE-HUMAINE⟧ double-point de concatenation (12 cles)", "Retirer le point surnuméraire à la source (titre + corps concaténés sans séparateur)."],
    ["⟦REECRITURE-HUMAINE⟧ narrations CSS (7 cles, deja corrigees en amont)", "Rien à faire : le collecteur a été corrigé, ces 7 narrations ont disparu du corpus régénéré. Maintenir le rejet de toute valeur matchant /\\{[^{}]*:[^{}]*\\}/ dans la branche textContent de collecter-narrations.mjs."],
    ["([:;,.])\\s*,", "$1"],
    [",\\s*,", ","],
    ["\\s+([.,])", "$1"]
  ];

  var compilees = [];
  for (var i = 0; i < REGLES.length; i++) {
    try { compilees.push([new RegExp(REGLES[i][0], "gu"), REGLES[i][1]]); }
    catch (e) {
      try { compilees.push([new RegExp(REGLES[i][0], "g"), REGLES[i][1]]); }
      catch (e2) { /* motif inutilisable : on l'ignore plutôt que de casser la lecture */ }
    }
  }

  function oraliser(texte) {
    if (typeof texte !== "string" || !texte) return texte;
    var resultat = texte;
    for (var i = 0; i < compilees.length; i++) {
      compilees[i][0].lastIndex = 0;
      resultat = resultat.replace(compilees[i][0], compilees[i][1]);
    }
    return resultat.replace(/\s+/g, " ").trim();
  }

  window.PILOTE_PRONONCIATION = { oraliser: oraliser, nombreDeRegles: compilees.length };
})();
