/* ============================================================
   inerWeb HoCourant — banque de questions
   Origine : livret HoCourant v2.1 (chaîne inerWeb « full ia »,
   79 questions reprises après audit du 24/08/2026) + 24 questions
   nouvelles couvrant les corrections v2.2 (domaines de tension,
   effets du courant, zones chiffrées, documents de consignation,
   repères BR).

   FORMAT : ok = LA bonne réponse, nok = les distracteurs.
   L'affichage assemble [ok, ...nok] puis MÉLANGE (Fisher-Yates) :
   aucune périodicité possible, contrairement au livret papier v2.1.
   `m` = module qui porte le contenu testé (les anciennes questions
   « RAPPEL » sont rattachées au module qu'elles testent réellement).
   ============================================================ */

const QUESTIONS = [

  /* ---------- M1 · Le danger électrique ---------- */
  { m:"M1", q:"Un contact direct correspond à…",
    ok:"toucher une partie active normalement sous tension",
    nok:["toucher une masse mise accidentellement sous tension","observer une armoire fermée"],
    exp:"Le contact direct est le contact avec une partie active normalement sous tension." },
  { m:"M1", q:"Une électrocution est…",
    ok:"une électrisation mortelle",
    nok:["un choc sans conséquence","une brûlure légère"],
    exp:"L'électrocution est une électrisation qui entraîne le décès." },
  { m:"M1", q:"Quel élément peut aggraver un choc électrique ?",
    ok:"toutes ces réponses",
    nok:["l'humidité","la durée du contact","le trajet du courant"],
    exp:"Humidité, durée et trajet du courant influencent la gravité." },
  { m:"M1", sc:"cable-abime", q:"Tu découvres un câble dont l'isolant est arraché. Tu dois d'abord…",
    ok:"cesser l'action, éloigner les personnes et signaler",
    nok:["le pousser avec le pied","mettre du ruban sans couper l'alimentation"],
    exp:"On cesse l'action, on protège la zone et on signale l'anomalie." },
  { m:"M1", sc:"arc", q:"Un arc électrique peut-il blesser sans contact direct avec un conducteur ?",
    ok:"oui, par la chaleur, les projections et la surpression",
    nok:["non, un contact de la main est obligatoire","seulement si le sol est mouillé"],
    exp:"Un arc peut provoquer chaleur, projections et surpression sans contact corporel direct." },
  { m:"M1", q:"Une personne est au sol près d'une armoire ouverte. Ton premier réflexe est de…",
    ok:"ne pas t'exposer, faire supprimer le risque et alerter",
    nok:["la tirer immédiatement","lui donner à boire"],
    exp:"On évite une seconde victime, on fait supprimer le risque par un moyen sûr et on alerte." },
  { m:"M1", q:"Des gants isolants sont humides avant usage. Tu dois…",
    ok:"les écarter, les protéger et signaler",
    nok:["les sécher rapidement puis les utiliser","mettre une deuxième paire par-dessus"],
    exp:"Un EPI humide ou douteux est écarté et signalé." },
  { m:"M1", sc:"contact-indirect", q:"Une carcasse métallique est accidentellement sous tension. Le contact avec elle est…",
    ok:"un contact indirect",
    nok:["un contact direct","sans danger si elle ne produit pas d'étincelle"],
    exp:"La masse n'est pas normalement sous tension : il s'agit d'un contact indirect." },
  { m:"M1", sc:"contact-indirect", q:"Toucher une masse mise sous tension par un défaut correspond à…",
    ok:"un contact indirect",
    nok:["un contact direct","une manœuvre normale"],
    exp:"Une masse mise sous tension par un défaut crée un contact indirect." },
  { m:"M1", sc:"cable-abime", q:"Un câble dénudé traverse le passage. La réponse sûre est de…",
    ok:"arrêter, protéger l'accès et signaler",
    nok:["le déplacer avec un manche","poser un chiffon dessus"],
    exp:"On cesse l'exposition, on protège l'accès et on signale l'anomalie." },

  /* ---------- M2 · Observer et analyser ---------- */
  { m:"M2", ph:"learn_check", q:"Avant une opération, l'analyse porte sur…",
    ok:"la tâche, l'installation, l'environnement et les personnes",
    nok:["la tâche seulement","le matériel seulement"],
    exp:"L'analyse relie tâche, installation, environnement et personnes." },
  { m:"M2", ph:"safe_identify", q:"Le repérage du circuit est incertain. Tu…",
    ok:"arrêtes et demandes une identification fiable",
    nok:["essaies quand même","choisis le disjoncteur le plus proche"],
    exp:"Un repérage incertain impose l'arrêt et une identification fiable." },
  { m:"M2", sc:"coactivite", q:"Pourquoi la coactivité compte-t-elle ?",
    ok:"elle peut modifier le risque et les protections",
    nok:["elle ne concerne que le bruit","elle permet de travailler plus vite"],
    exp:"Une autre activité peut supprimer une protection ou créer un nouveau risque." },
  { m:"M2", ph:"learn_group", q:"Quel comportement est professionnel ?",
    ok:"signaler une anomalie et attendre une consigne",
    nok:["cacher son doute","improviser"],
    exp:"Signaler et attendre une consigne est un comportement de sécurité." },
  { m:"M2", q:"La tâche change pendant l'opération. Tu dois d'abord…",
    ok:"t'arrêter et faire réévaluer la situation",
    nok:["continuer si tu connais le matériel","retirer le balisage pour mieux voir"],
    exp:"Toute modification de tâche impose un arrêt et une nouvelle analyse." },
  { m:"M2", sc:"acteurs", q:"Une instruction est imprécise sur le circuit concerné. Tu…",
    ok:"demandes une identification et une consigne fiables",
    nok:["choisis le circuit le plus proche","commences par démonter le capot"],
    exp:"L'identification du circuit et la consigne doivent être fiables avant l'action." },
  { m:"M2", sc:"coactivite", q:"Une équipe de nettoyage apporte de l'eau près de la zone. Tu…",
    ok:"arrêtes et fais réévaluer le risque et les protections",
    nok:["continues sans rien changer","retires tes EPI pour mieux communiquer"],
    exp:"L'arrivée d'eau modifie les conditions et impose une réévaluation." },

  /* ---------- M3 · Prévention, EPC, EPI, VAT ---------- */
  { m:"M3", sc:"protection-collective", q:"La première stratégie de prévention consiste à…",
    ok:"supprimer ou réduire le risque à la source",
    nok:["ajouter des EPI","travailler plus vite"],
    exp:"La prévention commence par supprimer ou réduire le risque à la source." },
  { m:"M3", sc:"epi", ph:"tool_damage", q:"Un EPI est…",
    ok:"un complément défini par l'analyse du risque",
    nok:["un remplacement des protections collectives","facultatif si l'on est expérimenté"],
    exp:"Les EPI complètent les autres mesures ; ils ne les remplacent pas." },
  { m:"M3", sc:"vat", q:"Le fonctionnement d'un dispositif de VAT se contrôle…",
    ok:"avant et après la VAT",
    nok:["avant seulement","après seulement"],
    exp:"Le dispositif est contrôlé avant et après la VAT." },
  { m:"M3", sc:"epi", ph:"tool_damage", q:"Un gant isolant présente une coupure. Tu…",
    ok:"l'écartes et le signales",
    nok:["le répares avec du ruban","l'utilises pour une courte tâche"],
    exp:"Un EPI détérioré est écarté et signalé." },
  { m:"M3", sc:"protection-collective", q:"Entre une barrière adaptée et une paire de gants, la priorité revient en général…",
    ok:"à la protection collective issue de l'analyse",
    nok:["aux gants, car ils suffisent toujours","au choix de la personne la plus expérimentée"],
    exp:"La prévention privilégie la suppression du risque puis la protection collective avant le complément individuel." },
  { m:"M3", sc:"vat", q:"Le dispositif de VAT ne fonctionne plus lors du contrôle après la vérification. Tu conclus que…",
    ok:"la vérification n'est pas validée et il faut reprendre selon la procédure",
    nok:["l'absence de tension reste certaine","le circuit peut être remis sous tension"],
    exp:"Si le dispositif échoue au contrôle final, la VAT ne peut pas être tenue pour validée." },
  { m:"M3", sc:"epi", q:"Porter des EPI permet-il de dépasser les limites de sa tâche ?",
    ok:"non, les EPI ne modifient ni le rôle ni les limites",
    nok:["oui, si les EPI sont neufs","oui, avec l'accord d'un collègue"],
    exp:"Les EPI ne donnent jamais un droit supplémentaire ni un nouveau rôle." },
  { m:"M3", q:"Quelle mesure vient en priorité lorsque cela est possible ?",
    ok:"supprimer l'exposition, notamment en travaillant hors tension",
    nok:["ajouter seulement des EPI","réduire la durée en travaillant plus vite"],
    exp:"Le premier choix est de supprimer l'exposition lorsque c'est possible." },
  { m:"M3", sc:"vat", q:"Pour une VAT prescrite, on utilise…",
    ok:"le dispositif prévu, contrôlé avant et après, selon la procédure",
    nok:["un tournevis testeur","n'importe quel multimètre"],
    exp:"La VAT se réalise avec le dispositif et la méthode prescrits, contrôle avant et après compris." },

  /* ---------- M4 · Domaines de tension (nouveau v2.2) ---------- */
  { m:"M4", sc:"bt-quotidien", q:"En courant alternatif, le domaine basse tension (BT) s'étend…",
    ok:"de 50 V à 1 000 V",
    nok:["de 0 V à 50 V","de 1 000 V à 50 000 V"],
    exp:"En alternatif : TBT jusqu'à 50 V, BT de 50 à 1 000 V, HTA de 1 000 à 50 000 V, HTB au-delà." },
  { m:"M4", sc:"bt-quotidien", q:"Une prise 230 V et un moteur triphasé 400 V appartiennent…",
    ok:"tous les deux au domaine BT",
    nok:["à la TBT pour la prise, à la BT pour le moteur","à la BT pour la prise, à la HTA pour le moteur"],
    exp:"230 V et 400 V sont dans le domaine BT : le quotidien du métier." },
  { m:"M4", sc:"bt-quotidien", q:"La très basse tension (TBT) en courant alternatif va…",
    ok:"jusqu'à 50 V",
    nok:["jusqu'à 230 V","jusqu'à 12 V seulement"],
    exp:"La TBT s'étend jusqu'à 50 V en alternatif (120 V en continu)." },
  { m:"M4", sc:"bt-quotidien", q:"Le domaine HTA commence, en courant alternatif…",
    ok:"au-delà de 1 000 V",
    nok:["au-delà de 400 V","au-delà de 50 000 V"],
    exp:"La HTA va de 1 000 V à 50 000 V en alternatif ; la HTB est au-delà." },
  { m:"M4", q:"Le premier caractère d'un symbole d'habilitation (B ou H) indique…",
    ok:"le domaine de tension des installations concernées",
    nok:["le niveau d'expérience de la personne","la marque du matériel utilisé"],
    exp:"B couvre la basse et très basse tension, H la haute tension." },
  { m:"M4", sc:"bt-quotidien", q:"« Basse tension » signifie…",
    ok:"un domaine de tension défini par la norme — le danger reste réel",
    nok:["une tension sans danger pour l'être humain","une installation qui ne nécessite aucune précaution"],
    exp:"Le domaine BT concentre la majorité des accidents : basse ne veut pas dire inoffensive." },

  /* ---------- M5 · Le courant et le corps (nouveau v2.2) ---------- */
  { m:"M5", sc:"trajet-courant", q:"Vers 10 mA en courant alternatif, l'effet caractéristique est…",
    ok:"la contraction musculaire : on ne peut plus lâcher",
    nok:["un simple picotement sans danger","l'arrêt immédiat du cœur dans tous les cas"],
    exp:"Vers 10 mA, les muscles se contractent : la victime ne peut plus lâcher le conducteur." },
  { m:"M5", sc:"differentiel", q:"Le seuil de 30 mA correspond…",
    ok:"à la sensibilité des disjoncteurs différentiels qui protègent les personnes",
    nok:["à la tension limite de sécurité","au courant minimal pour ressentir un picotement"],
    exp:"Les différentiels haute sensibilité 30 mA protègent les personnes en coupant très vite." },
  { m:"M5", q:"À intensité égale, qu'est-ce qui aggrave un choc électrique ?",
    ok:"une durée de passage plus longue et un trajet par le cœur",
    nok:["une meilleure qualité de chaussures","un local bien éclairé"],
    exp:"Durée et trajet (main-main, main-pied) déterminent largement la gravité." },
  { m:"M5", sc:"trajet-courant", q:"Une peau mouillée…",
    ok:"diminue la résistance du corps : le courant qui le traverse augmente",
    nok:["protège en refroidissant le contact","n'a aucun effet sur le risque"],
    exp:"L'humidité abaisse fortement la résistance : même tension, courant plus grand." },
  { m:"M5", q:"Ce qui blesse le corps lors d'un choc électrique, c'est d'abord…",
    ok:"l'intensité du courant qui le traverse et la durée du passage",
    nok:["la tension affichée sur l'étiquette, seule","le bruit de l'installation"],
    exp:"C'est le couple intensité-durée qui blesse ; la tension détermine le courant selon la résistance." },
  { m:"M5", sc:"trajet-courant", q:"Après une électrisation « légère », sans blessure apparente…",
    ok:"une prise en charge médicale reste nécessaire",
    nok:["on reprend le travail si l'on se sent bien","un verre d'eau et une pause suffisent"],
    exp:"Des troubles peuvent apparaître à retardement : toute électrisation est vue par un médecin." },

  /* ---------- M6 · L'habilitation et ses symboles ---------- */
  { m:"M6", sc:"titre", q:"Qui délivre le titre d'habilitation ?",
    ok:"l'employeur",
    nok:["le formateur","le stagiaire"],
    exp:"L'employeur délivre le titre d'habilitation (C. trav. R4544-10)." },
  { m:"M6", q:"Dans B1V, la lettre V indique…",
    ok:"le voisinage renforcé",
    nok:["la vitesse","la vérification"],
    exp:"V indique le voisinage renforcé." },
  { m:"M6", ph:"competence_check", q:"Une habilitation remplace-t-elle la compétence technique ?",
    ok:"non",
    nok:["oui","seulement pour BR"],
    exp:"L'habilitation ne remplace pas la compétence technique du métier." },
  { m:"M6", q:"Un titre B1V autorise-t-il toutes les opérations BT ?",
    ok:"non, il reste limité au rôle et au périmètre écrit",
    nok:["oui","oui si l'élève est accompagné"],
    exp:"Le titre reste limité au rôle, aux installations et aux tâches écrites." },
  { m:"M6", q:"Dans un symbole, le premier caractère H désigne…",
    ok:"la haute tension",
    nok:["le travail hors tension","l'habilitation du formateur"],
    exp:"H est le domaine haute tension." },
  { m:"M6", q:"Brancher et utiliser normalement un appareil en bon état exige-t-il toujours une habilitation ?",
    ok:"non, mais une sensibilisation au risque reste nécessaire",
    nok:["oui, au minimum B0","oui, au minimum BR"],
    exp:"L'utilisation normale d'un matériel en bon état ne requiert pas systématiquement une habilitation, mais le risque doit être connu." },
  { m:"M6", q:"Un titulaire B1V reçoit seul une demande de dépannage relevant d'une intervention BR. Il doit…",
    ok:"refuser cette opération hors de son rôle et demander une désignation adaptée",
    nok:["accepter car les deux symboles commencent par B","essayer seulement la mesure"],
    exp:"B1V et BR correspondent à des rôles différents ; le titre et la désignation doivent couvrir l'opération." },
  { m:"M6", ph:"learn_workbook", q:"Tu ne sais pas si une tâche entre dans ton symbole. Tu…",
    ok:"t'arrêtes et demandes une instruction fiable",
    nok:["essaies sous surveillance d'un camarade","choisis le symbole le plus proche"],
    exp:"Un doute sur le rôle ou la tâche impose l'arrêt et une instruction fiable." },
  { m:"M6", sc:"titre", q:"Une attestation de formation à l'habilitation est…",
    ok:"une preuve de formation — pas encore un titre d'habilitation",
    nok:["équivalente à un titre d'habilitation","suffisante pour intervenir seul"],
    exp:"Le titre est délivré par l'employeur, avec des limites écrites : l'attestation de formation n'en tient pas lieu." },

  /* ---------- M7 · Zones, distances, acteurs ---------- */
  { m:"M7", sc:"zone-limite", q:"En champ libre, la distance limite de voisinage simple est…",
    ok:"3 m jusqu'à 50 000 V, 5 m au-delà",
    nok:["1 m quelle que soit la tension","30 m dans tous les cas"],
    exp:"Repères publics : 3 m jusqu'à 50 kV, 5 m au-delà — repris par l'INRS." },
  { m:"M7", sc:"bt-quotidien", q:"La zone de voisinage renforcé en basse tension s'étend…",
    ok:"à moins de 0,30 m d'une pièce nue sous tension",
    nok:["à moins de 3 m de toute armoire","uniquement à l'intérieur des coffrets fermés"],
    exp:"En BT, le voisinage renforcé commence à moins de 0,30 m d'une pièce nue sous tension." },
  { m:"M7", sc:"zone-limite", q:"Une limite de zone a été déplacée. Tu…",
    ok:"arrêtes et rends compte",
    nok:["la franchis rapidement","la remets au hasard"],
    exp:"Une limite déplacée impose l'arrêt et le rétablissement de la protection par le responsable." },
  { m:"M7", sc:"acteurs", q:"L'exécutant doit…",
    ok:"respecter la tâche, les limites et les instructions",
    nok:["modifier la consigne","choisir seul son symbole"],
    exp:"L'exécutant respecte la tâche et les instructions reçues." },
  { m:"M7", q:"Si les conditions changent pendant le travail…",
    ok:"on s'arrête et on réévalue",
    nok:["on continue pour finir","on retire les protections gênantes"],
    exp:"Une condition nouvelle impose une nouvelle analyse." },
  { m:"M7", sc:"zone-limite", q:"La porte d'un local électrique est ouverte. Peux-tu entrer uniquement pour regarder ?",
    ok:"non, l'accès dépend de l'autorisation, du rôle et des instructions",
    nok:["oui, sans toucher","oui, avec des chaussures de sécurité"],
    exp:"Une porte ouverte n'est pas une autorisation d'accès." },
  { m:"M7", sc:"objet-long", q:"Tes mains restent hors d'une zone, mais une longue pièce métallique peut la franchir. Tu…",
    ok:"arrêtes et fais prendre en compte l'objet dans l'analyse",
    nok:["continues puisque ton corps reste dehors","demandes à un collègue de pousser l'objet"],
    exp:"Un objet conducteur peut franchir une limite même si le corps reste en retrait." },
  { m:"M7", sc:"zone-limite", q:"Pour connaître une limite de zone applicable, on utilise…",
    ok:"les documents, le balisage et les instructions adaptés à la situation",
    nok:["une estimation à l'œil","la couleur du sol uniquement"],
    exp:"La limite résulte des documents, du balisage et des instructions applicables, pas d'une estimation." },
  { m:"M7", q:"Le balisage est déplacé pendant la mise en sécurité. Tu…",
    ok:"t'arrêtes et fais rétablir les conditions prévues",
    nok:["termines rapidement la VAT","demandes à une personne non habilitée de le tenir"],
    exp:"Une protection déplacée modifie les conditions et impose l'arrêt." },
  { m:"M7", sc:"zone-limite", q:"Pour entrer dans une zone de voisinage, il faut…",
    ok:"le symbole adapté, l'instruction reçue et les protections prévues en place",
    nok:["uniquement des chaussures de sécurité","être accompagné d'un collègue, quel que soit son rôle"],
    exp:"L'accès en zone exige le titre adapté, l'instruction et le contrôle des protections." },

  /* ---------- M8 · B0 / H0 / H0V ---------- */
  { m:"M8", q:"B0 autorise…",
    ok:"les tâches non électriques dans le périmètre prévu",
    nok:["les travaux électriques BT","le dépannage d'un moteur"],
    exp:"B0 encadre des tâches non électriques dans un périmètre préparé." },
  { m:"M8", sc:"coffret-interdit", q:"Une personne B0 peut-elle ouvrir une armoire électrique ?",
    ok:"non",
    nok:["oui","oui si elle ne touche rien"],
    exp:"B0 n'autorise pas l'ouverture d'une armoire électrique." },
  { m:"M8", sc:"coffret-interdit", q:"Le balisage gêne le passage. Tu…",
    ok:"demandes au responsable de réévaluer la zone",
    nok:["le déplaces","passes par-dessus"],
    exp:"Le responsable doit réévaluer la zone et le passage." },
  { m:"M8", q:"Que signifie l'indice 0 ?",
    ok:"aucune opération d'ordre électrique",
    nok:["travail sans tension seulement","premier niveau d'électricien"],
    exp:"L'indice 0 correspond aux opérations d'ordre non électrique." },
  { m:"M8", q:"H0V concerne une personne qui réalise…",
    ok:"des opérations non électriques dans le périmètre HT prévu au voisinage renforcé",
    nok:["un dépannage électrique en BT","des travaux sous tension"],
    exp:"H0V reste un rôle d'ordre non électrique en HT, dans le périmètre et les conditions préparés." },
  { m:"M8", sc:"cable-abime", q:"Une personne B0 découvre un conducteur endommagé. Elle doit…",
    ok:"s'arrêter, protéger et rendre compte",
    nok:["le réparer si elle porte des gants","ouvrir l'armoire pour chercher le défaut"],
    exp:"B0 observe, s'arrête, protège et rend compte ; il ne répare pas le conducteur." },
  { m:"M8", sc:"coffret-interdit", q:"Une armoire condamnée peut-elle être ouverte par une personne B0 ?",
    ok:"non, la condamnation ne change pas son rôle",
    nok:["oui, puisque l'énergie est coupée","oui, si elle ne démonte rien"],
    exp:"La mise hors tension ne transforme pas une tâche non électrique en opération électrique autorisée." },
  { m:"M8", q:"Une entreprise voisine déplace la limite de la zone. L'exécutant B0…",
    ok:"s'arrête et alerte le chargé de chantier",
    nok:["poursuit sur ordre oral d'un collègue","replace la limite au jugé"],
    exp:"Le chargé de chantier doit être alerté lorsque la limite change." },
  { m:"M8", sc:"bs-remplacement", q:"Une personne B0 reçoit l'ordre de déplacer un obstacle placé dans une zone non prévue. Elle…",
    ok:"s'arrête et demande au responsable de préparer la situation",
    nok:["entre rapidement","utilise un outil isolé sans autre consigne"],
    exp:"B0 n'autorise pas à improviser une entrée ou une opération électrique." },
  { m:"M8", q:"Une personne H0V peut-elle remplacer un interrupteur BT ?",
    ok:"non, son rôle reste d'ordre non électrique",
    nok:["oui, car V autorise le voisinage","oui, si le circuit est hors tension"],
    exp:"H0V reste un symbole d'ordre non électrique." },

  /* ---------- M9 · Consignation et documents ---------- */
  { m:"M9", sc:"vat", q:"Mettre un équipement sur arrêt prouve-t-il l'absence de tension ?",
    ok:"non",
    nok:["oui","seulement si le voyant est éteint"],
    exp:"L'arrêt d'une commande ne prouve pas l'absence de tension." },
  { m:"M9", sc:"condamnation", q:"La condamnation sert à…",
    ok:"empêcher une remise sous tension non voulue",
    nok:["repérer la couleur du circuit","remplacer la VAT"],
    exp:"La condamnation empêche une remise sous tension non voulue." },
  { m:"M9", q:"La VAT est réalisée…",
    ok:"avec le dispositif prescrit et vérifié",
    nok:["avec n'importe quel testeur","en touchant rapidement"],
    exp:"La VAT utilise le dispositif et la procédure prescrits." },
  { m:"M9", q:"Qui remet sous tension ?",
    ok:"la personne autorisée selon la procédure",
    nok:["la première personne disponible","l'exécutant sans prévenir"],
    exp:"La remise sous tension revient à la personne autorisée par la procédure." },
  { m:"M9", ph:"safe_separate", q:"La source d'énergie du circuit ne peut pas être identifiée avec certitude. Tu…",
    ok:"arrêtes et demandes une identification fiable",
    nok:["essaies plusieurs organes","te fies au voyant de la machine"],
    exp:"Sans identification certaine de la source, la mise en sécurité ne peut pas continuer." },
  { m:"M9", sc:"condamnation", q:"Un collègue veut retirer le cadenas d'une autre personne pour gagner du temps. La bonne réponse est…",
    ok:"appliquer strictement la procédure et ne pas retirer un dispositif sans autorisation prévue",
    nok:["accepter si le travail semble fini","couper le cadenas puis prévenir"],
    exp:"La condamnation est gérée selon la procédure ; on ne retire pas librement le dispositif d'autrui." },
  { m:"M9", sc:"vat", q:"Pourquoi contrôler le dispositif de VAT après l'essai ?",
    ok:"pour confirmer qu'il fonctionne toujours",
    nok:["pour mesurer l'intensité","pour remplacer la condamnation"],
    exp:"Le contrôle après VAT confirme que le dispositif n'est pas tombé en panne pendant l'opération." },
  { m:"M9", sc:"condamnation", ph:"safe_separate", q:"Dans la consignation, l'ordre correct des premières étapes est…",
    ok:"séparer, condamner, identifier sur place, vérifier l'absence de tension",
    nok:["vérifier l'absence de tension, puis séparer et condamner","condamner, remettre sous tension, séparer"],
    exp:"Séparation, condamnation, identification puis VAT — la MALT/CC complète lorsqu'elle est prescrite." },
  { m:"M9", sc:"condamnation", q:"L'attestation de consignation est remise…",
    ok:"par le chargé de consignation au chargé de travaux, avant le début des travaux",
    nok:["par l'exécutant au client, après les travaux","par le fabricant du matériel, à la livraison"],
    exp:"Elle atteste que la zone est consignée : le chargé de travaux peut alors faire commencer." },
  { m:"M9", sc:"documents", q:"L'avis de fin de travail signifie que…",
    ok:"le travail est terminé, personnes et outils recensés — la déconsignation peut être engagée",
    nok:["l'installation est déjà remise sous tension par l'exécutant","la pause de midi commence"],
    exp:"L'avis de fin de travail clôt le chantier ; la déconsignation revient aux personnes autorisées." },
  { m:"M9", sc:"documents", q:"La mise à la terre et en court-circuit (MALT/CC)…",
    ok:"complète la consignation lorsqu'elle est prescrite par la procédure",
    nok:["remplace la VAT quand on est pressé","est interdite en toutes circonstances"],
    exp:"La MALT/CC est prescrite selon l'installation : risque de réalimentation, réseaux étendus, haute tension." },

  /* ---------- M10 · BS et BE Manœuvre ---------- */
  { m:"M10", sc:"bs-remplacement", q:"Le BS travaille normalement…",
    ok:"hors tension et hors voisinage renforcé",
    nok:["sous tension","dans toute installation BT"],
    exp:"Le BS intervient hors tension et hors voisinage renforcé." },
  { m:"M10", sc:"manoeuvre", q:"BE Manœuvre permet de…",
    ok:"agir sur un organe de commande dans le cadre prévu",
    nok:["dépanner un variateur","remplacer un disjoncteur"],
    exp:"BE Manœuvre agit sur une commande ou une protection dans le cadre prévu." },
  { m:"M10", sc:"manoeuvre", q:"Un défaut réapparaît après réarmement. Tu…",
    ok:"arrêtes et rends compte",
    nok:["réarmes jusqu'à ce qu'il tienne","retires la protection"],
    exp:"Un défaut qui réapparaît impose l'arrêt et le compte rendu." },
  { m:"M10", sc:"bs-remplacement", q:"Le BS peut-il diriger plusieurs exécutants ?",
    ok:"non",
    nok:["oui","oui si le circuit est hors tension"],
    exp:"Le BS agit seul et ne dirige pas d'exécutant." },
  { m:"M10", sc:"bs-remplacement", q:"Un remplacement à l'identique est demandé à un BS. Il peut l'envisager…",
    ok:"uniquement dans les limites de son titre, de la procédure et hors tension",
    nok:["dès qu'il possède un tournevis isolé","même si le circuit n'est pas identifié"],
    exp:"Le caractère élémentaire et à l'identique ne suffit pas : titre, procédure, limites et hors tension restent nécessaires." },
  { m:"M10", sc:"manoeuvre", q:"Une personne BE Manœuvre reçoit une demande de mesure de tension pour diagnostiquer une panne. Elle…",
    ok:"refuse cette opération hors de son rôle et rend compte",
    nok:["mesure si le multimètre est disponible","ouvre l'armoire mais ne touche rien"],
    exp:"Mesurer pour diagnostiquer n'est pas une simple manœuvre." },
  { m:"M10", sc:"bs-remplacement", q:"Un matériel de remplacement ne correspond pas exactement au modèle prévu. Le BS…",
    ok:"s'arrête et demande une vérification de compatibilité",
    nok:["l'adapte sur place","le monte puis le teste"],
    exp:"Une référence incertaine impose l'arrêt et la vérification de compatibilité." },
  { m:"M10", sc:"manoeuvre", q:"BE Manœuvre autorise-t-il le diagnostic d'un défaut interne ?",
    ok:"non, la manœuvre ne devient pas un dépannage",
    nok:["oui, avec un téléphone","oui, si le capot est déjà ouvert"],
    exp:"BE Manœuvre ne couvre pas le diagnostic interne." },
  { m:"M10", sc:"bs-remplacement", q:"Parmi les repères publics du cadre BS figurent…",
    ok:"un circuit terminal, au plus 400 V alternatif et une protection au plus 32 A",
    nok:["toute installation BT jusqu'à 1 000 V sans condition","les installations haute tension de faible puissance"],
    exp:"Repères INRS : circuit terminal, 400 V~ / 600 V= au plus, 32 A~ / 16 A= au plus, 6 mm² Cu / 10 mm² Al." },

  /* ---------- M11 · B1 / B1V ---------- */
  { m:"M11", q:"B1 correspond à…",
    ok:"un exécutant de travaux électriques BT",
    nok:["un chargé d'intervention générale","une personne non électrique"],
    exp:"B1 est l'exécutant de travaux électriques BT." },
  { m:"M11", q:"La lettre V de B1V autorise…",
    ok:"le voisinage renforcé dans le périmètre prévu",
    nok:["tous les travaux sous tension","les manœuvres HT"],
    exp:"V concerne le voisinage renforcé dans le périmètre autorisé." },
  { m:"M11", ph:"competence_check", q:"La formation à l'habilitation apprend-elle le métier d'électricien ?",
    ok:"non, elle porte sur la prévention du risque électrique",
    nok:["oui","seulement pour B1V"],
    exp:"La formation à l'habilitation porte sur la prévention du risque électrique." },
  { m:"M11", sc:"acteurs", q:"Une instruction reçue par un exécutant B1V est ambiguë. Il doit…",
    ok:"demander au chargé de travaux de préciser avant d'agir",
    nok:["choisir l'interprétation la plus rapide","commencer seulement la moitié de la tâche"],
    exp:"L'exécutant B1V agit selon les instructions du chargé de travaux et demande toute précision nécessaire." },
  { m:"M11", q:"L'exécutant B1 travaille…",
    ok:"sous la direction d'un chargé de travaux",
    nok:["seul, en toute autonomie","sous la seule surveillance du client"],
    exp:"B1 exécute selon les instructions du chargé de travaux (B2)." },

  /* ---------- M12 · Incident, accident, incendie ---------- */
  { m:"M12", sc:"secours", q:"Une victime est peut-être encore en contact électrique. Tu…",
    ok:"supprimes le risque par un moyen sûr et alertes",
    nok:["la tires immédiatement","jettes de l'eau"],
    exp:"On supprime le risque sans s'exposer puis on alerte." },
  { m:"M12", sc:"alerte", q:"Le numéro d'urgence européen est…",
    ok:"112",
    nok:["119","911"],
    exp:"112 est le numéro européen d'urgence." },
  { m:"M12", sc:"trajet-courant", ph:"rescue_aid", q:"Après une électrisation apparemment légère…",
    ok:"une prise en charge médicale est nécessaire",
    nok:["aucune démarche n'est utile","on reprend le travail"],
    exp:"Une électrisation nécessite une prise en charge médicale." },
  { m:"M12", sc:"secours", ph:"near_miss", q:"Un presque-accident doit…",
    ok:"être signalé et analysé",
    nok:["être caché","être oublié s'il n'y a pas de blessé"],
    exp:"Le presque-accident est un signal utile à la prévention." },
  { m:"M12", sc:"secours", q:"Lors d'un secours, pourquoi faut-il d'abord éviter de s'exposer ?",
    ok:"pour ne pas devenir une seconde victime",
    nok:["pour conserver ses EPI propres","pour attendre la fin de la journée"],
    exp:"La protection du sauveteur évite d'ajouter une victime." },
  { m:"M12", sc:"alerte", q:"Dans le message d'alerte, il faut donner…",
    ok:"le lieu, l'accès, le risque, l'état apparent et les protections réalisées",
    nok:["uniquement son prénom","uniquement le numéro de l'armoire"],
    exp:"Un message complet aide les secours à comprendre le lieu, le risque et l'état de la victime." },
  { m:"M12", q:"Après un accident ou un incident, la remise sous tension se fait…",
    ok:"uniquement selon la procédure et par la personne autorisée",
    nok:["dès que la victime est partie","par le premier témoin disponible"],
    exp:"La remise sous tension suit une procédure et relève d'une personne autorisée." },

  /* ---------- M13 · BR ---------- */
  { m:"M13", q:"BR correspond principalement à…",
    ok:"une intervention générale BT de faible étendue",
    nok:["un chantier de construction complet","une opération non électrique"],
    exp:"BR concerne une intervention générale BT de faible étendue." },
  { m:"M13", sc:"hors-perimetre", q:"Une modification complète d'armoire est demandée à une personne uniquement BR. Cette personne…",
    ok:"signale que l'opération dépasse l'intervention générale de faible étendue",
    nok:["la réalise car BR autorise tout en BT","la réalise hors tension sans autre condition"],
    exp:"BR vise une intervention générale BT de faible étendue, pas une modification complète d'armoire." },
  { m:"M13", q:"Avant de dépanner hors tension, le chargé d'intervention BR…",
    ok:"réalise sa propre mise en sécurité, pour son propre compte",
    nok:["attend qu'un chargé de consignation vienne toujours consigner à sa place","travaille directement, car BR dispense de consigner"],
    exp:"Le BR consigne pour son propre compte dans le périmètre de son intervention." },
  { m:"M13", q:"Le repère de 500 V parfois cité pour les interventions BT générales signifie…",
    ok:"un repère d'enseignement — la limite réelle est celle du titre, de l'installation et de la norme",
    nok:["que le BR peut tout faire jusqu'à 500 V","que sous 500 V, aucune règle ne s'applique"],
    exp:"Le titre et la norme fixent les limites réelles ; le repère chiffré ne les remplace pas." },
  { m:"M13", q:"BR est-il une autorisation générale de travailler sous tension ?",
    ok:"non — les opérations en présence de tension restent strictement limitées et préparées",
    nok:["oui, en basse tension","oui, si l'intervention est courte"],
    exp:"BR n'autorise jamais le travail sous tension généralisé : norme, titre, procédure et formation pratique bornent tout." },
];
