"use strict";

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const dossiers=[
  {id:"preparer",label:"Préparer",note:"reprendre au point sûr"},
  {id:"ouvrir",label:"Ouvrir",note:"déposer et refermer"},
  {id:"eprouver",label:"Éprouver",note:"prouver l’étanchéité"},
  {id:"charger",label:"Sécher et charger",note:"vide puis masse prévue"},
  {id:"controler",label:"Contrôler et tracer",note:"méthode directe"},
  {id:"controle",label:"Contrôle",note:"5 décisions finales"},
];
const completed=new Set(), wrongSeen=new Set(), quizAnswers={};
let current=0,furthest=0,extractMode=false,activeScreens=[],speechRun=0,speaking=false,paused=false,statusTimer=0;
const voiceRates=[.8,.95,1.1,1.25]; let rateIndex=safeStoredRateIndex();
function safeStoredRateIndex(){try{const n=Number(localStorage.getItem("intervention-hydrocarbures-voice-rate")),i=voiceRates.indexOf(n);return i>=0?i:1}catch(_){return 1}}
function saveRate(){try{localStorage.setItem("intervention-hydrocarbures-voice-rate",String(voiceRates[rateIndex]))}catch(_){}}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function stripHtml(v){const d=document.createElement("div");d.innerHTML=v;return d.textContent||""}
function screen(data){return{codes:[],level:"appliquer",prompt:"",speak:"",required:false,...data}}
function route(nodes){return `<div class="route"><div class="route-line">${nodes.map((n,i)=>`<span class="route-node ${n.kind||''}">${esc(n.label)}</span>${i<nodes.length-1?'<span class="route-arrow">→</span>':''}`).join("")}</div></div>`}
function panel(title,body){return `<div class="panel"><div class="panel-title">${esc(title)}</div>${body}</div>`}
function evidence(items){return `<div class="evidence">${items.map(i=>`<div class="evidence-card"><strong>${esc(i.title)}</strong>${esc(i.text)}</div>`).join("")}</div>`}
function tools(items){return `<div class="tool-strip">${items.map(i=>`<div class="tool-card"><img src="${esc(i.src)}" alt=""><span>${esc(i.label)}</span></div>`).join("")}</div>`}
function branchMarkup(item){return `<div class="branch-panel"><div class="branch-context">${esc(item.branch.context)}</div><div class="branch-choices">${item.branch.choices.map((c,i)=>`<button class="branch-choice" type="button" data-branch="${i}"><strong>${esc(c.title)}</strong><small>${esc(c.note)}</small></button>`).join("")}</div><div class="feedback" id="branch-feedback">Choisissez. Le parcours vous montrera la conséquence.</div></div>`}
function wireBranch(item){
  $$('[data-branch]').forEach(button=>button.addEventListener("click",()=>{
    const index=Number(button.dataset.branch),choice=item.branch.choices[index],good=index===item.branch.good;
    $$('.branch-choice').forEach(b=>b.classList.remove("correct","wrong"));button.classList.add(good?"correct":"wrong");
    const box=$("#branch-feedback");box.className=`consequence ${good?'good':''}`;
    if(good){completed.add(item.id);box.innerHTML=`<strong>Point sûr validé.</strong>${esc(choice.effect)}`;renderNavigation();}
    else{wrongSeen.add(item.id);box.innerHTML=`<strong>Ce qui se serait passé.</strong>${esc(choice.effect)}<button class="return-safe" id="return-safe" type="button">Revenir au dernier point sûr</button>`;$("#return-safe").addEventListener("click",()=>{box.className="feedback";box.textContent="Vous êtes revenu au dernier point sûr. Choisissez de nouveau.";button.classList.remove("wrong");button.focus();});}
  }));
}
function sequenceMarkup(items){return `<div class="panel"><div class="sequence">${items.map((x,i)=>`<button class="sequence-step ${i===0?'active':''}" type="button" data-seq="${i}">${i+1}<br>${esc(x)}</button>${i<items.length-1?'<span class="sequence-arrow">→</span>':''}`).join("")}</div><div class="feedback" id="feedback">Cliquez dans l’ordre.</div></div>`}
function wireSequence(item){let next=0;$$('[data-seq]').forEach(b=>b.addEventListener("click",()=>{if(Number(b.dataset.seq)!==next){$("#feedback").className="feedback bad";$("#feedback").textContent="L’ordre est rompu : revenez au dernier point sûr.";return}b.classList.remove("active");b.classList.add("done");next++;const n=$(`[data-seq="${next}"]`);if(n)n.classList.add("active");$("#feedback").className="feedback good";$("#feedback").textContent=next===$$('[data-seq]').length?"Séquence complète.":"Étape validée.";if(next===$$('[data-seq]').length){completed.add(item.id);renderNavigation()}}))}
function quizMarkup(item){const saved=quizAnswers[item.id];return `<div class="panel"><div class="cards" style="--cols:2">${item.quiz.choices.map((c,i)=>`<button class="choice ${saved===i?(i===item.quiz.good?'good':'bad'):''}" type="button" data-quiz="${i}" ${saved!==undefined?'disabled':''}><strong>${String.fromCharCode(65+i)}.</strong><small>${esc(c)}</small></button>`).join("")}</div><div class="feedback ${saved===undefined?'':saved===item.quiz.good?'good':'bad'}" id="feedback">${saved===undefined?'Choisissez une réponse.':`<strong>${saved===item.quiz.good?'Correct.':'À revoir.'}</strong> ${esc(item.quiz.explain)}`}</div></div>`}
function wireQuiz(item){$$('[data-quiz]').forEach(b=>b.addEventListener("click",()=>{if(quizAnswers[item.id]!==undefined)return;quizAnswers[item.id]=Number(b.dataset.quiz);completed.add(item.id);renderCurrent(false)}))}

const screens=[
  screen({id:"relais-mission-290",dossier:"preparer",title:"Mission 290 vous remet le chantier",kicker:"Préparer · 1",text:"La zone est ventilée et balisée. Les sources d’inflammation sont écartées. Le fluide a été récupéré avec l’outillage adapté, puis le circuit a été rempli d’azote selon la procédure. Vous ne recommencez pas la théorie : vous prenez la suite.",prompt:"Repérez le point de départ. Si une preuve manque, le travail s’arrête.",render:()=>route([{label:"Zone autorisée",kind:"safe"},{label:"Fluide récupéré",kind:"safe"},{label:"Azote selon procédure",kind:"safe"},{label:"G12B : ouvrir",kind:""}])}),
  screen({id:"point-arret",dossier:"preparer",title:"Le droit d’arrêter fait partie du geste",kicker:"Préparer · 2",codes:["12.07"],text:"Une alarme, une odeur inhabituelle, une ventilation arrêtée, un détecteur non conforme ou une preuve d’inertage absente impose STOP. S’éloigner, sécuriser, alerter et reprendre l’analyse : on ne compense jamais par la vitesse.",prompt:"Choisissez le chantier qui peut passer à l’ouverture.",required:true,branch:{context:"Deux postes vous attendent. Lequel franchit le point d’arrêt ?",good:1,choices:[{title:"Poste A : alarme active",note:"Un collègue propose de finir vite.",effect:"L’ouverture peut libérer un mélange inflammable dans une zone déjà en alarme. Le travail doit s’arrêter."},{title:"Poste B : preuves réunies",note:"Zone, récupération, azote et consignation vérifiés.",effect:"Le poste peut passer à l’étape suivante sous la procédure du site."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"fil-rouge",dossier:"preparer",title:"Chaque preuve ouvre la suivante",kicker:"Préparer · 3",codes:["12.07","12.08","12.09","12.10","12.11","12.12"],text:"Le parcours complet suit un ordre. Aucune flèche ne peut être sautée : un circuit ouvert est refermé avant l’épreuve ; une épreuve non concluante interdit le vide ; un vide non concluant interdit la charge.",prompt:"Lisez la chaîne de gauche à droite.",render:()=>route([{label:"Ouvrir · remplacer · refermer"},{label:"Épreuve à l’azote"},{label:"Essai sous vide"},{label:"Charge prévue"},{label:"Contrôle direct"},{label:"Rapport"}])}),

  screen({id:"avant-ouverture",dossier:"ouvrir",title:"Avant de couper : quatre confirmations",kicker:"Ouvrir · 1",codes:["12.07"],text:"Consignation électrique, récupération terminée, remplissage à l’azote conforme à la procédure et détection de gaz satisfaisante : ces confirmations viennent avant l’ouverture. L’azote n’autorise pas à ignorer la ventilation ou le détecteur.",prompt:"Ouvrez les preuves écrites.",render:()=>panel("Point sûr avant ouverture",evidence([{title:"Énergie",text:"Consignée selon le site."},{title:"Fluide",text:"Récupération terminée et tracée."},{title:"Atmosphère",text:"Ventilation et détection actives."},{title:"Circuit",text:"Azote appliqué selon la procédure."}]))}),
  screen({id:"embranchement-ouverture",dossier:"ouvrir",title:"La détection remonte",kicker:"Ouvrir · 2",codes:["12.07"],text:"Au dernier contrôle, le détecteur de gaz indique une présence anormale près du poste. Le circuit est annoncé récupéré, mais le signal contredit le dossier.",prompt:"Décidez avant de toucher au tube.",required:true,branch:{context:"Le planning presse. La preuve terrain contredit la preuve papier.",good:0,choices:[{title:"STOP et retour à l’analyse",note:"Éloigner, ventiler, localiser selon la procédure.",effect:"Vous gardez le circuit fermé et revenez au dernier point sûr. La détection doit être expliquée avant toute ouverture."},{title:"Ouvrir quand même",note:"Le dossier dit que le circuit est vide.",effect:"Le dossier peut être faux ou incomplet. L’ouverture peut libérer un hydrocarbure résiduel vers une source d’ignition."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"deposer-composant",dossier:"ouvrir",title:"Déposer sans improviser",kicker:"Ouvrir · 3",codes:["12.07"],text:"Le composant est déposé sur un poste hydrocarbures dédié, avec l’outillage et la méthode prévus. Si une opération avec flamme est autorisée, elle ne commence qu’après les preuves précédentes et s’exécute sous balayage d’azote selon la procédure encadrée.",prompt:"Identifiez ce qui reste interdit.",render:()=>tools([{src:"../bibliotheque/icones/ico-cadenas.png",label:"Consignation maintenue"},{src:"../bibliotheque/icones/ico-azote.png",label:"Azote selon procédure"},{src:"../bibliotheque/icones/ico-detecteur-fuite.png",label:"Détection active"},{src:"../bibliotheque/icones/ico-interdit.png",label:"Aucune improvisation"}])}),
  screen({id:"refermer-circuit",dossier:"ouvrir",title:"Refermer prépare la preuve",kicker:"Ouvrir · 4",codes:["12.07"],text:"Le composant neuf est compatible avec l’équipement et le fluide. Les assemblages sont terminés et contrôlables. Le circuit doit être refermé avant l’épreuve : la pression ne sert jamais à “finir” un montage.",prompt:"Remettez les quatre temps dans l’ordre.",required:true,render:()=>sequenceMarkup(["Identifier la pièce","Déposer sous procédure","Monter et assembler","Refermer complètement"]),wire(){wireSequence(this)}}),

  screen({id:"montage-azote",dossier:"eprouver",title:"L’azote passe par le mano-détendeur",kicker:"Éprouver · 1",codes:["12.08"],text:"L’épreuve de pression utilise de l’azote sec et le montage prévu, avec mano-détendeur. Jamais d’oxygène, jamais d’air comprimé, jamais de bouteille en direct. La pression d’épreuve vient de la documentation applicable.",prompt:"Choisissez le montage de départ.",required:true,branch:{context:"Le circuit est refermé. Deux montages sont proposés.",good:0,choices:[{title:"Azote + mano-détendeur",note:"Valeur issue de la documentation.",effect:"La pression peut être appliquée et surveillée selon la procédure."},{title:"Bouteille en direct",note:"Plus rapide, sans régulation.",effect:"La pression de bouteille peut dépasser ce que le circuit supporte et provoquer une rupture violente."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"epreuve-procedure",dossier:"eprouver",title:"Monter, stabiliser, contrôler",kicker:"Éprouver · 2",codes:["12.08"],text:"L’épreuve suit la procédure : appliquer l’azote avec le montage adapté, atteindre la valeur documentée, stabiliser, surveiller et rechercher l’absence de fuite avec la méthode prévue. Aucune durée ni pression universelle n’est donnée ici.",prompt:"Faites avancer la séquence.",required:true,render:()=>sequenceMarkup(["Montage vérifié","Pression documentée","Stabilisation","Contrôle d’étanchéité"]),wire(){wireSequence(this)}}),
  screen({id:"embranchement-epreuve",dossier:"eprouver",title:"La pression ne tient pas",kicker:"Éprouver · 3",codes:["12.08"],text:"Après stabilisation prévue, le résultat ne répond pas au critère de la procédure. Une microfuite sur l’assemblage neuf est possible.",prompt:"Que devient l’étape suivante ?",required:true,branch:{context:"Le planning prévoyait maintenant le tirage au vide.",good:1,choices:[{title:"Passer au vide",note:"La pompe dira si cela tient.",effect:"Le vide ne répare pas une fuite. Vous perdriez le point de preuve de l’épreuve et prépareriez une charge sur un circuit non conforme."},{title:"STOP, localiser et corriger",note:"Puis refaire l’épreuve complète.",effect:"Vous revenez au dernier point sûr. L’essai suivant ne commence qu’après une épreuve concluante."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"conclusion-epreuve",dossier:"eprouver",title:"Épreuve concluante = preuve datée",kicker:"Éprouver · 4",codes:["12.08"],text:"Une épreuve n’est pas “bonne” parce qu’un technicien le dit. Le rapport gardera le gaz utilisé, la valeur issue de la documentation, les conditions, le résultat, les points contrôlés et l’identification du matériel de mesure selon la procédure.",prompt:"Repérez les preuves qui devront être tracées.",render:()=>panel("Preuve d’épreuve",evidence([{title:"Référence",text:"Notice, norme ou procédure applicable."},{title:"Conditions",text:"Valeur, durée et ambiance selon le dossier."},{title:"Résultat",text:"Critère conclu ou non conclu."},{title:"Action",text:"Point contrôlé et correction éventuelle."}]))}),

  screen({id:"montage-vide",dossier:"charger",title:"Le vide retire l’air et l’humidité",kicker:"Sécher et charger · 1",codes:["12.09"],text:"Après retrait de l’azote selon la procédure, la pompe à vide et le vacuomètre adaptés sont raccordés comme prévu pour les hydrocarbures. Le refoulement de la pompe est géré conformément à sa notice et à la procédure du site.",prompt:"Identifiez les outils de cette étape.",render:()=>tools([{src:"../bibliotheque/icones/ico-pompe-vide.png",label:"Pompe compatible"},{src:"../bibliotheque/icones/ico-vacuometre.png",label:"Vacuomètre"},{src:"../bibliotheque/icones/ico-manifold.png",label:"Raccordement adapté"},{src:"../bibliotheque/icones/ico-cadenas.png",label:"Circuit isolé"}])}),
  screen({id:"essai-vide",dossier:"charger",title:"Atteindre ne suffit pas : il faut tenir",kicker:"Sécher et charger · 2",codes:["12.09"],text:"Le niveau cible et la durée viennent de la documentation. Après isolement de la pompe, l’observation de la tenue aide à repérer un défaut. Une remontée ne se “corrige” jamais en chargeant le fluide.",prompt:"Faites avancer l’essai.",required:true,render:()=>sequenceMarkup(["Tirer au vide","Atteindre le critère","Isoler la pompe","Observer la tenue"]),wire(){wireSequence(this)}}),
  screen({id:"embranchement-vide",dossier:"charger",title:"Le vide remonte",kicker:"Sécher et charger · 3",codes:["12.09"],text:"Après isolement, la mesure remonte au-delà du critère prévu. Le défaut peut venir d’une fuite, d’humidité ou du montage de mesure : il faut l’identifier.",prompt:"La bouteille de R-290 est prête. Décidez.",required:true,branch:{context:"Un collègue dit que le fluide “finira de pousser l’air”.",good:0,choices:[{title:"STOP et diagnostiquer",note:"Contrôler montage, fuite et humidité.",effect:"Vous gardez la bouteille fermée et revenez au dernier point sûr jusqu’à obtenir un essai conforme."},{title:"Charger pour gagner du temps",note:"Le fonctionnement montrera bien le défaut.",effect:"Vous enfermez air ou humidité dans le circuit et vous chargez un système dont l’étanchéité n’est pas démontrée."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"identifier-charge",dossier:"charger",title:"La charge vient de l’équipement",kicker:"Sécher et charger · 4",codes:["12.10"],text:"Le fluide, sa masse prévue et la méthode de charge se lisent sur la plaque, la notice et le dossier applicable. On ne reprend jamais la quantité d’une machine “qui ressemble”, et on ne convertit pas un autre fluide au jugé.",prompt:"Choisissez la source défendable.",required:true,branch:{context:"Deux appareils se ressemblent. Leurs plaques ne donnent pas la même charge.",good:1,choices:[{title:"Copier la charge du voisin",note:"Même taille extérieure.",effect:"L’apparence ne prouve ni le même circuit ni la même charge. L’efficacité et la sécurité peuvent être dégradées."},{title:"Lire la plaque et la notice",note:"Identifier l’appareil exact.",effect:"La charge prévue est liée au modèle réel et peut être pesée sans estimation."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"peser-charge",dossier:"charger",title:"Peser la quantité prévue",kicker:"Sécher et charger · 5",codes:["12.10"],text:"La bouteille adaptée est posée sur une balance stable. La quantité introduite est suivie par pesée selon la procédure. Une faible charge n’autorise aucune approximation : chaque écart compte pour le fonctionnement et la sécurité.",prompt:"Suivez le fil sans inventer de valeur.",render:()=>route([{label:"Identifier le fluide",kind:"safe"},{label:"Lire la charge prévue",kind:"safe"},{label:"Tarer et peser"},{label:"Fermer à la masse prévue",kind:"safe"}])}),
  screen({id:"embranchement-charge",dossier:"charger",title:"La masse ne correspond pas",kicker:"Sécher et charger · 6",codes:["12.10"],text:"La masse suivie à la balance dépasse la quantité prévue par le dossier. Le compresseur n’a pas encore démarré.",prompt:"Que faites-vous avant toute mise en marche ?",required:true,branch:{context:"Le collègue propose de laisser l’excès : “ça donnera plus de froid”.",good:0,choices:[{title:"STOP et corriger selon la procédure",note:"Retrouver la masse prévue et tracer l’écart.",effect:"La machine ne démarre pas tant que la charge n’est pas conforme et documentée."},{title:"Démarrer pour voir",note:"La pression décidera.",effect:"Une charge excessive peut augmenter la pression, dégrader le fonctionnement et contredire la charge de conception."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),

  screen({id:"methode-directe",dossier:"controler",title:"Chercher la fuite au bon endroit",kicker:"Contrôler et tracer · 1",codes:["12.11"],text:"Le contrôle direct recherche la présence de fluide au voisinage des raccords, assemblages et composants avec une méthode adaptée. Il vient après une remise en service conforme et ne remplace ni l’épreuve ni l’essai sous vide.",prompt:"Repérez les points contrôlés sans ouvrir le circuit.",render:()=>panel("Contrôle direct",evidence([{title:"Assemblage remplacé",text:"Contrôle autour de la zone travaillée."},{title:"Raccords",text:"Contrôle des points manipulés."},{title:"Vannes et accès",text:"Contrôle sans intervention dans le circuit."},{title:"Résultat",text:"Présence ou absence tracée."}]))}),
  screen({id:"detecteur-adapte",dossier:"controler",title:"Le détecteur doit reconnaître l’hydrocarbure",kicker:"Contrôler et tracer · 2",codes:["12.11"],text:"Un détecteur destiné uniquement à des HFC ne prouve rien sur le R-290. La compatibilité se vérifie sur le marquage et la documentation de l’appareil. Son contrôle de fonctionnement suit sa notice.",prompt:"Choisissez l’instrument qui peut fournir une preuve.",required:true,branch:{context:"Deux détecteurs s’allument. Un seul documente sa compatibilité R-290.",good:1,choices:[{title:"Détecteur HFC habituel",note:"Il fonctionne bien sur R-134a.",effect:"Son absence de signal ne prouve pas l’absence de R-290. Le mauvais capteur produit une fausse sécurité."},{title:"Détecteur documenté hydrocarbures",note:"Compatibilité et contrôle vérifiés.",effect:"Le contrôle peut être réalisé selon la notice, puis tracé."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"embranchement-fuite",dossier:"controler",title:"Le contrôle direct détecte",kicker:"Contrôler et tracer · 3",codes:["12.11"],text:"Le détecteur adapté réagit sur l’assemblage remplacé. L’épreuve et le vide avaient été concluants, mais ce signal nouveau doit être traité.",prompt:"Autorisez-vous la remise en service ?",required:true,branch:{context:"Le signal apparaît deux fois au même point après le contrôle de l’appareil.",good:0,choices:[{title:"Non : STOP, sécuriser et corriger",note:"Reprendre la procédure depuis le point sûr adapté.",effect:"La remise en service est suspendue. L’anomalie est localisée, corrigée puis les preuves nécessaires sont refaites."},{title:"Oui : les essais précédents suffisent",note:"Le signal est probablement résiduel.",effect:"Vous laisseriez fonctionner un équipement avec une indication directe de fuite d’hydrocarbure."}]},render(){return branchMarkup(this)},wire(){wireBranch(this)}}),
  screen({id:"rapport-intervention",dossier:"controler",title:"Le rapport ferme l’intervention",kicker:"Contrôler et tracer · 4",codes:["12.12"],text:"Le rapport identifie l’équipement et le fluide, décrit le composant remplacé, trace l’épreuve, le vide, la charge, le contrôle direct, les anomalies et la décision finale. Une case vide n’est jamais remplacée par une valeur inventée.",prompt:"Ouvrez les six preuves du rapport.",render:()=>panel("Rapport d’entretien",evidence([{title:"Équipement",text:"Identification et fluide."},{title:"Travail",text:"Composant déposé et remplacé."},{title:"Épreuve",text:"Référence, conditions, résultat."},{title:"Vide",text:"Critère et tenue observée."},{title:"Charge",text:"Masse prévue et masse introduite."},{title:"Contrôle final",text:"Méthode, résultat, décision et réserves."}]))}),

  screen({id:"quiz-ordre",dossier:"controle",title:"Contrôle 1 · Ordre complet",kicker:"Contrôle final",codes:["12.07","12.08","12.09","12.10","12.11","12.12"],level:"evaluer",required:true,text:"Après récupération et remplissage à l’azote, quelle chaîne respecte le référentiel ?",prompt:"Choisissez l’ordre complet.",quiz:{choices:["Ouvrir/remplacer/refermer → épreuve → vide → charge → contrôle direct → rapport","Vide → ouvrir → charge → épreuve → rapport","Charge → démarrer → ouvrir → contrôler","Ouvrir → charge → vide → rapport"],good:0,explain:"Chaque preuve autorise la suivante. Une étape non concluante arrête la chaîne."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),
  screen({id:"quiz-epreuve",dossier:"controle",title:"Contrôle 2 · Épreuve",kicker:"Contrôle final",codes:["12.08"],level:"evaluer",required:true,text:"L’épreuve à l’azote ne tient pas le critère de la procédure.",prompt:"Que faites-vous ?",quiz:{choices:["Localiser, corriger et refaire l’épreuve","Passer au vide","Charger une petite quantité","Augmenter la pression au jugé"],good:0,explain:"Une épreuve non concluante interdit l’étape suivante. La pression et le critère ne s’improvisent pas."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),
  screen({id:"quiz-vide",dossier:"controle",title:"Contrôle 3 · Vide",kicker:"Contrôle final",codes:["12.09"],level:"evaluer",required:true,text:"Après isolement de la pompe, la mesure remonte hors du critère prévu.",prompt:"Quelle décision protège le circuit ?",quiz:{choices:["Diagnostiquer fuite, humidité ou montage avant toute charge","Charger pour chasser l’air","Ignorer si la charge est faible","Réduire le temps de mesure"],good:0,explain:"La charge ne répare ni une fuite ni un séchage insuffisant. Le vide doit être concluant selon la documentation."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),
  screen({id:"quiz-charge",dossier:"controle",title:"Contrôle 4 · Charge",kicker:"Contrôle final",codes:["12.10"],level:"evaluer",required:true,text:"Quelle source donne la quantité de R-290 à introduire ?",prompt:"Choisissez la preuve.",quiz:{choices:["La plaque, la notice et le dossier de l’équipement exact","La mémoire du technicien","La charge d’un appareil voisin","La pression seule au démarrage"],good:0,explain:"La charge prévue appartient à l’équipement identifié et se suit par pesée selon la procédure."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),
  screen({id:"quiz-rapport",dossier:"controle",title:"Contrôle 5 · Fuite et rapport",kicker:"Contrôle final",codes:["12.11","12.12"],level:"evaluer",required:true,text:"Le détecteur hydrocarbures réagit sur l’assemblage remplacé.",prompt:"Quelle fin d’intervention est acceptable ?",quiz:{choices:["Suspendre, sécuriser, corriger, refaire les preuves et tracer","Mettre en service car le vide tenait","Effacer le résultat du rapport","Changer de détecteur jusqu’à obtenir zéro"],good:0,explain:"Une indication directe répétée suspend la remise en service. Le rapport garde l’anomalie, les actions et le nouveau résultat."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),
  screen({id:"bilan",dossier:"controle",title:"Le geste est une chaîne de permissions",kicker:"Bilan",level:"comprendre",text:"Ouvrir, éprouver, tirer au vide, charger, contrôler et tracer ne sont pas six gestes isolés. Chaque étape produit la preuve qui autorise la suivante. Au moindre signal contraire : STOP, retour au dernier point sûr, correction, puis nouvelle preuve.",prompt:"Le score porte sur cinq contrôles pédagogiques. La pratique reste encadrée sur le plateau.",render:()=>{const qs=screens.filter(s=>s.quiz),answered=Object.keys(quizAnswers).length,correct=qs.filter(s=>quizAnswers[s.id]===s.quiz.good).length;return `<div class="score"><div class="score-number">${correct}/${qs.length}</div><p><span class="branch-count">${wrongSeen.size} conséquence${wrongSeen.size>1?'s':''} explorée${wrongSeen.size>1?'s':''}</span></p><p>${answered<qs.length?`${qs.length-answered} contrôle${qs.length-answered>1?'s':''} encore sans réponse.`:correct>=4?"Ordre compris. À démontrer maintenant sur le poste dédié.":"Reprenez les points d’arrêt avant le plateau."}</p><button class="primary-button" id="restart" type="button">Revoir le contrôle</button></div>`},wire:()=>{$("#restart").addEventListener("click",()=>{Object.keys(quizAnswers).forEach(k=>delete quizAnswers[k]);screens.filter(s=>s.quiz).forEach(s=>completed.delete(s.id));goToId("quiz-ordre")})}})
];

function renderHome(){ $("#dossier-grid").innerHTML=dossiers.map((d,i)=>`<button class="dossier-button" type="button" data-dossier="${d.id}"><b>${i+1}</b><span>${esc(d.label)}<small>${esc(d.note)}</small></span></button>`).join("");$$('[data-dossier]').forEach(b=>b.addEventListener("click",()=>startCourse(b.dataset.dossier,1))) }
function startCourse(dossierId="preparer",screenNumber=1){extractMode=false;activeScreens=screens;const matches=screens.filter(s=>s.dossier===dossierId),target=matches[Math.max(0,Math.min(matches.length-1,screenNumber-1))]||screens[0];current=screens.indexOf(target);furthest=Math.max(furthest,current);showCourse();renderCurrent()}
function startExtract(ids){const found=ids.map(id=>screens.find(s=>s.id===id)).filter(Boolean);if(!found.length){showHome();showStatus("Extrait introuvable.");return}extractMode=true;activeScreens=found;current=0;furthest=found.length-1;showCourse();renderCurrent()}
function showCourse(){$("#home").hidden=true;$("#course-shell").hidden=false;$("#home-button").hidden=false;$("#exit-button").hidden=false;document.body.classList.add("course-running");$("#mode-badge").textContent=extractMode?"Mode extrait":"Cours complet";$("#rail-mode").textContent=extractMode?"EXTRAIT":"PARCOURS"}
function showHome(){stopSpeech();document.body.classList.remove("course-running");$("#home").hidden=false;$("#course-shell").hidden=true;$("#home-button").hidden=true;$("#exit-button").hidden=true;$("#mode-badge").textContent="Cours complet";history.replaceState(null,"","index.html")}
function currentItem(){return activeScreens[current]}
function renderCurrent(moveFocus=true){const item=currentItem();if(!item)return;stopSpeech(false);furthest=Math.max(furthest,current);$("#lesson-kicker").textContent=item.kicker;$("#lesson-title").textContent=item.title;$("#lesson-text").innerHTML=item.text;$("#action-prompt").textContent=item.prompt;$("#activity-zone").innerHTML=item.render?item.render():panel(item.title,route([{label:"Observer"},{label:"Décider"}]));if(item.wire)item.wire();renderReference(item);renderStepper(item);renderNavigation();updateUrl(item);if(moveFocus)$("#lesson-title").focus({preventScroll:true})}
function renderReference(item){$("#reference-box").innerHTML=`<strong>référentiel</strong> · ${item.codes.length?esc(item.codes.join(" · ")):"contexte"}<br>${esc(item.level)}`}
function renderStepper(item){const groups=extractMode?[{id:"extrait",label:"Extrait"}]:dossiers;$("#stepper").innerHTML=groups.map((d,i)=>{const indices=activeScreens.map((s,j)=>({s,j})).filter(x=>extractMode||x.s.dossier===d.id).map(x=>x.j),first=indices[0]??0,active=extractMode||item.dossier===d.id,done=indices.length&&Math.max(...indices)<furthest;return `<button class="step-button ${active?'active':''} ${done?'done':''}" type="button" data-step="${first}" ${active?'aria-current="step"':''}><b>${i+1}</b><span>${esc(d.label)}</span></button>`}).join("");$$('[data-step]').forEach(b=>b.addEventListener("click",()=>goTo(Number(b.dataset.step))));const total=activeScreens.length;$("#rail-progress").textContent=`${current+1} / ${total}`;$("#progress-bar").style.width=`${(current+1)/total*100}%`;$("#progress-copy").textContent=current===total-1?"Fin du parcours":`${total-current-1} écran${total-current-1>1?'s':''} à voir`}
function renderNavigation(){const item=currentItem();$("#prev-button").disabled=current===0;$("#next-button").disabled=Boolean(item.required&&!completed.has(item.id));$("#next-button").textContent=current===activeScreens.length-1?(extractMode?"Cours entier":"Retour au sommaire"):"Suivant →"}
function goTo(index){if(index<0||index>=activeScreens.length)return;current=index;renderCurrent()}
function goToId(id){let index=activeScreens.findIndex(s=>s.id===id);if(index>=0)return goTo(index);activeScreens=screens;extractMode=false;index=screens.findIndex(s=>s.id===id);if(index>=0){current=index;showCourse();renderCurrent()}}
function next(){const item=currentItem();if(item.required&&!completed.has(item.id)){showStatus("Prenez une décision avant de continuer.");return}if(current<activeScreens.length-1)goTo(current+1);else if(extractMode){const id=item.id;activeScreens=screens;extractMode=false;current=screens.findIndex(s=>s.id===id);showCourse();renderCurrent()}else showHome()}
function previous(){if(current>0)goTo(current-1)}
function updateUrl(item){const u=new URL(location.href);u.search="";if(extractMode)u.searchParams.set("extrait",activeScreens.map(s=>s.id).join(","));else{const same=activeScreens.filter(s=>s.dossier===item.dossier);u.searchParams.set("dossier",item.dossier);u.searchParams.set("ecran",String(same.indexOf(item)+1))}history.replaceState(null,"",u)}
async function copyCurrentLink(){const u=new URL(location.href);u.search="";u.searchParams.set("extrait",currentItem().id);try{await navigator.clipboard.writeText(u.href);showStatus("Lien de cet écran copié.")}catch(_){const t=document.createElement("textarea");t.value=u.href;document.body.append(t);t.select();document.execCommand("copy");t.remove();showStatus("Lien de cet écran copié.")}}
function showStatus(m){clearTimeout(statusTimer);$("#status-message").textContent=m;statusTimer=setTimeout(()=>$("#status-message").textContent="",2600)}
function speechSupported(){return"speechSynthesis"in window&&"SpeechSynthesisUtterance"in window}
function bestFrenchVoice(){const vs=speechSynthesis.getVoices();return vs.map(v=>{const l=(v.lang||"").toLowerCase(),n=(v.name||"").toLowerCase();return{v,s:(l==="fr-fr"?50:l.startsWith("fr")?25:0)+(/natural|naturel|neural|online|google|microsoft|denise|henri|julie|paul|hortense/.test(n)?12:0)}}).sort((a,b)=>b.s-a.s)[0]?.v||vs[0]||null}
function speakCurrent(){if(!speechSupported()){showStatus("La voix n’est pas disponible. Le texte reste complet.");return}stopSpeech(false);const item=currentItem(),token=++speechRun,u=new SpeechSynthesisUtterance(item.speak||`${item.title}. ${stripHtml(item.text)} ${item.prompt}`);u.lang="fr-FR";u.pitch=1;u.rate=voiceRates[rateIndex];const v=bestFrenchVoice();if(v)u.voice=v;u.onstart=()=>{if(token!==speechRun)return;speaking=true;paused=false;updateVoiceButtons()};u.onend=()=>{if(token!==speechRun)return;speaking=false;paused=false;updateVoiceButtons()};u.onerror=e=>{if(token!==speechRun||["canceled","interrupted"].includes(e.error))return;speaking=false;paused=false;updateVoiceButtons();showStatus("Lecture vocale indisponible.")};speechSynthesis.speak(u)}
function toggleSpeech(){if(!speechSupported())return showStatus("La voix n’est pas disponible.");if(speaking&&!paused){speechSynthesis.pause();paused=true;updateVoiceButtons()}else if(speaking&&paused){speechSynthesis.resume();paused=false;updateVoiceButtons()}else speakCurrent()}
function stopSpeech(){speechRun++;if(speechSupported())speechSynthesis.cancel();speaking=false;paused=false;updateVoiceButtons()}
function updateVoiceButtons(){const b=$("#listen");if(!b)return;b.innerHTML=paused?'<span aria-hidden="true">▶</span><span>Reprendre</span>':speaking?'<span aria-hidden="true">Ⅱ</span><span>Pause</span>':'<span aria-hidden="true">▶</span><span>Écouter</span>';$("#stop-voice").disabled=!speaking;$("#speed-value").textContent=voiceRates[rateIndex].toFixed(2).replace(".",",")+"×"}
function changeRate(d){rateIndex=Math.max(0,Math.min(voiceRates.length-1,rateIndex+d));saveRate();updateVoiceButtons();if(speaking||paused)speakCurrent()}
function buildPrintBook(){const qs=screens.filter(s=>s.quiz);$("#print-book").innerHTML=`<header class="print-title"><h1>Intervenir sur un circuit hydrocarbure</h1><p>Fiche g12b · 27 écrans · ${qs.length} contrôles · arrêté du 21 novembre 2025.</p><p><strong>Point de départ :</strong> zone autorisée, fluide récupéré, circuit rempli d’azote et installation consignée selon la procédure.</p></header>`+screens.map((item,i)=>`<article class="print-screen"><h2>${i+1}. ${esc(item.title)}</h2><p>${item.text}</p>${item.prompt?`<h3>Décision ou action</h3><p>${esc(item.prompt)}</p>`:""}${item.branch?`<div class="print-branch"><strong>Point sûr :</strong> ${esc(item.branch.choices[item.branch.good].title)} — ${esc(item.branch.choices[item.branch.good].effect)}<br><strong>Conséquence à étudier :</strong> ${item.branch.choices.filter((_,j)=>j!==item.branch.good).map(c=>esc(c.effect)).join(" ")}</div>`:""}${item.quiz?`<div class="print-answer"><strong>Correction :</strong> ${esc(item.quiz.choices[item.quiz.good])}. ${esc(item.quiz.explain)}</div>`:""}<p class="print-codes">Référentiel · ${item.codes.length?esc(item.codes.join(" · ")):"contexte"}</p></article>`).join("")}
function handleInitialUrl(){const p=new URLSearchParams(location.search),x=p.get("extrait");if(x)return startExtract(x.split(",").map(s=>s.trim()).filter(Boolean));const d=p.get("dossier");if(d)return startCourse(d,Number(p.get("ecran"))||1);showHome()}
function bindGlobalEvents(){$("#start-button").addEventListener("click",()=>startCourse());$("#home-button").addEventListener("click",showHome);$("#exit-button").addEventListener("click",showHome);$("#prev-button").addEventListener("click",previous);$("#next-button").addEventListener("click",next);$("#copy-link").addEventListener("click",copyCurrentLink);$("#listen").addEventListener("click",toggleSpeech);$("#stop-voice").addEventListener("click",stopSpeech);$("#slower").addEventListener("click",()=>changeRate(-1));$("#faster").addEventListener("click",()=>changeRate(1));addEventListener("keydown",e=>{const tag=document.activeElement?.tagName;if(["INPUT","TEXTAREA","SELECT","BUTTON"].includes(tag))return;if(e.key==="ArrowRight"){e.preventDefault();next()}else if(e.key==="ArrowLeft"){e.preventDefault();previous()}else if(e.key===" "){e.preventDefault();toggleSpeech()}else if(e.key==="Escape")showHome()});addEventListener("beforeunload",stopSpeech);document.addEventListener("visibilitychange",()=>{if(document.hidden)stopSpeech()})}

renderHome();buildPrintBook();bindGlobalEvents();updateVoiceButtons();handleInitialUrl();
