(() => {
  "use strict";
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><marker id="arr-hot-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#c9451a"/></marker><marker id="arr-cool-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#3d7fca"/></marker></defs>${body}</svg>`;
  const base=shell("dec-base","Boucles primaire et secondaire","Le primaire est à gauche avec son circulateur. Le secondaire est à droite avec son circulateur. Un séparateur vertical commun relie départs en haut et retours en bas.",`<rect x="310" y="70" width="100" height="280" rx="38" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/><path d="M55 125H310M310 295H55M410 125H665M665 295H410" stroke="#1b3a63" stroke-width="12"/><image href="assets/pompe_debit_variable.svg" x="105" y="85" width="85" height="85"/><image href="assets/pompe_debit_variable.svg" x="530" y="85" width="85" height="85"/><path d="M180 125H275" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-hot-dec-base)"/><path d="M540 125H445" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-hot-dec-base)"/><path d="M275 295H180" stroke="#3d7fca" stroke-width="6" marker-end="url(#arr-cool-dec-base)"/><path d="M445 295H540" stroke="#3d7fca" stroke-width="6" marker-end="url(#arr-cool-dec-base)"/><text x="150" y="55" text-anchor="middle" font-size="20" font-weight="700">PRIMAIRE · Qp</text><text x="570" y="55" text-anchor="middle" font-size="20" font-weight="700">SECONDAIRE · Qs</text><text x="360" y="205" text-anchor="middle" font-size="16" font-weight="700">ZONE COMMUNE</text>`);
  function calc(values={qp:2,qs:2}){
    const qp=Number(values.qp),qs=Number(values.qs),tps=60,trs=40;
    if(Math.abs(qp-qs)<.001)return{qp,qs,regime:"Qp = Qs",direction:"aucun transfert vertical net",internal:0,tss:tps,trp:trs};
    if(qp>qs)return{qp,qs,regime:"Qp > Qs",direction:"surplus primaire vers le bas",internal:qp-qs,tss:tps,trp:(qs*trs+(qp-qs)*tps)/qp};
    return{qp,qs,regime:"Qp < Qs",direction:"retour secondaire recyclé vers le haut",internal:qs-qp,tss:(qp*tps+(qs-qp)*trs)/qs,trp:trs};
  }
  const regimes=(values={qp:2,qs:2})=>{
    const s=calc(values),down=s.qp>s.qs,up=s.qp<s.qs,vertical=down?`<path d="M360 165V255" stroke="#c9451a" stroke-width="10" stroke-dasharray="12 7" marker-end="url(#arr-hot-dec-reg)"/>`:up?`<path d="M360 255V165" stroke="#3d7fca" stroke-width="10" stroke-dasharray="12 7" marker-end="url(#arr-cool-dec-reg)"/>`:`<path d="M330 210H390" stroke="#1e7e54" stroke-width="6" stroke-dasharray="4 5"/><text x="360" y="240" text-anchor="middle" font-size="13">pas de transfert net</text>`;
    return shell("dec-reg","Trois régimes de débit",`Le débit primaire vaut ${s.qp} mètres cubes par heure et le débit secondaire ${s.qs}. Le régime est ${s.regime}. Le transfert interne est ${s.direction}. Températures pédagogiques : primaire départ 60 degrés Celsius, secondaire retour 40 degrés Celsius.`,`<rect x="315" y="75" width="90" height="270" rx="35" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/><path d="M55 135H315M315 285H55M405 135H665M665 285H405" stroke="#1b3a63" stroke-width="11"/><path d="M135 135H275" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-hot-dec-reg)"/><path d="M585 135H445" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-hot-dec-reg)"/><path d="M275 285H135" stroke="#3d7fca" stroke-width="6" marker-end="url(#arr-cool-dec-reg)"/><path d="M445 285H585" stroke="#3d7fca" stroke-width="6" marker-end="url(#arr-cool-dec-reg)"/>${vertical}<text x="150" y="80" text-anchor="middle" font-size="18" font-weight="700">Qp = ${s.qp.toLocaleString("fr-FR")} m³/h</text><text x="570" y="80" text-anchor="middle" font-size="18" font-weight="700">Qs = ${s.qs.toLocaleString("fr-FR")} m³/h</text><text x="360" y="40" text-anchor="middle" font-size="22" font-weight="700">${s.regime}</text><rect x="90" y="330" width="540" height="70" rx="16" fill="#fff4e0" stroke="#b06a00" stroke-width="3" stroke-dasharray="5 4"/><text x="360" y="357" text-anchor="middle" font-size="15" font-weight="700">TRANSFERT INTERNE : ${s.internal.toLocaleString("fr-FR")} m³/h · ${s.direction}</text><text x="360" y="383" text-anchor="middle" font-size="14">T départ secondaire = ${s.tss.toFixed(1).replace(".",",")} °C · T retour primaire = ${s.trp.toFixed(1).replace(".",",")} °C</text>`);
  };
  const convention=shell("dec-conv","Convention et mélange calculé","Le schéma montre le mélange de l’exemple : un mètre cube par heure à 60 degrés venu du primaire rejoint un mètre cube par heure à 40 degrés recyclé du retour secondaire. Les deux flux entrent dans une zone de mélange et ressortent ensemble : deux mètres cubes par heure à 50 degrés. La convention est affichée : même eau, régime permanent, pertes négligées.",`<rect x="50" y="42" width="620" height="120" rx="18" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="360" y="76" text-anchor="middle" font-size="19" font-weight="700">CONVENTION AFFICHÉE</text><text x="360" y="106" text-anchor="middle" font-size="15">Tpd = 60 °C · Tsr = 40 °C · même eau · régime permanent · pertes négligées</text><text x="360" y="136" text-anchor="middle" font-size="15">Si Qp &lt; Qs : Tsd = [Qp × Tpd + (Qs − Qp) × Tsr] / Qs</text><path d="M70 245H265" stroke="#c9451a" stroke-width="14" marker-end="url(#arr-hot-dec-conv)"/><text x="165" y="222" text-anchor="middle" font-size="15" font-weight="700">Qp = 1 m³/h · 60 °C</text><path d="M70 330H265" stroke="#3d7fca" stroke-width="14" stroke-dasharray="14 8" marker-end="url(#arr-cool-dec-conv)"/><text x="165" y="365" text-anchor="middle" font-size="15" font-weight="700">recyclé = 1 m³/h · 40 °C</text><rect x="280" y="210" width="150" height="150" rx="20" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="6 5"/><text x="355" y="290" text-anchor="middle" font-size="16" font-weight="700">MÉLANGE</text><path d="M430 285H645" stroke="#1e7e54" stroke-width="26" marker-end="url(#arr-dec-conv)"/><text x="540" y="250" text-anchor="middle" font-size="15" font-weight="700">Qs = 2 m³/h · Tsd = 50,0 °C</text><text x="360" y="400" text-anchor="middle" font-size="15">Tsd = [1 × 60 + 1 × 40] / 2 = 50,0 °C · l’épaisseur des flèches suit le débit</text>`);
  const regimeMap=shell("dec-map","Sens du transfert selon les débits","Trois colonnes indiquent égalité sans transfert net, primaire supérieur avec transfert descendant et primaire inférieur avec transfert montant.",`${[[55,"Qp = Qs","NET = 0","M120 155V270"],[270,"Qp > Qs","VERS LE BAS","M335 155V270"],[485,"Qp < Qs","VERS LE HAUT","M550 270V155"]].map(([x,a,b,p],i)=>`<rect x="${x}" y="70" width="180" height="285" rx="20" fill="#fffdf8" stroke="${i===0?"#1e7e54":i===1?"#c9451a":"#3d7fca"}" stroke-width="${i===0?5:4}" stroke-dasharray="${i===0?"0":i===1?"10 6":"4 6"}"/><text x="${x+90}" y="112" text-anchor="middle" font-size="19" font-weight="700">${a}</text><path d="${p}" stroke="${i===0?"#1e7e54":i===1?"#c9451a":"#3d7fca"}" stroke-width="9" ${i===0?'stroke-dasharray="5 6"':`marker-end="url(#${i===1?"arr-hot":"arr-cool"}-dec-map)"`}/><text x="${x+90}" y="320" text-anchor="middle" font-size="14" font-weight="700">${b}</text>`).join("")}`);
  const method=shell("dec-method","Démarche de lecture du découplage","Cinq cartes : relever Qp et Qs, comparer, tracer le transfert, appliquer le bilan avec convention, conclure avec limites.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["RELEVER Qp / Qs","COMPARER","TRACER LE FLUX","CALCULER","CONCLURE"].map((t,i)=>`<rect x="${15+i*142}" y="150" width="125" height="110" rx="15"/><text x="${77+i*142}" y="194" text-anchor="middle" font-size="13" font-weight="700">${t}</text><text x="${77+i*142}" y="228" text-anchor="middle" font-size="12">${i+1}</text>`).join("")}</g>${[0,1,2,3].map(i=>`<path d="M${140+i*142} 205H${155+i*142}" stroke="#c9451a" stroke-width="5" marker-end="url(#arr-dec-method)"/>`).join("")}`);

  window.STATION_CONFIG={code:"M5",id:"decouplage",title:"Découplage — Trois régimes de débit",next:"poursuivre vers le diagnostic",levels:{CAP:{objective:"Reconnaître les deux circuits et suivre le sens de l’eau.",assessment:"nommer primaire, secondaire et suivre le sens"},TP:{objective:"Suivre les flux primaire, secondaire et interne dans trois régimes.",assessment:"lire Qp, Qs, le sens du transfert et rendre compte"},BTS:{objective:"Établir les bilans de débit et les températures de mélange avec une convention explicite.",assessment:"calculer, comparer les régimes et justifier les hypothèses du modèle"}},steps:[
    {short:"Repérer",kicker:"observer",title:"Deux circuits, une zone commune",text:"Chaque boucle garde son circulateur. Les débits peuvent donc différer.",cap:"Montre le circuit primaire et le circuit secondaire.",tp:"Repère primaire, secondaire, départ et retour.",bts:"Définis la frontière de bilan dans la zone commune.",scene:base,equivalent:"Le primaire est à gauche, le secondaire à droite, reliés par un séparateur vertical entre départs et retours.",action:{type:"choice",prompt:"Quelle grandeur comparer d’abord ?",options:[{label:"Qprimaire et Qsecondaire"},{label:"La couleur des tuyaux"},{label:"La marque des circulateurs"},{label:"Une température isolée"}],correct:0,explain:"La différence Qp − Qs commande le sens du transfert interne dans ce modèle."}},
    {short:"Débits",kicker:"manipuler",title:"Fais varier Qp et Qs",text:"Les deux curseurs utilisent des données pédagogiques. Observe le régime, la flèche interne et les températures calculées.",cap:"Lis les deux débits affichés sur l’écran.",tp:"Nommer le régime et le sens du transfert.",bts:"Contrôler le bilan de débit et le mélange calculé.",scene:regimes,equivalent:(v)=>{const s=calc(v);return`Q primaire ${s.qp} m³/h, Q secondaire ${s.qs} m³/h : ${s.regime}; ${s.direction}. T départ secondaire ${s.tss.toFixed(1)} °C et retour primaire ${s.trp.toFixed(1)} °C.`;},action:{type:"dual-range",prompt:"Déplace les deux débits et observe les trois régimes.",controls:[{id:"qp",label:"Débit primaire Qp",min:.5,max:3.5,step:.5,value:2,unit:"m³/h"},{id:"qs",label:"Débit secondaire Qs",min:.5,max:3.5,step:.5,value:2,unit:"m³/h"}],evaluate:(v)=>{const s=calc(v);return{observation:`${s.regime} : ${s.direction}. Transfert interne ${s.internal.toLocaleString("fr-FR")} m³/h.`,kind:s.internal===0?"correct":"info"};}}},
    {short:"Sens",kicker:"interpréter",title:"Trois régimes, trois transferts",text:"Le mot, le trait et la flèche doublent la couleur.",cap:"Repère le sens de la flèche, en haut ou en bas.",tp:"Associe comparaison et sens.",bts:"Relie le sens au bilan de masse de chaque boucle.",scene:regimeMap,equivalent:"Qp égal Qs donne zéro transfert net; Qp supérieur donne un transfert vers le bas; Qp inférieur recycle le retour vers le haut.",action:{type:"match",prompt:"Associe chaque régime à son transfert interne.",options:["Aucun transfert net","Vers le bas","Vers le haut"],items:[{label:"Qp = Qs",answer:0},{label:"Qp > Qs",answer:1},{label:"Qp < Qs",answer:2}],explain:"Le sens conserve les bilans : le surplus ou le déficit circule dans la zone commune."}},
    {short:"Mélange",kicker:"calculer",title:"Calculer avec une convention affichée",text:"Le calcul n’est valable que pour les données et hypothèses écrites.",cap:"Repère les deux températures données sur le schéma.",tp:"Lis les données et vérifie l’unité de température.",bts:"Applique le bilan de mélange et cite ses hypothèses.",scene:convention,equivalent:"Pour Qp 1 et Qs 2, avec T primaire départ 60 °C et T secondaire retour 40 °C, le départ secondaire mélangé vaut 50,0 °C dans le modèle.",action:{type:"choice",prompt:"Quel résultat donne l’exemple Qp = 1 et Qs = 2 ?",options:[{label:"T départ secondaire = 50,0 °C"},{label:"T départ secondaire = 100 °C"},{label:"T retour primaire = 60 °C par défaut"},{label:"Aucun mélange n’est possible"}],correct:0,explain:"Le secondaire reçoit une part primaire à 60 °C et une part recyclée à 40 °C : moyenne pondérée 50,0 °C."}},
    {short:"Conclure",kicker:"rendre compte",title:"Du relevé à la limite",text:"Ordonne la lecture avant de décider si le fonctionnement correspond au dossier.",cap:"Relève les débits avant de conclure.",tp:"Rends compte du régime observé.",bts:"Justifie le bilan et ses limites.",scene:method,equivalent:"La démarche relève Qp et Qs, compare, trace le transfert, calcule avec convention puis conclut.",action:{type:"sequence",prompt:"Place la démarche dans l’ordre.",items:["Relever Qp et Qs","Comparer les débits","Tracer le transfert interne","Calculer avec la convention","Conclure avec les limites"],correctOrder:[0,1,2,3,4],explain:"Un calcul de mélange sans débits, sens et convention explicites n’est pas vérifiable."}}
  ],quiz:[
    {context:"Qp = 2,0 m³/h et Qs = 2,0 m³/h.",question:"Quel transfert vertical net indique le modèle ?",options:["0 m³/h","2 m³/h vers le bas","2 m³/h vers le haut","4 m³/h"],correct:0,explain:"Les deux débits sont égaux."},
    {context:"Qp = 3,0 m³/h et Qs = 2,0 m³/h.",question:"Où va le surplus primaire ?",options:["Vers le bas, du départ primaire au retour primaire","Vers le haut","Il disparaît","Dans le circulateur secondaire uniquement"],correct:0,explain:"Le surplus de 1,0 m³/h recircule vers le retour primaire dans ce schéma."},
    {context:"Qp = 1,0 m³/h, Qs = 2,0 m³/h, Tpd = 60 °C et Tsr = 40 °C.",question:"Quelle température de départ secondaire calcule le modèle ?",options:["50,0 °C","40,0 °C","60,0 °C","20,0 °C"],correct:0,explain:"Le mélange porte sur deux parts égales à 60 °C et 40 °C."},
    {context:"Un calcul de mélange est présenté sans convention.",question:"Quelle décision est juste ?",options:["Demander débits, sens, températures et hypothèses","Accepter le résultat","Choisir la valeur la plus chaude","Conclure à une panne"],correct:0,explain:"Un bilan doit être reproductible et limité à ses hypothèses."}
  ],summaryScene:regimes({qp:1,qs:2}),summaryEquivalent:"Synthèse : Qp inférieur à Qs recycle une partie du retour secondaire vers le départ secondaire; les températures sont une moyenne pondérée selon la convention affichée."};
})();
