window.OIL_MODULE = {
  id: "reservoir-huile-pedagogique",
  title: "Le réservoir d’huile",
  subtitle: "LE CIRCUIT D’HUILE · STATION 8",
  codes: ["1.05", "6.05"],
  voix: true,
  nextStep: "Poursuivre avec le clapet différentiel : le réservoir doit rester à une pression qui permet l’alimentation des régulateurs sans transmettre directement la pression de refoulement.",
  nextUrl: "../clapet-differentiel-huile-pedagogique/index.html",
  nextLabel: "Station 9 · Le clapet différentiel d’huile",
  summaryVisual: { kind: "reservoirLevels", label: "Réservoir d’huile avec voyants haut et bas, entrée d’huile, sortie vers régulateurs et branche de pression" },
  lessons: [
    { id: "rappel", short: "Rappel", kicker: "Station 1 · Retour spiralé", recall: true, title: "Le séparateur récupère ; le réservoir rend disponible", lead: "Dans une centrale, l’huile séparée n’est pas envoyée au hasard vers le premier compresseur.", details: ["Elle rejoint une réserve commune placée entre le séparateur et les régulateurs de niveau.", "Le réservoir absorbe les variations d’entraînement et de retour entre plusieurs compresseurs."], box: { type: "key", text: "Séparer et stocker sont deux fonctions différentes." }, visual: { kind: "active", title: "Reprendre la chaîne", label: "Séparateur, réservoir puis distribution vers les régulateurs" } },
    { id: "fonction", short: "Fonction", kicker: "Station 2 · Réserve tampon", title: "Le « bouteillon » compense les variations", lead: "La quantité d’huile qui revient n’est pas identique à chaque instant.", details: ["Le réservoir reçoit l’huile du séparateur et constitue un volume tampon avant les carters.", "Il favorise aussi le dégazage d’une partie du fluide dissous avant la distribution basse pression."], box: { type: "warning", text: "Ne pas confondre réservoir d’huile et réservoir de liquide : contenu, raccordements et fonction diffèrent." }, visual: { kind: "receiver", title: "Stocker sans décider du niveau", label: "Réservoir vertical entre séparateur et régulateurs" } },
    { id: "raccordements", short: "Raccorder", kicker: "Station 3 · Chemins", title: "Chaque raccordement possède une mission", lead: "L’huile entre depuis le séparateur et ressort vers la ligne d’alimentation des régulateurs.", details: ["La partie haute peut porter une branche de pression ou de dégazage vers l’aspiration, selon l’architecture.", "Vannes, prises de pression et voyants servent à isoler, mesurer et suivre la réserve conformément à la notice."], box: { type: "exam", text: "Savoir montrer entrée d’huile, sortie d’huile et branche de pression sur le schéma." }, visual: { kind: "reservoirLevels", title: "Lire les raccordements", label: "Entrée d’huile, sortie vers régulateurs, voyants et ligne de pression" } },
    { id: "pression", short: "Pression", kicker: "Station 4 · Alimentation", title: "Une différence de pression fait circuler l’huile", lead: "L’huile ne quitte le réservoir que si la pression disponible dépasse celle du carter et les pertes de charge.", details: ["Cette différence peut provenir d’une hauteur prescrite ou d’une branche de pression contrôlée par un clapet différentiel.", "La solution et la valeur utile dépendent du montage, des pressions d’aspiration et des régulateurs installés."], box: { type: "warning", text: "Trop peu de différence : pas d’alimentation. Trop de différence : régulation perturbée et admission brutale." }, visual: { kind: "differential", title: "Comprendre la force motrice", label: "Pression du réservoir comparée à la pression d’aspiration et du carter" } },
    { id: "niveau", short: "Niveau", kicker: "Station 5 · Voyants", title: "Les voyants montrent une réserve, pas un verdict immédiat", lead: "Le niveau du réservoir varie avec les régimes, les dégivrages et le retour progressif de l’huile.", details: ["Observer les voyants sur une durée suffisante et noter les compresseurs actifs.", "Les limites d’ajout et de vidange se prennent dans la notice du réservoir et dans la procédure de mise en service."], box: { type: "key", text: "Lire haut, bas et évolution ; ne jamais conclure sur une seule photographie du niveau." }, visual: { kind: "reservoirLevels", title: "Suivre la réserve dans le temps", label: "Voyant haut, voyant bas et niveau d’huile variable" } },
    { id: "mise-en-service", short: "Démarrer", kicker: "Station 6 · Mise en service", title: "La première charge se fait avec l’huile approuvée", lead: "Le réservoir neuf est préparé selon la documentation du système.", details: ["Employer la même référence d’huile approuvée que celle des compresseurs et respecter la procédure de remplissage.", "Durant les premiers régimes, surveiller le retour avant tout nouvel ajout : l’huile répartie dans l’installation peut revenir progressivement."], box: { type: "exam", text: "Ajouter sans attendre le retour peut conduire à un excès lorsque l’huile piégée revient." }, visual: { kind: "timeline", title: "Observer la stabilisation", label: "Mise en service, retour progressif, charge variable et niveau stabilisé" } },
    { id: "securite", short: "Intervenir", kicker: "Station 7 · Étanchéité", title: "Le réservoir est un appareil sous pression", lead: "Voyants, vannes et raccords sont autant de points potentiels de fuite.", details: ["Avant toute intervention : consignation, isolement, contrôle de pression et procédure adaptée au fluide.", "Après un démontage, remplacer les joints prévus et appliquer le couple prescrit par le fabricant."], box: { type: "warning", text: "Un voyant n’est jamais démonté sur un réservoir sous pression." }, visual: { kind: "receiver", title: "Repérer les points de contrôle", label: "Réservoir avec vannes, voyants, raccord supérieur et sortie basse" } },
    { id: "diagnostic", short: "Diagnostiquer", kicker: "Station 8 · Décision", title: "Un réservoir vide ou plein raconte l’état de toute la chaîne", lead: "Un niveau durablement bas peut révéler un manque de séparation, une fuite ou une huile retenue dans le circuit.", details: ["Un niveau trop haut peut signaler un retour massif après dégivrage, un surremplissage ou des carters qui n’acceptent plus l’huile.", "Recouper niveaux de carter, pression du réservoir, état des vannes, filtres et régulateurs avant d’agir."], box: { type: "key", text: "Le réservoir est un observatoire du bilan d’huile, pas seulement un récipient." }, visual: { kind: "diagnostic", title: "Relier réserve et carters", label: "Diagnostic croisé du séparateur, du réservoir et des régulateurs" } }
  ],
  quiz: [
    { prompt: "Où se place le réservoir d’huile ?", options: ["Entre le séparateur et les régulateurs", "Entre le détendeur et l’évaporateur", "Entre le condenseur et la ligne liquide"], correct: 0, why: "Il reçoit l’huile séparée puis alimente les régulateurs de niveau.", code: "1.05" },
    { prompt: "Pourquoi est-il appelé réserve tampon ?", options: ["Il refroidit l’huile avant son retour au carter", "Il compense les écarts de départ et de retour", "Il détend le fluide avant l’évaporateur"], correct: 1, why: "Le départ et le retour d’huile varient dans le temps.", code: "1.05" },
    { prompt: "En quoi le réservoir d’huile diffère-t-il d’une bouteille liquide ?", options: ["Par sa fonction et ses raccordements", "Il n’en diffère pas : c’est le même organe", "Par sa seule position, verticale au sol"], correct: 0, why: "L’un gère l’huile ; l’autre stocke du fluide frigorigène liquide.", code: "1.05" },
    { prompt: "Qu’est-ce qui fait circuler l’huile vers le carter ?", options: ["La seule gravité, réservoir en hauteur", "Le débit du ventilateur de condenseur", "Une différence de pression suffisante"], correct: 2, why: "La pression disponible doit vaincre celle du carter et les pertes de charge.", code: "1.05 · 6.05" },
    { prompt: "Comment interpréter les deux voyants ?", options: ["Comme un feu vert et rouge universel", "Avec l’évolution, le régime et la notice", "En comparant au carter d’à côté"], correct: 1, why: "Le niveau varie ; les limites sont celles du système réel.", code: "6.05" },
    { prompt: "Quelle huile utiliser au remplissage ?", options: ["Une huile de même nombre ISO VG", "Celle qui reste ouverte dans l’atelier", "La référence approuvée du compresseur"], correct: 2, why: "La compatibilité fluide-compresseur-huile doit être respectée.", code: "1.05" },
    { prompt: "Avant de démonter un voyant, que faut-il faire ?", options: ["Consigner, isoler, vérifier l’absence de pression", "Attendre l’arrêt du compresseur, puis dévisser", "Mettre le réservoir côté refoulement"], correct: 0, why: "Le réservoir est sous pression et doit être sécurisé selon la procédure.", code: "1.05" },
    { prompt: "Le réservoir reste plein alors qu’un carter est bas. Que contrôler ?", options: ["Le séparateur d’huile, en priorité", "Pression, vannes, filtre et régulateur", "La température extérieure du local"], correct: 1, why: "L’huile est disponible, mais un maillon de la distribution peut l’empêcher d’atteindre le carter.", code: "6.05" }
  ],
  sources: [
    { title: "Parker Sporlan — Oil Level Control System", url: "https://www.parker.com/content/dam/Parker-com/Literature/Sporlan/Sporlan-pdf-files/Sporlan-pdf-110/SD-129_-Oil-Level-Control-System-Installation.pdf", use: "réservoir, voyants, différentiel et mise en service" },
    { title: "BITZER — Parallel compounding with oil level controllers", url: "https://www.bitzer.de/shared_media/html/kt-600/en-GB/313846411313848587.html", use: "réservoir tampon et architectures basse/haute pression" },
    { title: "Légifrance — Attestation d’aptitude fluides", url: "https://www.legifrance.gouv.fr/jorf/id/JORFSCTA000053004646", use: "compétences 1.05 et 6.05" }
  ]
};
