window.OIL_MODULE = {
  id: "diagnostic-circuit-huile",
  title: "Diagnostic : lire l’architecture et le retour",
  subtitle: "LE CIRCUIT D’HUILE · STATION 16",
  codes: ["1.05", "6.05", "9.07"],
  voix: true,
  nextStep: "Poursuivre avec la seconde moitié du diagnostic : le différentiel, la ligne d’huile, le croisement des indices et la conclusion.",
  nextUrl: "../diagnostic-circuit-huile-conclure/index.html",
  nextLabel: "Station 17 · Diagnostic : pression, distribution et conclusion",
  summaryVisual: { kind: "diagnostic", label: "Synthèse : observer, suivre l’huile, mesurer les pressions, interpréter puis décider" },
  lessons: [
    { id: "lire",
      narration: "Un diagnostic d'huile commence toujours par identifier l'architecture. Retour naturel seul, retour direct au compresseur, réservoir en basse pression, réserve en haute pression : ces quatre montages n'emploient pas les mêmes organes, et une même mesure n'y a pas le même sens. Une pression de réservoir n'existe pas dans une installation à retour naturel. Un clapet différentiel n'a pas de rôle dans un retour haute pression. Nommez donc l'architecture avant d'interpréter la moindre mesure — sans quoi vous chercherez un organe qui n'existe pas.", short: "Schéma", kicker: "Station 1 · Vue d’ensemble", recall: true, title: "Le diagnostic commence par identifier l’architecture", lead: "Retour naturel, retour direct, réservoir basse pression ou réserve haute pression n’emploient pas les mêmes organes.", details: ["Repérer compresseurs actifs, séparateur, réservoir, branche de pression, filtre et régulateurs.", "Tracer ensuite deux chemins distincts : celui de l’huile liquide et celui de la pression ou du dégazage."], box: { type: "key", text: "Nommer l’architecture avant d’interpréter une mesure." }, visual: { kind: "bpHp", title: "Comparer les architectures", label: "Circuit basse pression avec réservoir séparé et circuit haute pression avec régulateur compatible" } },
    { id: "symptome",
      narration: "Un niveau bas est un symptôme, jamais une panne complète. Le carter peut être bas pour quatre raisons très différentes : l'huile est partie et ne revient pas, elle est retenue quelque part dans le circuit, elle n'est pas séparée au refoulement, ou elle n'est pas distribuée depuis la réserve. Quatre causes, quatre traitements. Et voici la règle qui protège l'installation : n'ajoutez pas d'huile avant d'avoir cherché où se trouve celle qui manque au voyant. Si elle est simplement retenue dans un évaporateur, elle reviendra — et vous serez alors en excès.", short: "Symptôme", kicker: "Station 2 · Niveau carter", title: "Un niveau bas est un symptôme, jamais une panne complète", lead: "Le carter peut être bas parce que l’huile est partie, retenue, non séparée ou non distribuée.", details: ["Noter heure, durée, régime, compresseurs actifs et évolution du voyant.", "Rechercher aussi bruit, température, alarmes, traces de fuite et interventions récentes."], box: { type: "exam", text: "Ne pas ajouter d’huile avant d’avoir recherché où se trouve celle qui manque au voyant." }, visual: { kind: "observe", title: "Construire l’observation", label: "Voyant, temps, régime et tracé du circuit" } },
    { id: "naturel",
      narration: "Vérifiez d'abord le chemin naturel du retour, avant tout organe. C'est le fondement, et c'est souvent là que se trouve le vrai problème. Une huile retenue dans l'évaporateur ou dans une portion d'aspiration mal tracée n'atteindra jamais aucun organe de distribution — ni le séparateur, ni le réservoir, ni le régulateur. Reprenez donc la pente, les points bas, le siphon, la vitesse aux régimes minimal et maximal. Retenez la formule : le meilleur régulateur du monde ne videra pas une poche d'huile située à l'autre bout du circuit.", short: "Naturel", kicker: "Station 3 · Tuyauterie", title: "Vérifier d’abord le chemin naturel du retour", lead: "Une huile retenue dans l’évaporateur ou l’aspiration n’atteindra aucun organe de distribution.", details: ["Contrôler pentes, points bas, siphons, contre-siphons éventuels et colonne montante.", "Vérifier le fonctionnement à charge minimale, notamment la double colonne si elle existe."], box: { type: "key", text: "Le meilleur régulateur ne vide pas une poche d’huile située loin dans le circuit." }, visual: { kind: "natural", title: "Suivre l’aspiration", label: "Pente, siphon en pied, colonne et contre-siphon jusqu’au compresseur" } },
    { id: "separateur",
      narration: "Contrôlez ensuite que l'huile est bien collectée, puis effectivement évacuée. Deux conditions, et elles se vérifient séparément. Le séparateur doit recevoir la plage de débit pour laquelle il a été choisi — à charge très réduite, il peut ne plus séparer. Et il doit renvoyer l'huile sans laisser passer un flux continu de gaz : un retour bloqué ouvert enverrait du gaz chaud vers le carter. Observez la conduite de retour sur une séquence complète : elle doit raconter quelque chose de cohérent avec le régime en cours.", short: "Séparer", kicker: "Station 4 · Refoulement", title: "Contrôler que l’huile est collectée puis évacuée", lead: "Le séparateur doit recevoir la plage de débit prévue et renvoyer l’huile sans bipasse continu de gaz.", details: ["Observer niveaux, température et séquences de retour ; rechercher flotteur bloqué, pointeau, fuite ou mauvais raccordement.", "Recouper avec le niveau du réservoir et les carters : un seul indice ne suffit pas."], box: { type: "exam", text: "La conduite de retour doit raconter une séquence cohérente avec le régime." }, visual: { kind: "floatReturn", title: "Contrôler le retour par flotteur", label: "Huile collectée commandant un pointeau de retour" } },
    { id: "reservoir",
      narration: "Le réservoir, enfin, vous montre ce que toute la chaîne reçoit et distribue. Bas durablement : peu d'huile lui parvient, ou une fuite existe quelque part. Haut durablement : l'huile arrive bien, mais elle ne repart pas — la distribution est bloquée. Et voici la combinaison la plus parlante de toutes : un réservoir plein avec un carter bas. Elle vous oriente immédiatement vers la distribution — vanne, filtre, différentiel, régulateur — et non vers un manque global d'huile. Ajouter de l'huile dans cette situation ne ferait qu'aggraver le déséquilibre.", short: "Réserve", kicker: "Station 5 · Bilan", title: "Le réservoir montre ce que la chaîne reçoit et distribue", lead: "Bas durablement : peu d’huile arrive ou une fuite existe. Haut durablement : la distribution peut être bloquée.", details: ["Lire les voyants dans le temps et comparer aux niveaux des différents carters.", "Vérifier vannes, pression, branche de dégazage et cohérence avec les retours après changement de régime."], box: { type: "key", text: "Réservoir plein + carter bas oriente vers la distribution, pas vers un manque global d’huile." }, visual: { kind: "reservoirLevels", title: "Comparer réserve et carters", label: "Voyants haut et bas du réservoir reliés à la ligne de distribution" } }
  ],
  quiz: [
    { prompt: "Que faut-il identifier avant toute mesure ?", options: ["L’architecture du circuit d’huile", "Le niveau visible dans le carter", "La référence de l’huile en place"], correct: 0, why: "BP, HP, retour direct ou naturel ne se contrôlent pas de la même manière.", code: "1.05" },
    { prompt: "Que peut recouvrir un niveau d’huile bas ?", options: ["Un régulateur défaillant, dans tous les cas", "Un séparateur encrassé, dans tous les cas", "Rétention, perte, séparation ou distribution"], correct: 2, why: "L’huile peut être retenue, perdue, non séparée ou non distribuée.", code: "6.05" },
    { prompt: "Que contrôler dans le retour naturel ?", options: ["Pentes, siphons, montées et charge minimale", "Diamètre extérieur et isolation des tubes", "Température de condensation et sous-refroidissement"], correct: 0, why: "La géométrie et la vitesse conditionnent le transport de l’huile.", code: "6.05" },
    { prompt: "Réservoir plein et carter bas : où chercher ?", options: ["Dans l’évaporateur et son dégivrage", "Dans la distribution vers le carter", "Dans la bouteille liquide du circuit"], correct: 1, why: "L’huile est disponible dans la réserve mais n’atteint pas le carter.", code: "6.05" },
    { prompt: "Réservoir bas et plusieurs carters bas : quel axe ?", options: ["Une seule électrovanne restée fermée", "Le réglage du détendeur thermostatique", "Séparation, retour, fuite ou charge globale"], correct: 2, why: "Le manque concerne l’amont ou le bilan total.", code: "6.05 · 9.07" }
  ],
  sources: [
    { title: "BITZER — Causes for oil loss", url: "https://www.bitzer.de/shared_media/html/est-600/en-GB/345371019345395723.html", use: "diagnostic, vitesse, charge partielle et pertes d’huile" },
    { title: "BITZER — Parallel compounding with oil level controllers", url: "https://www.bitzer.de/shared_media/html/kt-600/en-GB/313846411313848587.html", use: "architectures et chaîne active" },
    { title: "Parker Sporlan — Oil Level Control System", url: "https://www.parker.com/content/dam/Parker-com/Literature/Sporlan/Sporlan-pdf-files/Sporlan-pdf-110/SD-129_-Oil-Level-Control-System-Installation.pdf", use: "méthode de diagnostic des contrôleurs et du réservoir" },
    { title: "Copeland — OM3/OM4/OM5 TraxOil Technical Information", url: "https://media.copeland.com/d8f801b5-15db-4430-bbda-b16b01022eae/OM3_OM4_OM5_TB_EN_0820_R08.pdf", use: "lecture des états et alarme électronique" },
    { title: "Légifrance — Attestation d’aptitude fluides", url: "https://www.legifrance.gouv.fr/jorf/id/JORFSCTA000053004646", use: "préparation aux compétences 1.05, 6.05 et 9.07" }
  ]
};
