(() => {
  "use strict";
  const stations=[
    {id:"mesurer",title:"Mesurer",hint:"Point, instrument, unité",status:"Correspondance P",interchange:true},
    {id:"releves",title:"Relevés",hint:"Preuve avant / après",status:"QA technique"},
    {id:"equilibrage",title:"Équilibrage",hint:"Réglage contrôlé",status:"Correspondance D · QA technique",interchange:true},
    {id:"tampon",title:"Volume tampon",hint:"Rôle selon raccordement",status:"QA technique"},
    {id:"decouplage",title:"Découplage",hint:"Trois régimes de débit",status:"QA technique"},
    {id:"diagnostic",title:"Diagnostic",hint:"Hypothèse à vérifier",status:"QA technique"},
    {id:"mission",title:"Mission réseau",hint:"Décider et rendre compte",status:"QA technique"}
  ];
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><pattern id="warm-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#c9451a" stroke-width="2"/></pattern><pattern id="cool-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="1.5" fill="#3d7fca"/></pattern></defs>${body}</svg>`;
  const measureScene=shell("mtest-measure","Choisir point, instrument et unité","Un débitmètre est proposé sur la branche B, une sonde sur un mur et un manomètre sans point. Seul le débitmètre sur B avec mètre cube par heure répond au besoin de débit local.",`<path d="M70 205H650" stroke="#1b3a63" stroke-width="13"/><rect x="85" y="85" width="170" height="90" rx="16" fill="#fffdf8" stroke="#1e7e54" stroke-width="5"/><text x="170" y="120" text-anchor="middle" font-size="16" font-weight="700">DÉBITMÈTRE</text><text x="170" y="150" text-anchor="middle" font-size="14">branche B · m³/h</text><rect x="275" y="85" width="170" height="90" rx="16" fill="#fffdf8" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="360" y="120" text-anchor="middle" font-size="16" font-weight="700">SONDE</text><text x="360" y="150" text-anchor="middle" font-size="14">mur · °C</text><rect x="465" y="85" width="170" height="90" rx="16" fill="#fffdf8" stroke="#c0392b" stroke-width="4" stroke-dasharray="9 6"/><text x="550" y="120" text-anchor="middle" font-size="16" font-weight="700">MANOMÈTRE</text><text x="550" y="150" text-anchor="middle" font-size="14">point non indiqué</text><text x="360" y="265" text-anchor="middle" font-size="20" font-weight="700">BESOIN : DÉBIT DE LA BRANCHE B</text><path d="M170 175V200" stroke="#1e7e54" stroke-width="6" marker-end="url(#arr-mtest-measure)"/>`);
  const recordScene=shell("mtest-record","Comparer deux relevés dans les mêmes conditions","Avant et après indiquent branche B, mode de pompe constant, état stabilisé, débit et heure. Les valeurs sont des données pédagogiques.",`${[[40,"AVANT","08:40","0,8 m³/h"],[380,"APRÈS","09:05","1,0 m³/h"]].map(([x,t,h,q])=>`<rect x="${x}" y="75" width="300" height="270" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="${x+150}" y="115" text-anchor="middle" font-size="20" font-weight="700">${t}</text><text x="${x+25}" y="165" font-size="16">Branche B · ${h}</text><text x="${x+25}" y="210" font-size="16">Pompe : mode constant</text><text x="${x+25}" y="255" font-size="16">État : stabilisé</text><text x="${x+25}" y="305" font-size="20" font-weight="700">Q = ${q}</text>`).join("")}<path d="M340 210H378" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-mtest-record)"/>`);
  const balanceScene=shell("mtest-balance","Séquence de réglage à exploiter depuis Équilibrage","Cinq cartes montrent état initial, action unique, stabilisation, nouveau relevé et conclusion. La station Équilibrage appartient à la ligne D, est raccordée au statut QA technique et reste une correspondance en lecture seule.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["ÉTAT INITIAL","ACTION UNIQUE","STABILISER","NOUVEAU RELEVÉ","CONCLURE"].map((t,i)=>`<rect x="${15+i*142}" y="145" width="125" height="120" rx="16"/><text x="${77+i*142}" y="194" text-anchor="middle" font-size="12" font-weight="700">${t}</text><text x="${77+i*142}" y="230" text-anchor="middle" font-size="12">${i+1}</text>`).join("")}</g>${[0,1,2,3].map(i=>`<path d="M${140+i*142} 205H${155+i*142}" stroke="#c9451a" stroke-width="5" marker-end="url(#arr-mtest-balance)"/>`).join("")}<text x="360" y="320" text-anchor="middle" font-size="16" font-weight="700">CORRESPONDANCE D · QA TECHNIQUE</text>`);
  const tamponScene=shell("mtest-tampon","Trois raccordements de volume tampon","Trois schémas recomposés montrent série à deux piquages, quatre piquages avec deux circuits, et dérivation. Seul le deuxième dessine deux débits indépendants.",`${[[35,"SÉRIE",2],[265,"4 PIQUAGES",4],[495,"DÉRIVATION",3]].map(([x,t,n],i)=>`<rect x="${x}" y="65" width="190" height="290" rx="20" fill="#fffdf8" stroke="${i===1?"#1e7e54":"#1b3a63"}" stroke-width="${i===1?5:3}"/><rect x="${x+67}" y="120" width="56" height="155" rx="25" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/>${i===0?`<path d="M${x+10} 150H${x+67}M${x+123} 245H${x+180}" stroke="#1b3a63" stroke-width="8"/>`:i===1?`<path d="M${x+10} 150H${x+67}M${x+67} 245H${x+10}M${x+123} 150H${x+180}M${x+180} 245H${x+123}" stroke="#1b3a63" stroke-width="8"/>`:`<path d="M${x+10} 150H${x+180}M${x+95} 150V245" stroke="#1b3a63" stroke-width="8"/>`}<text x="${x+95}" y="100" text-anchor="middle" font-size="16" font-weight="700">${t}</text><text x="${x+95}" y="320" text-anchor="middle" font-size="13">${n} connexions dessinées</text>`).join("")}`);
  const roleScene=shell("mtest-role","Fonctions réelles du ballon","Une carte montre volume et inertie comme fonction visible, découplage à vérifier selon le raccordement et stratification non garantie.",`<rect x="55" y="75" width="180" height="270" rx="20" fill="#fffdf8" stroke="#1e7e54" stroke-width="5"/><text x="145" y="115" text-anchor="middle" font-size="17" font-weight="700">DÉMONTRÉ</text><text x="145" y="185" text-anchor="middle" font-size="16">volume sur le chemin</text><text x="145" y="225" text-anchor="middle" font-size="16">inertie possible</text><rect x="270" y="75" width="180" height="270" rx="20" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="360" y="115" text-anchor="middle" font-size="17" font-weight="700">À VÉRIFIER</text><text x="360" y="185" text-anchor="middle" font-size="16">volume utile</text><text x="360" y="225" text-anchor="middle" font-size="16">transferts internes</text><rect x="485" y="75" width="180" height="270" rx="20" fill="#fbe7e4" stroke="#c0392b" stroke-width="4" stroke-dasharray="9 6"/><text x="575" y="115" text-anchor="middle" font-size="17" font-weight="700">NON AUTOMATIQUE</text><text x="575" y="185" text-anchor="middle" font-size="16">découplage</text><text x="575" y="225" text-anchor="middle" font-size="16">stratification</text>`);
  const chainScene=shell("mtest-chain","Chaîne du diagnostic","Cinq cartes reliées dans l’ordre imposent mesures, interprétation, hypothèse, vérification et décision.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["MESURES","INTERPRÉTATION","HYPOTHÈSE","VÉRIFICATION","DÉCISION"].map((t,i)=>`<rect x="${15+i*142}" y="150" width="125" height="110" rx="15"/><text x="${77+i*142}" y="197" text-anchor="middle" font-size="12" font-weight="700">${t}</text><text x="${77+i*142}" y="228" text-anchor="middle" font-size="12">${i+1}</text>`).join("")}</g>${[0,1,2,3].map(i=>`<path d="M${140+i*142} 205H${155+i*142}" stroke="#c9451a" stroke-width="5" marker-end="url(#arr-mtest-chain)"/>`).join("")}`);
  const unitScene=shell("mtest-unit","Choix de l’instrument et de l’unité","Trois cartes associent débitmètre et mètre cube par heure, sondes de contact et degrés Celsius, manomètre différentiel et pascals ou unité adaptée au dossier.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${[[40,"DÉBITMÈTRE","m³/h","débit branche"],[270,"2 SONDES","°C et K","départ / retour"],[500,"MANOMÈTRE Δp","Pa ou unité dossier","points amont / aval"]].map(([x,a,b,c])=>`<rect x="${x}" y="75" width="180" height="270" rx="20"/><text x="${x+90}" y="120" text-anchor="middle" font-size="16" font-weight="700">${a}</text><text x="${x+90}" y="180" text-anchor="middle" font-size="24" font-weight="700">${b}</text><text x="${x+90}" y="235" text-anchor="middle" font-size="14">${c}</text><circle cx="${x+90}" cy="295" r="22" fill="#fffdf8" stroke="#3d7fca" stroke-width="5"/>`).join("")}</g>`);
  const mixScene=shell("mtest-mix","Calcul de mélange en découplage","Pour Q primaire 1 et Q secondaire 2, température primaire départ 60 degrés Celsius et secondaire retour 40 degrés Celsius, le départ secondaire vaut 50 degrés Celsius selon la moyenne pondérée affichée.",`<rect x="60" y="60" width="600" height="300" rx="22" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="360" y="105" text-anchor="middle" font-size="20" font-weight="700">DONNÉES PÉDAGOGIQUES</text><text x="360" y="155" text-anchor="middle" font-size="18">Qp = 1 m³/h · Qs = 2 m³/h</text><text x="360" y="195" text-anchor="middle" font-size="18">Tpd = 60 °C · Tsr = 40 °C</text><path d="M115 225H605" stroke="#1b3a63" stroke-width="2"/><text x="360" y="270" text-anchor="middle" font-size="19">Tsd = [1 × 60 + 1 × 40] / 2</text><text x="360" y="325" text-anchor="middle" font-size="28" font-weight="700">Tsd = 50,0 °C</text>`);
  const regimeScene=shell("mtest-regime","Cause et effet des trois régimes","Trois colonnes : égalité sans transfert vertical net, primaire supérieur avec transfert vers le bas, primaire inférieur avec recyclage vers le haut.",`${[[45,"Qp = Qs","NET = 0","M135 155V270"],[270,"Qp > Qs","VERS LE BAS","M360 155V270"],[495,"Qp < Qs","VERS LE HAUT","M585 270V155"]].map(([x,a,b,p],i)=>`<rect x="${x}" y="65" width="180" height="290" rx="20" fill="#fffdf8" stroke="${i===0?"#1e7e54":i===1?"#c9451a":"#3d7fca"}" stroke-width="4" stroke-dasharray="${i===0?"0":i===1?"10 6":"4 6"}"/><text x="${x+90}" y="110" text-anchor="middle" font-size="18" font-weight="700">${a}</text><path d="${p}" stroke="${i===0?"#1e7e54":i===1?"#c9451a":"#3d7fca"}" stroke-width="9" ${i===0?'stroke-dasharray="5 6"':`marker-end="url(#arr-mtest-regime)"`}/><text x="${x+90}" y="320" text-anchor="middle" font-size="14" font-weight="700">${b}</text>`).join("")}`);
  const contextScene=shell("mtest-context","Effet d’un contexte modifié","Deux comparaisons sont opposées. La première conserve point, mode et stabilisation. La seconde change le mode de pompe et ne permet pas d’attribuer l’écart au seul réglage.",`<rect x="35" y="70" width="300" height="285" rx="20" fill="#e3f5ec" stroke="#1e7e54" stroke-width="5"/><text x="185" y="112" text-anchor="middle" font-size="18" font-weight="700">COMPARAISON EXPLOITABLE</text><text x="75" y="170" font-size="16">même branche</text><text x="75" y="215" font-size="16">même mode de pompe</text><text x="75" y="260" font-size="16">deux états stabilisés</text><rect x="385" y="70" width="300" height="285" rx="20" fill="#fbe7e4" stroke="#c0392b" stroke-width="4" stroke-dasharray="9 6"/><text x="535" y="112" text-anchor="middle" font-size="18" font-weight="700">CONCLUSION FRAGILE</text><text x="425" y="170" font-size="16">même branche</text><text x="425" y="215" font-size="16">mode de pompe changé</text><text x="425" y="260" font-size="16">stabilisation inconnue</text>`);
  const inquiryScene=shell("mtest-inquiry","Mini-diagnostic avec indices à demander","La branche B est froide. A et C ont du débit. B a un débit nul. La position réelle de la vanne B est inconnue et constitue l’indice utile à demander.",`<circle cx="360" cy="205" r="70" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="360" y="195" text-anchor="middle" font-size="17" font-weight="700">BRANCHE B FROIDE</text><text x="360" y="225" text-anchor="middle" font-size="15">Q = 0,0 m³/h</text>${[[35,55,"A / C : débit présent","MESURE"],[455,55,"Vanne B : position ?","À DEMANDER"],[35,300,"Pompe générale en panne","HYPOTHÈSE ÉCARTÉE"],[455,300,"Vanne B fermée","HYPOTHÈSE"]].map(([x,y,t,s],i)=>`<rect x="${x}" y="${y}" width="230" height="70" rx="15" fill="#fffdf8" stroke="${i===1?"#1e7e54":i===2?"#c0392b":"#1b3a63"}" stroke-width="${i===1?5:3}" stroke-dasharray="${i===2?"9 6":"0"}"/><text x="${x+115}" y="${y+28}" text-anchor="middle" font-size="14" font-weight="700">${t}</text><text x="${x+115}" y="${y+53}" text-anchor="middle" font-size="11">${s}</text>`).join("")}`);
  const reportScene=shell("mtest-report","Mission de synthèse et compte rendu","Le rapport final comporte constat, mesures, hypothèse, vérification, action unique, stabilisation, nouveau relevé et limite. La décision du cas restaure le réglage documenté.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["CONSTAT","MESURES","HYPOTHÈSE","VÉRIFICATION","ACTION","APRÈS / LIMITE"].map((t,i)=>`<rect x="${12+i*118}" y="130" width="105" height="115" rx="14"/><text x="${64+i*118}" y="178" text-anchor="middle" font-size="11" font-weight="700">${t}</text><text x="${64+i*118}" y="215" text-anchor="middle" font-size="11">${i+1}</text>`).join("")}</g>${[0,1,2,3,4].map(i=>`<path d="M${117+i*118} 188H${129+i*118}" stroke="#c9451a" stroke-width="4" marker-end="url(#arr-mtest-report)"/>`).join("")}<rect x="105" y="290" width="510" height="80" rx="18" fill="#e3f5ec" stroke="#1e7e54" stroke-width="5"/><text x="360" y="322" text-anchor="middle" font-size="15" font-weight="700">DÉCISION DU SCÉNARIO : RESTAURER LE RÉGLAGE DOCUMENTÉ</text><text x="360" y="348" text-anchor="middle" font-size="13">stabiliser · re-mesurer · limiter la conclusion au cas</text>`);

  function hacherTexte(texte){let hash=5381;for(let i=0;i<texte.length;i+=1)hash=((hash*33)^texte.charCodeAt(i))>>>0;hash^=hash>>>16;hash=Math.imul(hash,0x45d9f3b)>>>0;hash^=hash>>>16;hash=Math.imul(hash,0x45d9f3b)>>>0;hash^=hash>>>16;return hash>>>0;}
  function permutationDepuisIndex(n,graine){const factorielles=[1];for(let i=1;i<=n;i+=1)factorielles[i]=factorielles[i-1]*i;let reste=graine%factorielles[n];const disponibles=Array.from({length:n},(_,i)=>i);const permutation=[];for(let i=n;i>0;i-=1){const f=factorielles[i-1];const choix=Math.floor(reste/f);permutation.push(disponibles.splice(choix,1)[0]);reste%=f;}return permutation;}
  function melangerReponses(prompt,options,correct){const n=options.length;if(n<2)return{options,correct};const permutation=permutationDepuisIndex(n,hacherTexte(prompt||""));return{options:permutation.map(i=>options[i]),correct:permutation.indexOf(correct)};}

  const items=[
    {category:"1/12 · Lecture de schéma",station:"mesurer",context:"Le besoin est de relever le débit de la branche B.",question:"Quel choix associe point, instrument et unité ?",options:["Débitmètre sur B en m³/h","Sonde sur le mur en bar","Manomètre sans point en kW","Valeur sans unité"],correct:0,explain:"Les trois éléments correspondent à la grandeur demandée.",cap:"Montre le bon appareil pour mesurer le débit.",tp:"Choisir le matériel et nommer le point.",bts:"Justifier la chaîne de mesure et sa traçabilité.",scene:measureScene,equivalent:"Le débitmètre sur la branche B avec m³/h est le seul ensemble cohérent."},
    {category:"2/12 · Lecture de schéma",station:"releves",essential:true,context:"Deux relevés avant/après portent les mêmes conditions.",question:"Quelle conclusion est défendable ?",options:["Le débit de B a augmenté dans les conditions notées","Toute panne est résolue","La valeur vaut pour tous les réseaux","La cause est certaine"],correct:0,explain:"La fiche prouve un écart observé, pas une cause universelle.",cap:"Compare les deux relevés affichés.",tp:"Comparer les mêmes points.",bts:"Énoncer la portée et les limites de la comparaison.",scene:recordScene,equivalent:"Avant 0,8 m³/h et après 1,0 m³/h, même branche, mode et stabilisation."},
    {category:"3/12 · Lecture de schéma",station:"equilibrage",context:"La correspondance Équilibrage appartient à la ligne D et est raccordée au statut QA technique.",question:"Quelle séquence doit être exploitée pour un réglage ?",options:["État initial → action unique → stabilisation → nouveau relevé → conclusion","Action → conclusion","Deux actions → mesure","Conclusion → relevé"],correct:0,explain:"La station D doit imposer un avant/après attribuable à une seule action.",cap:"Suis l’ordre des cinq étapes.",tp:"Suivre l’ordre du réglage.",bts:"Justifier l’attribution de l’effet.",scene:balanceScene,equivalent:"Cinq cartes montrent la séquence complète; la correspondance D est disponible en lecture seule au statut QA technique."},
    {category:"4/12 · Classer et appliquer",station:"tampon",essential:true,context:"Trois raccordements de volume tampon sont dessinés.",question:"Lequel montre deux circuits dont les débits peuvent différer ?",options:["Le montage quatre piquages","Le montage série","La dérivation seule","Tous automatiquement"],correct:0,explain:"Le schéma quatre piquages dessine primaire, secondaire et volume commun.",cap:"Montre les tuyaux qui entrent et qui sortent.",tp:"Suivre les piquages.",bts:"Relier l’architecture au bilan de débit.",scene:tamponScene,equivalent:"Le montage quatre piquages est encadré comme seul dessin à deux circuits."},
    {category:"5/12 · Classer",station:"tampon",essential:true,context:"Un ballon est présent mais le volume utile n’est pas mesuré.",question:"Quelle fonction ne doit pas être attribuée automatiquement ?",options:["Le découplage pour tout raccordement","La présence d’un volume","La présence de piquages","La masse d’eau nominale"],correct:0,explain:"Le découplage dépend de l’architecture et des débits.",cap:"Montre le ballon sur le schéma.",tp:"Limiter la conclusion au dessin.",bts:"Nommer les vérifications hydrauliques nécessaires.",scene:roleScene,equivalent:"Volume montré; volume utile à vérifier; découplage et stratification non automatiques."},
    {category:"6/12 · Appliquer",station:"diagnostic",essential:true,context:"Une valeur anormale est relevée.",question:"Quelle étape vient après l’hypothèse ?",options:["La vérification","Le remplacement","La décision immédiate","L’effacement des mesures"],correct:0,explain:"L’hypothèse doit être testée avant toute décision.",cap:"Suis les étapes dans l’ordre donné.",tp:"Respecter la démarche.",bts:"Choisir une vérification discriminante.",scene:chainScene,equivalent:"La chaîne impose mesures, interprétation, hypothèse, vérification, décision."},
    {category:"7/12 · Mesurer",station:"releves",essential:true,context:"Il faut comparer débit et écart de température d’une branche.",question:"Quel ensemble d’unités est cohérent ?",options:["m³/h, °C et K","bar, kW/h et couleur","°C sans point","mCE pour une température"],correct:0,explain:"Le débit, les températures et leur écart portent leurs unités adaptées.",cap:"Lis l’unité de chaque appareil.",tp:"Associer instruments, points et unités.",bts:"Contrôler la cohérence dimensionnelle.",scene:unitScene,equivalent:"Débitmètre en m³/h et sondes en °C avec écart en K."},
    {category:"8/12 · Calculer",station:"decouplage",essential:true,context:"Données pédagogiques : Qp=1, Qs=2, Tpd=60 °C, Tsr=40 °C.",question:"Quelle température de départ secondaire donne le bilan affiché ?",options:["50,0 °C","40,0 °C","60,0 °C","100,0 °C"],correct:0,explain:"Une part à 60 °C et une part à 40 °C donnent 50,0 °C.",cap:"Lis les deux températures données.",tp:"Lire les données et l’unité.",bts:"Appliquer la moyenne pondérée avec les hypothèses écrites.",scene:mixScene,equivalent:"Le calcul pondéré affiché donne T départ secondaire égal 50,0 °C."},
    {category:"9/12 · Cause et effet",station:"decouplage",essential:true,context:"Les débits primaire et secondaire deviennent différents.",question:"Si Qp < Qs, quel transfert interne apparaît ?",options:["Retour secondaire vers le haut","Surplus primaire vers le bas","Aucun transfert net","Débit négatif dans les deux pompes"],correct:0,explain:"Le secondaire complète son débit en recyclant une part du retour dans ce modèle.",cap:"Montre le sens de la flèche.",tp:"Nommer le sens.",bts:"Relier le sens au bilan de masse.",scene:regimeScene,equivalent:"La colonne Qp inférieur Qs porte une flèche montante et le mot vers le haut."},
    {category:"10/12 · Cause et effet",station:"releves",essential:true,context:"Le mode de pompe change entre avant et après.",question:"Quel effet sur la conclusion ?",options:["Elle devient fragile; le débit peut changer pour plusieurs raisons","Elle devient certaine","L’unité disparaît","La stabilisation n’est plus utile"],correct:0,explain:"Plusieurs paramètres ont changé; l’effet ne peut pas être attribué au seul réglage.",cap:"Compare les deux fiches de relevé.",tp:"Comparer les conditions.",bts:"Identifier le facteur confondant.",scene:contextScene,equivalent:"La comparaison exploitable conserve le mode; la comparaison fragile change le mode et ignore la stabilisation."},
    {category:"11/12 · Mini-diagnostic",station:"diagnostic",essential:true,context:"B est froide, A et C circulent, Qb est nul.",question:"Quel indice demander avant de retenir la vanne fermée ?",options:["La position réelle de la vanne B","La couleur du radiateur","La marque de la pompe","Un remplacement immédiat"],correct:0,explain:"La position réelle vérifie directement l’hypothèse locale.",cap:"Signale la position de la vanne B.",tp:"Demander l’indice utile.",bts:"Choisir une preuve discriminante parmi plusieurs hypothèses.",scene:inquiryScene,equivalent:"La position réelle de la vanne B est la donnée manquante mise en évidence."},
    {category:"12/12 · Décider et rendre compte",station:"mission",essential:true,context:"Le dossier demande préréglage 2,5; l’état initial indique 0,0 et Q faible.",question:"Quelle décision est justifiée par le cas ?",options:["Restaurer le réglage documenté, stabiliser et re-mesurer","Changer le circulateur","Purger tout le réseau","Conclure sans contrôle"],correct:0,explain:"L’écart au dossier est vérifié et l’action unique prévoit un contrôle après stabilisation.",cap:"Signale le réglage à remettre en place.",tp:"Rendre compte de l’action et du nouveau relevé.",bts:"Justifier la décision et la limiter aux preuves du scénario.",scene:reportScene,equivalent:"Le compte rendu relie constat, mesures, hypothèse, vérification, action unique et contrôle après."}
  ].map(item=>item.options?{...item,...melangerReponses(item.question,item.options,item.correct)}:item);

  const els=Object.fromEntries(["routeScreen","testScreen","resultScreen","lineTrack","levelObjective","startTest","testProgress","testCategory","testTitle","testContext","levelDemand","answers","testScene","testEquivalent","testNavigation","quitTest","itemCount","nextItem","resultTitle","resultScore","resultExplain","remediation","retryTest","backRoute"].map(id=>[id,document.getElementById(id)]));
  let level="TP",index=0,score=0,answered=false,missed=[],essentialHits={releves:0,tampon:0,decouplage:0,diagnostic:0,mission:0};
  const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
  function renderRoute(){
    els.lineTrack.innerHTML=stations.map((station,i)=>`<a class="station-link ${station.interchange?"interchange":""} ${station.pending?"pending":""}" href="../../stations/${station.id}/index.html?line=M"><span class="station-number">${i+1}</span><h2>${station.title}</h2><p>${station.hint}</p><span></span><span class="status">${station.status}</span></a>`).join("");
    els.levelObjective.textContent=({CAP:"Observer, lire une valeur simple et dire si elle est normale avec la fiche d’aide.",TP:"Observer, choisir une mesure, relever avec contexte, vérifier une hypothèse puis rendre compte.",BTS:"Concevoir la stratégie de mesure, établir les bilans, comparer les hypothèses et justifier les limites."})[level];
  }
  function show(name){els.routeScreen.hidden=name!=="route";els.testScreen.hidden=name!=="test";els.resultScreen.hidden=name!=="result";els.testNavigation.hidden=name!=="test";}
  function renderProgress(){els.testProgress.innerHTML=items.map((_,i)=>`<span class="test-dot ${i===index?"current":""} ${i<index?"done":""}">${i+1}</span>`).join("");}
  function renderItem(){const item=items[index];answered=false;renderProgress();els.testCategory.textContent=item.category;els.testTitle.textContent=item.question;els.testContext.textContent=item.context;els.levelDemand.innerHTML=`<strong>${level==="CAP"?"CAP":level==="TP"?"Bac pro":"BTS"} :</strong> ${escapeHtml(item[level.toLowerCase()]||item.tp)}`;els.testScene.innerHTML=item.scene;els.testEquivalent.textContent=item.equivalent;els.answers.innerHTML="";item.options.forEach((option,i)=>{const button=document.createElement("button");button.type="button";button.className="answer";button.textContent=option;button.addEventListener("click",()=>answer(i));els.answers.append(button);});els.nextItem.disabled=true;els.nextItem.textContent=index===items.length-1?"Voir le bilan":"Activité suivante";els.itemCount.textContent=`${index+1} / ${items.length}`;requestAnimationFrame(()=>els.testTitle.focus({preventScroll:true}));}
  function answer(choice){if(answered)return;answered=true;const item=items[index],correct=choice===item.correct;if(correct){score+=1;if(item.essential)essentialHits[item.station]+=1;}else missed.push(item.station);[...els.answers.children].forEach((button,i)=>{button.disabled=true;if(i===item.correct)button.classList.add("correct");});els.answers.children[choice].classList.add(correct?"correct":"wrong");const feedback=document.createElement("p");feedback.className=`feedback ${correct?"correct":"wrong"}`;feedback.textContent=`${correct?"✓ Correct. ":"✗ À revoir. "}${item.explain}`;els.answers.append(feedback);els.nextItem.disabled=false;}
  function start(){index=0;score=0;answered=false;missed=[];essentialHits={releves:0,tampon:0,decouplage:0,diagnostic:0,mission:0};show("test");renderItem();}
  function result(){show("result");const essentialsOk=Object.values(essentialHits).every(value=>value>0);let label,cls,explain;if(score>=9&&essentialsOk){label="ACQUIS";cls="acquired";explain="Au moins 70 % et chaque famille essentielle a été mobilisée.";}else if(score>=6){label="FRAGILE";cls="fragile";explain=score>=9&&!essentialsOk?"Le score atteint 70 %, mais une famille essentielle n’a aucune réponse juste.":"Entre 50 % et 69 %, ou une famille essentielle reste absente.";}else{label="À RENFORCER";cls="reinforce";explain="Moins de 50 % : reprendre les stations liées aux erreurs.";}const card=els.resultScreen.querySelector(".result-card"),grade=Math.round((score/items.length)*200)/10;card.className=`result-card ${cls}`;els.resultTitle.textContent=label;els.resultScore.textContent=`Note : ${grade.toLocaleString("fr-FR")} / 20`;els.resultExplain.textContent=`Score brut : ${score} / ${items.length}. ${explain} Note d’entraînement, jamais la validation d’un diplôme.`;const unique=[...new Set(missed)];els.remediation.innerHTML=unique.length?`<strong>Stations à revoir :</strong> ${unique.map(id=>{const s=stations.find(st=>st.id===id);return`<a href="../../stations/${id}/index.html?line=M">${s?.title||id}</a>`;}).join("")}`:"<strong>Aucune erreur :</strong> refaire la mission sur une installation différente après validation humaine.";requestAnimationFrame(()=>els.resultTitle.focus({preventScroll:true}));}
  document.querySelectorAll(".level-btn").forEach(button=>button.addEventListener("click",()=>{level=button.dataset.level;document.querySelectorAll(".level-btn").forEach(item=>{const active=item===button;item.classList.toggle("is-active",active);item.setAttribute("aria-pressed",String(active));});renderRoute();if(!els.testScreen.hidden)renderItem();}));
  els.startTest.addEventListener("click",start);els.nextItem.addEventListener("click",()=>{if(!answered)return;if(index<items.length-1){index+=1;renderItem();}else result();});els.quitTest.addEventListener("click",()=>show("route"));els.retryTest.addEventListener("click",start);els.backRoute.addEventListener("click",()=>show("route"));
  document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!els.testScreen.hidden){show("route");return;}if(["INPUT","SELECT","BUTTON","A"].includes(event.target.tagName))return;if(event.key==="ArrowRight"&&!els.nextItem.disabled&&!els.testScreen.hidden)els.nextItem.click();});
  renderRoute();show("route");if(new URLSearchParams(window.location.search).get("evaluation")==="1")start();
})();
