(() => {
  "use strict";
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><pattern id="danger-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#c0392b" stroke-width="2"/></pattern><pattern id="safe-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="1.5" fill="#1e7e54"/></pattern></defs>${body}</svg>`;

  const identify=shell("safe-ident","Chaîne de protection hydraulique","Un générateur est raccordé à un manomètre, un vase d’expansion et une soupape avec évacuation. Le symbole validé de soupape est montré dans une loupe.",
    `<path d="M55 250H665" stroke="#1b3a63" stroke-width="14"/>
     <rect x="80" y="170" width="150" height="160" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="155" y="240" text-anchor="middle" font-size="18" font-weight="700">GÉNÉRATEUR</text>
     <circle cx="330" cy="180" r="45" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><path d="M330 180L355 155" stroke="#c9451a" stroke-width="5"/><text x="330" y="145" text-anchor="middle" font-size="14" font-weight="700">MANOMÈTRE</text>
     <path d="M330 225V250" stroke="#1b3a63" stroke-width="8"/>
     <path d="M460 250V335" stroke="#1b3a63" stroke-width="10"/><ellipse cx="460" cy="346" rx="48" ry="38" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="460" y="352" text-anchor="middle" font-size="14" font-weight="700">VASE</text>
     <path d="M570 250V170" stroke="#1b3a63" stroke-width="10"/><image href="assets/soupape-securite.svg" x="535" y="98" width="70" height="70"/>
     <path d="M605 133H670V350" fill="none" stroke="#c0392b" stroke-width="8" stroke-dasharray="12 7" marker-end="url(#arr-safe-ident)"/><text x="640" y="92" text-anchor="middle" font-size="14" font-weight="700">SOUPAPE</text><text x="642" y="380" text-anchor="middle" font-size="14" font-weight="700">ÉVACUATION SÛRE</text>
     <text x="360" y="48" text-anchor="middle" font-size="22" font-weight="700">MESURER · ABSORBER · LIMITER · ÉVACUER</text>`);

  function pressureScene(ratio=80){const open=ratio>=100;const angle=-120+Math.min(ratio,120)*2.0;return shell("safe-pressure","Réponse qualitative de la soupape",`Pression relative ${ratio} pour cent du seuil de déclenchement du modèle. La soupape est ${open?"ouverte":"fermée"}. Une soupape réelle agit selon son tarage et sa certification.`,
    `<text x="360" y="42" text-anchor="middle" font-size="21" font-weight="700">PRESSION RELATIVE AU SEUIL DU MODÈLE</text>
     <circle cx="235" cy="225" r="110" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/><path d="M235 225L${235+80*Math.cos(angle*Math.PI/180)} ${225+80*Math.sin(angle*Math.PI/180)}" stroke="#c9451a" stroke-width="8" stroke-linecap="round"/><circle cx="235" cy="225" r="13" fill="#1b3a63"/>
     <path d="M150 300A110 110 0 0 1 320 300" fill="none" stroke="#b06a00" stroke-width="8" stroke-dasharray="6 5"/><text x="235" y="365" text-anchor="middle" font-size="19" font-weight="700">${ratio} % du seuil</text>
     <rect x="420" y="105" width="190" height="155" rx="22" fill="${open?"url(#danger-safe-pressure)":"#fffdf8"}" stroke="${open?"#c0392b":"#1b3a63"}" stroke-width="5" stroke-dasharray="${open?"10 7":"0"}"/><image href="assets/soupape-securite.svg" x="475" y="125" width="80" height="80"/><text x="515" y="235" text-anchor="middle" font-size="18" font-weight="700">${open?"OUVERTE · ÉVACUE":"FERMÉE · VEILLE"}</text>
     <path d="M515 260V365" stroke="#c0392b" stroke-width="${open?10:3}" stroke-dasharray="${open?"12 7":"4 5"}" marker-end="url(#arr-safe-pressure)"/>
     <text x="515" y="397" text-anchor="middle" font-size="14">évacuation libre et prévue</text>`);}

  const discharge=shell("safe-discharge","Évacuation conçue pour rester libre","Deux conduites sont comparées. La première est libre, repérée et dirigée vers un point prévu. La seconde est bouchée par une vanne fermée et porte le mot interdit.",
    `<text x="360" y="42" text-anchor="middle" font-size="22" font-weight="700">UNE PROTECTION DOIT POUVOIR ÉVACUER</text>
     <g transform="translate(45 90)"><rect width="285" height="265" rx="20" fill="#e3f5ec" stroke="#1e7e54" stroke-width="6"/><text x="142" y="42" text-anchor="middle" font-size="18" font-weight="700">✓ VOIE LIBRE</text><image href="assets/soupape-securite.svg" x="35" y="85" width="75" height="75"/><path d="M110 125H210V220H245" fill="none" stroke="#1e7e54" stroke-width="10" marker-end="url(#arr-safe-discharge)"/><text x="142" y="250" text-anchor="middle" font-size="14">vers point sûr prévu</text></g>
     <g transform="translate(390 90)"><rect width="285" height="265" rx="20" fill="#fbe7e4" stroke="#c0392b" stroke-width="5" stroke-dasharray="10 7"/><text x="142" y="42" text-anchor="middle" font-size="18" font-weight="700">✗ INTERDIT : BOUCHÉ</text><image href="assets/soupape-securite.svg" x="35" y="85" width="75" height="75"/><path d="M110 125H205" stroke="#c0392b" stroke-width="10"/><path d="M190 95L230 155M230 95L190 155" stroke="#c0392b" stroke-width="10"/><text x="142" y="250" text-anchor="middle" font-size="14">danger de surpression</text></g>`);

  const symptoms=shell("safe-symptoms","Un écoulement est un symptôme à qualifier","Trois cartes distinguent gouttes pendant une phase connue, écoulement continu et absence d’évacuation malgré une anomalie. Chaque cas mène à vérifier et signaler, jamais à boucher.",
    `<text x="360" y="50" text-anchor="middle" font-size="22" font-weight="700">OBSERVER · DATER · MESURER · SIGNALER</text>
     <g>${[[35,"GOUTTES","pendant phase connue","qualifier le contexte"],[265,"CONTINU","hors phase attendue","mettre en sécurité"],[495,"AUCUN DÉBIT","malgré surpression présumée","danger à traiter"]].map(([x,a,b,c],i)=>`<rect x="${x}" y="105" width="190" height="220" rx="18" fill="${i===1?"#fff4e0":"#fffdf8"}" stroke="${i===1?"#b06a00":"#1b3a63"}" stroke-width="${i===1?4:3}" stroke-dasharray="${i===1?"5 5":"0"}"/><text x="${x+95}" y="150" text-anchor="middle" font-size="18" font-weight="700">${a}</text><path d="M${x+95} 175c-28 40-35 54-35 72a35 35 0 0 0 70 0c0-18-7-32-35-72Z" fill="${i===2?"#fffdf8":"#84b7ec"}" stroke="#1b3a63" stroke-width="3"/><text x="${x+95}" y="290" text-anchor="middle" font-size="13">${b}</text><text x="${x+95}" y="312" text-anchor="middle" font-size="13" font-weight="700">${c}</text>`).join("")}</g>
     <rect x="180" y="350" width="360" height="48" rx="14" fill="#fbe7e4" stroke="#c0392b" stroke-width="4" stroke-dasharray="9 6"/><text x="360" y="380" text-anchor="middle" font-size="16" font-weight="700">JAMAIS BOUCHER POUR FAIRE CESSER LE SYMPTÔME</text>`);

  const response=shell("safe-response","Conduite sûre face à une soupape","La chaîne commence par éviter l’exposition et appliquer la procédure, puis mettre l’équipement dans l’état sûr prévu, signaler et faire analyser la cause par une personne compétente.",
    `<text x="360" y="62" text-anchor="middle" font-size="22" font-weight="700">PROTÉGER LES PERSONNES · GARDER LA PROTECTION</text>
     <g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["S’éloigner du rejet", "Appliquer la procédure", "État sûr prévu", "Signaler / consigner"].map((t,i)=>`<rect x="${20+i*175}" y="150" width="150" height="95" rx="15"/><text x="${95+i*175}" y="190" text-anchor="middle" font-size="14" font-weight="700">${t}</text><text x="${95+i*175}" y="218" text-anchor="middle" font-size="12">étape ${i+1}</text>`).join("")}</g>
     ${Array.from({length:3},(_,i)=>`<path d="M${170+i*175} 198H${195+i*175}" stroke="#c9451a" stroke-width="5" marker-end="url(#arr-safe-response)"/>`).join("")}
     <rect x="145" y="295" width="430" height="72" rx="16" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="360" y="325" text-anchor="middle" font-size="16" font-weight="700">Puis : mesures → hypothèse → contrôle ciblé</text><text x="360" y="350" text-anchor="middle" font-size="14">par une personne autorisée</text>`);

  window.STATION_CONFIG={code:"E7",id:"securite",title:"Sécurité",next:"terminer la ligne E puis réinvestir les mesures",levels:{CAP:{objective:"Reconnaître les organes de sécurité et signaler sans y toucher.",assessment:"nommer un organe et signaler sans toucher"},TP:{objective:"Identifier les protections et adopter une conduite sûre face à une évacuation.",assessment:"repérer, protéger, signaler et ne jamais neutraliser"},BTS:{objective:"Justifier une chaîne de protection et son évacuation à partir des risques et prescriptions.",assessment:"relier risque, organe, implantation, symptômes et vérification"}},steps:[
    {short:"Identifier",kicker:"repérer",title:"Une chaîne, plusieurs fonctions",text:"Manomètre, vase et soupape ne se remplacent pas. Chacun traite une partie différente du risque.",cap:"Nomme le manomètre, le vase et la soupape.",tp:"Repère les organes et l’évacuation.",bts:"Relie chaque organe au phénomène surveillé ou limité.",scene:identify,equivalent:"Le réseau comprend un manomètre, un vase d’expansion, une soupape et une conduite d’évacuation sûre.",action:{type:"match",prompt:"Associe chaque organe à sa fonction.",options:["Indiquer la pression","Accepter la dilatation","Limiter une surpression","Conduire le rejet"],items:[{label:"Manomètre",answer:0},{label:"Vase",answer:1},{label:"Soupape",answer:2},{label:"Évacuation",answer:3}],explain:"Les fonctions se complètent. Une soupape n’est pas un organe de régulation normale ni un substitut au vase."}},
    {short:"Fonction",kicker:"comprendre",title:"La soupape reste une protection",text:"Augmente la pression relative. Le seuil est sans unité et propre à ce modèle : aucun tarage réel n’est enseigné ici.",cap:"Montre la soupape ouverte ou fermée sur le dessin.",tp:"Observe l’ouverture et garde la zone d’évacuation libre.",bts:"Distingue fonctionnement de protection, tarage certifié et régulation du système.",scene:pressureScene,equivalent:(v)=>`Pression relative ${v} % du seuil du modèle. Soupape ${v>=100?"ouverte et évacuant":"fermée et en veille"}.`,action:{type:"range",prompt:"Fais monter la pression relative.",label:"Pression / seuil",min:50,max:120,step:5,value:80,evaluate:(v)=>({readout:`${v} %`,observation:v<100?"La soupape reste fermée dans le modèle. Elle veille; le système doit rester dans sa plage normale.":"La soupape ouvre dans le modèle et évacue. La zone de rejet doit rester libre; rechercher la cause sans neutraliser."})}},
    {short:"Évacuer",kicker:"observer",title:"Un rejet ne se bouche jamais",text:"Compare la voie libre et la voie condamnée. La conduite réelle suit la conception, les prescriptions et le dossier du site.",cap:"Montre le tuyau d’évacuation toujours libre, jamais bouché.",tp:"Vérifie visuellement accessibilité et absence d’obstruction, sans dérégler.",bts:"Justifie implantation, absence d’isolement non prévu et conduite sûre du rejet selon les prescriptions applicables.",scene:discharge,equivalent:"À gauche une évacuation libre vers un point sûr prévu. À droite une évacuation bouchée porte le mot interdit.",action:{type:"choice",prompt:"Quel contrôle visuel est cohérent ?",options:[{label:"Voie libre, repérée et dirigée vers le point prévu"},{label:"Bouchon ajouté pour arrêter les gouttes"},{label:"Vanne fermée sur l’évacuation"},{label:"Rejet dirigé vers le passage"}],correct:0,explain:"Une protection doit pouvoir évacuer sans exposer les personnes. L’installation réelle se vérifie sur son dossier et ses prescriptions."}},
    {short:"Symptômes",kicker:"mesurer",title:"Qualifier l’écoulement",text:"La durée, la phase de fonctionnement et les pressions aident à distinguer les pistes. Aucun symptôme ne donne une cause unique.",cap:"Signale une goutte ou un écoulement sans y toucher.",tp:"Observe, date et signale sans toucher au tarage.",bts:"Croise pression, expansion, remplissage, température et état de la soupape.",scene:symptoms,equivalent:"Trois états sont décrits par mots et formes : gouttes en phase connue, écoulement continu, aucune évacuation malgré anomalie. Tous demandent vérification.",action:{type:"match",prompt:"Associe le constat à la conduite initiale.",options:["Qualifier la phase et surveiller selon procédure","Mettre en sécurité et signaler","Traiter comme danger; ne pas provoquer d’essai"],items:[{label:"Gouttes pendant une phase connue",answer:0},{label:"Écoulement continu",answer:1},{label:"Surpression présumée sans évacuation",answer:2}],explain:"Ces conduites ne posent pas de diagnostic. Elles protègent les personnes et préparent une analyse autorisée."}},
    {short:"Vérifier",kicker:"hypothèse",title:"Réagir sans neutraliser",text:"Une soupape évacue. Ordonne la conduite initiale avant toute recherche de cause.",cap:"Signale l’évacuation sans t’approcher de la soupape.",tp:"Protège-toi, applique la procédure et rends compte.",bts:"Après mise en sécurité, construis la vérification : mesure, interprétation, hypothèse et décision.",scene:response,equivalent:"Séquence : s’éloigner du rejet, appliquer la procédure, atteindre l’état sûr prévu, signaler et consigner; l’analyse vient ensuite.",action:{type:"sequence",prompt:"Place la conduite initiale dans l’ordre.",items:["S’éloigner du rejet","Appliquer la procédure du site","Mettre dans l’état sûr prévu","Signaler et consigner"],correctOrder:[0,1,2,3],explain:"La protection reste en place. La cause est recherchée ensuite par une personne autorisée à partir de mesures."}}
  ],quiz:[
    {context:"La pression dépasse le seuil d’une soupape correctement intégrée.",question:"Quel est son rôle ?",options:["Limiter la surpression par une évacuation prévue","Régler le débit normal","Remplacer le vase","Mesurer la température"],correct:0,explain:"La soupape est un dernier organe de protection, pas une régulation d’usage normal."},
    {context:"Une conduite d’évacuation goutte.",question:"Quelle action est interdite ?",options:["Boucher ou fermer la voie de rejet","Observer la phase","Signaler le constat","Relever la pression selon procédure"],correct:0,explain:"Bloquer l’évacuation peut supprimer la fonction de protection."},
    {context:"La soupape évacue en phase de chauffe.",question:"Quelle piste doit aussi être vérifiée ?",options:["Expansion, remplissage et plage de pression","La couleur du tube","La marque seule","Le débit d’air extérieur seul"],correct:0,explain:"Le vase et les conditions de remplissage peuvent influencer la montée en pression; ce ne sont que des pistes à vérifier."},
    {context:"Un rejet se produit près d’un passage.",question:"Quelle conduite initiale est sûre ?",options:["Éloigner les personnes et appliquer la procédure","Tenir la soupape fermée","Approcher le visage","Modifier le tarage"],correct:0,explain:"La priorité est l’exposition des personnes et l’état sûr prévu, sans neutralisation ni dérèglage."}
  ],summaryScene:identify,summaryEquivalent:"Synthèse : manomètre, vase, soupape et évacuation forment une chaîne complémentaire. Une protection n’est jamais neutralisée pour masquer un symptôme."};
})();
