(() => {
  "use strict";
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><pattern id="gas-${id}" width="10" height="10" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="1.5" fill="#b06a00"/></pattern><pattern id="water-${id}" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M0 10L10 0" stroke="#3d7fca" stroke-width="2"/></pattern></defs>${body}</svg>`;

  const cut=shell("vase-cut","Vase d’expansion à membrane","Le symbole validé est à gauche. La coupe pédagogique à droite montre une enveloppe, une membrane, un volume de gaz au-dessus et l’eau du réseau en dessous.",
    `<rect x="28" y="82" width="220" height="255" rx="22" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><image href="assets/vase-expansion.svg" x="78" y="118" width="120" height="150"/><text x="138" y="305" text-anchor="middle" font-size="17" font-weight="700">SYMBOLE VALIDÉ</text>
     <path d="M415 68C340 68 310 120 310 210S340 352 415 352S520 300 520 210S490 68 415 68Z" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/>
     <path d="M316 205C350 180 480 180 514 205V210C480 240 350 240 316 210Z" fill="#fff4e0" stroke="#c9451a" stroke-width="5"/>
     <path d="M323 210C350 238 480 238 507 210V330C470 365 360 365 323 330Z" fill="url(#water-vase-cut)"/>
     <path d="M323 205V92C360 55 470 55 507 92V205C475 178 355 178 323 205Z" fill="url(#gas-vase-cut)"/>
     <path d="M415 352V390" stroke="#1b3a63" stroke-width="12"/>
     <text x="415" y="125" text-anchor="middle" font-size="18" font-weight="700">GAZ · PRÉCHARGE</text><text x="415" y="290" text-anchor="middle" font-size="18" font-weight="700">EAU DU RÉSEAU</text><text x="608" y="205" text-anchor="middle" font-size="16" font-weight="700">MEMBRANE</text><path d="M560 210H505" stroke="#c9451a" stroke-width="4" marker-end="url(#arr-vase-cut)"/>`);

  function expansionScene(value=50){const expansion=3*value/100;const membraneY=245-value*.75;const waterHeight=335-membraneY;const pressure=(1.2+1.3*value/100).toFixed(2);return shell("vase-exp","Dilatation et déplacement de la membrane",`Indice thermique ${value} sur 100. Dilatation pédagogique ${expansion.toFixed(1)} pour cent. Pression simulée ${pressure} bar dans ce cas d’étude. La membrane monte et comprime le gaz.`,
    `<text x="360" y="40" text-anchor="middle" font-size="21" font-weight="700">CAS D’ÉTUDE QUALITATIF · CHAUD / FROID</text>
     <path d="M360 65C280 65 245 120 245 220S280 370 360 370S475 320 475 220S440 65 360 65Z" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/>
     <path d="M254 ${membraneY}C300 ${membraneY-24} 420 ${membraneY-24} 466 ${membraneY}V${membraneY+6}C420 ${membraneY+28} 300 ${membraneY+28} 254 ${membraneY+6}Z" fill="#fff4e0" stroke="#c9451a" stroke-width="5"/>
     <path d="M254 ${membraneY+5}C300 ${membraneY+30} 420 ${membraneY+30} 466 ${membraneY+5}V342C420 383 300 383 254 342Z" fill="url(#water-vase-exp)"/>
     <path d="M254 ${membraneY}V93C300 50 420 50 466 93V${membraneY}C420 ${membraneY-25} 300 ${membraneY-25} 254 ${membraneY}Z" fill="url(#gas-vase-exp)"/>
     <path d="M360 370V400" stroke="#1b3a63" stroke-width="12"/>
     <rect x="28" y="95" width="175" height="82" rx="15" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="115" y="124" text-anchor="middle" font-size="16" font-weight="700">DILATATION</text><text x="115" y="151" text-anchor="middle" font-size="18">${expansion.toFixed(1)} %</text>
     <rect x="520" y="95" width="170" height="82" rx="15" fill="#e3f5ec" stroke="#1e7e54" stroke-width="5"/><text x="605" y="124" text-anchor="middle" font-size="16" font-weight="700">PRESSION MODÈLE</text><text x="605" y="151" text-anchor="middle" font-size="18">${pressure} bar</text>
     <text x="360" y="410" text-anchor="middle" font-size="13">La vraie relation dépend du volume, des pressions, du fluide et de l’installation.</text>`);}

  function prechargeScene(p=1.2){const y=335-Math.max(35,Math.min(210,(2.8-p)*100));const state=p<1?"TROP BASSE":p>1.4?"TROP HAUTE":"ZONE DU CAS";const color=p<1||p>1.4?"#b06a00":"#1e7e54";const dash=p<1||p>1.4?"5 5":"0";return shell("vase-pre","Pression initiale du cas d’étude",`Précharge réglée à ${p.toFixed(1)} bar. L’installation pédagogique demande 1,2 bar selon son dossier. État affiché : ${state}.`,
    `<text x="360" y="40" text-anchor="middle" font-size="21" font-weight="700">CAS FICTIF : PRÉCHARGE ATTENDUE 1,2 bar</text>
     <path d="M360 65C280 65 250 120 250 220S280 370 360 370S470 320 470 220S440 65 360 65Z" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/>
     <path d="M258 ${y}C300 ${y-20} 420 ${y-20} 462 ${y}V${y+5}C420 ${y+25} 300 ${y+25} 258 ${y+5}Z" fill="#fff4e0" stroke="#c9451a" stroke-width="5"/>
     <path d="M258 ${y}V92C300 50 420 50 462 92V${y}C420 ${y-22} 300 ${y-22} 258 ${y}Z" fill="url(#gas-vase-pre)"/>
     <path d="M258 ${y+4}C300 ${y+25} 420 ${y+25} 462 ${y+4}V342C420 382 300 382 258 342Z" fill="url(#water-vase-pre)"/>
     <rect x="28" y="135" width="180" height="90" rx="15" fill="#fffdf8" stroke="${color}" stroke-width="5" stroke-dasharray="${dash}"/><text x="118" y="170" text-anchor="middle" font-size="20" font-weight="700">${p.toFixed(1)} bar</text><text x="118" y="201" text-anchor="middle" font-size="16" font-weight="700">${state}</text>
     <text x="590" y="165" text-anchor="middle" font-size="16" font-weight="700">PAS DE VALEUR</text><text x="590" y="190" text-anchor="middle" font-size="16" font-weight="700">UNIVERSELLE</text><text x="590" y="225" text-anchor="middle" font-size="14">lire le dossier</text>`);}

  const control=shell("vase-control","Conditions d’un contrôle de précharge","Le schéma ordonne autorisation, arrêt et refroidissement, isolement selon la procédure, pression d’eau relâchée en sécurité, puis mesure côté gaz. Il ne décrit pas un geste complet.",
    `<text x="360" y="62" text-anchor="middle" font-size="22" font-weight="700">CONTRÔLE PAR PERSONNE AUTORISÉE</text>
     <g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["Procédure", "Refroidir", "Isoler", "Côté eau à 0", "Mesurer gaz"].map((t,i)=>`<rect x="${15+i*142}" y="150" width="126" height="92" rx="15"/><text x="${78+i*142}" y="188" text-anchor="middle" font-size="15" font-weight="700">${t}</text><text x="${78+i*142}" y="216" text-anchor="middle" font-size="13">étape ${i+1}</text>`).join("")}</g>
     ${Array.from({length:4},(_,i)=>`<path d="M${141+i*142} 196H${155+i*142}" stroke="#c9451a" stroke-width="5" marker-end="url(#arr-vase-control)"/>`).join("")}
     <rect x="130" y="300" width="460" height="66" rx="16" fill="#fbe7e4" stroke="#c0392b" stroke-width="4" stroke-dasharray="8 5"/><text x="360" y="328" text-anchor="middle" font-size="16" font-weight="700">DANGER : pression et température réelles</text><text x="360" y="352" text-anchor="middle" font-size="14">la simulation ne remplace pas la procédure du site</text>`);

  const diagnosis=shell("vase-diag","Pression qui varie : symptômes et vérifications","Un graphe montre une forte variation entre froid et chaud et une soupape qui évacue. Des flèches mènent vers contrôle du vase et des pressions, jamais vers neutralisation de la soupape.",
    `<path d="M90 320V80M90 320H500" stroke="#1b3a63" stroke-width="4"/><path d="M100 280C180 270 205 120 285 145S390 90 480 115" fill="none" stroke="#c9451a" stroke-width="7"/>
     <path d="M100 260C190 250 280 230 480 220" fill="none" stroke="#3d7fca" stroke-width="5" stroke-dasharray="10 7"/>
     <text x="220" y="105" font-size="15" font-weight="700">variation forte · symptôme</text><text x="300" y="247" font-size="15" font-weight="700">plage attendue à vérifier</text>
     <rect x="530" y="90" width="165" height="100" rx="15" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 5"/><text x="612" y="125" text-anchor="middle" font-size="16" font-weight="700">SOUPAPE</text><text x="612" y="152" text-anchor="middle" font-size="14">évacuation constatée</text><text x="612" y="176" text-anchor="middle" font-size="14">ne pas neutraliser</text>
     <rect x="525" y="250" width="175" height="85" rx="15" fill="#e3f5ec" stroke="#1e7e54" stroke-width="5"/><text x="612" y="280" text-anchor="middle" font-size="15" font-weight="700">VÉRIFIER</text><text x="612" y="304" text-anchor="middle" font-size="13">vase + pressions</text><text x="612" y="324" text-anchor="middle" font-size="13">dans les conditions sûres</text>`);

  window.STATION_CONFIG={code:"E6",id:"vase",title:"Vase d’expansion",next:"poursuivre vers la sécurité",levels:{CAP:{objective:"Reconnaître le vase, l’eau, le gaz et signaler sans intervenir seul.",assessment:"nommer les deux côtés et signaler sans intervenir"},TP:{objective:"Identifier le vase, ses volumes et les conditions d’un contrôle sûr.",assessment:"relier symptômes, précharge et démarche sans neutraliser la sécurité"},BTS:{objective:"Relier dilatation, volume utile, précharge et plage de pression.",assessment:"analyser le cas d’étude et expliciter les données manquantes"}},steps:[
    {short:"Identifier",kicker:"repérer",title:"Eau, membrane et gaz",text:"La coupe explique la fonction derrière le symbole : accepter une variation de volume sans mélange eau-gaz normal.",cap:"Montre le côté eau et le côté gaz du vase.",tp:"Repère raccordement eau, membrane et côté gaz.",bts:"Distingue volume total, volume d’eau admissible et volume de gaz.",scene:cut,equivalent:"À gauche le symbole validé; à droite, eau et gaz sont séparés par une membrane dans une enveloppe raccordée au réseau.",action:{type:"match",prompt:"Associe chaque partie à son rôle.",options:["Volume variable du réseau","Séparation souple","Volume compressible"],items:[{label:"Eau",answer:0},{label:"Membrane",answer:1},{label:"Gaz",answer:2}],explain:"Le gaz se comprime lorsque l’eau dilatée entre dans le vase; la membrane sépare les deux milieux."}},
    {short:"Fonction",kicker:"comprendre",title:"La dilatation déplace la membrane",text:"Fais évoluer l’indice thermique. La pression et le déplacement sont qualitatifs, pas une courbe universelle de l’eau.",cap:"Suis la membrane qui bouge avec la chaleur.",tp:"Observe le passage froid-vers-chaud et nomme l’effet.",bts:"Liste les données nécessaires à un dimensionnement réel : volume, fluide, températures et pressions limites.",scene:expansionScene,equivalent:(v)=>`Indice thermique ${v}/100; dilatation pédagogique ${(3*v/100).toFixed(1)} %; pression simulée ${(1.2+1.3*v/100).toFixed(2)} bar.`,action:{type:"range",prompt:"Fais varier le cycle thermique.",label:"Indice thermique",min:0,max:100,step:10,value:50,evaluate:(v)=>({readout:`${v}/100`,observation:`Dilatation pédagogique ${(3*v/100).toFixed(1)} % ; pression du cas ${(1.2+1.3*v/100).toFixed(2)} bar. La vraie relation dépend du projet.`})}},
    {short:"Précharge",kicker:"observer",title:"La pression initiale vient du dossier",text:"Ce cas fictif demande 1,2 bar. Modifie la précharge et observe le volume d’eau disponible dans le modèle.",cap:"Compare la pression affichée avec la valeur de la fiche.",tp:"Compare la valeur mesurée à la valeur attendue du dossier.",bts:"Justifie la précharge à partir de la pression statique, des marges et des conditions retenues.",scene:prechargeScene,equivalent:(v)=>`Précharge ${Number(v).toFixed(1)} bar pour un cas fictif attendu à 1,2 bar. Le dessin de membrane est qualitatif.`,action:{type:"range",prompt:"Modifie la précharge du cas fictif.",label:"Précharge",min:.5,max:2.5,step:.1,value:1.2,evaluate:(v)=>({readout:`${v.toFixed(1)} bar`,observation:v<1?"Précharge basse pour ce cas : la réserve utile peut être mal répartie.":v>1.4?"Précharge haute pour ce cas : l’entrée d’eau peut être limitée.":"Valeur proche de la zone attendue de ce seul cas fictif."})}},
    {short:"Contrôler",kicker:"mesurer",title:"Préparer un contrôle sûr",text:"La précharge ne se lit pas correctement avec la pression d’eau appliquée. Ordonne seulement les conditions, pas un geste réel complet.",cap:"Signale que ce contrôle demande une personne autorisée.",tp:"Travaille sous autorisation et avec la procédure de l’installation.",bts:"Explique pourquoi la pression côté eau doit être relâchée en sécurité avant la mesure du gaz.",scene:control,equivalent:"Conditions : procédure, refroidissement, isolement, côté eau sans pression, mesure côté gaz par personne autorisée.",action:{type:"sequence",prompt:"Place les conditions dans l’ordre.",items:["Lire la procédure et autoriser","Arrêter et laisser refroidir","Isoler selon le dossier","Relâcher côté eau en sécurité"],correctOrder:[0,1,2,3],explain:"La mesure côté gaz vient ensuite, avec l’instrument et la procédure prévus. La simulation n’autorise aucune intervention."}},
    {short:"Vérifier",kicker:"hypothèse",title:"Forte variation ne signifie pas une cause unique",text:"Une pression qui monte fortement et une soupape qui évacue sont des symptômes. La protection reste active.",cap:"Signale la fuite sans toucher à la soupape.",tp:"Signale, sécurise et contrôle selon la procédure sans dérégler la soupape.",bts:"Vérifie vase, précharge, volume et plage de pression avant de retenir une cause.",scene:diagnosis,equivalent:"Le graphe compare une variation forte à une plage attendue. La soupape évacue; l’action proposée est vérifier, jamais neutraliser.",action:{type:"choice",prompt:"Quelle conduite est cohérente ?",options:[{label:"Garder la protection et vérifier vase + pressions"},{label:"Bloquer la soupape"},{label:"Gonfler au hasard"},{label:"Remplacer le vase sans mesure"}],correct:0,explain:"La soupape signale ou limite une surpression. On ne la neutralise pas; on traite la cause après contrôles sûrs."}}
  ],quiz:[
    {context:"L’eau chauffe dans un réseau fermé.",question:"Quel rôle remplit le vase ?",options:["Recevoir une partie de la dilatation et limiter la variation de pression","Créer le débit","Mélanger deux circuits","Évacuer toujours l’eau"],correct:0,explain:"La membrane permet au volume d’eau de varier en comprimant le gaz."},
    {context:"Le dossier d’un cas fictif indique une précharge attendue.",question:"Que faut-il faire d’une autre valeur ?",options:["La comparer dans les conditions de contrôle prévues","Utiliser 1,2 bar partout","Gonfler en service au hasard","Neutraliser la soupape"],correct:0,explain:"La précharge dépend de l’installation. Elle se contrôle dans des conditions définies et sûres."},
    {context:"La pression varie fortement entre froid et chaud.",question:"Quelle conclusion est juste ?",options:["C’est un symptôme qui demande plusieurs vérifications","La membrane est forcément percée","La soupape est la cause","Le circulateur doit être remplacé"],correct:0,explain:"Vase, précharge, volume, remplissage et autres conditions doivent être vérifiés."},
    {context:"La soupape évacue pendant la montée en pression.",question:"Quelle action est interdite ?",options:["Neutraliser ou boucher la protection","Signaler l’anomalie","Mettre en sécurité selon la procédure","Vérifier les pressions"],correct:0,explain:"Une protection ne se condamne jamais pour masquer le symptôme."}
  ],summaryScene:cut,summaryEquivalent:"Synthèse : le vase à membrane absorbe la dilatation grâce à un volume de gaz compressible. Précharge et volume se déterminent pour le projet; la sécurité reste active."};
})();
