"use strict";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const dossiers = [
  { id: "observer", label: "Observer", note: "voir la cause" },
  { id: "installer", label: "Installer", note: "laisser respirer" },
  { id: "regler", label: "Régler", note: "ne pas confondre" },
  { id: "verifier", label: "Vérifier", note: "mesurer dans l’ordre" },
  { id: "tracer", label: "Tracer", note: "écrire l’état" },
];

const quizAnswers = {};
let current = 0;
let furthest = 0;
let extractMode = false;
let activeScreens = [];
let speechRun = 0;
let speaking = false;
let paused = false;
let autoplay = false;
let statusTimer = 0;
const voiceRates = [0.8, 0.95, 1.1, 1.25];
let rateIndex = safeStoredRateIndex();

function safeStoredRateIndex() {
  try {
    const stored = Number(localStorage.getItem("condenseur-voice-rate"));
    const index = voiceRates.indexOf(stored);
    return index >= 0 ? index : 1;
  } catch (_) { return 1; }
}
function saveRate() { try { localStorage.setItem("condenseur-voice-rate", String(voiceRates[rateIndex])); } catch (_) {} }
function esc(value) { return String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])); }
function stripHtml(value) { const box = document.createElement("div"); box.innerHTML = value; return box.textContent || ""; }
function screen(data) { return { level: "comprendre", codes: [], prompt: "", speak: "", ...data }; }

function statement(item) {
  return `<div class="panel"><div class="panel-title">${esc(item.visual || item.title)}</div><div class="diagram">${item.diagram || ""}</div></div>`;
}
function causeScene(dirt = 8, fanOn = true) {
  const severity = !fanOn || dirt > 72 ? "danger" : dirt > 35 ? "warn" : "";
  const word = severity === "danger" ? "PRESSION TRÈS ÉLEVÉE" : severity === "warn" ? "PRESSION EN HAUSSE" : "PRESSION HABITUELLE";
  const needle = !fanOn || dirt > 72 ? 6 : dirt > 35 ? -55 : -130;
  return `<div class="cause-scene">
    <div><div class="air-arrows" style="--air:${fanOn ? Math.max(.16,1-dirt/115) : .08}" aria-hidden="true">→ → →</div><div class="coil" style="--dirt:${(dirt/100*.72).toFixed(2)}"><span class="fan ${fanOn ? "" : "off"}" aria-hidden="true"></span></div><p class="big-label">Batterie ${dirt > 55 ? "grise" : dirt > 20 ? "encrassée" : "propre"} · ventilateur ${fanOn ? "en marche" : "arrêté"}</p></div>
    <div class="gauge-wrap"><div class="gauge" role="img" aria-label="Indication qualitative de la pression de condensation"><span class="needle" style="--needle:${needle}deg"></span></div><span class="state-word ${severity}">${word}</span><p>Lecture qualitative, sans valeur de chantier.</p></div>
  </div>`;
}
function choiceMarkup(choices, name) {
  return `<div class="panel"><div class="cards" style="--cols:${Math.min(choices.length,3)}">${choices.map((c,i)=>`<button class="choice" type="button" data-choice="${i}" data-name="${name}"><strong>${esc(c.title)}</strong><small>${esc(c.note || "")}</small></button>`).join("")}</div><div class="feedback" id="feedback">Choisissez, puis lisez la conséquence.</div></div>`;
}
function wireChoice({ good, messages, lock = false }) {
  $$('[data-choice]').forEach(button => button.addEventListener("click", () => {
    const index = Number(button.dataset.choice);
    if (lock && $$('.choice.good,.choice.bad').length) return;
    $$('.choice').forEach(b => b.classList.remove("selected", "good", "bad"));
    button.classList.add(index === good ? "good" : "bad");
    const feedback = $("#feedback");
    feedback.className = `feedback ${index === good ? "good" : "bad"}`;
    feedback.innerHTML = `<strong>${index === good ? "Correct." : "À corriger."}</strong> ${messages[index]}`;
  }));
}
function checklistMarkup(items) {
  return `<div class="panel"><div class="cards" style="--cols:${Math.min(items.length,3)}">${items.map((item,i)=>`<button class="check-card" type="button" data-check="${i}" aria-pressed="false"><strong>${esc(item.title)}</strong><small>${esc(item.note)}</small></button>`).join("")}</div><div class="feedback" id="feedback">Ouvrez chaque point de contrôle.</div></div>`;
}
function wireChecklist(items) {
  $$('[data-check]').forEach(button => button.addEventListener("click", () => {
    button.classList.add("good"); button.setAttribute("aria-pressed", "true");
    const item = items[Number(button.dataset.check)];
    $("#feedback").className = "feedback good";
    $("#feedback").innerHTML = `<strong>${esc(item.title)}.</strong> ${esc(item.detail)}`;
  }));
}
function quizMarkup(item) {
  const saved = quizAnswers[item.id];
  return `<div class="panel"><div class="cards" style="--cols:2">${item.quiz.choices.map((choice,i)=>`<button class="choice ${saved === i ? (i === item.quiz.good ? "good" : "bad") : ""}" type="button" data-quiz-choice="${i}" ${saved !== undefined ? "disabled" : ""}><strong>${String.fromCharCode(65+i)}.</strong><small>${esc(choice)}</small></button>`).join("")}</div><div class="feedback ${saved === undefined ? "" : saved === item.quiz.good ? "good" : "bad"}" id="feedback">${saved === undefined ? "Choisissez une réponse." : `<strong>${saved === item.quiz.good ? "Correct." : "À revoir."}</strong> ${esc(item.quiz.explain)}`}</div></div>`;
}
function wireQuiz(item) {
  $$('[data-quiz-choice]').forEach(button => button.addEventListener("click", () => {
    if (quizAnswers[item.id] !== undefined) return;
    quizAnswers[item.id] = Number(button.dataset.quizChoice);
    renderCurrent(false);
  }));
}

const screens = [
  screen({ id:"condenseur-role", narration:"Le condenseur a une mission simple à énoncer : faire sortir la chaleur. Il reçoit la vapeur chaude du compresseur, il évacue cette chaleur vers l'air extérieur, et il livre du liquide au détendeur. Gardez cette image en tête pour tout le module : une machine frigorifique ne détruit pas la chaleur, elle la déplace, et c'est ici qu'elle sort. Si la chaleur ne trouve pas la sortie, tout le reste du circuit en souffre immédiatement.", dossier:"observer", title:"La chaleur doit sortir", kicker:"Observer · 1", visual:"Le condenseur est en haut", text:"Le condenseur reçoit la vapeur chaude du compresseur. Il rejette la chaleur vers l’air extérieur et livre du liquide au détendeur.", prompt:"Suivez le trajet. La batterie ne crée pas du froid : elle évacue de la chaleur.", diagram:'<div class="flow-row"><span class="flow-box">Compresseur<br>gaz chaud</span><span class="flow-arrow">→</span><span class="flow-box">CONDENSEUR<br>rejette la chaleur</span><span class="flow-arrow">→</span><span class="flow-box">Détendeur<br>liquide</span></div><div class="air-arrows" aria-hidden="true">AIR → BATTERIE → AIR CHAUD</div>' }),
  screen({ id:"trois-zones", narration:"À l'intérieur, le fluide traverse trois zones, toujours dans le même ordre. D'abord la désurchauffe : la vapeur, très chaude, se refroidit sans changer d'état. Ensuite la condensation : la vapeur devient liquide, et c'est là que la majeure partie de la chaleur est rejetée. Enfin le sous-refroidissement : le liquide continue de se refroidir. Les zones peuvent être plus ou moins longues selon les conditions, mais leur ordre ne change jamais. C'est ce qui vous permet de raisonner sur n'importe quelle machine.", dossier:"observer", title:"Trois zones, toujours dans le même ordre", kicker:"Observer · 2", codes:["1.02","1.04","7.01"], level:"comprendre", text:"Le condenseur retire d’abord la surchauffe de la vapeur. Il transforme ensuite la vapeur en liquide. Enfin, il refroidit encore le liquide. Les zones peuvent être plus ou moins longues, mais leur ordre ne change pas.", prompt:"Suivez le fluide de l’entrée vers la sortie : désurchauffe, puis condensation, puis sous-refroidissement.", render:()=>`<figure class="svg-lesson"><img src="assets/condenseur-trois-zones.svg" alt="Les trois zones du condenseur dans l’ordre : désurchauffe, condensation, sous-refroidissement."><figcaption>Désurchauffe · condensation · sous-refroidissement — l’ordre ne change jamais.</figcaption></figure>` }),
  screen({ id:"batterie-reelle", narration:"Une inspection commence toujours par ce qui se voit, avant tout appareil de mesure. Regardez les ailettes : sont-elles propres, droites, ou couchées ? Le ventilateur : tourne-t-il, et dans le bon sens ? Le passage de l'air : est-il dégagé ? Cherchez les traces d'huile, qui signalent une fuite. Cherchez les frottements et la corrosion sur les conduites. Cinq minutes d'observation vous en apprendront souvent plus qu'une heure de mesures — et elles orientent les mesures que vous ferez ensuite.", dossier:"observer", title:"Regardez avant de mesurer", kicker:"Observer · 3", codes:["7.05"], level:"appliquer", text:"Une inspection commence par ce qui se voit : ailettes, ventilateur, passage de l’air, traces d’huile, frottement et corrosion sur les conduites.", prompt:"Ouvrez les trois zones de reconnaissance.", render:()=>`<div class="photo-card"><img src="../tome-3-technologie-organes/images-organes/condenseur-air.webp" alt="Condenseur à air isolé, avec batterie à ailettes et ventilateurs."><div class="hotspot-list">${["Batterie et ailettes","Ventilateur et passage d’air","Conduites et raccords"].map((x,i)=>`<button type="button" data-hotspot="${i}">${esc(x)}</button>`).join("")}</div><div class="feedback" id="feedback">Une photo aide à reconnaître. La machine réelle et sa notice décident.</div></div>`, wire:()=>{$$('[data-hotspot]').forEach(b=>b.addEventListener("click",()=>{b.classList.add("seen"); const m=["Cherchez poussière, graisse, ailettes couchées et obstacle devant la batterie.","Vérifiez que rien ne bloque l’entrée ou la sortie d’air. Le sens réel se contrôle sur l’appareil.","Après consignation, cherchez trace d’huile, frottement, corrosion ou support détendu."][Number(b.dataset.hotspot)]; $("#feedback").className="feedback good"; $("#feedback").textContent=m;}));} }),
  screen({ id:"encrassement-progressif", narration:"Voyons ce qui se passe quand les ailettes s'encrassent. Moins d'air traverse la batterie ; la chaleur sort moins bien ; et pour évacuer la même quantité de chaleur, il faut un écart de température plus grand. Résultat, dans les mêmes conditions extérieures : la température de condensation monte, et la pression avec elle. C'est la chaîne qu'il faut retenir, parce qu'elle explique la plupart des hautes pressions anormales que vous rencontrerez.", dossier:"observer", title:"Grisez la batterie", kicker:"Observer · 4", codes:["7.07","7.10"], level:"appliquer", text:"Quand les ailettes s’encrassent, moins d’air traverse la batterie. La chaleur sort moins bien. Dans les mêmes conditions, la température et la pression de condensation tendent à monter.", prompt:"Déplacez le curseur de propre à très encrassé.", render:()=>`<div class="panel"><div class="range-row"><strong>Propre</strong><input id="dirt-range" type="range" min="0" max="100" value="8" aria-label="Niveau d’encrassement de la batterie"><strong>Grise</strong></div><div id="cause-output">${causeScene(8,true)}</div></div>`, wire:()=>{$("#dirt-range").addEventListener("input",e=>{$("#cause-output").innerHTML=causeScene(Number(e.target.value),true);});} }),
  screen({ id:"ventilation-coupee", narration:"Une batterie propre ne suffit pas si l'air ne circule pas. Le ventilateur peut être arrêté, tourner dans le mauvais sens, tourner trop lentement — ou bien l'air chaud rejeté peut revenir aussitôt vers l'entrée, ce qu'on appelle un recyclage d'air. Dans tous ces cas, le débit d'air réel s'effondre et le signal est exactement le même que pour une batterie sale : le rejet de chaleur chute, la pression monte. Deux causes différentes, un seul symptôme — c'est pour cela qu'on observe avant de conclure.", dossier:"observer", title:"Coupez le ventilateur", kicker:"Observer · 5", codes:["7.07","7.10"], level:"appliquer", text:"Une batterie propre ne suffit pas si le ventilateur est arrêté, tourne mal ou si l’air chaud revient aussitôt vers l’entrée. Le défaut d’air produit le même signal : le rejet de chaleur chute.", prompt:"Comparez ventilateur en marche et ventilateur arrêté.", render:()=>`<div class="panel"><div id="fan-output">${causeScene(5,true)}</div><button class="primary-button" id="fan-toggle" type="button" aria-pressed="true">Arrêter le ventilateur</button></div>`, wire:()=>{$("#fan-toggle").addEventListener("click",e=>{const on=e.currentTarget.getAttribute("aria-pressed")==="true"; e.currentTarget.setAttribute("aria-pressed",String(!on)); e.currentTarget.textContent=on?"Remettre le ventilateur":"Arrêter le ventilateur"; $("#fan-output").innerHTML=causeScene(5,!on);});} }),
  screen({ id:"lien-haute-pression", narration:"Une haute pression anormale confirme qu'il y a un problème. Elle ne dit pas lequel. C'est le message central de ce module : avant de toucher à la charge de fluide, contrôlez la propreté de la batterie, le fonctionnement du ventilateur, le passage de l'air, et la température ambiante. Dans la grande majorité des cas, la réponse est là. Retirer du fluide pour faire baisser une haute pression causée par un condenseur sale, c'est déséquilibrer la machine pour masquer un entretien non fait.", dossier:"observer", title:"Une HP haute n’est pas un diagnostic", kicker:"Observer · 6", codes:["7.07","7.10"], level:"evaluer", text:"Une haute pression anormale confirme un problème. Elle ne dit pas seule lequel. Avant de toucher à la charge, contrôlez la propreté, le ventilateur, le passage d’air, la température ambiante et la régulation.", prompt:"La batterie est grise et la HP est haute. Que faites-vous d’abord ?", render:()=>choiceMarkup([{title:"Nettoyer et vérifier l’air",note:"Cause visible, action contrôlable"},{title:"Ajouter du fluide",note:"La HP haute ne prouve pas un manque"},{title:"Shunter la sécurité HP",note:"La protection disparaît"}],"hp"), wire:()=>wireChoice({good:0,messages:["Vous traitez la cause observable, puis vous remesurez dans les mêmes conditions.","Une charge modifiée sans diagnostic peut aggraver la pression et masquer la cause.","On ne neutralise jamais une sécurité pour faire tenir une machine en marche."]}) }),

  screen({ id:"implantation-air", narration:"À l'installation, l'air doit pouvoir entrer et sortir librement. Une unité extérieure se pose avec les dégagements prescrits par le constructeur — ce ne sont pas des recommandations de confort, ce sont des conditions de fonctionnement. L'entrée d'air doit rester libre, et l'air chaud rejeté ne doit pas revenir directement vers la batterie. Une unité collée contre un mur, ou installée dans un recoin, fabriquera une haute pression permanente que personne ne comprendra dans trois ans.", dossier:"installer", title:"L’air doit entrer et sortir", kicker:"Installer · 1", codes:["7.03"], level:"appliquer", text:"Une unité extérieure s’installe avec les dégagements prescrits par le constructeur. L’entrée d’air reste libre et l’air chaud rejeté ne doit pas revenir directement vers la batterie.", prompt:"Choisissez l’implantation qui laisse circuler l’air.", render:()=>choiceMarkup([{title:"Dégagements conformes",note:"Entrée libre, rejet sans retour direct"},{title:"En niche fermée",note:"L’air chaud tourne en boucle"},{title:"Derrière un stockage",note:"La batterie aspire contre un obstacle"}],"implantation"), wire:()=>wireChoice({good:0,messages:["La notice fixe les distances. Le principe est simple : pas d’obstacle et pas de recyclage direct d’air chaud.","Une niche peut recirculer l’air chaud et faire monter la pression de condensation.","Un obstacle réduit le débit d’air et rend l’entretien difficile."]}) }),
  screen({ id:"fixation-vibrations", narration:"Le support doit être solide, stable et adapté à la machine. Et cette règle ne se négocie pas : les conduites ne servent jamais à tenir l'unité. Quand elles portent le poids, elles travaillent en permanence — vibrations, frottements, contraintes sur les raccords. Ce sont exactement les conditions qui préparent les fuites de demain. Une fuite n'apparaît presque jamais par hasard : elle apparaît là où le montage a laissé une contrainte pendant des années.", dossier:"installer", title:"Fixer sans faire travailler les tubes", kicker:"Installer · 2", codes:["7.03"], level:"appliquer", text:"Le support doit être solide, stable et adapté. Les conduites ne servent jamais à tenir l’unité. Les vibrations, frottements et contraintes sur les raccords préparent les fuites de demain.", prompt:"Ouvrez chaque point avant d’autoriser la pose.", render:()=>checklistMarkup([{title:"Support",note:"solide et adapté",detail:"L’unité ne bascule pas et reste accessible selon la notice."},{title:"Conduites",note:"supportées sans contrainte",detail:"Les tubes ne portent pas le poids et ne frottent pas contre une arête."},{title:"Vibrations",note:"transmission maîtrisée",detail:"Fixations et dispositifs prévus par le constructeur sont en place."}]), wire:()=>wireChecklist([{title:"Support",detail:"L’unité ne bascule pas et reste accessible selon la notice."},{title:"Conduites",detail:"Les tubes ne portent pas le poids et ne frottent pas contre une arête."},{title:"Vibrations",detail:"Fixations et dispositifs prévus par le constructeur sont en place."}]) }),
  screen({ id:"materiel-accessible", narration:"Régler et sécuriser doivent rester possibles après la pose. Le matériel de réglage et de sécurité se monte comme prévu, et il reste accessible : le régulateur de pression, le pressostat haute pression, les vannes, les connexions, les zones de mesure. Une machine installée dans un endroit où l'on ne peut plus atteindre ses organes n'est pas maintenable — et ce qui n'est pas accessible n'est pas contrôlé. Pensez à celui qui viendra après vous, ce sera peut-être vous.", dossier:"installer", title:"Régler et sécuriser doivent rester possibles", kicker:"Installer · 3", codes:["7.02","7.03"], level:"comprendre", text:"Le matériel de réglage et de sécurité se monte comme prévu et reste accessible : régulateur de pression, pressostat HP, vannes, connexions et zones de mesure.", prompt:"Reliez la fonction à l’organe.", render:()=>choiceMarkup([{title:"Régulateur",note:"maintient une pression prévue"},{title:"Pressostat HP",note:"coupe sur danger"},{title:"Mur devant la batterie",note:"bloque l’air et l’accès"}],"access"), wire:()=>wireChoice({good:0,messages:["Le régulateur agit sur la pression. Son réglage vient de la notice.","Le pressostat est indispensable, mais il protège : il ne remplace pas la régulation de pression demandée au code 7.02.","Un obstacle compromet l’air, l’inspection et l’entretien."]}) }),
  screen({ id:"quiz-installation", narration:"Faisons le point sur l'installation. Une pose correcte doit remplir deux exigences en même temps : éviter la fuite, et laisser le condenseur fonctionner puis être entretenu. La première dépend du support et de l'absence de contrainte. La seconde dépend des dégagements d'air et de l'accessibilité des organes. Un montage qui satisfait l'une et pas l'autre n'est pas un bon montage — il déplace simplement le problème dans le temps.", dossier:"installer", title:"Contrôle 1 · Installation", kicker:"Installer · contrôle", codes:["7.03"], level:"evaluer", text:"Une pose correcte doit éviter la fuite et laisser le condenseur fonctionner puis être entretenu.", prompt:"Quel ensemble est conforme ?", quiz:{choices:["Support stable, tubes sans contrainte, dégagements de notice, accès aux organes","Unité tenue par les tubes, mais batterie propre","Unité coincée en niche, avec pressostat HP shunté","Dégagement réduit pour cacher le bruit"],good:0,explain:"La pose protège les raccords, le débit d’air, l’accès et les sécurités. Les distances exactes viennent de la notice."}, render(){return quizMarkup(this)}, wire(){wireQuiz(this)} }),

  screen({ id:"regulateur-role", narration:"Le régulateur de pression de sortie du condenseur maintient la pression de condensation prévue quand les conditions changent — par exemple quand la température extérieure chute en hiver, ce qui ferait tomber la haute pression trop bas pour que le détendeur travaille correctement. Notez bien ce qu'il fait : il maintient, il module un passage. Il ne coupe pas le compresseur. C'est un organe de régulation, pas de sécurité.", dossier:"regler", title:"Le régulateur maintient", kicker:"Régler · 1", codes:["7.02"], level:"comprendre", text:"Le régulateur de pression de sortie du condenseur maintient la pression de condensation prévue lorsque les conditions changent. Il ne coupe pas le compresseur.", prompt:"Faites varier la température extérieure : l’image reste qualitative.", render:()=>`<div class="panel"><div class="range-row"><strong>Froid</strong><input id="ambient" type="range" min="0" max="100" value="50" aria-label="Température extérieure qualitative"><strong>Chaud</strong></div><div class="flow-row"><span class="flow-box">Condenseur</span><span class="flow-arrow">→</span><span class="flow-box" id="reg-state">Régulateur : position intermédiaire</span><span class="flow-arrow">→</span><span class="flow-box">Ligne liquide</span></div><div class="feedback" id="feedback">Le réglage réel ne se lit jamais sur ce curseur.</div></div>`, wire:()=>{$("#ambient").addEventListener("input",e=>{const v=Number(e.target.value); $("#reg-state").textContent=v<35?"Régulateur : retient davantage":v>70?"Régulateur : laisse davantage passer":"Régulateur : position intermédiaire"; $("#feedback").textContent="La notice fixe la consigne et la méthode. Le curseur montre seulement le rôle de maintien.";});} }),
  screen({ id:"regulateur-vs-pressostat", narration:"Deux organes parlent de pression, et il ne faut pas les confondre. Le régulateur module un passage pour maintenir une valeur : il travaille en permanence. Le pressostat haute pression, lui, ouvre un circuit électrique pour arrêter la machine quand la limite de sécurité est atteinte : il n'agit qu'en dernier recours. Maintenir n'est pas couper. L'un fait de la dentelle en continu, l'autre reste immobile toute sa vie et n'intervient qu'une fois — quand tout le reste a échoué.", dossier:"regler", title:"Maintenir n’est pas couper", kicker:"Régler · 2", codes:["7.02"], level:"appliquer", text:"Deux organes parlent de pression. Le régulateur module le passage. Le pressostat HP ouvre un circuit électrique pour arrêter la machine quand la limite de sécurité est atteinte.", prompt:"Quel organe répond au code 7.02 ?", render:()=>choiceMarkup([{title:"Régulateur de pression",note:"vanne de maintien"},{title:"Pressostat HP",note:"interrupteur de sécurité"},{title:"Ventilateur",note:"déplace l’air"}],"roles"), wire:()=>wireChoice({good:0,messages:["Oui : il se met au point selon la documentation et les conditions prévues.","Il protège le système. Il ne tient pas à lui seul la pression de fonctionnement demandée.","Le ventilateur agit sur l’échange, mais ce n’est pas le régulateur nommé par le référentiel."]}) }),
  screen({ id:"reglage-constructeur", narration:"Une valeur de réglage ne s'invente jamais. Avant de toucher à un organe : identifiez-le, lisez sa référence, retrouvez sa notice, sachez quel fluide circule et dans quelles conditions la machine travaille. Régler à l'oreille, ou recopier la valeur d'une autre machine parce qu'elle lui ressemble, produit un réglage qui n'a aucun fondement. Et cette valeur restera en place des années, appliquée par tous ceux qui passeront après vous en la croyant juste.", dossier:"regler", title:"La valeur n’est jamais inventée", kicker:"Régler · 3", codes:["7.02"], level:"appliquer", text:"Avant tout réglage : identifier l’organe, lire la référence, retrouver la notice, connaître le fluide et les conditions de service. Régler à l’oreille ou copier la valeur d’une autre machine est interdit.", prompt:"Remettez les quatre preuves dans l’ordre logique.", render:()=>`<div class="panel"><div class="sequence" id="sequence">${["Identifier","Lire la notice","Mesurer","Ajuster puis vérifier"].map((x,i)=>`<button class="sequence-step" type="button" data-seq="${i}">${i+1}<br>${x}</button>${i<3?'<span class="sequence-arrow">→</span>':''}`).join("")}</div><div class="feedback" id="feedback">Cliquez dans l’ordre, de l’identification au contrôle final.</div></div>`, wire:()=>{let next=0; $$('[data-seq]').forEach(b=>b.addEventListener("click",()=>{const i=Number(b.dataset.seq); if(i!==next){$("#feedback").className="feedback bad"; $("#feedback").textContent="À corriger : on ne saute ni l’identification, ni la notice, ni la mesure initiale."; return;} b.classList.add("done"); next++; $("#feedback").className="feedback good"; $("#feedback").textContent=next===4?"Ordre complet : le réglage se termine par une nouvelle mesure.":"Étape validée. Continuez.";}));} }),
  screen({ id:"quiz-regulation", narration:"Voici une situation qui vous arrivera. Le pressostat haute pression a coupé, et un collègue propose de monter sa consigne pour éviter l'arrêt. La réponse est non, et elle n'est pas négociable. Le pressostat vient de faire exactement ce pour quoi il existe : il a signalé que la pression atteignait la limite de sécurité. Monter sa consigne ne résout rien — cela supprime la protection en laissant la cause en place. Le geste juste, c'est de chercher pourquoi la pression est montée.", dossier:"regler", title:"Contrôle 2 · Régulation", kicker:"Régler · contrôle", codes:["7.02"], level:"evaluer", text:"Le pressostat HP a coupé. Un collègue propose de monter sa consigne pour éviter l’arrêt.", prompt:"Quelle décision prenez-vous ?", quiz:{choices:["Refuser, rechercher la cause et appliquer la documentation","Monter la consigne jusqu’à ce que la machine tienne","Shunter le pressostat pendant le nettoyage","Ajouter du fluide avant toute mesure"],good:0,explain:"Une coupure HP est un signal de protection. On traite la cause et on distingue toujours sécurité, régulation et défaut d’air."}, render(){return quizMarkup(this)}, wire(){wireQuiz(this)} }),

  screen({ id:"consignation-inspection", narration:"Avant de mettre les mains, on consigne. Le ventilateur et le compresseur peuvent redémarrer tout seuls, sur une régulation ou une temporisation, sans prévenir personne. Avant une inspection manuelle des conduites ou un nettoyage : arrêter, isoler l'alimentation, verrouiller, et vérifier l'absence de remise en marche possible. Ce n'est pas une procédure administrative : c'est ce qui fait la différence entre une main dans un ventilateur à l'arrêt et une main dans un ventilateur qui redémarre.", dossier:"verifier", title:"Avant les mains : consigner", kicker:"Vérifier · 1", codes:["7.05"], level:"appliquer", text:"Le ventilateur et le compresseur peuvent redémarrer. Avant une inspection manuelle des conduites ou un nettoyage : arrêter, isoler l’alimentation, verrouiller et vérifier l’absence de remise en marche selon la procédure du site.", prompt:"Choisissez le premier geste.", render:()=>choiceMarkup([{title:"Consigner l’alimentation",note:"empêcher le redémarrage"},{title:"Passer la main sur le tube",note:"risque mécanique et thermique"},{title:"Bloquer l’hélice avec un outil",note:"ne remplace pas la consignation"}],"lock"), wire:()=>wireChoice({good:0,messages:["La consignation vient avant le contact avec l’équipement.","Observer à distance peut précéder, mais toucher exige l’arrêt et la consignation.","Une hélice bloquée n’isole ni le moteur ni le compresseur."]}) }),
  screen({ id:"conduites", narration:"Deux conduites racontent l'état de cette partie du circuit. La conduite de refoulement, entre le compresseur et le condenseur : elle est chaude, elle vibre, elle subit des cycles de température. Et la conduite liquide, après le condenseur. Sur les deux, cherchez la même chose : traces d'huile, corrosion, frottement, support détendu, déformation. L'huile est le meilleur indicateur qui soit — là où l'huile marque, le fluide s'est échappé.", dossier:"verifier", title:"Deux conduites racontent l’état", kicker:"Vérifier · 2", codes:["7.05"], level:"appliquer", text:"Inspectez la conduite de refoulement entre compresseur et condenseur, puis la conduite liquide après le condenseur. Cherchez traces d’huile, corrosion, frottement, support détendu ou déformation.", prompt:"Ouvrez les quatre familles d’indice.", render:()=>checklistMarkup([{title:"Huile",note:"indice possible de fuite",detail:"Une trace se documente et se contrôle ; elle n’est pas essuyée puis oubliée."},{title:"Frottement",note:"tube contre support",detail:"Le contact répété peut user le tube et créer une fuite future."},{title:"Corrosion",note:"surface attaquée",detail:"Repérez l’étendue et transmettez l’anomalie avant d’agir."},{title:"Fixation",note:"support ou collier",detail:"Le tube reste guidé sans contrainte ni vibration anormale."}]), wire:()=>wireChecklist([{title:"Huile",detail:"Une trace se documente et se contrôle ; elle n’est pas essuyée puis oubliée."},{title:"Frottement",detail:"Le contact répété peut user le tube et créer une fuite future."},{title:"Corrosion",detail:"Repérez l’étendue et transmettez l’anomalie avant d’agir."},{title:"Fixation",detail:"Le tube reste guidé sans contrainte ni vibration anormale."}]) }),
  screen({ id:"demarrer-mesurer", narration:"Une intervention se prépare avant le départ. Notez les conditions attendues et préparez vos points de mesure : vous saurez alors quoi relever, et où. Au démarrage, observez le ventilateur et la montée en régime — beaucoup de défauts ne se voient qu'à ce moment-là. Puis, en fonctionnement stabilisé seulement, relevez les valeurs prévues. Une feuille de route préparée transforme une visite en constat exploitable ; sans elle, vous rapportez des impressions.", dossier:"verifier", title:"Démarrer avec une feuille de route", kicker:"Vérifier · 3", codes:["7.07"], level:"appliquer", text:"Avant le départ, notez les conditions et préparez les points de mesure. Au démarrage, observez le ventilateur et la montée en régime. En fonctionnement stabilisé, relevez les valeurs prévues par la procédure.", prompt:"Ouvrez les quatre temps du contrôle.", render:()=>checklistMarkup([{title:"Avant",note:"état et conditions",detail:"Température ambiante, propreté, obstacles et sécurité sont notés."},{title:"Démarrage",note:"sens et bruit",detail:"Le ventilateur démarre comme prévu, sans bruit ni vibration anormale."},{title:"Fonctionnement",note:"pressions et températures",detail:"Les mesures sont prises avec le matériel adapté et les conditions consignées."},{title:"Arrêt",note:"ordre constructeur",detail:"La machine est arrêtée selon sa commande normale, puis sécurisée si une intervention suit."}]), wire:()=>wireChecklist([{title:"Avant",detail:"Température ambiante, propreté, obstacles et sécurité sont notés."},{title:"Démarrage",detail:"Le ventilateur démarre comme prévu, sans bruit ni vibration anormale."},{title:"Fonctionnement",detail:"Les mesures sont prises avec le matériel adapté et les conditions consignées."},{title:"Arrêt",detail:"La machine est arrêtée selon sa commande normale, puis sécurisée si une intervention suit."}]) }),
  screen({ id:"mesures-conditions", narration:"Une mesure sans contexte ment. Une pression ne se lit jamais seule : elle se lit avec la température ambiante, le fluide en place, l'état du ventilateur, la propreté de la batterie, la charge de l'installation et son régime. La même valeur de haute pression peut être parfaitement normale un jour de canicule et très anormale par quinze degrés. Et quand vous comparez deux relevés, assurez-vous qu'ils ont été pris dans des conditions comparables — sinon la comparaison ne veut rien dire.", dossier:"verifier", title:"Une mesure sans contexte ment", kicker:"Vérifier · 4", codes:["7.07"], level:"comprendre", text:"Une pression se lit avec la température ambiante, le fluide, l’état du ventilateur, la propreté, la charge et le régime de la machine. Comparez des mesures prises dans des conditions comparables.", prompt:"Choisissez le relevé qui peut être interprété.", render:()=>choiceMarkup([{title:"HP + température ambiante + état air + heure",note:"contexte documenté"},{title:"HP seule",note:"aucune condition"},{title:"Bruit décrit de mémoire",note:"pas de mesure ni d’heure"}],"measure"), wire:()=>wireChoice({good:0,messages:["Ce relevé permet une comparaison et une décision argumentée.","La HP seule ne sépare pas encrassement, défaut de ventilateur, ambiance, charge ou autre cause.","Une impression non tracée ne suffit pas pour un rapport d’état."]}) }),
  screen({ id:"sous-refroidissement", narration:"Le sous-refroidissement se calcule en deux mesures et une soustraction. Première mesure : la haute pression, que vous convertissez en température de saturation liquide grâce à la table du fluide. Deuxième mesure : la température réelle du tube liquide, prise avec une sonde de contact, au même régime. Le sous-refroidissement est la différence entre les deux. Il vous dit de combien le liquide a été refroidi au-delà de sa condensation — et donc si le détendeur reçoit bien du liquide franc.", dossier:"verifier", title:"Deux mesures, puis une soustraction", kicker:"Vérifier · 5", codes:["1.02","5.05","7.07"], level:"appliquer", text:"La haute pression est convertie en température de saturation liquide avec la table du fluide. Une sonde de contact mesure le tube liquide au même régime. Le sous-refroidissement est la différence entre les deux, exprimée en kelvins. Pour un mélange à glissement, on utilise le point de bulle côté sous-refroidissement.", prompt:"Un tube liquide à la température de saturation donne zéro kelvin de sous-refroidissement.", render:()=>`<figure class="svg-lesson"><img src="assets/mesure-sous-refroidissement.svg" alt="Pression HP convertie en température de saturation, moins la température du tube liquide."><figcaption>Saturation liquide moins tube liquide : toujours la même soustraction.</figcaption></figure>` }),
  screen({ id:"diagramme-condenseur", narration:"Le même trajet se lit sur le diagramme enthalpique. Le passage dans le condenseur se suit en haut, de la droite vers la gauche : d'abord la désurchauffe, puis le palier de condensation, puis le sous-refroidissement qui pousse le point au-delà de la courbe de liquide saturé. Vous retrouvez exactement les trois zones vues au début du module, mais représentées autrement. Savoir passer de la machine au diagramme et inversement, c'est ce qui vous permettra de raisonner sur des cas que vous n'avez jamais vus.", dossier:"verifier", title:"Le même trajet, vu sur le diagramme", kicker:"Vérifier · 6", codes:["1.02","7.01"], level:"comprendre", text:"Sur le diagramme enthalpique, le passage dans le condenseur se lit de gauche à droite en haut : la désurchauffe, puis le palier de condensation, puis le sous-refroidissement qui pousse le point au-delà de la courbe de liquide saturé.", prompt:"Repérez le palier : c’est là que la vapeur devient liquide, à pression sensiblement constante.", render:()=>`<figure class="svg-lesson"><img src="assets/diagramme-condenseur-focus.svg" alt="Focus du diagramme enthalpique sur la partie condenseur, avec le palier de condensation."><figcaption>Le palier de condensation, et ce qui se passe juste avant et juste après.</figcaption></figure>` }),
  screen({ id:"nettoyer-remesurer", narration:"Nettoyer, puis prouver. Après consignation, le nettoyage suit la méthode du constructeur — et une règle vaut partout : les ailettes ne doivent être ni couchées ni détériorées. Un jet trop puissant ou mal orienté fait plus de mal que la saleté qu'il enlève. Une fois l'unité remise en service et stabilisée, reprenez les mêmes mesures, dans les mêmes conditions. C'est cette comparaison avant-après qui prouve que votre intervention a servi. Sans elle, vous avez nettoyé sans savoir ce que ça a changé.", dossier:"verifier", title:"Nettoyer, puis prouver", kicker:"Vérifier · 7", codes:["7.07","7.08","7.10"], level:"appliquer", text:"Après consignation, le nettoyage suit la méthode du constructeur. Les ailettes ne doivent pas être couchées ni détériorées. Une fois l’unité remise en service, reprenez les mêmes mesures dans des conditions comparables.", prompt:"Faites avancer la séquence.", render:()=>`<div class="panel"><div class="sequence">${["Consigner","Nettoyer selon notice","Contrôler l’air","Redémarrer","Remesurer"].map((x,i)=>`<button class="sequence-step ${i===0?'active':''}" type="button" data-clean="${i}">${i+1}<br>${x}</button>${i<4?'<span class="sequence-arrow">→</span>':''}`).join("")}</div><div class="feedback" id="feedback">Cliquez sur l’étape suivante.</div></div>`, wire:()=>{let next=0; $$('[data-clean]').forEach(b=>b.addEventListener("click",()=>{if(Number(b.dataset.clean)!==next){$("#feedback").className="feedback bad"; $("#feedback").textContent="L’ordre protège la personne et rend la comparaison valable."; return;} b.classList.remove("active"); b.classList.add("done"); next++; const n=$(`[data-clean="${next}"]`); if(n)n.classList.add("active"); $("#feedback").className="feedback good"; $("#feedback").textContent=next===5?"Séquence complète : l’amélioration est prouvée par une nouvelle mesure.":"Étape validée.";}));} }),
  screen({ id:"purge-incondensables", narration:"L'air n'a rien à faire dans un condenseur. Les gaz non condensables entrent pendant les interventions — un tirage au vide insuffisant, un raccord ouvert trop longtemps — et ils se rassemblent au point haut du condenseur, là où rien ne peut les condenser. Ils occupent alors une place et ajoutent leur propre pression. Le symptôme est caractéristique : la haute pression monte alors que la température de condensation, elle, ne bouge pas autant. Cet écart entre les deux est votre indice.", dossier:"verifier", title:"L’air n’a rien à faire dans le condenseur", kicker:"Vérifier · 8", codes:["7.06"], level:"appliquer", text:"Des gaz non condensables entrent pendant les interventions et se rassemblent au point haut du condenseur, où rien ne les condense : la haute pression monte pour la même température de condensation. On les extrait avec un appareil de purge raccordé au point haut, installation à l’arrêt et stabilisée, selon la notice — l’appareil retient le fluide et ne rejette que l’air.", prompt:"Où l’air s’accumule-t-il ?", render:()=>choiceMarkup([{title:"Au point haut du condenseur",note:"là où rien ne le condense"},{title:"Dans le carter du compresseur",note:"on y trouve l’huile, pas l’air du circuit"},{title:"Au fond de l’évaporateur",note:"côté basse pression"}],"purge"), wire:()=>wireChoice({good:0,messages:["C’est là que l’appareil de purge se raccorde, installation à l’arrêt et stabilisée.","Non — les incondensables se rassemblent côté haute pression, au point le plus haut du condenseur.","Non — ils suivent le refoulement et s’accumulent au point haut du côté condensation."]}) }),
  screen({ id:"quiz-diagnostic", narration:"Voici un cas de diagnostic. La batterie est grise, le ventilateur tourne, et la pression de condensation est anormalement haute. Vous avez tous les éléments pour raisonner : le ventilateur fonctionne, donc le débit d'air théorique est là — mais la batterie encrassée l'empêche de traverser. La chaleur sort mal, la pression monte. Le geste juste est le nettoyage, suivi d'une nouvelle mesure. Ni ajout, ni retrait de fluide : la charge n'est pas en cause dans ce scénario.", dossier:"verifier", title:"Contrôle 3 · Diagnostic", kicker:"Vérifier · contrôle", codes:["7.05","7.07","7.10"], level:"evaluer", text:"La batterie est grise, le ventilateur tourne et la pression de condensation est anormalement haute.", prompt:"Quelle suite est la plus défendable ?", quiz:{choices:["Consigner, nettoyer selon la notice, redémarrer et comparer les mesures","Ajouter immédiatement du fluide","Shunter le pressostat HP","Conclure que le compresseur est hors service"],good:0,explain:"Le défaut visible et le signal vont dans le même sens. On traite ce défaut, puis on confirme par la mesure, sans prétendre que la HP seule prouve toute la panne."}, render(){return quizMarkup(this)}, wire(){wireQuiz(this)} }),

  screen({ id:"rapport-observations", narration:"Un rapport utile sépare quatre choses : les faits constatés, les mesures relevées, les actions réalisées, et ce qui reste à faire. Et il nomme précisément. Écrivez « batterie encrassée » plutôt que « condenseur mauvais » : le premier désigne une cause et une action, le second n'est qu'un jugement. Celui qui vous lira dans six mois ne pourra rien faire d'un jugement ; il pourra agir sur un fait daté et localisé.", dossier:"tracer", title:"Écrire ce qui est vu", kicker:"Tracer · 1", codes:["7.09"], level:"appliquer", text:"Un rapport utile sépare les faits, les mesures, les actions et ce qui reste à faire. Écrivez « batterie encrassée » plutôt que « condenseur mauvais ».", prompt:"Complétez un rapport court. Rien n’est enregistré.", render:()=>`<div class="panel"><div class="report-grid"><label>Observation<input id="report-observation" autocomplete="off" placeholder="Ex. batterie grise"></label><label>Mesure et condition<input id="report-measure" autocomplete="off" placeholder="Ex. HP haute, air extérieur…"></label><label>Action<textarea id="report-action" placeholder="Action réalisée"></textarea></label><label>Suite<textarea id="report-next" placeholder="Contrôle ou réserve"></textarea></label></div><button class="primary-button" id="check-report" type="button">Vérifier la structure</button><div class="feedback" id="feedback">Le texte reste seulement dans cet écran.</div></div>`, wire:()=>{$("#check-report").addEventListener("click",()=>{const filled=["#report-observation","#report-measure","#report-action","#report-next"].filter(s=>$(s).value.trim()).length; $("#feedback").className=`feedback ${filled===4?'good':'bad'}`; $("#feedback").textContent=filled===4?"Structure complète : un autre technicien peut comprendre ce qui a été vu, fait et attendu.":`Il manque ${4-filled} rubrique${4-filled>1?'s':''}. Un rapport doit distinguer fait, mesure, action et suite.`;});} }),
  screen({ id:"rapport-risque", narration:"Le référentiel demande de signaler tout problème susceptible d'endommager le système et d'entraîner plus tard une fuite ou une émission. C'est une obligation, et elle demande un raisonnement : il faut relier l'indice constaté à sa conséquence possible. Une trace de frottement sur une conduite n'est pas une fuite aujourd'hui — c'est une fuite probable demain. Le signaler n'est pas de la sur-qualité, c'est votre travail, et c'est ce qui distingue un rapport professionnel d'un simple compte rendu d'intervention.", dossier:"tracer", title:"Nommer le risque futur", kicker:"Tracer · 2", codes:["7.09"], level:"comprendre", text:"Le code 7.09 demande de signaler tout problème susceptible d’endommager le système et d’entraîner plus tard une fuite ou une émission. Il faut donc relier l’indice à sa conséquence possible, sans annoncer une certitude fausse.", prompt:"Choisissez la formulation professionnelle.", render:()=>choiceMarkup([{title:"Tube frotté sur support",note:"usure possible ; contrôle et correction requis"},{title:"Tout va fuir demain",note:"certitude non démontrée"},{title:"RAS",note:"alors qu’un frottement est visible"}],"report"), wire:()=>wireChoice({good:0,messages:["Le fait est précis, le risque est formulé comme un risque, et une suite est demandée.","On ne transforme pas un risque en prédiction certaine.","« RAS » efface une anomalie observable et prive l’intervention suivante d’une information utile."]}) }),
  screen({ id:"quiz-rapport", narration:"Autre situation. Après nettoyage, la pression revient à un niveau cohérent avec la notice et les conditions : l'intervention a fonctionné, et vous pouvez le prouver. Mais une trace de frottement reste sur la conduite liquide. Elle ne fuit pas aujourd'hui. Elle doit malgré tout figurer au rapport, avec sa conséquence possible : frottement, usure, fuite à terme. Le problème résolu et le problème signalé cohabitent très bien dans un même rapport.", dossier:"tracer", title:"Contrôle 4 · Rapport", kicker:"Tracer · contrôle", codes:["7.09"], level:"evaluer", text:"Après nettoyage, la pression revient à un niveau cohérent avec la notice et les conditions. Une trace de frottement reste sur la conduite liquide.", prompt:"Que doit contenir le rapport ?", quiz:{choices:["État initial, conditions et mesures, nettoyage, nouvelle mesure, frottement restant et suite","Nettoyé, fonctionne","Pression correcte, donc aucune anomalie","Remplacer le compresseur"],good:0,explain:"Le rapport garde la preuve avant/après et n’efface pas l’anomalie distincte encore présente."}, render(){return quizMarkup(this)}, wire(){wireQuiz(this)} }),
  screen({ id:"quiz-efficacite", narration:"Dernière question de contrôle : quel entretien aide directement le condenseur à rejeter la chaleur sans faire travailler inutilement le compresseur ? La réponse tient dans tout ce que vous venez de voir : maintenir la batterie propre et l'air libre de circuler. Un condenseur qui rejette bien sa chaleur travaille à une pression plus basse, et un compresseur qui refoule moins haut consomme moins et s'use moins. L'entretien du condenseur est le geste le plus rentable de toute l'installation.", dossier:"tracer", title:"Contrôle 5 · Efficacité", kicker:"Tracer · contrôle", codes:["7.10"], level:"evaluer", text:"Quel entretien aide directement le condenseur à rejeter la chaleur sans faire travailler inutilement le compresseur ?", prompt:"Choisissez la réponse complète.", quiz:{choices:["Maintenir batterie et passage d’air propres, ventilateur et réglages conformes","Ajouter du fluide à chaque visite","Réduire les dégagements autour de l’unité","Neutraliser l’arrêt haute pression"],good:0,explain:"Le maintien du débit d’air, de la propreté et des réglages prévus conserve l’échange et limite une pression de condensation inutilement élevée."}, render(){return quizMarkup(this)}, wire(){wireQuiz(this)} }),
  screen({ id:"bilan", narration:"Le lien à retenir, en une chaîne : batterie grise, donc débit d'air réduit, donc chaleur moins bien rejetée, donc température et pression de condensation en hausse. Ce fil guide votre premier contrôle devant une haute pression anormale, et il sera souvent le bon. Mais gardez la rigueur jusqu'au bout : chaque diagnostic se confirme avec des mesures prises dans des conditions comparables. Une chaîne de raisonnement juste ne dispense jamais de la vérifier.", dossier:"tracer", title:"Le lien à retenir", kicker:"Bilan", text:"Batterie grise → débit d’air réduit → chaleur moins bien rejetée → température et pression de condensation en hausse. Ce fil guide le premier contrôle, mais chaque diagnostic se confirme avec les conditions et les mesures.", prompt:"Votre score porte sur cinq contrôles pédagogiques. Ce n’est pas une validation pratique.", render:()=>{const answered=Object.keys(quizAnswers).length; const correct=screens.filter(s=>s.quiz&&quizAnswers[s.id]===s.quiz.good).length; return `<div class="score"><div class="score-number">${correct}/${screens.filter(s=>s.quiz).length}</div><p>${answered<5?`${5-answered} contrôle${5-answered>1?'s':''} encore sans réponse.`:correct>=4?"Repères acquis. Rejouez maintenant sur une vraie unité encadrée.":"Reprenez les écrans signalés avant le plateau."}</p><button class="primary-button" id="restart-quiz" type="button">Revoir les contrôles</button></div>`;}, wire:()=>{$("#restart-quiz").addEventListener("click",()=>{Object.keys(quizAnswers).forEach(k=>delete quizAnswers[k]); goToId("quiz-installation");});} })
];

function renderHome() {
  $("#dossier-grid").innerHTML = dossiers.map((dossier,index) => `<button class="dossier-button" type="button" data-dossier="${dossier.id}"><b>${index+1}</b><span>${esc(dossier.label)}<small>${esc(dossier.note)}</small></span></button>`).join("");
  $$('[data-dossier]').forEach(button => button.addEventListener("click", () => startCourse(button.dataset.dossier, 1)));
}
function startCourse(dossierId="observer", screenNumber=1) {
  extractMode=false; activeScreens=screens; const matches=screens.filter(item=>item.dossier===dossierId); const target=matches[Math.max(0,Math.min(matches.length-1,screenNumber-1))]||screens[0]; current=screens.indexOf(target); furthest=Math.max(furthest,current); showCourse(); renderCurrent();
}
function startExtract(ids) {
  const found=ids.map(id=>screens.find(item=>item.id===id)).filter(Boolean); if(!found.length){showHome();showStatus("Extrait introuvable.");return;} extractMode=true; activeScreens=found; current=0; furthest=found.length-1; showCourse(); renderCurrent();
}
function showCourse(){ $("#home").hidden=true; $("#course-shell").hidden=false; $("#home-button").hidden=false; $("#exit-button").hidden=false; document.body.classList.add("course-running"); $("#mode-badge").textContent=extractMode?"Mode extrait":"Cours complet"; $("#rail-mode").textContent=extractMode?"EXTRAIT":"PARCOURS"; }
function showHome(){stopSpeech(); document.body.classList.remove("course-running"); $("#home").hidden=false; $("#course-shell").hidden=true; $("#home-button").hidden=true; $("#exit-button").hidden=true; $("#mode-badge").textContent="Cours complet"; history.replaceState(null,"","index.html");}
function currentItem(){return activeScreens[current]}
function renderCurrent(moveFocus=true){
  const item=currentItem(); if(!item)return; stopSpeech(false); furthest=Math.max(furthest,current); $("#lesson-kicker").textContent=item.kicker; $("#lesson-title").textContent=item.title; $("#lesson-text").innerHTML=item.text; $("#action-prompt").textContent=item.prompt; const zone=$("#activity-zone"); zone.innerHTML=item.render?item.render():statement(item); if(item.wire)item.wire(); renderReference(item); renderStepper(item); renderNavigation(); updateUrl(item); if(moveFocus)$("#lesson-title").focus({preventScroll:true});
}
function renderReference(item){const codes=item.codes.length?item.codes.join(" · "):"contexte"; $("#reference-box").innerHTML=`<strong>référentiel</strong> · ${esc(codes)}<br>${esc(item.level)}`;}
function renderStepper(item){
  const groups=extractMode?[{id:"extrait",label:"Extrait"}]:dossiers; $("#stepper").innerHTML=groups.map((dossier,index)=>{const indices=activeScreens.map((s,i)=>({s,i})).filter(x=>extractMode||x.s.dossier===dossier.id).map(x=>x.i); const first=indices[0]??0; const active=extractMode||item.dossier===dossier.id; const done=indices.length&&Math.max(...indices)<furthest; return `<button class="step-button ${active?'active':''} ${done?'done':''}" type="button" data-step="${first}" ${active?'aria-current="step"':''}><b>${index+1}</b><span>${esc(dossier.label)}</span></button>`;}).join("");
  $$('[data-step]').forEach(button=>button.addEventListener("click",()=>goTo(Number(button.dataset.step)))); const total=activeScreens.length; $("#rail-progress").textContent=`${current+1} / ${total}`; $("#progress-bar").style.width=`${((current+1)/total)*100}%`; $("#progress-copy").textContent=current===total-1?"Fin du parcours":`${total-current-1} écran${total-current-1>1?'s':''} à voir`;
}
function renderNavigation(){ $("#prev-button").disabled=current===0; $("#next-button").textContent=current===activeScreens.length-1?(extractMode?"Cours entier":"Retour au sommaire"):"Suivant →"; }
function goTo(index){if(index<0||index>=activeScreens.length)return; current=index; renderCurrent();}
function goToId(id){const index=activeScreens.findIndex(item=>item.id===id); if(index>=0)goTo(index); else{activeScreens=screens;extractMode=false;const full=screens.findIndex(item=>item.id===id);if(full>=0){current=full;showCourse();renderCurrent();}}}
function next(){if(current<activeScreens.length-1)goTo(current+1);else if(extractMode){activeScreens=screens;extractMode=false;current=screens.findIndex(s=>s.id===currentItem().id);showCourse();renderCurrent();}else showHome();}
function previous(){if(current>0)goTo(current-1)}
function updateUrl(item){const url=new URL(location.href); url.search=""; if(extractMode)url.searchParams.set("extrait",activeScreens.map(s=>s.id).join(",")); else{const same=activeScreens.filter(s=>s.dossier===item.dossier); url.searchParams.set("dossier",item.dossier); url.searchParams.set("ecran",String(same.indexOf(item)+1));} history.replaceState(null,"",url);}
async function copyCurrentLink(){const item=currentItem(); const url=new URL(location.href); url.search=""; url.searchParams.set("extrait",item.id); try{await navigator.clipboard.writeText(url.href);showStatus("Lien de cet écran copié.");}catch(_){const input=document.createElement("textarea");input.value=url.href;document.body.append(input);input.select();document.execCommand("copy");input.remove();showStatus("Lien de cet écran copié.");}}
function showStatus(message){clearTimeout(statusTimer);$("#status-message").textContent=message;statusTimer=setTimeout(()=>$("#status-message").textContent="",2600)}
function bestFrenchVoice(){const voices=speechSynthesis.getVoices(); const ranked=voices.map(voice=>{const lang=(voice.lang||"").toLowerCase(),name=(voice.name||"").toLowerCase();let score=0;if(lang==="fr-fr")score+=50;else if(lang.startsWith("fr"))score+=25;if(/natural|naturel|neural|online|google|microsoft|denise|henri|julie|paul|hortense/.test(name))score+=12;return{voice,score};}).sort((a,b)=>b.score-a.score);return ranked[0]?.voice||voices[0]||null;}
function speechSupported(){return "speechSynthesis" in window&&"SpeechSynthesisUtterance" in window}
function speakCurrent(){if(!speechSupported()){showStatus("La voix n’est pas disponible. Le texte reste complet.");return;} stopSpeech(false); autoplay=true; const item=currentItem(); const token=++speechRun; const ditVoix=item.narration || item.speak || ""; if(!ditVoix){showStatus("Cet écran n’a pas encore de narration. Le texte reste complet.");return;} const utterance=new SpeechSynthesisUtterance(ditVoix); utterance.lang="fr-FR";utterance.pitch=1;if(window.PILOTE_VOIX_REGLAGE)window.PILOTE_VOIX_REGLAGE.appliquer(utterance);else utterance.rate=voiceRates[rateIndex];const voice=bestFrenchVoice();if(voice)utterance.voice=voice;utterance.onstart=()=>{if(token!==speechRun)return;speaking=true;paused=false;updateVoiceButtons();};utterance.onend=()=>{if(token!==speechRun)return;speaking=false;paused=false;updateVoiceButtons();};utterance.onerror=e=>{if(token!==speechRun||["canceled","interrupted"].includes(e.error))return;speaking=false;paused=false;updateVoiceButtons();showStatus("Lecture vocale indisponible.");};speechSynthesis.speak(utterance);}
function toggleSpeech(){if(!speechSupported()){showStatus("La voix n’est pas disponible.");return;}if(speaking&&!paused){speechSynthesis.pause();paused=true;updateVoiceButtons();}else if(speaking&&paused){speechSynthesis.resume();paused=false;updateVoiceButtons();}else speakCurrent();}
function stopSpeech(disableAutoplay=true){speechRun++;if(speechSupported())speechSynthesis.cancel();speaking=false;paused=false;if(disableAutoplay)autoplay=false;updateVoiceButtons();}
function updateVoiceButtons(){const button=$("#listen");if(!button)return;button.innerHTML=paused?'<span aria-hidden="true">▶</span><span>Reprendre</span>':speaking?'<span aria-hidden="true">Ⅱ</span><span>Pause</span>':'<span aria-hidden="true">▶</span><span>Écouter</span>';$("#stop-voice").disabled=!speaking;$("#speed-value").textContent=voiceRates[rateIndex].toFixed(2).replace(".",",")+"×";}
function changeRate(direction){rateIndex=Math.max(0,Math.min(voiceRates.length-1,rateIndex+direction));saveRate();updateVoiceButtons();if(speaking||paused)speakCurrent();}
function buildPrintBook(){const quizCount=screens.filter(s=>s.quiz).length;$("#print-book").innerHTML=`<header class="print-title"><h1>Condenseur — installer, régler, vérifier</h1><p>Fiche g7b · 24 écrans · ${quizCount} contrôles · arrêté du 21 novembre 2025.</p><p><strong>Principe :</strong> batterie grise → débit d’air réduit → chaleur moins bien rejetée → pression de condensation qui tend à monter.</p></header>`+screens.map((item,index)=>`<article class="print-screen"><h2>${index+1}. ${esc(item.title)}</h2><p>${item.text}</p>${item.prompt?`<h3>Action à réaliser</h3><p>${esc(item.prompt)}</p>`:""}${item.quiz?`<div class="print-answer"><strong>Correction :</strong> ${esc(item.quiz.choices[item.quiz.good])}. ${esc(item.quiz.explain)}</div>`:""}<p class="print-codes">Référentiel · ${item.codes.length?esc(item.codes.join(" · ")):"contexte"}</p></article>`).join("");}
function handleInitialUrl(){const params=new URLSearchParams(location.search);const extract=params.get("extrait");if(extract){startExtract(extract.split(",").map(x=>x.trim()).filter(Boolean));return;}const dossier=params.get("dossier");if(dossier){startCourse(dossier,Number(params.get("ecran"))||1);return;}showHome();}
function bindGlobalEvents(){
  $("#start-button").addEventListener("click",()=>startCourse());$("#home-button").addEventListener("click",showHome);$("#exit-button").addEventListener("click",showHome);$("#prev-button").addEventListener("click",previous);$("#next-button").addEventListener("click",next);$("#copy-link").addEventListener("click",copyCurrentLink);$("#listen").addEventListener("click",toggleSpeech);$("#stop-voice").addEventListener("click",()=>stopSpeech());$("#slower").addEventListener("click",()=>changeRate(-1));$("#faster").addEventListener("click",()=>changeRate(1));
  addEventListener("keydown",event=>{const tag=document.activeElement?.tagName;if(["INPUT","TEXTAREA","SELECT","BUTTON"].includes(tag))return;if(event.key==="ArrowRight"){event.preventDefault();next();}else if(event.key==="ArrowLeft"){event.preventDefault();previous();}else if(event.key===" "){event.preventDefault();toggleSpeech();}else if(event.key==="Escape")showHome();});
  addEventListener("beforeunload",()=>stopSpeech());document.addEventListener("visibilitychange",()=>{if(document.hidden)stopSpeech();});if(speechSupported())speechSynthesis.addEventListener?.("voiceschanged",()=>{});
}

renderHome();buildPrintBook();bindGlobalEvents();updateVoiceButtons();handleInitialUrl();
