"use strict";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const dossiers = [
  { id:"orienter", label:"Orienter", note:"registre et points" },
  { id:"soupconner", label:"Soupçonner", note:"méthode indirecte" },
  { id:"localiser", label:"Localiser", note:"méthode directe" },
  { id:"comparer", label:"Comparer", note:"choisir sans confondre" },
  { id:"tracer", label:"Tracer", note:"rendre le contrôle utile" },
  { id:"bilan", label:"Bilan", note:"tenir le fil" },
];

const screenIllustrations = {
  "regle-aujourdhui": ["../bibliotheque/illu-x-detective.webp", "Loupe examinant plusieurs points d’une installation frigorifique."],
  "registre-dabord": ["../bibliotheque/icones/ico-registre.png", "Pictogramme métier représentant le registre de l’équipement."],
  "controle-visuel": ["../bibliotheque/illu-g4a.webp", "Technicien examinant plusieurs points sensibles sur une installation."],
  "controle-orienter": ["../bibliotheque/illu-x-detective.webp", "Loupe utilisée comme repère visuel de l’enquête."],
  "indirect-definition": ["../bibliotheque/illu-g4b.webp", "Manomètre et thermomètre reliés par un point d’interrogation."],
  "instruments-portables": ["../svg/lecture-table.svg", "Schéma manuel reliant un manomètre, une table de saturation et une sonde de température."],
  "controle-indirect": ["../bibliotheque/illu-g4b.webp", "Manomètre et thermomètre représentant la méthode indirecte."],
  "direct-definition": ["../bibliotheque/illu-g4c.webp", "Solution moussante appliquée sur un raccord."],
  "choisir-methode": ["../bibliotheque/illu-g4a.webp", "Technicien utilisant un détecteur de fuite sur une installation."],
  "detecteur-conditions": ["../bibliotheque/icones/ico-detecteur-fuite.png", "Pictogramme du détecteur électronique de fuite."],
  "controle-direct": ["../bibliotheque/illu-g4c.webp", "Recherche directe sur un raccord avec une solution moussante."],
  "enquete-complete": ["../bibliotheque/illu-x-detective.webp", "Loupe suivant les indices d’une enquête technique."],
  "controle-comparer": ["../bibliotheque/illu-x-detective.webp", "Loupe représentant le passage de l’indice à la localisation."],
  "registre-resultat": ["../bibliotheque/icones/ico-registre.png", "Pictogramme du registre de contrôle."],
  "controle-trace": ["../bibliotheque/icones/ico-registre.png", "Pictogramme du registre de l’équipement."],
  "ordre-final": ["../bibliotheque/illu-x-detective.webp", "Loupe regroupant les points contrôlés de l’installation."],
  "bilan": ["../bibliotheque/illu-x-detective.webp", "Illustration finale de l’enquête d’étanchéité."],
};

const quizAnswers = {};
const completed = new Set();
let current = 0;
let furthest = 0;
let extractMode = false;
let activeScreens = [];
let speechRun = 0;
let speaking = false;
let paused = false;
let autoplay = false;
let statusTimer = 0;
const voiceRates = [0.8, 0.95, 1.1, 1.25];
let rateIndex = safeStoredRateIndex();

function safeStoredRateIndex(){try{const stored=Number(localStorage.getItem("etancheite-voice-rate"));const index=voiceRates.indexOf(stored);return index>=0?index:1}catch(_){return 1}}
function saveRate(){try{localStorage.setItem("etancheite-voice-rate",String(voiceRates[rateIndex]))}catch(_){}}
function esc(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function stripHtml(value){const box=document.createElement("div");box.innerHTML=value;return box.textContent||""}
function screen(data){const visual=screenIllustrations[data.id]||["",""];return{level:"comprendre",codes:[],prompt:"",speak:"",requiresAction:false,image:visual[0],imageAlt:visual[1]||"Illustration pédagogique de l’étape.",...data}}
function completeCurrent(message="Action réalisée. Vous pouvez continuer."){completed.add(activeScreens[current].id);updateNav();setStatus(message)}
function setStatus(message){clearTimeout(statusTimer);$("#status-message").textContent=message;statusTimer=setTimeout(()=>{$("#status-message").textContent=""},2600)}

function choiceMarkup(choices){return `<div class="panel"><div class="cards" style="--cols:${Math.min(choices.length,3)}">${choices.map((choice,index)=>`<button class="choice" type="button" data-choice="${index}"><strong>${esc(choice.title)}</strong><small>${esc(choice.note||"")}</small></button>`).join("")}</div><div class="feedback" id="feedback">Choisissez, puis lisez la conséquence.</div></div>`}
function wireChoice(good,messages){$$('[data-choice]').forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.choice);$$('[data-choice]').forEach(item=>item.classList.remove("good","bad"));button.classList.add(index===good?"good":"bad");const feedback=$("#feedback");feedback.className=`feedback ${index===good?"good":"bad"}`;feedback.innerHTML=`<strong>${index===good?"Correct.":"À corriger."}</strong> ${esc(messages[index])}`;if(index===good)completeCurrent("Décision correcte. Vous pouvez continuer.")}))}
function checklistMarkup(items){return `<div class="panel"><div class="cards" style="--cols:${Math.min(items.length,3)}">${items.map((item,index)=>`<button class="check-card" type="button" data-check="${index}" aria-pressed="false"><strong>${esc(item.title)}</strong><small>${esc(item.note)}</small></button>`).join("")}</div><div class="feedback" id="feedback">Ouvrez chaque point.</div></div>`}
function wireChecklist(items){$$('[data-check]').forEach(button=>button.addEventListener("click",()=>{button.classList.add("good");button.setAttribute("aria-pressed","true");const item=items[Number(button.dataset.check)];const feedback=$("#feedback");feedback.className="feedback good";feedback.innerHTML=`<strong>${esc(item.title)}.</strong> ${esc(item.detail)}`;if($$('[data-check][aria-pressed="false"]').length===0)completeCurrent("Tous les points ont été examinés.")}))}
function sequenceMarkup(items){return `<div class="panel"><div class="sequence">${items.map((item,index)=>`<button class="sequence-step" type="button" data-sequence="${index}">${index+1}<br>${esc(item)}</button>${index<items.length-1?'<span class="sequence-arrow">→</span>':''}`).join("")}</div><div class="feedback" id="feedback">Cliquez dans l’ordre.</div></div>`}
function wireSequence(items){let next=0;$$('[data-sequence]').forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.sequence);const feedback=$("#feedback");if(index!==next){feedback.className="feedback bad";feedback.textContent="À corriger : revenez au premier geste non validé.";return}button.classList.add("done");next+=1;feedback.className="feedback good";feedback.textContent=next===items.length?"Ordre complet.":"Étape validée. Continuez.";if(next===items.length)completeCurrent("Ordre complet. Vous pouvez continuer.")}))}
function quizMarkup(item){const saved=quizAnswers[item.id];return `<div class="panel"><div class="cards" style="--cols:2">${item.quiz.choices.map((choice,index)=>`<button class="choice ${saved===index?(index===item.quiz.good?"good":"bad"):""}" type="button" data-quiz="${index}" ${saved!==undefined?"disabled":""}><strong>${String.fromCharCode(65+index)}.</strong><small>${esc(choice)}</small></button>`).join("")}</div><div class="feedback ${saved===undefined?"":saved===item.quiz.good?"good":"bad"}" id="feedback">${saved===undefined?"Choisissez une réponse.":`<strong>${saved===item.quiz.good?"Correct.":"À revoir."}</strong> ${esc(item.quiz.explain)}`}</div></div>`}
function wireQuiz(item){$$('[data-quiz]').forEach(button=>button.addEventListener("click",()=>{if(quizAnswers[item.id]!==undefined)return;quizAnswers[item.id]=Number(button.dataset.quiz);completed.add(item.id);renderCurrent(false)}))}

const screens = [
  screen({id:"regle-aujourdhui",dossier:"orienter",title:"Deux vérités à tenir ensemble",kicker:"Orienter · actualité",level:"decouvrir",text:"Le référentiel 2024/2215 cite encore le règlement 1516/2007 pour les compétences 4.03 à 4.07. Ce règlement a pourtant été abrogé le 23 juillet 2026, sans remplacement, parce que des méthodes actualisées sont désormais utilisées.",prompt:"Pour l’examen, connaissez les neuf compétences. Sur le terrain, appliquez la procédure actuelle du site, la notice et les consignes validées.",render:()=>'<div class="law-note"><strong>RÉFÉRENTIEL ≠ PROCÉDURE ACTUELLE</strong><p>Le cours conserve les mots « directe » et « indirecte » pour préparer l’évaluation. Il ne transforme aucun ancien seuil ni aucune ancienne méthode en consigne de chantier.</p></div>'}),
  screen({id:"registre-dabord",dossier:"orienter",title:"Le registre donne la première piste",kicker:"Orienter · 1",codes:["4.02"],level:"appliquer",requiresAction:true,text:"Avant l’instrument, consultez le registre. Il donne le fluide, la charge déclarée, les incidents, les réparations et les zones déjà problématiques. Dans notre enquête, un raccord flare de la ligne liquide a déjà été repris.",prompt:"Sélectionnez les trois informations qui orientent réellement le contrôle.",render:()=>`<div class="panel"><div class="registry">${[{t:"Fluide et charge",n:"Identifier l’équipement"},{t:"Raccord flare déjà réparé",n:"Priorité de contrôle"},{t:"Ajout récent de fluide",n:"Perte possible à expliquer"},{t:"Couleur de la porte",n:"Sans lien avec l’étanchéité"}].map((item,index)=>`<button type="button" data-register="${index}"><strong>${item.t}</strong>${item.n}</button>`).join("")}</div><button class="primary-button" id="check-register" type="button">Vérifier la sélection</button><div class="feedback" id="feedback">Trois éléments sont utiles.</div></div>`,wire:()=>{const selected=new Set();$$('[data-register]').forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.register);if(selected.has(index)){selected.delete(index);button.classList.remove("selected","noise")}else{selected.add(index);button.classList.add("selected")}}));$("#check-register").addEventListener("click",()=>{const good=[0,1,2].every(index=>selected.has(index))&&selected.size===3;const feedback=$("#feedback");feedback.className=`feedback ${good?"good":"bad"}`;feedback.textContent=good?"Le registre désigne le raccord repris comme suspect prioritaire.":"À corriger : gardez fluide/charge, réparation antérieure et ajout récent.";if(selected.has(3))$('[data-register="3"]').classList.add("noise");if(good)completeCurrent("Registre exploité. La piste prioritaire est identifiée.")})}}),
  screen({id:"points-sensibles",dossier:"orienter",title:"Une fuite préfère les assemblages",kicker:"Orienter · 2",codes:["4.01"],level:"appliquer",requiresAction:true,text:"Les points sensibles sont les joints, vannes, raccords, filtres démontables, connexions aux organes de sécurité et parties soumises aux vibrations. Le registre indique où commencer, mais tout le système reste à examiner.",prompt:"Ouvrez les six familles repérées sur le schéma.",render:()=>`<div class="photo-card"><img src="../svg/points-de-fuite.svg" alt="Circuit frigorifique avec six familles de points de fuite potentiels."><div class="hotspot-list">${["Joints et raccords","Vannes et presse-étoupes","Brasures","Filtres et voyants","Capteurs et sécurités","Zones soumises aux vibrations"].map((label,index)=>`<button type="button" data-hotspot="${index}">${label}</button>`).join("")}</div><div class="feedback" id="feedback">Un tube intact n’est pas le premier suspect.</div></div>`,wire:()=>{$$('[data-hotspot]').forEach(button=>button.addEventListener("click",()=>{button.classList.add("seen");const feedback=$("#feedback");feedback.className="feedback good";feedback.textContent="Point sensible repéré. Cherchez une trace, une dégradation ou un historique concordant.";if($$('[data-hotspot]:not(.seen)').length===0)completeCurrent("Les six familles de points sensibles sont repérées.")}))}}),
  screen({id:"controle-visuel",dossier:"orienter",title:"Voir et toucher avant d’instrumenter",kicker:"Orienter · 3",codes:["4.03"],level:"appliquer",requiresAction:true,text:"Le contrôle visuel et manuel cherche des traces d’huile, de la corrosion, du givre anormal, un joint dégradé, un frottement, une fixation desserrée ou une vibration. Il prépare la suite sans conclure seul.",prompt:"Examinez les quatre signes de notre installation.",render:()=>checklistMarkup([{title:"Trace d’huile",note:"près du flare repris",detail:"Indice fort au même endroit que l’historique, mais localisation encore à confirmer."},{title:"Tuyau frotté",note:"contre une arête",detail:"La vibration et le frottement créent une zone à contrôler."},{title:"Givre anormal",note:"sur une zone localisée",detail:"Le givre peut signaler un fonctionnement anormal ; il ne nomme pas seul la cause."},{title:"Fixation desserrée",note:"vibration visible",detail:"La zone soumise aux vibrations rejoint la liste des points sensibles."}]),wire:()=>wireChecklist([{title:"Trace d’huile",detail:"Indice fort au même endroit que l’historique, mais localisation encore à confirmer."},{title:"Tuyau frotté",detail:"La vibration et le frottement créent une zone à contrôler."},{title:"Givre anormal",detail:"Le givre peut signaler un fonctionnement anormal ; il ne nomme pas seul la cause."},{title:"Fixation desserrée",detail:"La zone soumise aux vibrations rejoint la liste des points sensibles."}])}),
  screen({id:"controle-orienter",dossier:"orienter",title:"Contrôle 1 · Orienter",kicker:"Orienter · contrôle",codes:["4.01","4.02","4.03"],level:"evaluer",requiresAction:true,text:"Vous arrivez devant l’installation. Un collègue allume immédiatement son détecteur.",prompt:"Quelle est votre première séquence ?",quiz:{choices:["Registre, points sensibles, contrôle visuel et manuel","Détecteur, resserrage, ajout de fluide","Mise sous azote sans consulter l’historique","Lecture d’une seule pression puis conclusion"],good:0,explain:"Le registre oriente les points sensibles ; le contrôle visuel et manuel prépare le choix de mesure."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"indirect-definition",dossier:"soupconner",title:"L’indirect répond : « quelque chose cloche-t-il ? »",kicker:"Soupçonner · 1",codes:["4.04"],level:"comprendre",text:"La méthode indirecte analyse le fonctionnement. Pressions, températures, courant du compresseur, niveaux ou quantité ajoutée peuvent révéler une dérive. Elle rend une fuite plausible ; elle ne donne pas son adresse.",prompt:"Retenez le verbe : la méthode indirecte soupçonne.",render:()=>'<div class="method-line"><div class="method-node indirect">MESURER<br>le fonctionnement</div><span class="method-arrow">→</span><div class="method-node">SOUPÇONNER<br>une perte de charge</div><span class="method-arrow">≠</span><div class="method-node direct">LOCALISER<br>un point précis</div></div>'}),
  screen({id:"instruments-portables",dossier:"soupconner",title:"Trois instruments, trois familles d’indices",kicker:"Soupçonner · 2",codes:["4.05"],level:"appliquer",requiresAction:true,text:"Le manomètre renseigne les pressions. Le thermomètre mesure les températures utiles aux comparaisons. Le multimètre contrôle la cohérence électrique et le courant du compresseur. Chaque résultat se lit avec la notice et les conditions de fonctionnement.",prompt:"Choisissez l’association complète.",render:()=>choiceMarkup([{title:"Manomètre → pression",note:"Thermomètre → température · multimètre → électrique"},{title:"Manomètre → charge exacte",note:"Thermomètre → fuite localisée"},{title:"Multimètre → type de fluide",note:"Manomètre → état du registre"}]),wire:()=>wireChoice(0,["Chaque instrument répond à sa grandeur ; leur convergence oriente le diagnostic.","Aucun manomètre ne pèse la charge et aucune température ne localise seule une fuite.","Le fluide se lit sur l’identification de l’équipement, pas au multimètre."])}),
  screen({id:"indices-convergents",dossier:"soupconner",title:"Un indice seul ne conclut rien",kicker:"Soupçonner · 3",codes:["4.04","4.05"],level:"appliquer",requiresAction:true,text:"Notre installation refroidit moins bien. Les paramètres s’écartent de son fonctionnement attendu et le registre mentionne un ajout récent. Plusieurs indices concordants justifient de rechercher une fuite ; une seule valeur isolée ne suffit pas.",prompt:"Gardez les quatre indices utiles et écartez le bruit.",render:()=>`<div class="panel"><div class="evidence-board">${[{t:"Pressions anormales",ok:true},{t:"Températures incohérentes",ok:true},{t:"Courant compresseur modifié",ok:true},{t:"Ajout récent de fluide",ok:true},{t:"Peinture de l’unité",ok:false},{t:"Marque des tournevis",ok:false}].map((item,index)=>`<button class="evidence-card" type="button" data-evidence="${index}" data-good="${item.ok}"><strong>${item.t}</strong>${item.ok?"Indice à interpréter":"Information sans valeur pour cette enquête"}</button>`).join("")}</div><button class="primary-button" id="check-evidence" type="button">Vérifier les indices</button><div class="feedback" id="feedback">Sélectionnez ce qui décrit le fonctionnement ou l’historique.</div></div>`,wire:()=>{const selected=new Set();$$('[data-evidence]').forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.evidence);if(selected.has(index)){selected.delete(index);button.classList.remove("kept","rejected")}else{selected.add(index);button.classList.add(button.dataset.good==="true"?"kept":"rejected")}}));$("#check-evidence").addEventListener("click",()=>{const good=[0,1,2,3].every(index=>selected.has(index))&&selected.size===4;const feedback=$("#feedback");feedback.className=`feedback ${good?"good":"bad"}`;feedback.textContent=good?"Les indices convergent : une fuite devient plausible, mais elle n’est pas localisée.":"À corriger : gardez seulement les paramètres et l’historique pertinents.";if(good)completeCurrent("Indices convergents identifiés.")})}}),
  screen({id:"indirect-conclusion",dossier:"soupconner",title:"Soupçonner oblige à poursuivre",kicker:"Soupçonner · 4",codes:["4.04"],level:"evaluer",requiresAction:true,text:"La méthode indirecte montre une dérive compatible avec une perte de charge. Le registre et la trace d’huile désignent le raccord flare comme piste prioritaire.",prompt:"Quelle phrase peut être écrite à ce stade ?",render:()=>choiceMarkup([{title:"Fuite soupçonnée",note:"Une méthode directe doit chercher le point exact"},{title:"Fuite prouvée au flare",note:"La localisation n’est pas encore confirmée"},{title:"Installation étanche",note:"Les indices disent l’inverse"}]),wire:()=>wireChoice(0,["Vous avez une hypothèse étayée et une zone prioritaire.","La méthode indirecte n’a pas localisé physiquement l’échappement.","L’absence de localisation ne transforme pas les indices en conformité."])}),
  screen({id:"controle-indirect",dossier:"soupconner",title:"Contrôle 2 · Méthode indirecte",kicker:"Soupçonner · contrôle",codes:["4.04","4.05"],level:"evaluer",requiresAction:true,text:"Les pressions, températures et le courant du compresseur s’écartent du fonctionnement attendu.",prompt:"Que permet cette convergence ?",quiz:{choices:["Soupçonner une fuite et choisir une recherche directe adaptée","Écrire immédiatement le point exact de fuite","Décider d’une charge complémentaire sans recherche","Déclarer le détecteur électronique inutile"],good:0,explain:"L’indirect analyse et oriente. La localisation réclame une méthode directe adaptée."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"direct-definition",dossier:"localiser",title:"Le direct répond : « où le fluide s’échappe-t-il ? »",kicker:"Localiser · 1",codes:["4.06","4.07"],level:"comprendre",text:"Une méthode directe cherche un point précis. Certaines vérifications se font sans ouvrir le circuit ; d’autres supposent une intervention dans le circuit. Cette frontière est une compétence à part entière.",prompt:"Retenez le verbe : la méthode directe localise.",render:()=>'<div class="method-compare"><section class="method-card indirect"><h3>Sans ouvrir le circuit</h3><p>Détecteur adapté, solution moussante appliquée sur une zone accessible selon la procédure.</p><strong>Code 4.07</strong></section><section class="method-card direct"><h3>Avec intervention dans le circuit</h3><p>Méthode autorisée seulement dans le périmètre, avec la procédure, le matériel et les compétences correspondants.</p><strong>Code 4.06</strong></section></div>'}),
  screen({id:"choisir-methode",dossier:"localiser",title:"Choisir la méthode la moins intrusive",kicker:"Localiser · 2",codes:["4.06","4.07"],level:"appliquer",requiresAction:true,text:"Le circuit fonctionne, le registre désigne un raccord accessible et les indices indirects convergent. Vous devez localiser sans ouvrir le circuit.",prompt:"Choisissez la première recherche compatible avec cette situation.",render:()=>choiceMarkup([{title:"Détecteur adapté au fluide",note:"Recherche directe sans ouvrir"},{title:"Introduire un traceur",note:"Intervention dans le circuit"},{title:"Ajouter du fluide",note:"Ne localise rien"}]),wire:()=>wireChoice(0,["Vous cherchez la zone précise sans modifier le circuit.","Cette option suppose une intervention ; elle ne répond pas au besoin le moins intrusif.","Ajouter du fluide masque le problème et ne fournit aucune localisation."])}),
  screen({id:"detecteur-conditions",dossier:"localiser",title:"Le détecteur doit être prêt et adapté",kicker:"Localiser · 3",codes:["4.08"],level:"appliquer",requiresAction:true,text:"Avant le balayage, identifiez le fluide, vérifiez que l’appareil convient, appliquez son autocontrôle et préparez des conditions qui ne dispersent pas le prélèvement. Les exigences exactes viennent de la procédure actuelle et de la notice.",prompt:"Quel ensemble permet un résultat interprétable ?",render:()=>choiceMarkup([{title:"Appareil adapté et contrôlé",note:"Air calme · notice appliquée · zone accessible"},{title:"Appareil inconnu",note:"Ventilateur en marche · passage rapide"},{title:"Détecteur adapté à un autre fluide",note:"Alerte acceptée sans confirmation"}]),wire:()=>wireChoice(0,["L’instrument et les conditions font partie de la preuve.","Un passage rapide dans l’air brassé peut manquer la zone ou déplacer l’alerte.","Un détecteur non adapté ne permet pas de conclure."])}),
  screen({id:"balayage-detecteur",dossier:"localiser",title:"Balayez les points, pas le local au hasard",kicker:"Localiser · 4",codes:["4.08"],level:"appliquer",requiresAction:true,text:"Le registre et l’inspection ont donné un ordre de priorité. La sonde suit les raccords et les zones sensibles dans les conditions prévues par sa notice. Notre scénario place la fuite sur le flare déjà réparé.",prompt:"Contrôlez les zones jusqu’à retrouver le point concordant.",render:()=>`<div class="detector-board"><div class="detector-zones">${["Brasure haute","Vanne de service","Raccord flare repris","Filtre déshydrateur"].map((label,index)=>`<button class="detector-zone" type="button" data-zone="${index}">${label}</button>`).join("")}</div><img src="../svg/balayage-detecteur.svg" alt="Schéma manuel montrant la sonde d’un détecteur longeant un raccord."><div class="feedback" id="feedback">Commencez par la zone prioritaire donnée par le registre.</div></div>`,wire:()=>{$$('[data-zone]').forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.zone);button.classList.add(index===2?"found":"checked");const feedback=$("#feedback");feedback.className=`feedback ${index===2?"good":""}`;feedback.textContent=index===2?"Alerte au raccord flare repris : la localisation concorde avec le registre et la trace d’huile. Elle doit encore être confirmée.":"Pas d’alerte concordante ici. Poursuivez selon l’ordre de contrôle.";if(index===2)completeCurrent("Zone localisée. Il reste à confirmer l’alerte.")}))}}),
  screen({id:"confirmer-alerte",dossier:"localiser",title:"Une alerte se confirme",kicker:"Localiser · 5",codes:["4.08"],level:"evaluer",requiresAction:true,text:"Le détecteur réagit près du raccord flare. Une alerte unique ne suffit pas : l’air, le déplacement de la sonde ou une contamination peuvent perturber la lecture.",prompt:"Quelle suite rend le résultat plus solide ?",render:()=>choiceMarkup([{title:"Repasser selon la notice",note:"Conditions maîtrisées · résultat concordant"},{title:"Écrire la fuite immédiatement",note:"Un seul signal suffit"},{title:"Resserrer tous les raccords",note:"Intervention sans diagnostic"}]),wire:()=>wireChoice(0,["La répétition dans les bonnes conditions renforce la localisation.","La trace doit distinguer alerte et localisation confirmée.","Un resserrage général modifie le système et peut créer d’autres défauts."])}),
  screen({id:"controle-direct",dossier:"localiser",title:"Contrôle 3 · Méthode directe",kicker:"Localiser · contrôle",codes:["4.06","4.07","4.08"],level:"evaluer",requiresAction:true,text:"Vous devez contrôler un raccord accessible sans ouvrir le circuit.",prompt:"Quelle démarche est cohérente ?",quiz:{choices:["Détecteur adapté, autocontrôle, balayage ciblé et confirmation","Introduction systématique d’un traceur dans le circuit","Passage très rapide pendant que le ventilateur brasse l’air","Ajout de fluide jusqu’à disparition du défaut"],good:0,explain:"Le choix répond au code 4.07 et l’usage raisonné du détecteur au code 4.08."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"deux-methodes",dossier:"comparer",title:"Les méthodes répondent à deux questions",kicker:"Comparer · 1",codes:["4.04","4.06","4.07"],level:"comprendre",text:"La méthode indirecte analyse des paramètres et demande : « une perte de charge est-elle plausible ? ». La méthode directe examine une zone et demande : « où se trouve l’échappement ? ». Elles se renforcent ; elles ne se remplacent pas.",prompt:"Lisez le fil complet de gauche à droite.",render:()=>'<div class="method-line"><div class="method-node indirect">INDIRECTE<br>soupçonne</div><span class="method-arrow">→</span><div class="method-node">HYPOTHÈSE<br>zone prioritaire</div><span class="method-arrow">→</span><div class="method-node direct">DIRECTE<br>localise</div></div>'}),
  screen({id:"frontiere-circuit",dossier:"comparer",title:"La frontière est l’ouverture du circuit",kicker:"Comparer · 2",codes:["4.06","4.07"],level:"appliquer",requiresAction:true,text:"Le même objectif — trouver une fuite — peut appeler des actes de périmètres différents. Le code 4.07 ne nécessite pas d’intervenir dans le circuit. Le code 4.06 couvre une méthode directe qui implique cette intervention.",prompt:"Classez la situation demandée : détecteur sur un raccord accessible, circuit fermé.",render:()=>choiceMarkup([{title:"Sans intervenir dans le circuit",note:"Code 4.07"},{title:"Avec intervention dans le circuit",note:"Code 4.06"},{title:"Méthode indirecte",note:"Analyse de paramètres"}]),wire:()=>wireChoice(0,["Le circuit reste fermé : la recherche directe relève ici de 4.07.","Aucune ouverture ni introduction dans le circuit n’est demandée.","Le détecteur cherche un point précis : c’est une méthode directe."])}),
  screen({id:"enquete-complete",dossier:"comparer",title:"Une enquête, quatre preuves",kicker:"Comparer · 3",codes:["4.02","4.03","4.04","4.07","4.08","4.09"],level:"appliquer",requiresAction:true,text:"Dans notre cas, chaque étape réduit l’incertitude. Le registre désigne le flare, l’inspection voit une trace d’huile, les paramètres rendent la fuite plausible, puis le détecteur localise et confirme.",prompt:"Reconstituez le fil avant d’écrire le registre.",render:()=>sequenceMarkup(["Registre et historique","Visuel et manuel","Indirecte : soupçonner","Directe : localiser","Consigner"]),wire:()=>wireSequence(["Registre et historique","Visuel et manuel","Indirecte : soupçonner","Directe : localiser","Consigner"])}),
  screen({id:"controle-comparer",dossier:"comparer",title:"Contrôle 4 · Comparer",kicker:"Comparer · contrôle",codes:["4.06","4.07"],level:"evaluer",requiresAction:true,text:"Les paramètres indiquent une perte de charge possible. Un technicien écrit déjà : « fuite sur le flare ».",prompt:"Pourquoi sa conclusion va-t-elle trop loin ?",quiz:{choices:["L’indirecte soupçonne ; une méthode directe doit encore localiser","Une méthode indirecte donne toujours le point exact","Le registre interdit d’utiliser un détecteur","Une trace d’huile prouve à elle seule l’étanchéité"],good:0,explain:"Le passage de l’hypothèse à la localisation est précisément ce qui relie les deux méthodes."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"registre-resultat",dossier:"tracer",title:"Le registre raconte ce qui a réellement été fait",kicker:"Tracer · 1",codes:["4.09"],level:"appliquer",requiresAction:true,text:"La trace distingue l’équipement, la date, la méthode, les zones contrôlées, les conditions utiles, le résultat et la suite donnée. Elle n’écrit ni une certitude non obtenue ni une conformité générale à partir d’un contrôle partiel.",prompt:"Ouvrez les quatre parties indispensables.",render:()=>checklistMarkup([{title:"Contexte",note:"équipement · fluide · date",detail:"La trace doit permettre d’identifier sans ambiguïté le contrôle."},{title:"Méthode",note:"indirecte ou directe",detail:"Notez les instruments et la procédure appliquée, sans inventer de valeur."},{title:"Résultat",note:"faits et localisation",detail:"Séparez observation, alerte et localisation confirmée."},{title:"Suite",note:"action ou réserve",detail:"Indiquez ce qui a été fait et ce qui reste à traiter."}]),wire:()=>wireChecklist([{title:"Contexte",detail:"La trace doit permettre d’identifier sans ambiguïté le contrôle."},{title:"Méthode",detail:"Notez les instruments et la procédure appliquée, sans inventer de valeur."},{title:"Résultat",detail:"Séparez observation, alerte et localisation confirmée."},{title:"Suite",detail:"Indiquez ce qui a été fait et ce qui reste à traiter."}])}),
  screen({id:"trace-structure",dossier:"tracer",title:"Écrivez des faits, pas une impression",kicker:"Tracer · 2",codes:["4.09"],level:"appliquer",requiresAction:true,text:"Un autre technicien doit pouvoir comprendre votre raisonnement. Écrivez ce qui a été observé, comment le contrôle a été conduit, ce qui a été obtenu et la décision prise.",prompt:"Complétez les quatre rubriques. Rien n’est enregistré.",render:()=>'<div class="panel"><div class="report-grid"><label>Observation<input id="report-observation" autocomplete="off" placeholder="Ex. trace d’huile au raccord"></label><label>Méthode<input id="report-method" autocomplete="off" placeholder="Méthode et appareil"></label><label>Résultat<textarea id="report-result" placeholder="Alerte, confirmation, localisation"></textarea></label><label>Suite<textarea id="report-next" placeholder="Action ou réserve"></textarea></label></div><button class="primary-button" id="check-report" type="button">Vérifier la structure</button><div class="feedback" id="feedback">Le texte reste seulement dans cet écran.</div></div>',wire:()=>{$("#check-report").addEventListener("click",()=>{const filled=["#report-observation","#report-method","#report-result","#report-next"].filter(selector=>$(selector).value.trim()).length;const feedback=$("#feedback");feedback.className=`feedback ${filled===4?"good":"bad"}`;feedback.textContent=filled===4?"Structure complète : faits, méthode, résultat et suite sont séparés.":`Il manque ${4-filled} rubrique${4-filled>1?"s":""}.`;if(filled===4)completeCurrent("Structure du registre complète.")})}}),
  screen({id:"absence-preuve",dossier:"tracer",title:"« Rien détecté » doit rester précis",kicker:"Tracer · 3",codes:["4.09"],level:"evaluer",requiresAction:true,text:"Un contrôle direct ciblé ne détecte aucune fuite sur les zones examinées. Cette phrase ne prouve pas que toute l’installation est étanche dans toutes les conditions.",prompt:"Quelle formulation est honnête et réutilisable ?",render:()=>choiceMarkup([{title:"Aucune fuite détectée sur les zones contrôlées",note:"Méthode et conditions consignées"},{title:"Installation parfaitement étanche",note:"Conclusion générale non démontrée"},{title:"Aucun problème possible",note:"Le contrôle ferme définitivement le dossier"}]),wire:()=>wireChoice(0,["La phrase dit exactement la portée du contrôle.","La conformité générale dépasse les faits obtenus.","Un contrôle n’efface ni l’historique ni les contrôles futurs."])}),
  screen({id:"controle-trace",dossier:"tracer",title:"Contrôle 5 · Tracer",kicker:"Tracer · contrôle",codes:["4.09"],level:"evaluer",requiresAction:true,text:"Le détecteur a réagi deux fois au même raccord dans les conditions prévues. Le registre contient seulement : « fuite trouvée ».",prompt:"Que manque-t-il ?",quiz:{choices:["Méthode, zone précise, conditions, résultat et suite donnée","Le nom commercial du détecteur uniquement","Une estimation de charge inventée","La conclusion « tout le reste est étanche »"],good:0,explain:"Une trace utile permet de comprendre et de poursuivre l’intervention sans transformer une observation locale en certitude générale."},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"deux-questions",dossier:"bilan",title:"Le repère qui évite la confusion",kicker:"Bilan · 1",level:"comprendre",text:"Face à un doute d’étanchéité, posez deux questions. Premièrement : les paramètres rendent-ils une fuite plausible ? Deuxièmement : quelle méthode autorisée permet de trouver le point exact ?",prompt:"Indirecte : « est-ce plausible ? » · Directe : « où est-ce ? »",render:()=>'<div class="method-compare"><section class="method-card indirect"><h3>1 · SOUPÇONNER</h3><p>Paramètres, historique, observation.</p><strong>Méthode indirecte</strong></section><section class="method-card direct"><h3>2 · LOCALISER</h3><p>Recherche ciblée avec une méthode adaptée.</p><strong>Méthode directe</strong></section></div>'}),
  screen({id:"ordre-final",dossier:"bilan",title:"Tenez tout le fil",kicker:"Bilan · 2",codes:["4.04","4.09"],level:"evaluer",requiresAction:true,text:"La valeur du contrôle vient de l’ordre : orienter, observer, analyser, localiser et tracer. Sauter une étape produit une conclusion fragile ou impossible à reprendre.",prompt:"Validez la chaîne complète.",render:()=>sequenceMarkup(["Lire le registre","Observer","Analyser les paramètres","Localiser","Consigner"]),wire:()=>wireSequence(["Lire le registre","Observer","Analyser les paramètres","Localiser","Consigner"])}),
  screen({id:"bilan",dossier:"bilan",title:"De l’indice à la preuve",kicker:"Bilan",level:"evaluer",text:"Vous avez relié les neuf compétences G4 dans une seule enquête. Le score mesure cinq contrôles pédagogiques ; il ne remplace ni la manipulation réelle ni la validation pratique.",prompt:"Reprenez un contrôle si son raisonnement reste hésitant.",render:()=>{const quizzes=screens.filter(item=>item.quiz);const answered=Object.keys(quizAnswers).length;const correct=quizzes.filter(item=>quizAnswers[item.id]===item.quiz.good).length;return `<div class="score"><div class="score-number">${correct}/${quizzes.length}</div><p>${answered<quizzes.length?`${quizzes.length-answered} contrôle${quizzes.length-answered>1?"s":""} encore sans réponse.`:correct>=4?"Le fil est solide. Rejouez-le maintenant sur un poste encadré.":"Reprenez les contrôles avant le plateau."}</p><button class="primary-button" id="restart-quiz" type="button">Revoir les contrôles</button></div>`},wire:()=>{$("#restart-quiz").addEventListener("click",()=>{Object.keys(quizAnswers).forEach(key=>delete quizAnswers[key]);screens.filter(item=>item.quiz).forEach(item=>completed.delete(item.id));goToId("controle-orienter")})}}),
];

function renderHome(){$("#dossier-grid").innerHTML=dossiers.map((dossier,index)=>`<button class="dossier-button" type="button" data-dossier="${dossier.id}"><b>${index+1}</b><span>${esc(dossier.label)}<small>${esc(dossier.note)}</small></span></button>`).join("");$$('[data-dossier]').forEach(button=>button.addEventListener("click",()=>startCourse(button.dataset.dossier)))}
function showHome(){stopSpeech();document.body.classList.remove("course-running");$("#home").hidden=false;$("#course-shell").hidden=true;$("#home-button").hidden=true;$("#exit-button").hidden=true;$("#mode-badge").textContent="Cours complet";history.replaceState(null,"",location.pathname);scrollTo(0,0)}
function startCourse(dossierId="orienter",screenNumber=1){extractMode=false;activeScreens=[...screens];const first=Math.max(0,activeScreens.findIndex(item=>item.dossier===dossierId));current=Math.min(activeScreens.length-1,first+Math.max(0,screenNumber-1));furthest=Math.max(furthest,current);openCourse();renderCurrent(false)}
function startExtract(ids){const picked=ids.map(id=>screens.find(item=>item.id===id)).filter(Boolean);if(!picked.length){showHome();setStatus("Extrait introuvable.");return}extractMode=true;activeScreens=picked;current=0;furthest=0;openCourse();renderCurrent(false)}
function openCourse(){document.body.classList.add("course-running");$("#home").hidden=true;$("#course-shell").hidden=false;$("#home-button").hidden=false;$("#exit-button").hidden=false;$("#mode-badge").textContent=extractMode?"Mode extrait":"Cours complet";$("#rail-mode").textContent=extractMode?"EXTRAIT":"ENQUÊTE";scrollTo(0,0)}
function renderStepper(item){const groups=extractMode?[{id:"extrait",label:"Extrait"}]:dossiers;$("#stepper").innerHTML=groups.map((group,index)=>{const indices=activeScreens.map((screenItem,screenIndex)=>({screenItem,screenIndex})).filter(entry=>extractMode||entry.screenItem.dossier===group.id).map(entry=>entry.screenIndex);const first=indices[0]??0;const active=extractMode||item.dossier===group.id;const done=indices.length&&Math.max(...indices)<furthest;return `<button class="step-button ${active?"active":""} ${done?"done":""}" type="button" data-step="${first}" ${active?'aria-current="step"':""}><b>${index+1}</b><span>${esc(group.label)}</span></button>`}).join("");$$('[data-step]').forEach(button=>button.addEventListener("click",()=>goTo(Number(button.dataset.step))));const total=activeScreens.length;$("#rail-progress").textContent=`${current+1} / ${total}`;$("#progress-bar").style.width=`${(current+1)/total*100}%`;$("#progress-copy").textContent=current===total-1?"Fin du parcours":`${total-current-1} écran${total-current-1>1?"s":""} à voir`}
function renderCurrent(moveFocus=true){stopSpeech(false);const item=activeScreens[current];if(!item)return;$("#lesson-kicker").textContent=item.kicker;$("#lesson-title").textContent=item.title;$("#lesson-text").textContent=item.text;$("#action-prompt").textContent=item.prompt||"Lisez, puis continuez.";const activity=item.render?item.render():`<div class="panel"><div class="panel-title">${esc(item.title)}</div><div class="method-line"><div class="method-node">OBSERVER</div><span class="method-arrow">→</span><div class="method-node">COMPRENDRE</div><span class="method-arrow">→</span><div class="method-node">AGIR</div></div></div>`;$("#activity-zone").innerHTML=item.image?`<div class="visual-split"><img src="${esc(item.image)}" alt="${esc(item.imageAlt)}"><div class="visual-host">${activity}</div></div>`:activity;item.wire?.();$("#reference-box").innerHTML=item.codes.length?`<strong>Référentiel</strong> · ${item.codes.map(esc).join(" · ")}`:"<strong>Contexte</strong> · hors référentiel";renderStepper(item);updateNav();updateUrl();if(moveFocus)$("#lesson-title").focus({preventScroll:true});if(autoplay)setTimeout(()=>speakCurrent(),320)}
function updateNav(){const item=activeScreens[current];$("#prev-button").disabled=current===0;const blocked=item?.requiresAction&&!completed.has(item.id);$("#next-button").disabled=blocked;$("#next-button").textContent=current===activeScreens.length-1?"Terminer":"Suivant →"}
function goTo(index){if(index<0||index>=activeScreens.length)return;current=index;furthest=Math.max(furthest,current);renderCurrent()}
function goToId(id){const index=activeScreens.findIndex(item=>item.id===id);if(index>=0)goTo(index)}
function previous(){if(current>0)goTo(current-1)}
function next(){const item=activeScreens[current];if(item.requiresAction&&!completed.has(item.id)){setStatus("Réalisez l’activité avant de continuer.");return}if(current<activeScreens.length-1)goTo(current+1);else showHome()}
function updateUrl(){const item=activeScreens[current];const url=new URL(location.href);url.search="";if(extractMode)url.searchParams.set("extrait",activeScreens.map(screenItem=>screenItem.id).join(","));else{url.searchParams.set("dossier",item.dossier);const dossierScreens=activeScreens.filter(screenItem=>screenItem.dossier===item.dossier);url.searchParams.set("ecran",String(dossierScreens.indexOf(item)+1))}history.replaceState(null,"",url)}
function screenLink(){const url=new URL(location.href);url.search="";url.searchParams.set("extrait",activeScreens[current].id);return url.href}
async function copyCurrentLink(){const link=screenLink();try{await navigator.clipboard.writeText(link)}catch(_){const area=document.createElement("textarea");area.value=link;area.setAttribute("readonly","");area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();document.execCommand("copy");area.remove()}setStatus("Lien de cet écran copié.")}
function speechSupported(){return"speechSynthesis"in window&&"SpeechSynthesisUtterance"in window}
function chooseFrenchVoice(){const voices=speechSynthesis.getVoices();const quality=voice=>/natural|naturel|neural|online|google|microsoft|denise|henri|julie|paul|hortense/i.test(voice.name);return voices.find(voice=>voice.lang.toLowerCase()==="fr-fr"&&quality(voice))||voices.find(voice=>voice.lang.toLowerCase()==="fr-fr")||voices.find(voice=>voice.lang.toLowerCase().startsWith("fr")&&quality(voice))||voices.find(voice=>voice.lang.toLowerCase().startsWith("fr"))||voices[0]}
function stopSpeech(disableAutoplay=true){speechRun+=1;if(speechSupported())speechSynthesis.cancel();speaking=false;paused=false;if(disableAutoplay)autoplay=false;updateVoiceButtons()}
function speakCurrent(){if(!speechSupported()){setStatus("La synthèse vocale n’est pas disponible. Le texte affiché reste complet.");return}stopSpeech(false);const item=activeScreens[current];const run=++speechRun;const visible=`${item.title}. ${item.text} ${item.prompt}`;const utterance=new SpeechSynthesisUtterance(item.speak||stripHtml(visible));utterance.lang="fr-FR";utterance.pitch=1;utterance.rate=voiceRates[rateIndex];const voice=chooseFrenchVoice();if(voice)utterance.voice=voice;utterance.onstart=()=>{if(run!==speechRun)return;speaking=true;paused=false;updateVoiceButtons()};utterance.onend=()=>{if(run!==speechRun)return;speaking=false;paused=false;updateVoiceButtons()};utterance.onerror=event=>{if(run!==speechRun||["canceled","interrupted"].includes(event.error))return;speaking=false;paused=false;updateVoiceButtons();setStatus("La voix est indisponible ; poursuivez avec le texte affiché.")};speaking=true;paused=false;updateVoiceButtons();speechSynthesis.speak(utterance)}
function toggleSpeech(){if(!speechSupported()){setStatus("La synthèse vocale n’est pas disponible.");return}autoplay=true;if(speaking&&!paused){speechSynthesis.pause();paused=true;updateVoiceButtons();return}if(speaking&&paused){speechSynthesis.resume();paused=false;updateVoiceButtons();return}speakCurrent()}
function updateVoiceButtons(){const button=$("#listen");if(!button)return;button.innerHTML=speaking&&!paused?'<span aria-hidden="true">Ⅱ</span><span>Pause</span>':speaking&&paused?'<span aria-hidden="true">▶</span><span>Reprendre</span>':'<span aria-hidden="true">▶</span><span>Écouter</span>';$("#stop-voice").disabled=!speaking;$("#speed-value").textContent=voiceRates[rateIndex].toFixed(2).replace(".",",")+"×"}
function changeRate(direction){rateIndex=Math.max(0,Math.min(voiceRates.length-1,rateIndex+direction));saveRate();updateVoiceButtons();if(speaking||paused)speakCurrent()}
function buildPrintBook(){const quizCount=screens.filter(item=>item.quiz).length;$("#print-book").innerHTML=`<header class="print-title"><h1>L’étanchéité — de l’indice à la preuve</h1><p>Fiches g4a + g4b + g4c · 27 écrans · 9 codes · ${quizCount} contrôles.</p><p class="print-law"><strong>Actualité au 1er août 2026 :</strong> le référentiel 2024/2215 cite encore le règlement 1516/2007, abrogé depuis le 23 juillet 2026 par le règlement 2026/1444. Appliquer la procédure actuelle validée sur le site.</p></header>`+screens.map((item,index)=>`<article class="print-screen"><h2>${index+1}. ${esc(item.title)}</h2><p>${esc(item.text)}</p>${item.prompt?`<h3>Action à réaliser</h3><p>${esc(item.prompt)}</p>`:""}${item.quiz?`<div class="print-answer"><strong>Correction :</strong> ${esc(item.quiz.choices[item.quiz.good])}. ${esc(item.quiz.explain)}</div>`:""}<p class="print-codes">Référentiel · ${item.codes.length?esc(item.codes.join(" · ")):"contexte"}</p></article>`).join("")}
function handleInitialUrl(){const params=new URLSearchParams(location.search);const extract=params.get("extrait");if(extract){startExtract(extract.split(",").map(value=>value.trim()).filter(Boolean));return}const dossier=params.get("dossier");if(dossier){startCourse(dossier,Number(params.get("ecran"))||1);return}showHome()}
function bindGlobalEvents(){$("#start-button").addEventListener("click",()=>startCourse());$("#home-button").addEventListener("click",showHome);$("#exit-button").addEventListener("click",showHome);$("#prev-button").addEventListener("click",previous);$("#next-button").addEventListener("click",next);$("#copy-link").addEventListener("click",copyCurrentLink);$("#listen").addEventListener("click",toggleSpeech);$("#stop-voice").addEventListener("click",()=>stopSpeech());$("#slower").addEventListener("click",()=>changeRate(-1));$("#faster").addEventListener("click",()=>changeRate(1));addEventListener("keydown",event=>{const tag=document.activeElement?.tagName;if(["INPUT","TEXTAREA","SELECT","BUTTON"].includes(tag))return;if(event.key==="ArrowRight"){event.preventDefault();next()}else if(event.key==="ArrowLeft"){event.preventDefault();previous()}else if(event.key===" "){event.preventDefault();toggleSpeech()}else if(event.key==="Escape")showHome()});addEventListener("beforeunload",()=>stopSpeech());document.addEventListener("visibilitychange",()=>{if(document.hidden)stopSpeech()});if(speechSupported())speechSynthesis.addEventListener?.("voiceschanged",()=>{})}

renderHome();
buildPrintBook();
bindGlobalEvents();
updateVoiceButtons();
handleInitialUrl();
