(() => {
  "use strict";

  const svg = (id, title, desc, body) => `<svg viewBox="0 0 760 430" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker></defs>${body}</svg>`;

  const collectorScene = svg("floor-collector", "Collecteurs d’un plancher chauffant à trois boucles", "Le collecteur de départ porte trois débitmètres. Le collecteur de retour porte trois organes de réglage. Chaque paire dessert une boucle nommée A, B ou C.", `
    <text x="380" y="35" text-anchor="middle" font-size="22" font-weight="700">DÉPART · DÉBITMÈTRES · BOUCLES · RETOUR · RÉGLAGES</text>
    <path d="M105 90H655" stroke="#c9451a" stroke-width="16"/><path d="M105 340H655" stroke="#3d7fca" stroke-width="16"/>
    ${[210,380,550].map((x,i)=>`<g><circle cx="${x}" cy="90" r="25" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="${x}" y="96" text-anchor="middle" font-size="14" font-weight="700">${["1,1","1,2","0,8"][i]}</text><path d="M${x} 115V150Q${x} 190 ${x-55} 215Q${x} 240 ${x} 280V315" fill="none" stroke="#1b3a63" stroke-width="8"/><image href="assets/vanne_manuelle.svg" x="${x-36}" y="300" width="72" height="42"/><text x="${x}" y="257" text-anchor="middle" font-size="15" font-weight="700">BOUCLE ${["A","B","C"][i]}</text></g>`).join("")}
    <text x="115" y="70" font-size="16" font-weight="700">DÉPART</text><text x="115" y="377" font-size="16" font-weight="700">RETOUR</text><text x="615" y="70" font-size="14">L/min</text>
    <text x="380" y="410" text-anchor="middle" font-size="14">Les mots, formes et flèches complètent la couleur.</text>`);

  const zonesScene = svg("floor-zones", "Trois zones reliées à trois boucles", "Données pédagogiques : la boucle A dessert le salon et mesure 80 mètres. B dessert le bureau et mesure 55 mètres. C dessert la salle d’eau et mesure 35 mètres.", `
    <text x="380" y="35" text-anchor="middle" font-size="22" font-weight="700">ASSOCIER LE REPÈRE, LA ZONE ET LA LONGUEUR</text>
    ${[[180,"A","SALON","80 m"],[380,"B","BUREAU","55 m"],[580,"C","SALLE D’EAU","35 m"]].map(([x,l,z,n])=>`<g><rect x="${x-85}" y="105" width="170" height="190" rx="20" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><circle cx="${x}" cy="145" r="27" fill="#fffdf8" stroke="#3d7fca" stroke-width="5"/><text x="${x}" y="152" text-anchor="middle" font-size="20" font-weight="700">${l}</text><path d="M${x-55} 200q55-55 110 0q-55 55-110 0" fill="none" stroke="#c9451a" stroke-width="6" stroke-dasharray="10 7"/><text x="${x}" y="252" text-anchor="middle" font-size="15" font-weight="700">${z}</text><text x="${x}" y="278" text-anchor="middle" font-size="17">${n}</text></g>`).join("")}
    <rect x="165" y="330" width="430" height="58" rx="14" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="6 5"/><text x="380" y="365" text-anchor="middle" font-size="15" font-weight="700">LONGUEUR ET DÉBIT SONT DES DONNÉES D’EXERCICE</text>`);

  const readingsScene = svg("floor-read", "Débits mesurés et cibles des trois boucles", "Données pédagogiques : A mesure 1,10 litre par minute pour une cible 1,80. B mesure et vise 1,20. C mesure et vise 0,80. A présente le plus grand déficit relatif et absolu.", `
    <text x="380" y="34" text-anchor="middle" font-size="22" font-weight="700">LIRE MESURE ET CIBLE, BOUCLE PAR BOUCLE</text>
    ${[[190,"A",1.1,1.8],[380,"B",1.2,1.2],[570,"C",.8,.8]].map(([x,l,q,t])=>{const ok=Math.abs(q-t)<.05;return`<g><rect x="${x-72}" y="95" width="144" height="235" rx="18" fill="#fffdf8" stroke="${ok?"#1e7e54":"#c0392b"}" stroke-width="${ok?5:4}" stroke-dasharray="${ok?"0":"9 6"}"/><text x="${x}" y="132" text-anchor="middle" font-size="18" font-weight="700">BOUCLE ${l}</text><rect x="${x-38}" y="275" width="76" height="${q*80}" transform="translate(0 ${-(q*80)})" rx="8" fill="${ok?"#e3f5ec":"#fbe7e4"}" stroke="#1b3a63" stroke-width="3"/><text x="${x}" y="290" text-anchor="middle" font-size="17" font-weight="700">${q.toFixed(2)} L/min</text><text x="${x}" y="315" text-anchor="middle" font-size="14">cible ${t.toFixed(2)}</text><text x="${x}" y="360" text-anchor="middle" font-size="14" font-weight="700">${ok?"CONFORME AU MODÈLE":"DÉFICIT"}</text></g>`;}).join("")}
    <text x="380" y="402" text-anchor="middle" font-size="14">La longueur seule ne prouve pas la cause du déficit.</text>`);

  function settingScene(opening = 60) {
    const qa = .6 + .012 * opening;
    const ok = Math.abs(qa - 1.8) <= .05;
    return svg("floor-setting", "Prévision de réglage de la boucle A", `Sous l’hypothèse pédagogique d’une différence de pression maintenue, une ouverture de ${opening} pour cent prévoit ${qa.toFixed(2)} litre par minute sur A. B reste à 1,20 et C à 0,80 dans ce modèle simplifié.`, `
      <text x="380" y="34" text-anchor="middle" font-size="21" font-weight="700">RÉGLAGE DE A · MODÈLE À Δp MAINTENUE</text>
      <path d="M110 115H650M650 115V335H110" fill="none" stroke="#1b3a63" stroke-width="12"/>
      ${[[220,"A",qa],[390,"B",1.2],[560,"C",.8]].map(([x,l,q],i)=>`<g><path d="M${x} 115V335" stroke="#3d7fca" stroke-width="9"/><circle cx="${x}" cy="205" r="45" fill="#fffdf8" stroke="${i===0?(ok?"#1e7e54":"#b06a00"):"#1e7e54"}" stroke-width="${i===0&&ok?5:4}" stroke-dasharray="${i===0&&!ok?"6 5":"0"}"/><text x="${x}" y="199" text-anchor="middle" font-size="16" font-weight="700">${l}</text><text x="${x}" y="224" text-anchor="middle" font-size="16">${q.toFixed(2)} L/min</text></g>`).join("")}
      <rect x="75" y="280" width="250" height="80" rx="14" fill="#fffdf8" stroke="#1b3a63" stroke-width="3"/><text x="200" y="310" text-anchor="middle" font-size="16" font-weight="700">OUVERTURE A : ${opening} %</text><text x="200" y="338" text-anchor="middle" font-size="14">cible A : 1,80 L/min</text>
      <rect x="430" y="280" width="260" height="80" rx="14" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="6 5"/><text x="560" y="309" text-anchor="middle" font-size="15" font-weight="700">PRÉVISION À CONFIRMER</text><text x="560" y="336" text-anchor="middle" font-size="14">stabiliser puis relire</text>`);
  }

  const methodScene = svg("floor-method", "Procédure de lecture et réglage d’un collecteur", "La démarche associe zones et boucles, relève débit et cible, choisit un seul réglage, stabilise, remesure et consigne la conclusion sans agir sur une installation chaude ou sous pression hors procédure.", `
    ${["Associer","Relever","Régler","Stabiliser","Remesurer"].map((t,i)=>`<g transform="translate(${90+i*145} 210)"><circle r="38" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/><text y="6" text-anchor="middle" font-size="18" font-weight="700">${i+1}</text><text y="70" text-anchor="middle" font-size="14" font-weight="700">${t}</text>${i<4?`<path d="M43 0H95" stroke="#3d7fca" stroke-width="5" marker-end="url(#arr-floor-method)"/>`:""}</g>`).join("")}
    <text x="380" y="65" text-anchor="middle" font-size="22" font-weight="700">UN REPÈRE DE BOUCLE DOIT SUIVRE JUSQU’AU COMPTE RENDU</text>
    <rect x="145" y="330" width="470" height="58" rx="14" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="6 5"/><text x="380" y="365" text-anchor="middle" font-size="14" font-weight="700">VIRTUEL : AUCUN DESSERRAGE, PURGE OU ACTION SUR CIRCUIT RÉEL</text>`);

  window.STATION_CONFIG = {
    code: "D6", id: "plancher", title: "Plancher chauffant — Collecteur mystère", next: "terminer le parcours de la ligne D",
    levels: {
      CAP: { objective: "Reconnaître chaque boucle et lire son débit sur le collecteur.", assessment: "nommer une boucle et lire son débitmètre" },
      TP: { objective: "Associer zones et boucles, lire les débitmètres et contrôler un réglage.", assessment: "garder les repères, comparer mesure et cible et remesurer" },
      BTS: { objective: "Analyser longueurs, débits visés et limites d’un modèle de collecteur.", assessment: "justifier la boucle défavorisée par les données, pas par la longueur seule" }
    },
    steps: [
      { short: "Repérer", kicker: "collecteurs", title: "Départ, retour, débitmètres et réglages", text: "Suis une paire de piquages du départ au retour.", cap: "Montre le collecteur départ et le collecteur retour.", tp: "Identifie où lire et où régler.", bts: "Distingue la mesure de débit de l’organe qui modifie la résistance.", scene: collectorScene, equivalent: "Le départ porte les débitmètres, trois boucles A B C rejoignent le retour et des organes de réglage sont représentés sur le retour.", action: { type: "match", prompt: "Associe la fonction à son emplacement.", options: ["Collecteur départ","Collecteur retour"], items: [{label:"Débitmètres du modèle",answer:0},{label:"Organes de réglage du modèle",answer:1},{label:"Entrée des trois boucles",answer:0},{label:"Sortie des trois boucles",answer:1}], explain: "Le repérage doit suivre le schéma et le matériel réel, dont l’implantation peut varier." } },
      { short: "Associer", kicker: "zones", title: "Une boucle, une zone, un repère", text: "Les longueurs et zones sont des données créées pour le jeu.", cap: "Associe chaque lettre à sa pièce de la maison.", tp: "Associe chaque zone au bon repère.", bts: "Conserve aussi longueur et débit visé dans la fiche de calcul.", scene: zonesScene, equivalent: "A dessert le salon sur 80 m, B le bureau sur 55 m et C la salle d’eau sur 35 m, données pédagogiques.", action: { type: "match", prompt: "Retrouve les boucles.", options: ["A · 80 m","B · 55 m","C · 35 m"], items: [{label:"Salon",answer:0},{label:"Bureau",answer:1},{label:"Salle d’eau",answer:2}], explain: "Le repère de boucle évite de régler une autre zone que celle contrôlée." } },
      { short: "Lire", kicker: "débitmètres", title: "Comparer chaque mesure à sa cible", text: "A est en déficit. B et C atteignent leur cible dans l’exercice.", cap: "Repère la boucle avec le débit le plus bas.", tp: "Nomme la boucle défavorisée à partir du relevé.", bts: "Calcule l’écart à la cible et refuse un diagnostic fondé sur la longueur seule.", scene: readingsScene, equivalent: "A 1,10 pour cible 1,80 L/min ; B 1,20 pour 1,20 ; C 0,80 pour 0,80.", action: { type: "choice", prompt: "Quelle boucle est défavorisée par le relevé ?", options: [{label:"A : déficit de 0,70 L/min"},{label:"B : aucun écart"},{label:"C : aucun écart"},{label:"La plus courte par définition"}], correct: 0, explain: "A est la seule sous sa cible. La longueur peut contribuer à la résistance, mais ne prouve pas seule la cause." } },
      { short: "Régler", kicker: "action contrôlée", title: "Ouvrir A dans le modèle", text: "Le modèle suppose une différence de pression maintenue et laisse B et C inchangées.", cap: "Lis le nouveau débit après avoir ouvert la vanne.", tp: "Cherche 1,80 L/min sur A, puis annonce la nécessité de stabiliser.", bts: "Critique l’hypothèse de branches indépendantes et demande la courbe du réseau réel.", scene: settingScene, equivalent: (v) => `Prévision pédagogique : ouverture A ${v} %, débit A ${(.6+.012*v).toFixed(2)} L/min, B 1,20 et C 0,80 sous Δp maintenue.`, action: { type: "range", prompt: "Ouvre progressivement la boucle A.", label: "Ouverture relative A", min: 40, max: 100, step: 10, value: 60, evaluate: (v) => { const q=.6+.012*v; return {readout:`${v} %`,observation:`Prévision A = 0,60 + 0,012 × ${v} = ${q.toFixed(2)} L/min. Stabilise et remesure avant de conclure.`}; } } },
      { short: "Contrôler", kicker: "méthode", title: "Un réglage laisse une trace vérifiable", text: "Ordonne la procédure du collecteur au compte rendu.", cap: "Relève le débit avant et après le réglage.", tp: "Conserve repère, mesure initiale, action et mesure finale.", bts: "Ajoute données de calcul, conditions de pression et interaction entre branches.", scene: methodScene, equivalent: "Associer, relever, régler une seule boucle, stabiliser puis remesurer.", action: { type: "sequence", prompt: "Ordonne le contrôle.", items: ["Remesurer toutes les boucles","Associer zone et repère","Stabiliser le réseau","Noter mesures et cibles","Régler une seule boucle"], correctOrder: [1,3,4,2,0], explain: "La remesure finale vérifie l’effet et détecte une interaction avec les autres boucles." } }
    ],
    quiz: [
      { context: "A dessert le salon, B le bureau, C la salle d’eau.", question: "Pourquoi garder ces repères ?", options: ["Pour relier mesure, action et zone dans le compte rendu","Pour remplacer les unités","Pour régler au hasard","Pour supprimer le retour"], correct: 0, explain: "Le même identifiant doit accompagner la boucle de l’observation à la conclusion." },
      { context: "A mesure 1,10 L/min pour une cible de 1,80.", question: "Quel est l’écart ?", options: ["Déficit de 0,70 L/min","Excès de 0,70 L/min","Déficit de 1,80 L/min","Aucun écart"], correct: 0, explain: "1,80 − 1,10 = 0,70 L/min." },
      { context: "La boucle A est aussi la plus longue.", question: "Quelle conclusion est recevable ?", options: ["A est défavorisée par le relevé ; la cause reste à vérifier","La longueur prouve seule la panne","Toute boucle longue doit être fermée","Le débitmètre est inutile"], correct: 0, explain: "La mesure identifie le déficit, mais plusieurs résistances et réglages peuvent l’expliquer." },
      { context: "Le réglage de A vient de changer.", question: "Quelle suite est correcte ?", options: ["Stabiliser puis remesurer A, B et C","Conclure sans attendre","Desserrer un raccord chaud","Masquer la valeur initiale"], correct: 0, explain: "Toutes les boucles sont relues pour contrôler l’effet et les interactions." }
    ],
    summaryScene: methodScene,
    summaryEquivalent: "Synthèse : associer chaque zone, lire mesure et cible, agir sur un seul réglage, stabiliser puis remesurer toutes les boucles."
  };
})();
