"use strict";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

const dossiers = [
  { id:"manifold", label:"Reconnaître", note:"lire le manifold" },
  { id:"raccorder", label:"Raccorder", note:"vannes fermées" },
  { id:"vide", label:"Tirer au vide", note:"pompe et vacuomètre" },
  { id:"isoler", label:"Isoler", note:"avant d’arrêter" },
  { id:"deconnecter", label:"Déconnecter", note:"sans rejeter" },
  { id:"bilan", label:"Enchaîner", note:"tenir tout le fil" },
];

const screenIllustrations = {
  "trois-gestes": ["../bibliotheque/illu-p1.webp", "Manifold et flexibles prêts pour une intervention."],
  "lire-manifold": ["../svg/manifold-lecture.svg", "Schéma du manifold : basse pression à gauche, haute pression à droite et flexible central."],
  "vannes-fermees": ["../bibliotheque/illu-p1.webp", "Manifold dont les vannes sont vérifiées avant le raccordement."],
  "lecture-continue": ["../bibliotheque/icones/ico-manifold.png", "Pictogramme d’un manifold à deux manomètres."],
  "controle-manifold": ["../bibliotheque/illu-p1.webp", "Manifold utilisé pour le contrôle de lecture."],
  "consigner-avant": ["../bibliotheque/illu-p5.webp", "Main préparant une vanne avant l’intervention."],
  "raccorder-bp-hp": ["../svg/manifold-lecture.svg", "Schéma des côtés basse pression et haute pression du manifold."],
  "flexible-central": ["../bibliotheque/icones/ico-manifold.png", "Pictogramme du manifold avec son flexible central."],
  "chasser-air": ["../bibliotheque/illu-p1.webp", "Flexibles raccordés au manifold selon une procédure préparée."],
  "controle-raccordement": ["../svg/manifold-lecture.svg", "Schéma de raccordement utilisé pour le contrôle."],
  "but-vide": ["../bibliotheque/illu-p3.webp", "Pompe à vide reliée à un vacuomètre électronique."],
  "montage-vide": ["../svg/tirage-au-vide.svg", "Courbes et montage de tirage au vide."],
  "courbes-vide": ["../svg/tirage-au-vide.svg", "Trois comportements : descente stable, humidité et remontée après isolement."],
  "controle-vide": ["../bibliotheque/illu-p3.webp", "Pompe à vide et vacuomètre pour le contrôle."],
  "isoler-avant-arret": ["../bibliotheque/illu-p5.webp", "Main fermant une vanne avant l’arrêt de la pompe."],
  "mauvais-ordre": ["../svg/ordre-vannes.svg", "Schéma de l’ordre des vannes et de la déconnexion."],
  "controle-isoler": ["../bibliotheque/illu-p3.webp", "Montage pompe à vide et vacuomètre à isoler."],
  "fermer-stabiliser": ["../svg/ordre-vannes.svg", "Séquence fermer, stabiliser puis desserrer lentement."],
  "residu-flexible": ["../bibliotheque/illu-p5.webp", "Déconnexion lente d’un flexible après récupération du résidu."],
  "controle-deconnexion": ["../svg/ordre-vannes.svg", "Ordre correct de déconnexion utilisé pour le contrôle."],
  "bilan": ["../bibliotheque/illu-p5.webp", "Dernier geste de la chaîne d’intervention."],
};

const completed = new Set();
const quizAnswers = {};
let activeScreens = [];
let current = 0;
let furthest = 0;
let extractMode = false;
let speechRun = 0;
let speaking = false;
let paused = false;
let autoplay = false;
let statusTimer = 0;
const voiceRates = [0.8, 0.95, 1.1, 1.25];
let rateIndex = safeStoredRateIndex();

function safeStoredRateIndex(){try{const stored=Number(localStorage.getItem("chaine-intervention-voice-rate"));const index=voiceRates.indexOf(stored);return index>=0?index:1}catch(_){return 1}}
function saveRate(){try{localStorage.setItem("chaine-intervention-voice-rate",String(voiceRates[rateIndex]))}catch(_){}}
function esc(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}
function stripHtml(value){const box=document.createElement("div");box.innerHTML=value;return box.textContent||""}
function screen(data){const visual=screenIllustrations[data.id]||["",""];return{codes:[],prompt:"Lisez, puis continuez.",speak:"",requiresAction:false,image:visual[0],imageAlt:visual[1]||"Illustration pédagogique de l’étape.",...data}}
function completeCurrent(message="Action réalisée. Vous pouvez continuer."){completed.add(activeScreens[current].id);updateNav();setStatus(message)}
function setStatus(message){clearTimeout(statusTimer);$("#status-message").textContent=message;statusTimer=setTimeout(()=>{$("#status-message").textContent=""},3000)}

function choiceMarkup(choices){return `<div class="panel"><div class="cards" style="--cols:${Math.min(choices.length,3)}">${choices.map((choice,index)=>`<button class="choice" type="button" data-choice="${index}"><strong>${esc(choice.title)}</strong><small>${esc(choice.note||"")}</small></button>`).join("")}</div><div class="feedback" id="feedback">Choisissez, puis observez la conséquence.</div></div>`}
function wireChoice(good,messages){$$('[data-choice]').forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.choice);$$('[data-choice]').forEach(item=>item.classList.remove("good","bad"));button.classList.add(index===good?"good":"bad");const feedback=$("#feedback");feedback.className=`feedback ${index===good?"good":"bad"}`;feedback.innerHTML=`<strong>${index===good?"Geste juste.":"Conséquence."}</strong> ${esc(messages[index])}`;if(index===good)completeCurrent("Décision correcte. Vous pouvez continuer.")}))}
function checklistMarkup(items){return `<div class="panel"><div class="cards" style="--cols:${Math.min(items.length,3)}">${items.map((item,index)=>`<button class="check-card" type="button" data-check="${index}" aria-pressed="false"><strong>${esc(item.title)}</strong><small>${esc(item.note)}</small></button>`).join("")}</div><div class="feedback" id="feedback">Ouvrez chaque point.</div></div>`}
function wireChecklist(items){$$('[data-check]').forEach(button=>button.addEventListener("click",()=>{button.classList.add("good");button.setAttribute("aria-pressed","true");const item=items[Number(button.dataset.check)];const feedback=$("#feedback");feedback.className="feedback good";feedback.innerHTML=`<strong>${esc(item.title)}.</strong> ${esc(item.detail)}`;if($$('[data-check][aria-pressed="false"]').length===0)completeCurrent("Tous les points ont été examinés.")}))}
function orderMarkup(items){return `<div class="panel"><div class="cards order-choices" style="--cols:${Math.min(items.length,4)}">${items.map(item=>`<button class="sequence-step" type="button" data-order="${item.order}">${esc(item.label)}</button>`).join("")}</div><div class="feedback" id="feedback">Cliquez les gestes dans l’ordre.</div></div>`}
function wireOrder(total){let next=1;$$('[data-order]').forEach(button=>button.addEventListener("click",()=>{const order=Number(button.dataset.order);const feedback=$("#feedback");if(button.classList.contains("done"))return;if(order!==next){feedback.className="feedback bad";feedback.textContent="Mauvais ordre : revenez au premier geste non validé.";return}button.classList.add("done");button.textContent=`${order} · ${button.textContent}`;next+=1;feedback.className="feedback good";feedback.textContent=next>total?"Chaîne complète.":"Geste validé. Quel est le suivant ?";if(next>total)completeCurrent("Ordre complet. Vous pouvez continuer.")}))}
function quizMarkup(item){const saved=quizAnswers[item.id];return `<div class="panel"><div class="cards" style="--cols:2">${item.quiz.choices.map((choice,index)=>`<button class="choice ${saved===index?(index===item.quiz.good?"good":"bad"):""}" type="button" data-quiz="${index}"><strong>${String.fromCharCode(65+index)}.</strong><small>${esc(choice)}</small></button>`).join("")}</div><div class="feedback ${saved===undefined?"":saved===item.quiz.good?"good":"bad"}" id="feedback">${saved===undefined?"Choisissez une réponse.":saved===item.quiz.good?`<strong>Correct.</strong> ${esc(item.quiz.explain)}`:"Ce choix produit un ordre incorrect. Essayez encore."}</div></div>`}
function wireQuiz(item){$$('[data-quiz]').forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.quiz);quizAnswers[item.id]=index;$$('[data-quiz]').forEach(choice=>choice.classList.remove("good","bad"));button.classList.add(index===item.quiz.good?"good":"bad");const feedback=$("#feedback");feedback.className=`feedback ${index===item.quiz.good?"good":"bad"}`;if(index===item.quiz.good){feedback.innerHTML=`<strong>Correct.</strong> ${esc(item.quiz.explain)}`;completeCurrent("Contrôle validé.")}else{feedback.innerHTML=`<strong>À corriger.</strong> ${esc(item.quiz.wrong[index]||"Relisez l’ordre des gestes, puis essayez encore.")}`}}))}
function routeMarkup(nodes){return `<div class="route">${nodes.map((node,index)=>`${index?'<span class="route-arrow" aria-hidden="true">→</span>':''}<div class="route-node ${esc(node.kind||"")}">${esc(node.label)}</div>`).join("")}</div>`}

const screens = [
  screen({id:"trois-gestes",dossier:"manifold",title:"Trois appareils, une seule chaîne",kicker:"Reconnaître · 1",text:"Le manifold relie le circuit aux appareils. La pompe retire l’air et l’humidité. Le vacuomètre dit ce qui se passe réellement dans le circuit. Leur efficacité dépend moins de la vitesse que de l’ordre des vannes.",prompt:"Repérez le fil : raccorder → tirer au vide → isoler → déconnecter.",render:()=>routeMarkup([{label:"MANIFOLD",kind:"blue"},{label:"POMPE",kind:"yellow"},{label:"VACUOMÈTRE",kind:"red"},{label:"VANNES",kind:"blue"}])}),
  screen({id:"lire-manifold",dossier:"manifold",title:"Bleu, rouge, jaune : trois fonctions",kicker:"Reconnaître · 2",codes:["4.05"],text:"Le manomètre BP est à gauche, en bleu. Le HP est à droite, en rouge. Le flexible central, souvent jaune, conduit vers la pompe ou l’appareil prévu. Les cadrans mesurent ; les vannes commandent le passage vers la ligne centrale.",prompt:"Lisez le schéma de gauche à droite.",render:()=>'<div class="manifold-board"><div class="gauge-card bp"><strong>BP · BLEU</strong><span>Mesure côté basse pression</span></div><div class="gauge-card hp"><strong>HP · ROUGE</strong><span>Mesure côté haute pression</span></div><div class="center-hose">JAUNE · LIGNE CENTRALE → appareil raccordé</div></div>'}),
  screen({id:"vannes-fermees",dossier:"manifold",title:"Avant de toucher un raccord : fermé",kicker:"Reconnaître · 3",codes:["5.01"],requiresAction:true,text:"À la connexion comme à la déconnexion, la position sûre de départ est connue : les vannes du manifold sont fermées. Cette vérification précède le vissage ; elle ne se suppose jamais.",prompt:"Fermez les deux vannes.",render:()=>'<div class="panel"><div class="valve-board"><button class="valve open" type="button" data-valve="bp">BP · OUVERTE</button><span class="valve-link">↔</span><button class="valve open" type="button" data-valve="hp">HP · OUVERTE</button></div><div class="feedback" id="feedback">Deux vannes ouvertes : ne raccordez rien.</div></div>',wire:()=>{$$('[data-valve]').forEach(button=>button.addEventListener("click",()=>{button.classList.remove("open");button.classList.add("closed");button.textContent=`${button.dataset.valve.toUpperCase()} · FERMÉE`;const count=$$('[data-valve].closed').length;const feedback=$("#feedback");feedback.className="feedback good";feedback.textContent=count===2?"Deux vannes fermées : le raccordement peut commencer.":"Une vanne est fermée. Vérifiez l’autre.";if(count===2)completeCurrent("Position de départ sécurisée.")}))}}),
  screen({id:"lecture-continue",dossier:"manifold",title:"Mesurer n’est pas mettre en communication",kicker:"Reconnaître · 4",codes:["4.05"],text:"Les manomètres indiquent les pressions auxquelles ils sont raccordés même lorsque les vannes du manifold restent fermées. Ouvrir une vanne met en communication ce côté avec le flexible central. Ouvrir BP et HP ensemble sans raison crée un chemin indésirable.",prompt:"Gardez le repère : cadran = lire ; vanne = communiquer.",render:()=>'<div class="consequence"><section class="consequence-card good"><h3>CADRAN</h3><p>Il donne une mesure du côté raccordé.</p></section><section class="consequence-card bad"><h3>VANNE</h3><p>Elle ouvre un chemin vers la ligne centrale.</p></section></div>'}),
  screen({id:"controle-manifold",dossier:"manifold",title:"Contrôle 1 · Lire le manifold",kicker:"Reconnaître · contrôle",codes:["4.05"],requiresAction:true,text:"Les flexibles BP et HP sont raccordés. Les deux vannes du manifold sont fermées. Vous devez seulement lire les deux pressions.",prompt:"Quelle action est correcte ?",quiz:{choices:["Lire les deux cadrans sans ouvrir les vannes","Ouvrir BP et HP ensemble","Débrancher le flexible jaune sous pression","Inverser les flexibles bleu et rouge"],good:0,explain:"Les cadrans lisent les pressions des côtés raccordés ; aucune communication avec la ligne centrale n’est nécessaire.",wrong:{1:"Vous créez une communication entre les côtés par le manifold.",2:"Une ligne sous pression ne se débranche pas d’un coup.",3:"BP et HP ne sont pas interchangeables."}},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"consigner-avant",dossier:"raccorder",title:"Préparer le poste avant les flexibles",kicker:"Raccorder · 1",text:"L’installation est identifiée, arrêtée et consignée selon la procédure du site avant le montage. Le fluide, les raccords, l’appareil à brancher et son état sont vérifiés. Le geste commence avant le premier tour de clé.",prompt:"Ouvrez les trois vérifications.",requiresAction:true,render:()=>checklistMarkup([{title:"Installation",note:"identifiée et consignée"},{title:"Matériel",note:"compatible et en état"},{title:"Procédure",note:"notice et plateau"}]),wire:()=>wireChecklist([{title:"Installation",detail:"L’intervention porte sur le bon équipement, dans l’état prévu."},{title:"Matériel",detail:"Flexibles, raccords et appareil sont adaptés et contrôlés."},{title:"Procédure",detail:"Le chemin et l’ordre des vannes sont connus avant l’ouverture."}])}),
  screen({id:"raccorder-bp-hp",dossier:"raccorder",title:"BP sur BP, HP sur HP",kicker:"Raccorder · 2",codes:["5.01"],requiresAction:true,text:"Le flexible bleu rejoint le raccord basse pression. Le rouge rejoint la haute pression. Les vannes restent fermées pendant le vissage. La couleur aide à se repérer, mais l’identification du circuit reste la preuve.",prompt:"Choisissez le raccordement cohérent.",render:()=>choiceMarkup([{title:"Bleu → BP · Rouge → HP",note:"Vannes fermées"},{title:"Bleu → HP · Rouge → BP",note:"Couleurs inversées"},{title:"Les deux sur la BP",note:"Aucune lecture HP"}]),wire:()=>wireChoice(0,["Chaque ligne rejoint le côté identifié, manifold fermé.","Les indications du manifold deviennent trompeuses et le geste est à reprendre.","Le côté haute pression n’est ni identifié ni mesuré."])}),
  screen({id:"flexible-central",dossier:"raccorder",title:"Le jaune mène à l’appareil utile",kicker:"Raccorder · 3",codes:["5.01"],text:"La ligne centrale ne va pas « quelque part ». Pour ce parcours, elle rejoint la pompe à vide. Dans une autre opération, elle peut rejoindre l’appareil prévu par le montage. Avant d’ouvrir, suivez physiquement le flexible jusqu’à son extrémité.",prompt:"Suivez le chemin complet, sans ouvrir les vannes.",render:()=>routeMarkup([{label:"CIRCUIT BP",kind:"blue"},{label:"MANIFOLD"},{label:"FLEXIBLE CENTRAL",kind:"yellow"},{label:"POMPE À VIDE"}])}),
  screen({id:"chasser-air",dossier:"raccorder",title:"Une ligne ne doit pas injecter son air",kicker:"Raccorder · 4",codes:["5.01"],requiresAction:true,text:"Un flexible raccordé contient de l’air. Il est évacué selon la procédure validée de l’appareil et du plateau, avec un minimum d’émissions. Cette étape ne justifie jamais un rejet volontaire ou prolongé de réfrigérant.",prompt:"Quel principe doit guider le geste ?",render:()=>choiceMarkup([{title:"Procédure validée",note:"Évacuer l’air, limiter toute émission"},{title:"Purge longue à l’air libre",note:"« Pour être certain »"},{title:"Ouvrir toutes les vannes",note:"Sans suivre le chemin"}]),wire:()=>wireChoice(0,["L’air de la ligne est traité selon le montage prévu, sans banaliser une émission.","Un rejet prolongé est contraire à l’objectif de minimum d’émissions.","Vous créez des communications non maîtrisées dans le montage."])}),
  screen({id:"controle-raccordement",dossier:"raccorder",title:"Contrôle 2 · Raccorder",kicker:"Raccorder · contrôle",codes:["5.01"],requiresAction:true,text:"Le matériel est compatible et le poste consigné. Les flexibles sont encore libres. Vous allez raccorder le manifold.",prompt:"Quelle séquence prépare correctement l’ouverture ?",quiz:{choices:["Fermer les vannes → identifier BP/HP → raccorder → vérifier le chemin","Ouvrir les vannes → raccorder vite → chercher BP/HP","Raccorder la ligne centrale au hasard → ouvrir BP et HP","Dévisser les obus → mettre la pompe en marche"],good:0,explain:"La position fermée, l’identification et la vérification du chemin précèdent toute ouverture.",wrong:{1:"Le raccordement commence vannes fermées et côtés identifiés.",2:"Une ligne centrale doit conduire à l’appareil prévu, jamais au hasard.",3:"Ce geste ne correspond pas au montage préparé et expose le circuit."}},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"but-vide",dossier:"vide",title:"Retirer l’air et l’humidité",kicker:"Tirer au vide · 1",codes:["3.04"],text:"Après l’intervention et avant la charge, le tirage au vide évacue l’air et la vapeur d’eau présents dans le circuit. Il ne remplace ni une épreuve d’étanchéité ni une récupération de réfrigérant.",prompt:"Distinguez le but du vide de celui des autres opérations.",render:()=>'<div class="consequence"><section class="consequence-card good"><h3>TIRAGE AU VIDE</h3><p>Retirer l’air et l’humidité.</p></section><section class="consequence-card bad"><h3>CE QU’IL NE FAIT PAS</h3><p>Récupérer une charge ou prouver seul l’étanchéité.</p></section></div>'}),
  screen({id:"pompe-role",dossier:"vide",title:"La pompe aspire ; le vacuomètre mesure",kicker:"Tirer au vide · 2",codes:["3.03"],text:"La pompe crée le vide. Son huile est contrôlée avant l’usage. Le vacuomètre mesure finement le vide du circuit et se place côté circuit, pas collé à la pompe. Le manomètre du manifold n’est pas assez précis pour cette lecture.",prompt:"Associez chaque appareil à son rôle.",render:()=>'<div class="equipment-row"><div class="equipment"><img src="../bibliotheque/icones/ico-pompe-vide.png" alt=""><strong>POMPE</strong><small>aspire</small></div><div class="equipment"><img src="../bibliotheque/icones/ico-vacuometre.png" alt=""><strong>VACUOMÈTRE</strong><small>mesure côté circuit</small></div><div class="equipment"><img src="../bibliotheque/icones/ico-manifold.png" alt=""><strong>MANIFOLD</strong><small>ouvre le chemin</small></div></div>'}),
  screen({id:"montage-vide",dossier:"vide",title:"Monter avant de démarrer",kicker:"Tirer au vide · 3",codes:["3.03"],requiresAction:true,text:"La pompe est contrôlée, le vacuomètre est placé côté circuit et les flexibles sont raccordés. Le chemin utile peut alors être ouvert selon le montage, puis la pompe mise en marche.",prompt:"Remettez les quatre gestes dans l’ordre.",render:()=>orderMarkup([{order:3,label:"Ouvrir le chemin utile"},{order:1,label:"Contrôler la pompe et son huile"},{order:4,label:"Démarrer la pompe"},{order:2,label:"Raccorder et placer le vacuomètre côté circuit"}]),wire:()=>wireOrder(4)}),
  screen({id:"courbes-vide",dossier:"vide",title:"La courbe raconte le circuit",kicker:"Tirer au vide · 4",codes:["3.04"],requiresAction:true,text:"Une descente qui atteint la cible prescrite puis tient après isolement est le comportement attendu. Une stagnation peut orienter vers de l’humidité résiduelle. Une remontée après isolement impose de rechercher la cause, notamment une fuite ou de l’humidité.",prompt:"Choisissez la seule conclusion prudente.",render:()=>choiceMarkup([{title:"Lire la forme et rechercher la cause",note:"Sans inventer un diagnostic"},{title:"Toute remontée prouve une fuite",note:"Une seule cause possible"},{title:"Le temps suffit",note:"Le vacuomètre est inutile"}]),wire:()=>wireChoice(0,["La courbe oriente ; le contrôle et la procédure permettent de conclure.","L’humidité résiduelle peut aussi contribuer à une remontée : il faut rechercher.","Une durée sans mesure ne dit pas le niveau de vide réel du circuit."])}),
  screen({id:"controle-vide",dossier:"vide",title:"Contrôle 3 · Tirer au vide",kicker:"Tirer au vide · contrôle",codes:["3.03","3.04"],requiresAction:true,text:"La pompe fonctionne. Le vacuomètre, installé directement à la pompe, affiche une valeur très basse. Le circuit est relié par un long flexible.",prompt:"Pourquoi cette lecture ne suffit-elle pas ?",quiz:{choices:["Elle décrit surtout la proximité de la pompe, pas forcément le vide réel du circuit","Une valeur basse prouve toujours l’absence d’humidité","Le manifold mesure mieux le vide que le vacuomètre","Il faut arrêter la pompe avant toute lecture"],good:0,explain:"Le vacuomètre se place côté circuit afin que la mesure représente le circuit et les pertes du montage.",wrong:{1:"Une valeur seule ne prouve ni la stabilité ni l’absence d’humidité.",2:"Le vacuomètre est l’instrument adapté à la mesure fine du vide.",3:"On observe pendant le tirage, puis après isolement selon la procédure."}},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"isoler-avant-arret",dossier:"isoler",title:"Isoler, puis arrêter",kicker:"Isoler · 1",codes:["3.03","3.04"],requiresAction:true,text:"Lorsque la cible définie par la procédure est atteinte et stabilisée, le circuit est isolé de la pompe avant l’arrêt. Cet ordre protège le circuit contre un retour d’huile depuis la pompe.",prompt:"Cliquez les deux gestes dans le bon ordre.",render:()=>orderMarkup([{order:2,label:"Arrêter la pompe"},{order:1,label:"Fermer la vanne côté circuit"}]),wire:()=>wireOrder(2)}),
  screen({id:"mauvais-ordre",dossier:"isoler",title:"Voir ce qu’aurait produit le mauvais choix",kicker:"Isoler · 2",requiresAction:true,text:"La pompe tourne encore et communique avec le circuit. Le technicien doit choisir. Ici, le mauvais bouton ne déclenche aucun appareil : il montre seulement la conséquence probable.",prompt:"Prenez la décision qui protège le circuit.",render:()=>choiceMarkup([{title:"Isoler le circuit, puis arrêter",note:"Le chemin retour est fermé"},{title:"Arrêter, puis chercher la vanne",note:"Risque de retour d’huile"},{title:"Débrancher la pompe en marche",note:"Montage rompu brutalement"}]),wire:()=>wireChoice(0,["Le circuit est isolé avant que la pompe cesse de créer le vide.","La pompe arrêtée reste reliée : son huile peut repartir vers le circuit.","Le raccord et le vide sont rompus sans maîtrise de la ligne."])}),
  screen({id:"controle-isoler",dossier:"isoler",title:"Contrôle 4 · Isoler",kicker:"Isoler · contrôle",codes:["3.03","3.04"],requiresAction:true,text:"Le niveau prescrit par la procédure est atteint. Vous devez observer sa tenue sans que la pompe masque une remontée.",prompt:"Quelle séquence permet l’observation ?",quiz:{choices:["Isoler côté circuit → arrêter la pompe → observer le vacuomètre","Arrêter la pompe → ouvrir les deux vannes → débrancher","Laisser la pompe tourner et conclure à l’étanchéité","Retirer le vacuomètre avant d’isoler"],good:0,explain:"L’isolement précède l’arrêt ; le vacuomètre côté circuit permet ensuite d’observer la stabilité.",wrong:{1:"Ouvrir les vannes et débrancher détruit les conditions d’observation.",2:"La pompe peut masquer une remontée et ne prouve pas l’étanchéité.",3:"Sans vacuomètre côté circuit, la tenue du vide n’est plus mesurée."}},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"fermer-stabiliser",dossier:"deconnecter",title:"Fermer, stabiliser, desserrer",kicker:"Déconnecter · 1",codes:["5.01"],requiresAction:true,text:"En fin d’opération, fermez côté circuit puis côté appareil selon le montage. Regardez la pression. Tant qu’elle évolue, attendez. Le raccord ne se desserre que lentement, lorsque l’état de la ligne est connu.",prompt:"Reconstituez le triptyque.",render:()=>orderMarkup([{order:2,label:"Laisser stabiliser"},{order:3,label:"Desserrer lentement"},{order:1,label:"Fermer les vannes prévues"}]),wire:()=>wireOrder(3)}),
  screen({id:"residu-flexible",dossier:"deconnecter",title:"Le résidu ne part pas à l’air libre",kicker:"Déconnecter · 2",codes:["5.01"],requiresAction:true,text:"Une faible pression reste une pression. Si du réfrigérant est emprisonné dans le flexible, il est récupéré par l’appareil et la procédure prévus. Desserrer d’un coup ou purger à l’atmosphère ne devient pas acceptable parce que la quantité paraît petite.",prompt:"Choisissez le geste professionnel.",render:()=>choiceMarkup([{title:"Récupérer le résidu",note:"Puis confirmer l’état de la ligne"},{title:"Purger dehors",note:"« Il n’y en a presque pas »"},{title:"Dévisser d’un coup",note:"Pour aller plus vite"}]),wire:()=>wireChoice(0,["La ligne est traitée avec un minimum d’émissions avant la déconnexion.","Chaque émission compte ; la faible quantité ne justifie pas le rejet.","Le jet résiduel peut atteindre l’opérateur et libérer du fluide."])}),
  screen({id:"cylindre-phases",dossier:"deconnecter",title:"Liquide ou gaz : suivre le cylindre",kicker:"Déconnecter · 3",codes:["5.02"],requiresAction:true,image:"",text:"Vider ou remplir un cylindre en phase liquide ou gazeuse exige d’identifier la prise, le marquage et le sens d’utilisation prévus. La couleur ou l’habitude ne remplace jamais l’étiquette et la procédure du cylindre.",prompt:"Ouvrez les deux phases pour lire leur règle commune.",render:()=>'<div class="panel"><div class="cylinder"><button class="phase liquid" type="button" data-phase="liquide" aria-pressed="false"><strong>PHASE LIQUIDE</strong><small>prise et sens identifiés</small></button><button class="phase gas" type="button" data-phase="gazeuse" aria-pressed="false"><strong>PHASE GAZEUSE</strong><small>prise et sens identifiés</small></button></div><div class="feedback" id="feedback">Deux phases, une règle : lire avant de raccorder.</div></div>',wire:()=>{$$('[data-phase]').forEach(button=>button.addEventListener("click",()=>{button.classList.add("selected");button.setAttribute("aria-pressed","true");const feedback=$("#feedback");feedback.className="feedback good";feedback.textContent=`${button.dataset.phase[0].toUpperCase()+button.dataset.phase.slice(1)} : suivre le marquage et la procédure du cylindre.`;if($$('[data-phase][aria-pressed="false"]').length===0)completeCurrent("Les deux phases ont été identifiées.")}))}}),
  screen({id:"controle-deconnexion",dossier:"deconnecter",title:"Contrôle 5 · Déconnecter",kicker:"Déconnecter · contrôle",codes:["5.01","5.02"],requiresAction:true,text:"Les vannes sont fermées. Le manomètre indique encore une pression résiduelle dans le flexible relié au cylindre.",prompt:"Que faites-vous ?",quiz:{choices:["Attendre la stabilité, récupérer le résidu, puis desserrer lentement","Desserrer d’un coup puisque les vannes sont fermées","Purger le flexible à l’atmosphère","Retourner le cylindre sans lire son marquage"],good:0,explain:"La fermeture ne suffit pas : l’état de la ligne est observé, le résidu récupéré et le raccord desserré lentement.",wrong:{1:"La ligne peut rester sous pression malgré les vannes fermées.",2:"Le résidu doit être récupéré, jamais volontairement rejeté.",3:"La phase et le sens d’utilisation viennent du marquage et de la procédure."}},render(){return quizMarkup(this)},wire(){wireQuiz(this)}}),

  screen({id:"chaine-complete",dossier:"bilan",title:"Tenir la chaîne complète",kicker:"Enchaîner · 1",codes:["3.03","3.04","4.05","5.01","5.02"],requiresAction:true,image:"",text:"Chaque geste prépare le suivant. Une vanne oubliée au début réapparaît au moment du vide ou de la déconnexion. Rejouez maintenant le fil sans appareil réel.",prompt:"Cliquez les huit étapes dans l’ordre.",render:()=>`<div class="full-chain">${[{order:5,label:"Isoler"},{order:1,label:"Fermer"},{order:7,label:"Stabiliser"},{order:3,label:"Vérifier le chemin"},{order:8,label:"Déconnecter proprement"},{order:2,label:"Raccorder"},{order:6,label:"Arrêter"},{order:4,label:"Tirer au vide"}].map(item=>`<button class="sequence-step" type="button" data-order="${item.order}">${esc(item.label)}</button>`).join('<span class="sequence-arrow">→</span>')}</div><div class="feedback" id="feedback">Commencez par la position sûre du manifold.</div>`,wire:()=>wireOrder(8)}),
  screen({id:"deux-reperes",dossier:"bilan",title:"Deux phrases à dire avant le geste",kicker:"Enchaîner · 2",image:"",text:"Avant le raccordement : « fermé, identifié, chemin vérifié ». Avant l’arrêt de la pompe : « isoler, puis arrêter ». Ces deux phrases courtes empêchent les erreurs les plus difficiles à rattraper.",prompt:"Dites-les à voix haute, puis visualisez le chemin.",render:()=>'<div class="consequence"><section class="consequence-card good"><h3>AVANT DE RACCORDER</h3><p>Fermé · identifié · chemin vérifié.</p></section><section class="consequence-card good"><h3>AVANT D’ARRÊTER</h3><p>Isoler · puis arrêter.</p></section></div>'}),
  screen({id:"bilan",dossier:"bilan",title:"Prêt à passer au plateau",kicker:"Bilan",text:"Vous avez relié les cinq compétences officielles des fiches p1, p3 et p5. Le score porte sur cinq décisions. Il ne remplace ni la manipulation encadrée, ni les valeurs et procédures du matériel utilisé.",prompt:"Reprenez un contrôle si l’ordre n’est pas encore automatique.",render:()=>{const quizzes=screens.filter(item=>item.quiz);const correct=quizzes.filter(item=>quizAnswers[item.id]===item.quiz.good).length;return `<div class="score"><div class="score-number">${correct}/${quizzes.length}</div><p>${correct===quizzes.length?"Les cinq décisions sont justes. Rejouez maintenant la chaîne sur le poste encadré.":`${quizzes.length-correct} contrôle${quizzes.length-correct>1?"s":""} à reprendre avant la manipulation.`}</p><button class="primary-button" id="restart-quiz" type="button">Revoir les contrôles</button></div>`},wire:()=>{$("#restart-quiz").addEventListener("click",()=>{Object.keys(quizAnswers).forEach(key=>delete quizAnswers[key]);screens.filter(item=>item.quiz).forEach(item=>completed.delete(item.id));goToId("controle-manifold")})}}),
];

function renderHome(){$("#dossier-grid").innerHTML=dossiers.map((dossier,index)=>`<button class="dossier-button" type="button" data-dossier="${dossier.id}"><b>${index+1}</b><span>${esc(dossier.label)}<small>${esc(dossier.note)}</small></span></button>`).join("");$$('[data-dossier]').forEach(button=>button.addEventListener("click",()=>startCourse(button.dataset.dossier)))}
function showHome(){stopSpeech();document.body.classList.remove("course-running");$("#home").hidden=false;$("#course-shell").hidden=true;$("#home-button").hidden=true;$("#exit-button").hidden=true;$("#mode-badge").textContent="Cours complet";history.replaceState(null,"",location.pathname);scrollTo(0,0)}
function startCourse(dossierId="manifold",screenNumber=1){extractMode=false;activeScreens=[...screens];const first=Math.max(0,activeScreens.findIndex(item=>item.dossier===dossierId));current=Math.min(activeScreens.length-1,first+Math.max(0,screenNumber-1));furthest=Math.max(furthest,current);openCourse();renderCurrent(false)}
function startExtract(ids){const picked=ids.map(id=>screens.find(item=>item.id===id)).filter(Boolean);if(!picked.length){showHome();setStatus("Extrait introuvable.");return}extractMode=true;activeScreens=picked;current=0;furthest=0;openCourse();renderCurrent(false)}
function openCourse(){document.body.classList.add("course-running");$("#home").hidden=true;$("#course-shell").hidden=false;$("#home-button").hidden=false;$("#exit-button").hidden=false;$("#mode-badge").textContent=extractMode?"Mode extrait":"Cours complet";$("#rail-mode").textContent=extractMode?"EXTRAIT":"PARCOURS";scrollTo(0,0)}
function renderStepper(item){const groups=extractMode?[{id:"extrait",label:"Extrait"}]:dossiers;$("#stepper").innerHTML=groups.map((group,index)=>{const indices=activeScreens.map((screenItem,screenIndex)=>({screenItem,screenIndex})).filter(entry=>extractMode||entry.screenItem.dossier===group.id).map(entry=>entry.screenIndex);const first=indices[0]??0;const active=extractMode||item.dossier===group.id;const done=indices.length&&Math.max(...indices)<furthest;return `<button class="step-button ${active?"active":""} ${done?"done":""}" type="button" data-step="${first}" ${active?'aria-current="step"':""}><b>${index+1}</b><span>${esc(group.label)}</span></button>`}).join("");$$('[data-step]').forEach(button=>button.addEventListener("click",()=>goTo(Number(button.dataset.step))));const total=activeScreens.length;$("#rail-progress").textContent=`${current+1} / ${total}`;$("#progress-bar").style.width=`${(current+1)/total*100}%`;$("#progress-copy").textContent=current===total-1?"Fin du parcours":`${total-current-1} écran${total-current-1>1?"s":""} à voir`}
function renderCurrent(moveFocus=true){stopSpeech(false);const item=activeScreens[current];if(!item)return;scrollTo(0,0);$("#lesson-kicker").textContent=item.kicker;$("#lesson-title").textContent=item.title;$("#lesson-text").textContent=item.text;$("#action-prompt").textContent=item.prompt;const activity=item.render?item.render():routeMarkup([{label:"OBSERVER"},{label:"COMPRENDRE"},{label:"AGIR"}]);$("#activity-zone").innerHTML=item.image?`<div class="visual-split"><img src="${esc(item.image)}" alt="${esc(item.imageAlt)}"><div class="visual-host">${activity}</div></div>`:activity;item.wire?.();$("#reference-box").innerHTML=item.codes.length?`<strong>Référentiel</strong> · ${item.codes.map(esc).join(" · ")}`:"<strong>Contexte</strong> · préparation au geste";renderStepper(item);updateNav();updateUrl();if(moveFocus)$("#lesson-title").focus({preventScroll:true});if(autoplay)setTimeout(()=>speakCurrent(),320)}
function updateNav(){const item=activeScreens[current];$("#prev-button").disabled=current===0;const blocked=item?.requiresAction&&!completed.has(item.id);$("#next-button").disabled=blocked;$("#next-button").textContent=current===activeScreens.length-1?"Terminer":"Suivant →"}
function goTo(index){if(index<0||index>=activeScreens.length)return;current=index;furthest=Math.max(furthest,current);renderCurrent()}
function goToId(id){const index=activeScreens.findIndex(item=>item.id===id);if(index>=0)goTo(index)}
function previous(){if(current>0)goTo(current-1)}
function next(){const item=activeScreens[current];if(item.requiresAction&&!completed.has(item.id)){setStatus("Réalisez l’activité avant de continuer.");return}if(current<activeScreens.length-1)goTo(current+1);else showHome()}
function updateUrl(){const item=activeScreens[current];const url=new URL(location.href);url.search="";if(extractMode)url.searchParams.set("extrait",activeScreens.map(screenItem=>screenItem.id).join(","));else{url.searchParams.set("dossier",item.dossier);const dossierScreens=activeScreens.filter(screenItem=>screenItem.dossier===item.dossier);url.searchParams.set("ecran",String(dossierScreens.indexOf(item)+1))}history.replaceState(null,"",url)}
function screenLink(){const url=new URL(location.href);url.search="";url.searchParams.set("extrait",activeScreens[current].id);return url.href}
async function copyCurrentLink(){const link=screenLink();try{await navigator.clipboard.writeText(link)}catch(_){const area=document.createElement("textarea");area.value=link;area.setAttribute("readonly","");area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();document.execCommand("copy");area.remove()}setStatus("Lien de cet écran copié.")}
function speechSupported(){return"speechSynthesis"in window&&"SpeechSynthesisUtterance"in window}
function chooseFrenchVoice(){const voices=speechSynthesis.getVoices();const quality=voice=>/natural|naturel|neural|online|google|microsoft|denise|henri|julie|paul|hortense/i.test(voice.name);return voices.find(voice=>voice.lang.toLowerCase()==="fr-fr"&&quality(voice))||voices.find(voice=>voice.lang.toLowerCase()==="fr-fr")||voices.find(voice=>voice.lang.toLowerCase().startsWith("fr")&&quality(voice))||voices.find(voice=>voice.lang.toLowerCase().startsWith("fr"))||voices[0]}
function stopSpeech(disableAutoplay=true){speechRun+=1;if(speechSupported())speechSynthesis.cancel();speaking=false;paused=false;if(disableAutoplay)autoplay=false;updateVoiceButtons()}
function speakCurrent(){if(!speechSupported()){setStatus("La synthèse vocale n’est pas disponible. Le texte affiché reste complet.");return}stopSpeech(false);const item=activeScreens[current];const run=++speechRun;const visible=`${item.title}. ${item.text} ${item.prompt}`;const utterance=new SpeechSynthesisUtterance(item.speak||stripHtml(visible));utterance.lang="fr-FR";utterance.pitch=1;utterance.rate=voiceRates[rateIndex];const voice=chooseFrenchVoice();if(voice)utterance.voice=voice;utterance.onstart=()=>{if(run!==speechRun)return;speaking=true;paused=false;updateVoiceButtons()};utterance.onend=()=>{if(run!==speechRun)return;speaking=false;paused=false;updateVoiceButtons()};utterance.onerror=event=>{if(run!==speechRun||["canceled","interrupted"].includes(event.error))return;speaking=false;paused=false;updateVoiceButtons();setStatus("La voix est indisponible ; poursuivez avec le texte affiché.")};speaking=true;paused=false;updateVoiceButtons();speechSynthesis.speak(utterance)}
function toggleSpeech(){if(!speechSupported()){setStatus("La synthèse vocale n’est pas disponible.");return}autoplay=true;if(speaking&&!paused){speechSynthesis.pause();paused=true;updateVoiceButtons();return}if(speaking&&paused){speechSynthesis.resume();paused=false;updateVoiceButtons();return}speakCurrent()}
function updateVoiceButtons(){const button=$("#listen");if(!button)return;button.innerHTML=speaking&&!paused?'<span aria-hidden="true">Ⅱ</span><span>Pause</span>':speaking&&paused?'<span aria-hidden="true">▶</span><span>Reprendre</span>':'<span aria-hidden="true">▶</span><span>Écouter</span>';$("#stop-voice").disabled=!speaking;$("#speed-value").textContent=voiceRates[rateIndex].toFixed(2).replace(".",",")+"×"}
function changeRate(direction){rateIndex=Math.max(0,Math.min(voiceRates.length-1,rateIndex+direction));saveRate();updateVoiceButtons();if(speaking||paused)speakCurrent()}
function buildPrintBook(){const quizCount=screens.filter(item=>item.quiz).length;$("#print-book").innerHTML=`<header class="print-title"><h1>La chaîne de l’intervention</h1><p>Fiches p1 + p3 + p5 · 25 écrans · 5 codes distincts · ${quizCount} contrôles.</p><p class="print-chain-note"><strong>Préparation pratique :</strong> les valeurs cibles et procédures restent celles de la notice, du fluide et du plateau.</p></header>`+screens.map((item,index)=>`<article class="print-screen"><h2>${index+1}. ${esc(item.title)}</h2><p>${esc(item.text)}</p>${item.prompt?`<h3>Action à réaliser</h3><p>${esc(item.prompt)}</p>`:""}${item.quiz?`<div class="print-answer"><strong>Correction :</strong> ${esc(item.quiz.choices[item.quiz.good])}. ${esc(item.quiz.explain)}</div>`:""}<p class="print-codes">Référentiel · ${item.codes.length?esc(item.codes.join(" · ")):"contexte"}</p></article>`).join("")}
function handleInitialUrl(){const params=new URLSearchParams(location.search);const extract=params.get("extrait");if(extract){startExtract(extract.split(",").map(value=>value.trim()).filter(Boolean));return}const dossier=params.get("dossier");if(dossier){startCourse(dossier,Number(params.get("ecran"))||1);return}showHome()}
function bindGlobalEvents(){$("#start-button").addEventListener("click",()=>startCourse());$("#home-button").addEventListener("click",showHome);$("#exit-button").addEventListener("click",showHome);$("#prev-button").addEventListener("click",previous);$("#next-button").addEventListener("click",next);$("#copy-link").addEventListener("click",copyCurrentLink);$("#listen").addEventListener("click",toggleSpeech);$("#stop-voice").addEventListener("click",()=>stopSpeech());$("#slower").addEventListener("click",()=>changeRate(-1));$("#faster").addEventListener("click",()=>changeRate(1));addEventListener("keydown",event=>{const tag=document.activeElement?.tagName;if(["INPUT","TEXTAREA","SELECT","BUTTON"].includes(tag))return;if(event.key==="ArrowRight"){event.preventDefault();next()}else if(event.key==="ArrowLeft"){event.preventDefault();previous()}else if(event.key===" "){event.preventDefault();toggleSpeech()}else if(event.key==="Escape")showHome()});addEventListener("beforeunload",()=>stopSpeech());document.addEventListener("visibilitychange",()=>{if(document.hidden)stopSpeech()});if(speechSupported())speechSynthesis.addEventListener?.("voiceschanged",()=>{})}

renderHome();
buildPrintBook();
bindGlobalEvents();
updateVoiceButtons();
handleInitialUrl();
