(() => {
  "use strict";
  const shell=(id,title,desc,body)=>`<svg viewBox="0 0 720 420" role="img" aria-labelledby="${id}-title ${id}-desc"><title id="${id}-title">${title}</title><desc id="${id}-desc">${desc}</desc><defs><marker id="arr-${id}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0 0L0 6L9 3Z" fill="#1b3a63"/></marker><pattern id="warm-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#c9451a" stroke-width="2"/></pattern><pattern id="cool-${id}" width="9" height="9" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="1.5" fill="#3d7fca"/></pattern></defs>${body}</svg>`;
  const intro=shell("tam-intro","Volume tampon et fonctions à démontrer","Un ballon vertical apporte un volume d’eau. Trois étiquettes sont séparées : inertie démontrée par le volume traversé, découplage à vérifier par le raccordement, mélange ou stratification à observer.",`<image href="assets/ballon-tampon.svg" x="280" y="85" width="160" height="240"/><rect x="30" y="80" width="205" height="70" rx="16" fill="#fffdf8" stroke="#1e7e54" stroke-width="5"/><text x="132" y="110" text-anchor="middle" font-size="16" font-weight="700">VOLUME / INERTIE</text><text x="132" y="136" text-anchor="middle" font-size="13">si volume utile mobilisé</text><rect x="485" y="80" width="205" height="70" rx="16" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="588" y="110" text-anchor="middle" font-size="16" font-weight="700">DÉCOUPLAGE ?</text><text x="588" y="136" text-anchor="middle" font-size="13">raccordement à vérifier</text><rect x="485" y="265" width="205" height="70" rx="16" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="588" y="295" text-anchor="middle" font-size="16" font-weight="700">STRATIFICATION ?</text><text x="588" y="321" text-anchor="middle" font-size="13">conditions à vérifier</text><path d="M235 115H278M440 115H484M440 300H484" stroke="#1b3a63" stroke-width="5" marker-end="url(#arr-tam-intro)"/>`);
  const connection=(mode=0)=>{
    const id=`tam-mode-${mode}`;
    const data=[
      {title:"DEUX PIQUAGES · EN SÉRIE",desc:"Le même débit traverse le ballon. Le volume utile contribue à l’inertie. Il n’y a pas deux circuits hydrauliquement séparés dans ce schéma.",body:`<path d="M45 115H285M435 305H675" stroke="#1b3a63" stroke-width="12"/><image href="assets/ballon-tampon.svg" x="285" y="75" width="150" height="270"/><path d="M130 115H255" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-${id})"/><path d="M585 305H465" stroke="#3d7fca" stroke-width="6" marker-end="url(#arr-${id})"/><text x="360" y="55" text-anchor="middle" font-size="20" font-weight="700">UN SEUL CHEMIN</text><text x="360" y="385" text-anchor="middle" font-size="16">Inertie : oui · Découplage : non démontré</text>`},
      {title:"QUATRE PIQUAGES · PRIMAIRE / SECONDAIRE",desc:"Deux circuits et deux circulateurs sont reliés au volume commun. Ce schéma peut assurer inertie et découplage hydraulique; les transferts internes restent à analyser.",body:`<image href="assets/ballon-tampon.svg" x="285" y="75" width="150" height="270"/><path d="M45 130H300M300 295H45M420 130H675M675 295H420" stroke="#1b3a63" stroke-width="11"/><circle cx="120" cy="130" r="26" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><circle cx="600" cy="130" r="26" fill="#fffdf8" stroke="#1b3a63" stroke-width="4"/><text x="120" y="136" text-anchor="middle" font-size="14" font-weight="700">P1</text><text x="600" y="136" text-anchor="middle" font-size="14" font-weight="700">P2</text><path d="M165 130H260M555 130H460" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-${id})"/><text x="360" y="55" text-anchor="middle" font-size="20" font-weight="700">DEUX CIRCUITS · VOLUME COMMUN</text><text x="360" y="385" text-anchor="middle" font-size="16">Inertie + découplage possibles dans ce schéma</text>`},
      {title:"PIQUAGE EN DÉRIVATION",desc:"Le ballon est raccordé sur une branche latérale. La part du volume réellement traversée dépend des conditions hydrauliques; aucun découplage n’est démontré par le dessin seul.",body:`<path d="M45 155H675" stroke="#1b3a63" stroke-width="12"/><path d="M360 155V235" stroke="#1b3a63" stroke-width="10"/><image href="assets/ballon-tampon.svg" x="285" y="215" width="150" height="190"/><path d="M110 155H300" stroke="#c9451a" stroke-width="6" marker-end="url(#arr-${id})"/><text x="360" y="55" text-anchor="middle" font-size="20" font-weight="700">BRANCHE LATÉRALE</text><rect x="450" y="245" width="220" height="85" rx="14" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="560" y="278" text-anchor="middle" font-size="15" font-weight="700">VOLUME UTILE ?</text><text x="560" y="305" text-anchor="middle" font-size="13">circulation à vérifier</text>`}
    ][mode]||null;
    return shell(id,data.title,data.desc,data.body);
  };
  const roles=shell("tam-roles","Fonctions attribuées avec prudence","Trois cartes distinguent fonction montrée, fonction à vérifier et fonction non démontrée. La forme du ballon ne suffit pas.",`<rect x="35" y="75" width="200" height="270" rx="20" fill="#fffdf8" stroke="#1e7e54" stroke-width="5"/><text x="135" y="115" text-anchor="middle" font-size="17" font-weight="700">MONTRÉE</text><text x="135" y="170" text-anchor="middle" font-size="15">volume d’eau</text><text x="135" y="205" text-anchor="middle" font-size="15">chemin traversé</text><rect x="260" y="75" width="200" height="270" rx="20" fill="#fff4e0" stroke="#b06a00" stroke-width="4" stroke-dasharray="5 4"/><text x="360" y="115" text-anchor="middle" font-size="17" font-weight="700">À VÉRIFIER</text><text x="360" y="170" text-anchor="middle" font-size="15">volume utile</text><text x="360" y="205" text-anchor="middle" font-size="15">transferts internes</text><text x="360" y="240" text-anchor="middle" font-size="15">températures</text><rect x="485" y="75" width="200" height="270" rx="20" fill="#fbe7e4" stroke="#c0392b" stroke-width="4" stroke-dasharray="9 6"/><text x="585" y="115" text-anchor="middle" font-size="17" font-weight="700">NON AUTOMATIQUE</text><text x="585" y="170" text-anchor="middle" font-size="15">découplage</text><text x="585" y="205" text-anchor="middle" font-size="15">stratification</text><text x="585" y="240" text-anchor="middle" font-size="15">rendement</text>`);
  const useful=(value=60)=>shell("tam-useful","Part de volume balayée dans un modèle qualitatif",`La part représentée comme balayée vaut ${value} pour cent du volume dessiné. Cette commande qualitative ne calcule pas le volume utile réel d’un produit.`,`<path d="M260 45C205 45 185 95 185 210S205 375 260 375H460C515 375 535 325 535 210S515 45 460 45Z" fill="#fffdf8" stroke="#1b3a63" stroke-width="5"/><clipPath id="clip-tam-useful"><path d="M260 45C205 45 185 95 185 210S205 375 260 375H460C515 375 535 325 535 210S515 45 460 45Z"/></clipPath><rect x="185" y="${375-3.3*value}" width="350" height="${3.3*value}" fill="url(#cool-tam-useful)" clip-path="url(#clip-tam-useful)"/><path d="M185 110H70M535 310H650" stroke="#1b3a63" stroke-width="11"/><text x="360" y="205" text-anchor="middle" font-size="28" font-weight="700">${value} %</text><text x="360" y="238" text-anchor="middle" font-size="16">part balayée représentée</text><text x="360" y="405" text-anchor="middle" font-size="14">Donnée qualitative du scénario · pas un dimensionnement</text>`);
  const method=shell("tam-method","Vérifier les fonctions du raccordement","Cinq étapes : lire les piquages, suivre les débits, observer le volume mobilisé, vérifier les transferts et températures, conclure seulement sur les fonctions prouvées.",`<g fill="#fffdf8" stroke="#1b3a63" stroke-width="3">${["PIQUAGES","DÉBITS","VOLUME UTILE","TRANSFERTS / T°","CONCLUSION"].map((t,i)=>`<rect x="${15+i*142}" y="150" width="125" height="110" rx="15"/><text x="${77+i*142}" y="194" text-anchor="middle" font-size="13" font-weight="700">${t}</text><text x="${77+i*142}" y="228" text-anchor="middle" font-size="12">${i+1}</text>`).join("")}</g>${[0,1,2,3].map(i=>`<path d="M${140+i*142} 205H${155+i*142}" stroke="#c9451a" stroke-width="5" marker-end="url(#arr-tam-method)"/>`).join("")}`);

  window.STATION_CONFIG={code:"M4",id:"tampon",title:"Volume tampon — Quatre piquages",next:"poursuivre vers le découplage",levels:{CAP:{objective:"Reconnaître le ballon tampon et suivre le chemin de l’eau.",assessment:"nommer le ballon et suivre un piquage"},TP:{objective:"Reconnaître le raccordement et attribuer seulement les fonctions visibles.",assessment:"lire les piquages, suivre le chemin et limiter la conclusion"},BTS:{objective:"Analyser volume utile, transferts et découplage selon l’architecture.",assessment:"comparer les montages et justifier les fonctions avec leurs conditions"}},steps:[
    {short:"Rôle",kicker:"observer",title:"Un ballon n’a pas une seule fonction",text:"Le volume apporte une possibilité d’inertie. Les autres fonctions dépendent du raccordement et des conditions.",cap:"Montre le ballon et l’eau qu’il contient.",tp:"Distingue volume, inertie et découplage.",bts:"Sépare propriété géométrique, fonction hydraulique et performance à vérifier.",scene:intro,equivalent:"Le volume peut contribuer à l’inertie; découplage et stratification restent à démontrer.",action:{type:"choice",prompt:"Quelle affirmation est prudente ?",options:[{label:"Le raccordement détermine les fonctions réellement assurées"},{label:"Tout ballon découple automatiquement"},{label:"Quatre piquages garantissent toute performance"},{label:"Le volume nominal est toujours entièrement utile"}],correct:0,explain:"Il faut suivre les circuits et vérifier les conditions avant d’attribuer une fonction."}},
    {short:"Comparer",kicker:"manipuler",title:"Trois raccordements, trois lectures",text:"Choisis le schéma qui montre deux circuits reliés au volume commun.",cap:"Compte les tuyaux reliés au ballon sur le dessin.",tp:"Repère les circulateurs et les quatre piquages.",bts:"Relie l’architecture aux transferts possibles entre primaire et secondaire.",scene:connection,equivalent:(value)=>["Montage série : un seul chemin; inertie visible, pas de découplage démontré.","Montage quatre piquages : deux circuits et un volume commun; découplage possible dans le schéma.","Montage en dérivation : circulation dans le volume à vérifier; découplage non démontré."][value||0],action:{type:"choice",sceneFor:true,prompt:"Quel dessin montre deux circuits avec deux débits pouvant différer ?",options:[{label:"Deux piquages en série"},{label:"Quatre piquages primaire / secondaire"},{label:"Piquage en dérivation"}],correct:1,explain:"Le montage quatre piquages montré relie deux circuits au volume commun. Il faut encore analyser les transferts."}},
    {short:"Attribuer",kicker:"interpréter",title:"Fonction montrée ou supposée ?",text:"Classe les affirmations sans surpromesse.",cap:"Nomme ce que montre vraiment le dessin.",tp:"Écris ce que le schéma permet d’affirmer.",bts:"Nomme les vérifications nécessaires avant dimensionnement.",scene:roles,equivalent:"Les fonctions sont classées en montrées, à vérifier et non automatiques.",action:{type:"match",prompt:"Associe chaque affirmation à son niveau de preuve.",options:["Montrée par le schéma","À vérifier par mesures","Non automatique"],items:[{label:"Présence d’un volume d’eau",answer:0},{label:"Part réellement balayée",answer:1},{label:"Découplage pour tout raccordement",answer:2}],explain:"La présence du ballon ne prouve ni le volume utile ni le découplage dans toutes les architectures."}},
    {short:"Volume utile",kicker:"mesurer",title:"Nominal ne veut pas dire utile",text:"Déplace la part balayée représentée. Le curseur est qualitatif et ne dimensionne aucun produit.",cap:"Lis le pourcentage affiché sur le ballon.",tp:"Observe que le chemin peut mobiliser une part différente du volume.",bts:"Explique les limites d’un modèle sans données d’écoulement et de température.",scene:useful,equivalent:(v)=>`Le modèle colore ${v} pour cent du volume comme balayé. Cette part est une donnée pédagogique, pas un résultat de produit.`,action:{type:"range",prompt:"Fais varier la part de volume balayée.",label:"Part représentée",min:20,max:100,step:10,value:60,evaluate:(v)=>({readout:`${v} %`,observation:v<50?"Une faible part est représentée mobilisée : le volume nominal ne suffit pas.":v<100?"Une part importante est mobilisée, mais le modèle ne prouve ni stratification ni performance réelle.":"Tout le volume est coloré dans le dessin; seule une mesure ou une étude réelle confirmerait ce cas."})}},
    {short:"Vérifier",kicker:"conclure",title:"Prouver le rôle réel",text:"Ordonne les contrôles avant de parler de découplage.",cap:"Suis les tuyaux avant de nommer le rôle du ballon.",tp:"Suis les circuits et rends compte.",bts:"Croise débits et températures avant le bilan.",scene:method,equivalent:"La méthode lit les piquages, suit les débits, observe le volume utile, vérifie transferts et températures, puis conclut.",action:{type:"sequence",prompt:"Place la vérification dans l’ordre.",items:["Lire les piquages","Suivre les débits","Observer le volume utile","Vérifier transferts et températures","Conclure"],correctOrder:[0,1,2,3,4],explain:"La fonction se démontre à partir de l’architecture et des grandeurs, pas du nom ballon tampon."}}
  ],quiz:[
    {context:"Un ballon est raccordé en série avec deux piquages.",question:"Quelle fonction est directement visible ?",options:["Ajout de volume sur le chemin","Découplage de deux circuits","Équilibrage automatique","Stratification garantie"],correct:0,explain:"Un seul chemin traverse le volume; le découplage n’est pas démontré."},
    {context:"Un schéma montre quatre piquages et deux circulateurs.",question:"Quelle conclusion est juste ?",options:["Deux débits peuvent différer; les transferts internes sont à analyser","Toutes les températures sont identiques","Le ballon équilibre toutes les branches","Le volume utile est toujours nominal"],correct:0,explain:"Le schéma permet le découplage, mais son fonctionnement se vérifie par les flux et températures."},
    {context:"Le volume nominal est connu.",question:"Que faut-il encore vérifier ?",options:["La part réellement mobilisée dans les conditions du système","La couleur de la cuve","Le nom du fabricant seul","Un seuil universel"],correct:0,explain:"Le volume utile dépend du raccordement et du fonctionnement."},
    {context:"Un dossier attribue trois fonctions au ballon sans schéma.",question:"Quelle démarche adopter ?",options:["Lire piquages, débits et températures avant de confirmer","Recopier les fonctions","Supposer un découplage","Ignorer le raccordement"],correct:0,explain:"Chaque fonction doit être reliée à une preuve du montage."}
  ],summaryScene:connection(1),summaryEquivalent:"Synthèse : le montage quatre piquages peut associer inertie et découplage; les transferts et le volume utile restent à vérifier."};
})();
