window.OIL_MODULE = {
  id: "clapet-differentiel-huile-pedagogique",
  title: "Le clapet différentiel d’huile",
  subtitle: "LE CIRCUIT D’HUILE · STATION 9",
  codes: ["1.05", "6.05"],
  voix: true,
  nextStep: "Poursuivre avec le régulateur mécanique : une pression d’huile disponible ne suffit pas, il faut encore admettre uniquement la quantité demandée par chaque carter.",
  nextUrl: "../regulateur-huile-mecanique-pedagogique/index.html",
  nextLabel: "Station 10 · Le régulateur mécanique AC&R",
  summaryVisual: { kind: "differential", label: "Clapet taré entre la partie haute du réservoir et l’aspiration pour maintenir un différentiel prévu" },
  lessons: [
    { id: "rappel", short: "Rappel", kicker: "Station 1 · Retour spiralé", recall: true, title: "Le réservoir doit pousser l’huile vers le carter", lead: "L’écoulement exige une pression disponible supérieure à celle du carter.", details: ["Cette différence doit aussi vaincre les pertes de charge de la conduite, de la vanne, du filtre et du régulateur.", "Dans un système basse pression, le clapet taré contrôle la pression du réservoir par rapport à l’aspiration."], box: { type: "key", text: "Le clapet crée une condition de circulation ; il ne règle pas directement le niveau du carter." }, visual: { kind: "active", title: "Distinguer pression et niveau", label: "Réservoir, branche de pression vers aspiration et conduite d’huile vers régulateur" } },
    { id: "branche", short: "Branche", kicker: "Station 2 · Implantation", title: "Le clapet travaille sur la branche de pression", lead: "Il relie la partie haute du réservoir à une pression de référence, généralement l’aspiration prévue par le concepteur.", details: ["Il évacue l’excès de pression afin de conserver un écart déterminé au-dessus de cette référence.", "L’huile liquide suit une autre conduite vers le filtre et les régulateurs : elle ne traverse pas normalement ce clapet."], box: { type: "warning", text: "Ne pas dessiner le clapet taré en série dans la ligne d’alimentation d’huile." }, visual: { kind: "differential", title: "Lire la bonne branche", label: "Branche de pression du réservoir vers l’aspiration, distincte de la ligne d’huile" } },
    { id: "fonctionnement", short: "Tarage", kicker: "Station 3 · Fonctionnement", title: "Le ressort fixe l’écart de pression recherché", lead: "Tant que la pression reste sous la condition d’ouverture, le clapet demeure fermé.", details: ["Quand la pression du réservoir dépasse la référence de la valeur prévue, il s’ouvre vers l’aspiration.", "Le choix du tarage dépend des régulateurs, des pertes de charge et des variations de pression du système."], box: { type: "exam", text: "Tarage = différence de pression contrôlée, pas pression absolue universelle." }, visual: { kind: "differential", title: "Comparer les deux pressions", label: "Pression réservoir, ressort taré et pression d’aspiration" } },
    { id: "modeles", short: "Modèles", kicker: "Station 4 · Sélection", title: "Fixe ou réglable : la notice commande", lead: "Un clapet fixe possède un ressort étalonné ; un modèle réglable permet une adaptation dans sa plage autorisée.", details: ["Vérifier sens de passage, raccordements, pression admissible, plage différentielle et compatibilité fluide-huile.", "Un réglage ne se fait jamais pour « essayer » : il répond au calcul et à la documentation de l’installation."], box: { type: "warning", text: "Un bouchon de réglage ou un plombage protège contre les manœuvres accidentelles : ne pas les neutraliser." }, visual: { kind: "differential", title: "Sélectionner sans improviser", label: "Clapet différentiel avec sens, ressort et réglage protégé" } },
    { id: "pressions-multiples", short: "Centrale", kicker: "Station 5 · Plusieurs aspirations", title: "La pression de référence doit couvrir tous les carters concernés", lead: "Une centrale peut alimenter des compresseurs fonctionnant à des pressions d’aspiration différentes.", details: ["Le réservoir doit rester suffisamment au-dessus du carter soumis à la pression de référence la plus défavorable.", "Le point de raccordement et le clapet se sélectionnent selon l’architecture réelle, notamment pour les systèmes à étages."], box: { type: "exam", text: "La plus forte pression d’aspiration concernée peut devenir la condition dimensionnante." }, visual: { kind: "active", title: "Penser à tous les compresseurs", label: "Réserve commune alimentant plusieurs carters à des conditions différentes" } },
    { id: "defauts", short: "Défauts", kicker: "Station 6 · Symptômes", title: "Trop peu ou trop de différentiel produisent des défauts opposés", lead: "Si l’écart est insuffisant, l’huile circule mal vers les régulateurs.", details: ["Si l’écart est excessif, le régulateur peut être alimenté trop brutalement et le carter perturbé.", "Une flèche inversée, un ressort inadapté, une conduite obstruée ou une aspiration très variable peuvent reproduire ces symptômes."], box: { type: "key", text: "Mesurer les pressions avant d’accuser le régulateur de niveau." }, visual: { kind: "decision", title: "Relier symptôme et mesure", label: "Décision à partir du niveau, du régime et du différentiel mesuré" } },
    { id: "verification", short: "Vérifier", kicker: "Station 7 · Méthode", title: "Le contrôle compare réservoir et pression de référence", lead: "Relever les deux pressions dans un régime stabilisé et identifier les compresseurs actifs.", details: ["Comparer le différentiel obtenu à la valeur prescrite pour le clapet et les régulateurs.", "Contrôler ensuite sens, raccordement, stabilité et absence de fuite avant tout réglage ou remplacement."], box: { type: "exam", text: "Pression réservoir moins pression de référence = différentiel observé ; l’acceptation vient de la notice." }, visual: { kind: "diagnostic", title: "Mesurer puis interpréter", label: "Contrôle du réservoir, du clapet, de la ligne d’huile et du régulateur" } }
  ],
  quiz: [
    { prompt: "Quelle est la mission du clapet taré ?", options: ["Maintenir un différentiel de pression prévu", "Mesurer la surchauffe à l’aspiration", "Limiter la pression de condensation"], correct: 0, why: "Il contrôle la pression du réservoir par rapport à une référence.", code: "1.05" },
    { prompt: "Dans quelle conduite se trouve-t-il ?", options: ["La ligne liquide, après le détendeur", "La branche de pression vers l’aspiration", "La conduite d’huile vers chaque régulateur"], correct: 1, why: "La ligne d’huile vers les régulateurs est une autre branche.", code: "1.05" },
    { prompt: "Que signifie le tarage ?", options: ["Une température fixe d’enclenchement", "La quantité d’huile du réservoir", "Une différence de pression d’ouverture"], correct: 2, why: "Le ressort contrôle un écart entre l’amont et la référence.", code: "1.05" },
    { prompt: "De quoi dépend la valeur de tarage retenue ?", options: ["Du système, des organes et des régimes", "Du modèle de compresseur seulement", "D’une valeur unique donnée par la norme"], correct: 0, why: "Variations d’aspiration, pertes de charge et régulateurs doivent être pris en compte.", code: "1.05" },
    { prompt: "Que vérifier sur le montage ?", options: ["Diamètre du tube et longueur de la ligne", "Sens, raccordement, plage et compatibilité", "Position verticale et hauteur au sol"], correct: 1, why: "Le clapet doit correspondre à la branche de pression réelle.", code: "1.05" },
    { prompt: "Un différentiel trop faible provoque surtout…", options: ["Une hausse du débit d’air au condenseur", "Une surchauffe excessive à l’aspiration", "Une alimentation d’huile insuffisante"], correct: 2, why: "La force motrice ne suffit plus à vaincre les pertes de charge.", code: "6.05" },
    { prompt: "Comment vérifier le clapet ?", options: ["Comparer les pressions à la valeur prescrite", "Régler jusqu’à ce que le voyant se remplisse", "Ajouter de l’huile avant toute mesure"], correct: 0, why: "Le contrôle repose sur un différentiel mesuré en conditions connues.", code: "6.05" }
  ],
  sources: [
    { title: "Parker Sporlan — Oil Level Control System", url: "https://www.parker.com/content/dam/Parker-com/Literature/Sporlan/Sporlan-pdf-files/Sporlan-pdf-110/SD-129_-Oil-Level-Control-System-Installation.pdf", use: "fonction et sélection du clapet différentiel OCV" },
    { title: "BITZER — Parallel compounding with oil level controllers", url: "https://www.bitzer.de/shared_media/html/kt-600/en-GB/313846411313848587.html", use: "dégazage du réservoir et différence de pression" },
    { title: "Légifrance — Attestation d’aptitude fluides", url: "https://www.legifrance.gouv.fr/jorf/id/JORFSCTA000053004646", use: "compétences 1.05 et 6.05" }
  ]
};
