window.OIL_MODULE = {
  id: "regulateur-huile-mecanique-pedagogique",
  title: "Le régulateur d’huile mécanique AC&R",
  subtitle: "LE CIRCUIT D’HUILE · STATION 10",
  codes: ["1.05", "6.05"],
  voix: true,
  nextStep: "Poursuivre avec TraxOil : la régulation électronique reprend la mesure et l’admission d’huile, puis ajoute une temporisation et une sortie d’alarme.",
  nextUrl: "../traxoil-pedagogique/index.html",
  nextLabel: "Station 11 · TraxOil : comment il travaille",
  summaryVisual: { kind: "mechanical", label: "Régulateur mécanique de niveau avec voyant, flotteur, levier et pointeau d’admission" },
  lessons: [
    { id: "rappel", short: "Rappel", kicker: "Station 1 · Retour spiralé", recall: true, title: "Le réservoir fournit ; le régulateur dose pour un carter", lead: "Chaque compresseur possède son propre besoin de niveau.", details: ["Le réservoir et le clapet différentiel rendent l’huile disponible.", "Le régulateur mécanique, souvent appelé « pot AC&R » en atelier, admet l’huile seulement quand son flotteur détecte un niveau trop bas."], box: { type: "key", text: "Une réserve commune peut alimenter plusieurs décisions locales de niveau." }, visual: { kind: "active", title: "Replacer le régulateur", label: "Réservoir alimentant un régulateur monté sur le carter" } },
    { id: "montage", short: "Monter", kicker: "Station 2 · Implantation", title: "Il remplace le voyant du carter ou utilise un adaptateur", lead: "Le régulateur se fixe au raccord de voyant prévu par le compresseur.", details: ["Une bride ou un adaptateur assure la liaison mécanique et l’étanchéité.", "Le voyant reste visible sur le régulateur lorsque le modèle le permet ; l’ensemble doit être parfaitement horizontal selon la notice."], box: { type: "warning", text: "Un appareil incliné fausse le flotteur et donc le niveau régulé." }, visual: { kind: "mechanical", title: "Respecter la position de travail", label: "Régulateur horizontal monté au niveau du voyant du carter" } },
    { id: "mecanisme", short: "Mécanisme", kicker: "Station 3 · Flotteur", title: "Le flotteur commande une vanne-pointeau", lead: "Quand le niveau baisse, le flotteur descend et ouvre l’admission.", details: ["L’huile entre grâce au différentiel disponible entre la ligne d’alimentation et le carter.", "Quand le niveau remonte, le flotteur referme progressivement le pointeau."], box: { type: "key", text: "Le mécanisme mesure un niveau ; il ne pompe pas l’huile." }, visual: { kind: "mechanical", title: "Suivre le mouvement", label: "Flotteur bas ouvrant le pointeau puis flotteur haut refermant l’admission" } },
    { id: "niveau", short: "Niveau", kicker: "Station 4 · Réglage", title: "Fixe ou réglable : le compresseur fixe la cible", lead: "Certains modèles maintiennent un niveau défini ; d’autres autorisent une plage d’ajustement.", details: ["Le niveau attendu vient de la documentation du compresseur et du régulateur.", "Le sens et le nombre de tours de réglage ne sont jamais devinés : ils varient selon le produit."], box: { type: "exam", text: "Ne jamais apprendre « demi-voyant » comme une règle universelle." }, visual: { kind: "observe", title: "Lire la bonne référence", label: "Voyant de carter, notice du compresseur et réglage du régulateur" } },
    { id: "differentiel", short: "Δp", kicker: "Station 5 · Alimentation", title: "Le régulateur possède une plage de différentiel admissible", lead: "Un pointeau prévu pour une faible différence de pression ne se comporte pas comme un organe haute pression.", details: ["Vérifier pression amont, pression carter, pertes de charge et plage du modèle.", "Une admission trop faible laisse le carter bas ; une admission trop brutale peut provoquer instabilité et excès."], box: { type: "warning", text: "Le clapet taré et le régulateur se sélectionnent ensemble." }, visual: { kind: "differential", title: "Comparer l’amont et le carter", label: "Différentiel entre réservoir, ligne d’huile et carter" } },
    { id: "proteger", short: "Filtrer", kicker: "Station 6 · Propreté", title: "Le pointeau doit recevoir une huile propre", lead: "Une particule peut empêcher la fermeture ou réduire le débit d’admission.", details: ["Prévoir le filtre et les vannes demandés en amont du régulateur.", "Contrôler colmatage, sens, ouverture et perte de charge avant de remplacer le régulateur."], box: { type: "exam", text: "Un filtre colmaté peut imiter un régulateur qui ne s’ouvre pas." }, visual: { kind: "oilLine", title: "Suivre les obstacles", label: "Réservoir, vanne, filtre, régulateur puis carter" } },
    { id: "limites", short: "Limites", kicker: "Station 7 · Ce qu’il ne fait pas", title: "Le pot mécanique ajoute ; il ne retire pas un excès", lead: "Si le carter est déjà trop rempli, fermer le pointeau n’évacue aucune huile.", details: ["Le régulateur mécanique ne produit pas non plus d’alarme électrique par lui-même.", "Vibrations, mauvaise horizontalité, pression instable ou huile dégradée peuvent perturber son mouvement."], box: { type: "warning", text: "Niveau haut et niveau bas n’appellent pas la même recherche de cause." }, visual: { kind: "decision", title: "Distinguer manque et excès", label: "Décision différente selon niveau bas stabilisé ou niveau trop haut" } },
    { id: "diagnostic", short: "Diagnostiquer", kicker: "Station 8 · Chaîne de preuve", title: "Le voyant bas ne condamne pas le flotteur", lead: "Commencer par vérifier qu’une huile correcte arrive réellement à l’entrée du régulateur.", details: ["Contrôler réserve, différentiel, vannes, filtre et raccords ; puis observer le mouvement et le niveau.", "Recouper avec le retour naturel, les régimes et la présence de fuites avant démontage."], box: { type: "key", text: "Amont correct + niveau bas persistant + mécanisme immobile orientent alors vers le régulateur." }, visual: { kind: "diagnostic", title: "Procéder de l’amont vers l’aval", label: "Contrôle du réservoir, du différentiel, du filtre et du régulateur mécanique" } }
  ],
  quiz: [
    { prompt: "Que désigne souvent « pot AC&R » en atelier ?", options: ["Un régulateur de niveau à flotteur", "Un filtre déshydrateur de ligne liquide", "Un détendeur électronique d’évaporateur"], correct: 0, why: "Le terme d’atelier renvoie au régulateur à flotteur monté sur le carter.", code: "1.05" },
    { prompt: "Où se monte-t-il ?", options: ["Sur la sortie du condenseur", "Au raccord du voyant du carter", "Sur la ligne liquide, après le détendeur"], correct: 1, why: "Il doit mesurer le niveau du carter qu’il alimente.", code: "1.05" },
    { prompt: "Comment agit-il ?", options: ["Le flotteur commande un pointeau", "Une pompe aspire l’huile du bac", "Un ressort taré ouvre par pression"], correct: 0, why: "Le niveau déplace mécaniquement le système d’admission.", code: "1.05" },
    { prompt: "Pourquoi doit-il être horizontal ?", options: ["Pour faciliter la purge du carter", "Pour limiter les vibrations du bloc", "Pour que le flotteur suive le vrai niveau"], correct: 2, why: "Une inclinaison décale la mesure gravitaire du niveau.", code: "1.05" },
    { prompt: "Qui fixe le niveau cible ?", options: ["La moitié de la hauteur du voyant", "Les notices du compresseur et du bloc", "Une valeur unique, la même partout"], correct: 1, why: "La géométrie et la lubrification varient selon les matériels.", code: "1.05" },
    { prompt: "Pourquoi installer un filtre en amont ?", options: ["Pour ralentir le débit vers le carter", "Pour retenir l’humidité de l’huile", "Pour protéger le pointeau des impuretés"], correct: 2, why: "Une particule peut réduire le débit ou empêcher la fermeture.", code: "1.05" },
    { prompt: "Que peut faire le régulateur mécanique face à un excès d’huile ?", options: ["Fermer son admission, sans plus", "Renvoyer l’excès vers le réservoir", "Purger l’huile vers l’aspiration"], correct: 0, why: "Aucune voie n’évacue l’huile déjà présente dans le carter.", code: "6.05" },
    { prompt: "Le carter reste bas : que vérifier d’abord ?", options: ["Remplacer le flotteur sans mesurer", "Réserve, différentiel, vannes et filtre", "Ajouter une huile d’un autre type"], correct: 1, why: "Un défaut d’alimentation amont produit le même symptôme.", code: "6.05" }
  ],
  sources: [
    { title: "Parker Sporlan — Oil Level Control System", url: "https://www.parker.com/content/dam/Parker-com/Literature/Sporlan/Sporlan-pdf-files/Sporlan-pdf-110/SD-129_-Oil-Level-Control-System-Installation.pdf", use: "montage, réglage et diagnostic des contrôleurs mécaniques" },
    { title: "BITZER — Parallel compounding with oil level controllers", url: "https://www.bitzer.de/shared_media/html/kt-600/en-GB/313846411313848587.html", use: "contrôleurs mécaniques, plages de pression et filtre amont" },
    { title: "Légifrance — Attestation d’aptitude fluides", url: "https://www.legifrance.gouv.fr/jorf/id/JORFSCTA000053004646", use: "compétences 1.05 et 6.05" }
  ]
};
